-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GamelibInfoShieldInviter = {
    en    = "Inviter",
    ptbr  = "Convidador",
    ptpt  = "Convidador",
    es419 = "Invitante",
    eses  = "Invitante",
    pl    = "Zapraszający",
    ru    = "Приглашающий",
    sv    = "Inbjudare",
    nb    = "Invitør",
    de    = "Einladender",
    nlnl  = "Uitnodiger",
    frfr  = "Inviteur",
    fi    = "Kutsuja",
    it    = "Invitante",
    zhcn  = "邀请者",
    ja    = "招待者",
    ko    = "초대한 사람",
  },

  GamelibInfoShieldInvitee = {
    en    = "Invitee",
    ptbr  = "Convidado",
    ptpt  = "Convidado",
    es419 = "Invitado",
    eses  = "Invitado",
    pl    = "Zaproszony",
    ru    = "Приглашённый",
    sv    = "Inbjuden",
    nb    = "Invitert",
    de    = "Eingeladener",
    nlnl  = "Uitgenodigde",
    frfr  = "Invité",
    fi    = "Kutsuttu",
    it    = "Invitato",
    zhcn  = "被邀请者",
    ja    = "招待された人",
    ko    = "초대받은 사람",
  },

  GamelibInfoShieldPartner = {
    en    = "Partner",
    ptbr  = "Parceiro",
    ptpt  = "Parceiro",
    es419 = "Compañero",
    eses  = "Compañero",
    pl    = "Partner",
    ru    = "Партнёр",
    sv    = "Partner",
    nb    = "Partner",
    de    = "Partner",
    nlnl  = "Partner",
    frfr  = "Partenaire",
    fi    = "Ryhmätoveri",
    it    = "Compagno",
    zhcn  = "伙伴",
    ja    = "パートナー",
    ko    = "파트너",
  },

  GamelibInfoShieldLeader = {
    en    = "Leader",
    ptbr  = "Líder",
    ptpt  = "Líder",
    es419 = "Líder",
    eses  = "Líder",
    pl    = "Lider",
    ru    = "Лидер",
    sv    = "Ledare",
    nb    = "Leder",
    de    = "Anführer",
    nlnl  = "Leider",
    frfr  = "Chef",
    fi    = "Johtaja",
    it    = "Capogruppo",
    zhcn  = "队长",
    ja    = "リーダー",
    ko    = "리더",
  },

  GamelibInfoShieldOtherMember = {
    en    = "Other member",
    ptbr  = "Outro membro",
    ptpt  = "Outro membro",
    es419 = "Otro miembro",
    eses  = "Otro miembro",
    pl    = "Inny członek",
    ru    = "Другой участник",
    sv    = "Annan medlem",
    nb    = "Annet medlem",
    de    = "Anderes Mitglied",
    nlnl  = "Ander lid",
    frfr  = "Autre membre",
    fi    = "Muu jäsen",
    it    = "Altro membro",
    zhcn  = "其他成员",
    ja    = "他のメンバー",
    ko    = "다른 멤버",
  },

  GamelibInfoVocationLearner = {
    en    = "Learner",
    ptbr  = "Aprendiz",
    ptpt  = "Aprendiz",
    es419 = "Aprendiz",
    eses  = "Aprendiz",
    pl    = "Uczeń",
    ru    = "Ученик",
    sv    = "Lärling",
    nb    = "Lærling",
    de    = "Lehrling",
    nlnl  = "Leerling",
    frfr  = "Apprenti",
    fi    = "Harjoittelija",
    it    = "Apprendista",
    zhcn  = "学徒",
    ja    = "見習い",
    ko    = "수습생",
  },

  GamelibInfoVocationKnight = {
    en    = "Knight",
    ptbr  = "Cavaleiro",
    ptpt  = "Cavaleiro",
    es419 = "Caballero",
    eses  = "Caballero",
    pl    = "Rycerz",
    ru    = "Рыцарь",
    sv    = "Riddare",
    nb    = "Ridder",
    de    = "Ritter",
    nlnl  = "Ridder",
    frfr  = "Chevalier",
    fi    = "Ritari",
    it    = "Cavaliere",
    zhcn  = "骑士",
    ja    = "ナイト",
    ko    = "기사",
  },

  GamelibInfoVocationPaladin = {
    en    = "Paladin",
    ptbr  = "Paladino",
    ptpt  = "Paladino",
    es419 = "Paladín",
    eses  = "Paladín",
    pl    = "Paladyn",
    ru    = "Паладин",
    sv    = "Paladin",
    nb    = "Paladin",
    de    = "Paladin",
    nlnl  = "Paladijn",
    frfr  = "Paladin",
    fi    = "Paladiini",
    it    = "Paladino",
    zhcn  = "圣骑士",
    ja    = "パラディン",
    ko    = "성기사",
  },

  GamelibInfoVocationArcher = {
    en    = "Archer",
    ptbr  = "Arqueiro",
    ptpt  = "Arqueiro",
    es419 = "Arquero",
    eses  = "Arquero",
    pl    = "Łucznik",
    ru    = "Лучник",
    sv    = "Bågskytt",
    nb    = "Bueskytter",
    de    = "Bogenschütze",
    nlnl  = "Boogschutter",
    frfr  = "Archer",
    fi    = "Jousiampuja",
    it    = "Arciere",
    zhcn  = "弓箭手",
    ja    = "アーチャー",
    ko    = "궁수",
  },

  GamelibInfoVocationAssassin = {
    en    = "Assassin",
    ptbr  = "Assassino",
    ptpt  = "Assassino",
    es419 = "Asesino",
    eses  = "Asesino",
    pl    = "Zabójca",
    ru    = "Ассасин",
    sv    = "Lönnmördare",
    nb    = "Leiemorder",
    de    = "Assassine",
    nlnl  = "Moordenaar",
    frfr  = "Assassin",
    fi    = "Salamurhaaja",
    it    = "Assassino",
    zhcn  = "刺客",
    ja    = "アサシン",
    ko    = "암살자",
  },

  GamelibInfoVocationWizard = {
    en    = "Wizard",
    ptbr  = "Mago",
    ptpt  = "Mago",
    es419 = "Hechicero",
    eses  = "Hechicero",
    pl    = "Czarodziej",
    ru    = "Маг",
    sv    = "Trollkarl",
    nb    = "Trollmann",
    de    = "Zauberer",
    nlnl  = "Tovenaar",
    frfr  = "Sorcier",
    fi    = "Velho",
    it    = "Mago",
    zhcn  = "法师",
    ja    = "ウィザード",
    ko    = "마법사",
  },

  GamelibInfoVocationBard = {
    en    = "Bard",
    ptbr  = "Bardo",
    ptpt  = "Bardo",
    es419 = "Bardo",
    eses  = "Bardo",
    pl    = "Bard",
    ru    = "Бард",
    sv    = "Bard",
    nb    = "Barde",
    de    = "Barde",
    nlnl  = "Bard",
    frfr  = "Barde",
    fi    = "Bardi",
    it    = "Bardo",
    zhcn  = "吟游诗人",
    ja    = "バード",
    ko    = "음유시인",
  },

  GamelibInfoVocationUnknown = {
    en    = "Unknown",
    ptbr  = "Desconhecido",
    ptpt  = "Desconhecido",
    es419 = "Desconocido",
    eses  = "Desconocido",
    pl    = "Nieznany",
    ru    = "Неизвестно",
    sv    = "Okänd",
    nb    = "Ukjent",
    de    = "Unbekannt",
    nlnl  = "Onbekend",
    frfr  = "Inconnu",
    fi    = "Tuntematon",
    it    = "Sconosciuto",
    zhcn  = "未知",
    ja    = "不明",
    ko    = "알 수 없음",
  },

  GamelibInfoEnterValidServerPort = {
    en    = "You must enter a valid server address and port.",
    ptbr  = "Você deve inserir um endereço e porta de servidor válidos.",
    ptpt  = "Você deve inserir um endereço e porta de servidor válidos.",
    es419 = "Debes ingresar una dirección y un puerto de servidor válidos.",
    eses  = "Debes introducir una dirección y un puerto de servidor válidos.",
    pl    = "Musisz wprowadzić prawidłowy adres i port serwera.",
    ru    = "Необходимо ввести действительный адрес и порт сервера.",
    sv    = "Du måste ange en giltig serveradress och port.",
    nb    = "Du må angi en gyldig serveradresse og port.",
    de    = "Sie müssen eine gültige Serveradresse und einen gültigen Port eingeben.",
    nlnl  = "Je moet een geldig serveradres en een geldige poort invoeren.",
    frfr  = "Vous devez saisir une adresse et un port de serveur valides.",
    fi    = "Anna kelvollinen palvelinosoite ja portti.",
    it    = "Devi inserire un indirizzo e una porta del server validi.",
    zhcn  = "你必须输入有效的服务器地址和端口。",
    ja    = "有効なサーバーアドレスとポートを入力してください。",
    ko    = "유효한 서버 주소와 포트를 입력해야 합니다.",
  },

  GamelibInfoClientNeedsUpdate = {
    en    = "Client needs update.",
    ptbr  = "O cliente precisa ser atualizado.",
    ptpt  = "O cliente precisa ser atualizado.",
    es419 = "El cliente necesita actualizarse.",
    eses  = "El cliente necesita actualizarse.",
    pl    = "Klient wymaga aktualizacji.",
    ru    = "Клиент необходимо обновить.",
    sv    = "Klienten behöver uppdateras.",
    nb    = "Klienten må oppdateres.",
    de    = "Der Client muss aktualisiert werden.",
    nlnl  = "De client moet worden bijgewerkt.",
    frfr  = "Le client doit être mis à jour.",
    fi    = "Asiakas on päivitettävä.",
    it    = "Il client deve essere aggiornato.",
    zhcn  = "客户端需要更新。",
    ja    = "クライアントの更新が必要です。",
    ko    = "클라이언트를 업데이트해야 합니다.",
  },

  GamelibInfoInvalidAuthToken = {
    en    = "Invalid authentication token.",
    ptbr  = "Token de autenticação inválido.",
    ptpt  = "Token de autenticação inválido.",
    es419 = "Token de autenticación inválido.",
    eses  = "Token de autenticación inválido.",
    pl    = "Nieprawidłowy token uwierzytelniający.",
    ru    = "Недействительный токен аутентификации.",
    sv    = "Ogiltig autentiseringstoken.",
    nb    = "Ugyldig autentiseringstoken.",
    de    = "Ungültiges Authentifizierungs-Token.",
    nlnl  = "Ongeldig authenticatietoken.",
    frfr  = "Jeton d'authentification invalide.",
    fi    = "Virheellinen todennustunnus.",
    it    = "Token di autenticazione non valido.",
    zhcn  = "无效的身份验证令牌。",
    ja    = "認証トークンが無効です。",
    ko    = "잘못된 인증 토큰입니다.",
  },

  GamelibInfoBoostLow = {
    en    = "Low",
    ptbr  = "Baixo",
    ptpt  = "Baixo",
    es419 = "Bajo",
    eses  = "Bajo",
    pl    = "Niski",
    ru    = "Низкий",
    sv    = "Låg",
    nb    = "Lav",
    de    = "Niedrig",
    nlnl  = "Laag",
    frfr  = "Faible",
    fi    = "Matala",
    it    = "Basso",
    zhcn  = "低",
    ja    = "低",
    ko    = "낮음",
  },

  GamelibInfoBoostHigh = {
    en    = "High",
    ptbr  = "Alto",
    ptpt  = "Alto",
    es419 = "Alto",
    eses  = "Alto",
    pl    = "Wysoki",
    ru    = "Высокий",
    sv    = "Hög",
    nb    = "Høy",
    de    = "Hoch",
    nlnl  = "Hoog",
    frfr  = "Élevé",
    fi    = "Korkea",
    it    = "Alto",
    zhcn  = "高",
    ja    = "高",
    ko    = "높음",
  },

  GamelibInfoCreatureButtonHierarchy = {
    en    = "Hierarchy",
    ptbr  = "Hierarquia",
    ptpt  = "Hierarquia",
    es419 = "Jerarquía",
    eses  = "Jerarquía",
    pl    = "Hierarchia",
    ru    = "Иерархия",
    sv    = "Hierarki",
    nb    = "Hierarki",
    de    = "Hierarchie",
    nlnl  = "Hiërarchie",
    frfr  = "Hiérarchie",
    fi    = "Hierarkia",
    it    = "Gerarchia",
    zhcn  = "层级",
    ja    = "階層",
    ko    = "계층",
  },

  GamelibInfoCreatureButtonSummon = {
    en    = "Summon",
    ptbr  = "Invocar",
    ptpt  = "Invocar",
    es419 = "Invocar",
    eses  = "Invocar",
    pl    = "Przywołaj",
    ru    = "Призвать",
    sv    = "Framkalla",
    nb    = "Påkall",
    de    = "Beschwören",
    nlnl  = "Oproepen",
    frfr  = "Invoquer",
    fi    = "Kutsu",
    it    = "Evoca",
    zhcn  = "召唤",
    ja    = "召喚",
    ko    = "소환",
  },

  GamelibInfoCreatureButtonUnknown = {
    en    = "Unknown",
    ptbr  = "Desconhecido",
    ptpt  = "Desconhecido",
    es419 = "Desconocido",
    eses  = "Desconocido",
    pl    = "Nieznany",
    ru    = "Неизвестно",
    sv    = "Okänd",
    nb    = "Ukjent",
    de    = "Unbekannt",
    nlnl  = "Onbekend",
    frfr  = "Inconnu",
    fi    = "Tuntematon",
    it    = "Sconosciuto",
    zhcn  = "未知",
    ja    = "不明",
    ko    = "알 수 없음",
  },

  GamelibInfoCreatureButtonSQMs = {
    en    = "%d SQMs",
    ptbr  = "%d SQMs",
    ptpt  = "%d SQMs",
    es419 = "%d SQMs",
    eses  = "%d SQMs",
    pl    = "%d SQMs",
    ru    = "%d клеток",
    sv    = "%d SQMs",
    nb    = "%d SQMs",
    de    = "%d SQMs",
    nlnl  = "%d SQMs",
    frfr  = "%d cases",
    fi    = "%d ruutua",
    it    = "%d caselle",
    zhcn  = "%d SQMs",
    ja    = "%dマス",
    ko    = "%d SQM",
  },

  GamelibInfoRegionRookieIsland = {
    en    = "Rookie Island",
    ptbr  = "Ilha dos Novatos",
    ptpt  = "Ilha dos Novatos",
    es419 = "Isla de Novatos",
    eses  = "Isla de Novatos",
    pl    = "Wyspa Nowicjuszy",
    ru    = "Остров новичков",
    sv    = "Nybörjarön",
    nb    = "Nybegynnerøya",
    de    = "Anfängerinsel",
    nlnl  = "Eiland voor beginners",
    frfr  = "Île des débutants",
    fi    = "Aloittelijoiden saari",
    it    = "Isola dei novizi",
    zhcn  = "新手岛",
    ja    = "ルーキー島",
    ko    = "초보자 섬",
  },

  GamelibInfoRegionCityErembor = {
    en    = "City of Erembor",
    ptbr  = "Cidade de Erembor",
    ptpt  = "Cidade de Erembor",
    es419 = "Ciudad de Erembor",
    eses  = "Ciudad de Erembor",
    pl    = "Miasto Erembor",
    ru    = "Город Эрембор",
    sv    = "Staden Erembor",
    nb    = "Byen Erembor",
    de    = "Stadt Erembor",
    nlnl  = "Stad Erembor",
    frfr  = "Ville d'Erembor",
    fi    = "Eremborin kaupunki",
    it    = "Città di Erembor",
    zhcn  = "埃伦博尔城",
    ja    = "エレンボールの街",
    ko    = "에렘보르의 도시",
  },

  GamelibInfoRegionCityElensar = {
    en    = "City of Elensar",
    ptbr  = "Cidade de Elensar",
    ptpt  = "Cidade de Elensar",
    es419 = "Ciudad de Elensar",
    eses  = "Ciudad de Elensar",
    pl    = "Miasto Elensar",
    ru    = "Город Эленсар",
    sv    = "Staden Elensar",
    nb    = "Byen Elensar",
    de    = "Stadt Elensar",
    nlnl  = "Stad Elensar",
    frfr  = "Ville d'Elensar",
    fi    = "Elensarin kaupunki",
    it    = "Città di Elensar",
    zhcn  = "埃伦萨尔城",
    ja    = "エレンザーの街",
    ko    = "엘렌사르의 도시",
  },

  GamelibInfoRegionCityNova = {
    en    = "City of Nova",
    ptbr  = "Cidade de Nova",
    ptpt  = "Cidade de Nova",
    es419 = "Ciudad de Nova",
    eses  = "Ciudad de Nova",
    pl    = "Miasto Nova",
    ru    = "Город Нова",
    sv    = "Staden Nova",
    nb    = "Byen Nova",
    de    = "Stadt Nova",
    nlnl  = "Stad Nova",
    frfr  = "Ville de Nova",
    fi    = "Novan kaupunki",
    it    = "Città di Nova",
    zhcn  = "诺瓦城",
    ja    = "ノヴァの街",
    ko    = "노바의 도시",
  },

  GamelibInfoRegionCityNalta = {
    en    = "City of Nalta",
    ptbr  = "Cidade de Nalta",
    ptpt  = "Cidade de Nalta",
    es419 = "Ciudad de Nalta",
    eses  = "Ciudad de Nalta",
    pl    = "Miasto Nalta",
    ru    = "Город Налта",
    sv    = "Staden Nalta",
    nb    = "Byen Nalta",
    de    = "Stadt Nalta",
    nlnl  = "Stad Nalta",
    frfr  = "Ville de Nalta",
    fi    = "Naltan kaupunki",
    it    = "Città di Nalta",
    zhcn  = "纳尔塔城",
    ja    = "ナルタの街",
    ko    = "날타의 도시",
  },

  GamelibInfoRegionCityDronMa = {
    en    = "City of Dron'Ma",
    ptbr  = "Cidade de Dron'Ma",
    ptpt  = "Cidade de Dron'Ma",
    es419 = "Ciudad de Dron'Ma",
    eses  = "Ciudad de Dron'Ma",
    pl    = "Miasto Dron'Ma",
    ru    = "Город Дрон'Ма",
    sv    = "Staden Dron'Ma",
    nb    = "Byen Dron'Ma",
    de    = "Stadt Dron'Ma",
    nlnl  = "Stad Dron'Ma",
    frfr  = "Ville de Dron'Ma",
    fi    = "Dron'Man kaupunki",
    it    = "Città di Dron'Ma",
    zhcn  = "德隆玛城",
    ja    = "ドロン・マの街",
    ko    = "드론마의 도시",
  },

  GamelibInfoRegionAmazoniaHideout = {
    en    = "Amazonia Hideout",
    ptbr  = "Esconderijo da Amazônia",
    ptpt  = "Esconderijo da Amazônia",
    es419 = "Escondite de Amazonia",
    eses  = "Escondite de Amazonia",
    pl    = "Kryjówka Amazonii",
    ru    = "Убежище Амазонии",
    sv    = "Amazonias gömställe",
    nb    = "Amazonias gjemmested",
    de    = "Versteck von Amazonia",
    nlnl  = "Schuilplaats van Amazonia",
    frfr  = "Repaire d'Amazonia",
    fi    = "Amazonian piilopaikka",
    it    = "Nascondiglio di Amazonia",
    zhcn  = "亚马逊藏身处",
    ja    = "アマゾニアの隠れ家",
    ko    = "아마조니아 은신처",
  },

  GamelibInfoRegionVengeanceVillage = {
    en    = "Vengeance Village",
    ptbr  = "Aldeia da Vingança",
    ptpt  = "Aldeia da Vingança",
    es419 = "Aldea de la Venganza",
    eses  = "Aldea de la Venganza",
    pl    = "Wioska Zemsty",
    ru    = "Деревня Мести",
    sv    = "Hämndbyn",
    nb    = "Hevnbyen",
    de    = "Rachedorf",
    nlnl  = "Wraakdorp",
    frfr  = "Village de la Vengeance",
    fi    = "Koston kylä",
    it    = "Villaggio della Vendetta",
    zhcn  = "复仇村",
    ja    = "復讐の村",
    ko    = "복수의 마을",
  },

  GamelibInfoRegionMountFarber = {
    en    = "Mount Farber",
    ptbr  = "Monte Farber",
    ptpt  = "Monte Farber",
    es419 = "Monte Farber",
    eses  = "Monte Farber",
    pl    = "Góra Farber",
    ru    = "Гора Фарбер",
    sv    = "Farberberget",
    nb    = "Farberfjellet",
    de    = "Berg Farber",
    nlnl  = "Mount Farber",
    frfr  = "Mont Farber",
    fi    = "Farber-vuori",
    it    = "Monte Farber",
    zhcn  = "法伯山",
    ja    = "ファーバー山",
    ko    = "파버 산",
  },

  GamelibInfoRegionEraninWoods = {
    en    = "Eranin Woods",
    ptbr  = "Floresta Eranin",
    ptpt  = "Floresta Eranin",
    es419 = "Bosque de Eranin",
    eses  = "Bosque de Eranin",
    pl    = "Lasy Eranin",
    ru    = "Лес Эранина",
    sv    = "Eranin-skogarna",
    nb    = "Eranin-skogene",
    de    = "Eranin-Wald",
    nlnl  = "Bossen van Eranin",
    frfr  = "Bois d'Eranin",
    fi    = "Eraninin metsät",
    it    = "Foreste di Eranin",
    zhcn  = "埃拉宁森林",
    ja    = "エラニンの森",
    ko    = "에라닌 숲",
  },

  GamelibInfoRegionTrollShaws = {
    en    = "Troll Shaws",
    ptbr  = "Bosques dos Trolls",
    ptpt  = "Bosques dos Trolls",
    es419 = "Bosques de Trolls",
    eses  = "Bosques de Trolls",
    pl    = "Lasy Trolli",
    ru    = "Тролльи леса",
    sv    = "Trollskogarna",
    nb    = "Trollskogane",
    de    = "Trollwälder",
    nlnl  = "Trollenbossen",
    frfr  = "Bois des trolls",
    fi    = "Peikkolehdot",
    it    = "Boschi dei troll",
    zhcn  = "巨魔森林",
    ja    = "トロールの森",
    ko    = "트롤 숲",
  },

  GamelibInfoRegionDeathClawMountain = {
    en    = "Death Claw Mountain",
    ptbr  = "Montanha Garra da Morte",
    ptpt  = "Montanha Garra da Morte",
    es419 = "Montaña Garra de la Muerte",
    eses  = "Montaña Garra de la Muerte",
    pl    = "Góra Szponu Śmierci",
    ru    = "Гора Когтя Смерти",
    sv    = "Dödsklo-berget",
    nb    = "Dødskloklauen",
    de    = "Berg der Todesklaue",
    nlnl  = "Doods Klauwberg",
    frfr  = "Montagne de la Griffe de mort",
    fi    = "Kuolonkynsivuori",
    it    = "Montagna Artiglio della Morte",
    zhcn  = "死亡之爪山",
    ja    = "デスクロウ山",
    ko    = "데스 클로 산",
  },

  GamelibInfoRegionKrogHar = {
    en    = "Krog-Har",
    ptbr  = "Krog-Har",
    ptpt  = "Krog-Har",
    es419 = "Krog-Har",
    eses  = "Krog-Har",
    pl    = "Krog-Har",
    ru    = "Krog-Har",
    sv    = "Krog-Har",
    nb    = "Krog-Har",
    de    = "Krog-Har",
    nlnl  = "Krog-Har",
    frfr  = "Krog-Har",
    fi    = "Krog-Har",
    it    = "Krog-Har",
    zhcn  = "Krog-Har",
    ja    = "クログ・ハール",
    ko    = "크로그-하르",
  },

  GamelibInfoRegionSandHills = {
    en    = "Sand Hills",
    ptbr  = "Colinas de Areia",
    ptpt  = "Colinas de Areia",
    es419 = "Colinas de Arena",
    eses  = "Colinas de Arena",
    pl    = "Piaszczyste Wzgórza",
    ru    = "Песчаные холмы",
    sv    = "Sandkullarna",
    nb    = "Sandhaugene",
    de    = "Sandhügel",
    nlnl  = "Zandheuvels",
    frfr  = "Collines de sable",
    fi    = "Hiekkakukkulat",
    it    = "Colline sabbiose",
    zhcn  = "沙丘",
    ja    = "砂丘",
    ko    = "모래 언덕",
  },

  GamelibInfoRegionMountChrist = {
    en    = "Mount Christ",
    ptbr  = "Monte Cristo",
    ptpt  = "Monte Cristo",
    es419 = "Monte Cristo",
    eses  = "Monte Cristo",
    pl    = "Góra Chrystusa",
    ru    = "Гора Христа",
    sv    = "Kristusberget",
    nb    = "Kristusberget",
    de    = "Christusberg",
    nlnl  = "Christusberg",
    frfr  = "Mont Christ",
    fi    = "Kristusvuori",
    it    = "Monte Cristo",
    zhcn  = "基督山",
    ja    = "クリスト山",
    ko    = "크리스트 산",
  },

  GamelibInfoRegionMavigicValley = {
    en    = "Mavigic Valley",
    ptbr  = "Vale de Mavigic",
    ptpt  = "Vale de Mavigic",
    es419 = "Valle de Mavigic",
    eses  = "Valle de Mavigic",
    pl    = "Dolina Mavigic",
    ru    = "Долина Мавиджик",
    sv    = "Mavigicdalen",
    nb    = "Mavigicdalen",
    de    = "Mavigic-Tal",
    nlnl  = "Mavigic-vallei",
    frfr  = "Vallée de Mavigic",
    fi    = "Mavigicin laakso",
    it    = "Valle di Mavigic",
    zhcn  = "马维吉克谷",
    ja    = "マビジック渓谷",
    ko    = "마비직 계곡",
  },

  GamelibInfoRegionMavigicForest = {
    en    = "Mavigic Forest",
    ptbr  = "Floresta de Mavigic",
    ptpt  = "Floresta de Mavigic",
    es419 = "Bosque de Mavigic",
    eses  = "Bosque de Mavigic",
    pl    = "Las Mavigic",
    ru    = "Лес Мавиджик",
    sv    = "Mavigicskogen",
    nb    = "Mavigicskogen",
    de    = "Mavigic-Wald",
    nlnl  = "Mavigic-woud",
    frfr  = "Forêt de Mavigic",
    fi    = "Mavigicin metsä",
    it    = "Foresta di Mavigic",
    zhcn  = "马维吉克森林",
    ja    = "マビジックの森",
    ko    = "마비직 숲",
  },

  GamelibInfoRegionMavigicCitadel = {
    en    = "Mavigic Citadel",
    ptbr  = "Cidadela de Mavigic",
    ptpt  = "Cidadela de Mavigic",
    es419 = "Ciudadela de Mavigic",
    eses  = "Ciudadela de Mavigic",
    pl    = "Cytadela Mavigic",
    ru    = "Цитадель Мавиджик",
    sv    = "Mavigiccitadellet",
    nb    = "Mavigiccitadellet",
    de    = "Mavigic-Zitadelle",
    nlnl  = "Mavigic-citadel",
    frfr  = "Citadelle de Mavigic",
    fi    = "Mavigicin linnoitus",
    it    = "Cittadella di Mavigic",
    zhcn  = "马维吉克城堡",
    ja    = "マビジック城塞",
    ko    = "마비직 성채",
  },

  GamelibInfoRegionAnvhiansMines = {
    en    = "Anvhian's Mines",
    ptbr  = "Minas de Anvhian",
    ptpt  = "Minas de Anvhian",
    es419 = "Minas de Anvhian",
    eses  = "Minas de Anvhian",
    pl    = "Kopalnie Anvhiana",
    ru    = "Шахты Анвхиана",
    sv    = "Anvhians gruvor",
    nb    = "Anvhians gruver",
    de    = "Anvhians Minen",
    nlnl  = "Mijnen van Anvhian",
    frfr  = "Mines d'Anvhian",
    fi    = "Anvhianin kaivokset",
    it    = "Miniere di Anvhian",
    zhcn  = "安维安的矿井",
    ja    = "アンヴィアンの鉱山",
    ko    = "안비안의 광산",
  },

  GamelibInfoRegionHolkaganDesert = {
    en    = "Holkagan Desert",
    ptbr  = "Deserto de Holkagan",
    ptpt  = "Deserto de Holkagan",
    es419 = "Desierto de Holkagan",
    eses  = "Desierto de Holkagan",
    pl    = "Pustynia Holkagan",
    ru    = "Пустыня Холкаган",
    sv    = "Holkaganöknen",
    nb    = "Holkaganørkenen",
    de    = "Holkagan-Wüste",
    nlnl  = "Woestijn van Holkagan",
    frfr  = "Désert de Holkagan",
    fi    = "Holkaganin autiomaa",
    it    = "Deserto di Holkagan",
    zhcn  = "霍尔卡甘沙漠",
    ja    = "ホルカガン砂漠",
    ko    = "홀카간 사막",
  },

  GamelibInfoRegionCyclopsTunnel = {
    en    = "Cyclops Tunnel",
    ptbr  = "Túnel dos Ciclope",
    ptpt  = "Túnel dos Ciclope",
    es419 = "Túnel de los cíclopes",
    eses  = "Túnel de los cíclopes",
    pl    = "Tunel Cyklopów",
    ru    = "Туннель циклопов",
    sv    = "Cyklopernas tunnel",
    nb    = "Kyklopenes tunnel",
    de    = "Zyklopen-Tunnel",
    nlnl  = "Cyclopentunnel",
    frfr  = "Tunnel des cyclopes",
    fi    = "Kyklooppien tunneli",
    it    = "Tunnel dei ciclopi",
    zhcn  = "独眼巨人隧道",
    ja    = "サイクロプスのトンネル",
    ko    = "사이클롭스 터널",
  },

  GamelibInfoRegionElvenCamp = {
    en    = "Elven Camp",
    ptbr  = "Acampamento Élfico",
    ptpt  = "Acampamento Élfico",
    es419 = "Campamento élfico",
    eses  = "Campamento élfico",
    pl    = "Obóz elfów",
    ru    = "Лагерь эльфов",
    sv    = "Alvlägret",
    nb    = "Alveleiren",
    de    = "Elfenlager",
    nlnl  = "Elfenkamp",
    frfr  = "Camp des elfes",
    fi    = "Haltialeiri",
    it    = "Accampamento degli elfi",
    zhcn  = "精灵营地",
    ja    = "エルフのキャンプ",
    ko    = "엘프 야영지",
  },

  GamelibInfoRegionLollaardCave = {
    en    = "Lollaard Cave",
    ptbr  = "Caverna Lollaard",
    ptpt  = "Caverna Lollaard",
    es419 = "Cueva Lollaard",
    eses  = "Cueva Lollaard",
    pl    = "Jaskinia Lollaard",
    ru    = "Пещера Лоллаард",
    sv    = "Lollaardgrottan",
    nb    = "Lollaardgrotten",
    de    = "Lollaard-Höhle",
    nlnl  = "Lollaard-grot",
    frfr  = "Grotte de Lollaard",
    fi    = "Lollaardin luola",
    it    = "Grotta di Lollaard",
    zhcn  = "Lollaard洞窟",
    ja    = "ロラード洞窟",
    ko    = "롤라드 동굴",
  },

  GamelibInfoRegionTempleAcegordsPlains = {
    en    = "Temple of Acegord's Plains",
    ptbr  = "Templo das Planícies de Acegord",
    ptpt  = "Templo das Planícies de Acegord",
    es419 = "Templo de las Llanuras de Acegord",
    eses  = "Templo de las Llanuras de Acegord",
    pl    = "Świątynia Równin Acegorda",
    ru    = "Храм равнин Ацегорда",
    sv    = "Acegords slätts tempel",
    nb    = "Acegords slettens tempel",
    de    = "Tempel der Acegord-Ebene",
    nlnl  = "Tempel van de vlakten van Acegord",
    frfr  = "Temple des plaines d'Acegord",
    fi    = "Acegordin tasankojen temppeli",
    it    = "Tempio delle pianure di Acegord",
    zhcn  = "阿塞戈德平原神殿",
    ja    = "アセゴード平原の寺院",
    ko    = "에이스고드 평원의 사원",
  },

  GamelibInfoRegionAcegordsPlains = {
    en    = "Acegord's Plains",
    ptbr  = "Planícies de Acegord",
    ptpt  = "Planícies de Acegord",
    es419 = "Llanuras de Acegord",
    eses  = "Llanuras de Acegord",
    pl    = "Równiny Acegorda",
    ru    = "Равнины Ацегорда",
    sv    = "Acegords slätt",
    nb    = "Acegords slette",
    de    = "Acegord-Ebene",
    nlnl  = "Vlakten van Acegord",
    frfr  = "Plaines d'Acegord",
    fi    = "Acegordin tasangot",
    it    = "Pianure di Acegord",
    zhcn  = "阿塞戈德平原",
    ja    = "アセゴード平原",
    ko    = "에이스고드 평원",
  },

  GamelibInfoRegionDragonLair = {
    en    = "Dragon Lair",
    ptbr  = "Covil do Dragão",
    ptpt  = "Covil do Dragão",
    es419 = "Guarida del Dragón",
    eses  = "Guarida del Dragón",
    pl    = "Legowisko Smoka",
    ru    = "Логово дракона",
    sv    = "Draknäste",
    nb    = "Dragehi",
    de    = "Drachenhort",
    nlnl  = "Drakennest",
    frfr  = "Repaire du dragon",
    fi    = "Lohikäärmeen luola",
    it    = "Tana del drago",
    zhcn  = "巨龙巢穴",
    ja    = "ドラゴンの巣",
    ko    = "용의 둥지",
  },

  GamelibInfoRegionVampireMansion = {
    en    = "Vampire Mansion",
    ptbr  = "Mansão Vampiresca",
    ptpt  = "Mansão Vampiresca",
    es419 = "Mansión Vampiresca",
    eses  = "Mansión Vampiresca",
    pl    = "Dwór Wampirów",
    ru    = "Вампирский особняк",
    sv    = "Vampyrherrgården",
    nb    = "Vampyrherskapshuset",
    de    = "Vampirvilla",
    nlnl  = "Vampierlandhuis",
    frfr  = "Manoir des vampires",
    fi    = "Vampyyrikartano",
    it    = "Dimora dei vampiri",
    zhcn  = "吸血鬼庄园",
    ja    = "ヴァンパイア邸",
    ko    = "뱀파이어 저택",
  },

  GamelibInfoRegionRakkarHills = {
    en    = "Rakkar Hills",
    ptbr  = "Colinas de Rakkar",
    ptpt  = "Colinas de Rakkar",
    es419 = "Colinas de Rakkar",
    eses  = "Colinas de Rakkar",
    pl    = "Wzgórza Rakkar",
    ru    = "Холмы Раккар",
    sv    = "Rakkarkullarna",
    nb    = "Rakkaråsene",
    de    = "Rakkar-Hügel",
    nlnl  = "Rakkarheuvels",
    frfr  = "Collines de Rakkar",
    fi    = "Rakkarin kukkulat",
    it    = "Colline di Rakkar",
    zhcn  = "拉卡尔丘陵",
    ja    = "ラッカー丘陵",
    ko    = "라카르 언덕",
  },

  GamelibInfoRegionGreenest = {
    en    = "Greenest",
    ptbr  = "Greenest",
    ptpt  = "Greenest",
    es419 = "Greenest",
    eses  = "Greenest",
    pl    = "Greenest",
    ru    = "Гринист",
    sv    = "Greenest",
    nb    = "Greenest",
    de    = "Greenest",
    nlnl  = "Greenest",
    frfr  = "Greenest",
    fi    = "Greenest",
    it    = "Greenest",
    zhcn  = "格林尼斯特",
    ja    = "グリーネスト",
    ko    = "그리니스트",
  },

  GamelibInfoRegionLusorSwamp = {
    en    = "Lusor Swamp",
    ptbr  = "Pântano de Lusor",
    ptpt  = "Pântano de Lusor",
    es419 = "Pantano de Lusor",
    eses  = "Pantano de Lusor",
    pl    = "Bagno Lusor",
    ru    = "Болота Лусора",
    sv    = "Lusorträsket",
    nb    = "Lusor-myren",
    de    = "Lusor-Sumpf",
    nlnl  = "Lusormoeras",
    frfr  = "Marais de Lusor",
    fi    = "Lusorin suo",
    it    = "Palude di Lusor",
    zhcn  = "卢索尔沼泽",
    ja    = "ルソール沼地",
    ko    = "루소르 늪",
  },

  GamelibInfoRegionThartov = {
    en    = "Thartov",
    ptbr  = "Thartov",
    ptpt  = "Thartov",
    es419 = "Thartov",
    eses  = "Thartov",
    pl    = "Thartov",
    ru    = "Thartov",
    sv    = "Thartov",
    nb    = "Thartov",
    de    = "Thartov",
    nlnl  = "Thartov",
    frfr  = "Thartov",
    fi    = "Thartov",
    it    = "Thartov",
    zhcn  = "Thartov",
    ja    = "サルタフ",
    ko    = "타르토프",
  },

  GamelibInfoRegionOutlawVillage = {
    en    = "Outlaw Village",
    ptbr  = "Aldeia Fora-da-Lei",
    ptpt  = "Aldeia Fora-da-Lei",
    es419 = "Aldea Forajida",
    eses  = "Aldea Forajida",
    pl    = "Wieś Banitów",
    ru    = "Деревня разбойников",
    sv    = "Laglösas by",
    nb    = "Lagløysas by",
    de    = "Dorf der Gesetzlosen",
    nlnl  = "Dorp van vogelvrijen",
    frfr  = "Village des hors-la-loi",
    fi    = "Lainsuojattomien kylä",
    it    = "Villaggio dei fuorilegge",
    zhcn  = "无赖村",
    ja    = "無法者の村",
    ko    = "무법자 마을",
  },

  GamelibInfoRegionWealthIsland = {
    en    = "Wealth Island",
    ptbr  = "Ilha da Riqueza",
    ptpt  = "Ilha da Riqueza",
    es419 = "Isla de la Riqueza",
    eses  = "Isla de la Riqueza",
    pl    = "Wyspa Bogactwa",
    ru    = "Остров Богатства",
    sv    = "Rikedomens ö",
    nb    = "Rikdommens øy",
    de    = "Insel des Reichtums",
    nlnl  = "Rijkdomseiland",
    frfr  = "Île de la richesse",
    fi    = "Rikkauden saari",
    it    = "Isola della ricchezza",
    zhcn  = "财富岛",
    ja    = "富の島",
    ko    = "부의 섬",
  },

  GamelibInfoRegionRoshamuul = {
    en    = "Roshamuul",
    ptbr  = "Roshamuul",
    ptpt  = "Roshamuul",
    es419 = "Roshamuul",
    eses  = "Roshamuul",
    pl    = "Roshamuul",
    ru    = "Roshamuul",
    sv    = "Roshamuul",
    nb    = "Roshamuul",
    de    = "Roshamuul",
    nlnl  = "Roshamuul",
    frfr  = "Roshamuul",
    fi    = "Roshamuul",
    it    = "Roshamuul",
    zhcn  = "Roshamuul",
    ja    = "ロシャムール",
    ko    = "로샤뮬",
  },

  GamelibInfoOptionCopyPosition = {
    en    = "Copy position",
    ptbr  = "Copiar posição",
    ptpt  = "Copiar posição",
    es419 = "Copiar posición",
    eses  = "Copiar posición",
    pl    = "Skopiuj pozycję",
    ru    = "Копировать позицию",
    sv    = "Kopiera position",
    nb    = "Kopier posisjon",
    de    = "Position kopieren",
    nlnl  = "Positie kopiëren",
    frfr  = "Copier la position",
    fi    = "Kopioi sijainti",
    it    = "Copia posizione",
    zhcn  = "复制位置",
    ja    = "位置をコピー",
    ko    = "위치 복사",
  },

  GamelibInfoPosition = {
    en    = "Position(%d, %d, %d)",
    ptbr  = "Posição(%d, %d, %d)",
    ptpt  = "Posição(%d, %d, %d)",
    es419 = "Posición(%d, %d, %d)",
    eses  = "Posición(%d, %d, %d)",
    pl    = "Pozycja(%d, %d, %d)",
    ru    = "Позиция(%d, %d, %d)",
    sv    = "Position(%d, %d, %d)",
    nb    = "Posisjon(%d, %d, %d)",
    de    = "Position(%d, %d, %d)",
    nlnl  = "Positie(%d, %d, %d)",
    frfr  = "Position (%d, %d, %d)",
    fi    = "Sijainti (%d, %d, %d)",
    it    = "Posizione(%d, %d, %d)",
    zhcn  = "位置(%d, %d, %d)",
    ja    = "位置（%d, %d, %d）",
    ko    = "위치(%d, %d, %d)",
  },

  GamelibInfoDestinationOutRange = {
    en    = "Destination is out of range.",
    ptbr  = "Destino fora de alcance.",
    ptpt  = "Destino fora de alcance.",
    es419 = "Destino fuera de alcance.",
    eses  = "Destino fuera de alcance.",
    pl    = "Cel jest poza zasięgiem.",
    ru    = "Пункт назначения вне зоны действия.",
    sv    = "Målet är utanför räckhåll.",
    nb    = "Målet er utenfor rekkevidde.",
    de    = "Das Ziel ist außer Reichweite.",
    nlnl  = "De bestemming is buiten bereik.",
    frfr  = "La destination est hors de portée.",
    fi    = "Kohde on kantaman ulkopuolella.",
    it    = "La destinazione è fuori portata.",
    zhcn  = "目的地超出范围。",
    ja    = "目的地が範囲外です。",
    ko    = "목적지가 범위를 벗어났습니다.",
  },

  GamelibInfoNoOpenedPanel = {
    en    = "Open a side panel first.",
    ptbr  = "Abra um painel lateral primeiro.",
    ptpt  = "Abra um painel lateral primeiro.",
    es419 = "Abra primero un panel lateral.",
    eses  = "Abra primero un panel lateral.",
    pl    = "Najpierw otwórz panel boczny.",
    ru    = "Сначала откройте боковую панель.",
    sv    = "Öppna en sidopanel först.",
    nb    = "Åpne et sidepanel først.",
    de    = "Öffnen Sie zuerst ein Seitenpanel.",
    nlnl  = "Open eerst een zijpaneel.",
    frfr  = "Ouvrez d'abord un panneau latéral.",
    fi    = "Avaa ensin sivupaneeli.",
    it    = "Apri prima un pannello laterale.",
    zhcn  = "请先打开侧边面板。",
    ja    = "先にサイドパネルを開いてください。",
    ko    = "먼저 측면 패널을 여세요.",
  },

  GamelibInfoOptionEditMark = {
    en    = "Edit mark",
    ptbr  = "Editar marca",
    ptpt  = "Editar marca",
    es419 = "Editar marca",
    eses  = "Editar marca",
    pl    = "Edytuj znacznik",
    ru    = "Изменить метку",
    sv    = "Redigera markering",
    nb    = "Rediger markering",
    de    = "Markierung bearbeiten",
    nlnl  = "Markering bewerken",
    frfr  = "Modifier le repère",
    fi    = "Muokkaa merkkiä",
    it    = "Modifica contrassegno",
    zhcn  = "编辑标记",
    ja    = "マークを編集",
    ko    = "표시 편집",
  },

  GamelibInfoOptionRemoveMark = {
    en    = "Remove mark",
    ptbr  = "Remover marca",
    ptpt  = "Remover marca",
    es419 = "Eliminar marca",
    eses  = "Eliminar marca",
    pl    = "Usuń znacznik",
    ru    = "Удалить метку",
    sv    = "Ta bort markering",
    nb    = "Fjern markering",
    de    = "Markierung entfernen",
    nlnl  = "Markering verwijderen",
    frfr  = "Supprimer le repère",
    fi    = "Poista merkki",
    it    = "Rimuovi contrassegno",
    zhcn  = "移除标记",
    ja    = "マークを削除",
    ko    = "표시 삭제",
  },

  GamelibInfoOptionAddNewMark = {
    en    = "Add new mark",
    ptbr  = "Adicionar nova marca",
    ptpt  = "Adicionar nova marca",
    es419 = "Añadir nueva marca",
    eses  = "Añadir nueva marca",
    pl    = "Dodaj nowy znacznik",
    ru    = "Добавить новую метку",
    sv    = "Lägg till ny markering",
    nb    = "Legg til ny markering",
    de    = "Neue Markierung hinzufügen",
    nlnl  = "Nieuwe markering toevoegen",
    frfr  = "Ajouter un nouveau repère",
    fi    = "Lisää uusi merkki",
    it    = "Aggiungi nuovo contrassegno",
    zhcn  = "添加新标记",
    ja    = "新しいマークを追加",
    ko    = "새 표시 추가",
  },

  GamelibInfoOptionTrackPos = {
    en    = "Track position",
    ptbr  = "Rastrear posição",
    ptpt  = "Rastrear posição",
    es419 = "Rastrear posición",
    eses  = "Rastrear posición",
    pl    = "Śledź pozycję",
    ru    = "Отслеживать позицию",
    sv    = "Spåra position",
    nb    = "Spor posisjon",
    de    = "Position verfolgen",
    nlnl  = "Positie volgen",
    frfr  = "Suivre la position",
    fi    = "Seuraa sijaintia",
    it    = "Segui posizione",
    zhcn  = "追踪位置",
    ja    = "位置を追跡",
    ko    = "위치 추적",
  },

  GamelibInfoOptionTrackCustomPos = {
    en    = "Track another position",
    ptbr  = "Rastrear outra posição",
    ptpt  = "Rastrear outra posição",
    es419 = "Rastrear otra posición",
    eses  = "Rastrear otra posición",
    pl    = "Śledź inną pozycję",
    ru    = "Отслеживать другую позицию",
    sv    = "Spåra en annan position",
    nb    = "Spor en annen posisjon",
    de    = "Eine andere Position verfolgen",
    nlnl  = "Een andere positie volgen",
    frfr  = "Suivre une autre position",
    fi    = "Seuraa muuta sijaintia",
    it    = "Segui un'altra posizione",
    zhcn  = "追踪另一个位置",
    ja    = "別の位置を追跡",
    ko    = "다른 위치 추적",
  },

  GamelibInfoPowerClassOffensive = {
    en    = "Offensive",
    ptbr  = "Ofensivo",
    ptpt  = "Ofensivo",
    es419 = "Ofensivo",
    eses  = "Ofensivo",
    pl    = "Ofensywny",
    ru    = "Атакующий",
    sv    = "Offensiv",
    nb    = "Offensiv",
    de    = "Offensiv",
    nlnl  = "Agressief",
    frfr  = "Offensif",
    fi    = "Hyökkäävä",
    it    = "Offensivo",
    zhcn  = "攻击",
    ja    = "攻撃",
    ko    = "공격",
  },

  GamelibInfoPowerClassDefensive = {
    en    = "Defensive",
    ptbr  = "Defensivo",
    ptpt  = "Defensivo",
    es419 = "Defensivo",
    eses  = "Defensivo",
    pl    = "Defensywny",
    ru    = "Защитный",
    sv    = "Defensiv",
    nb    = "Defensiv",
    de    = "Defensiv",
    nlnl  = "Defensief",
    frfr  = "Défensif",
    fi    = "Puolustava",
    it    = "Difensivo",
    zhcn  = "防御",
    ja    = "防御",
    ko    = "방어",
  },

  GamelibInfoPowerClassSupport = {
    en    = "Support",
    ptbr  = "Suporte",
    ptpt  = "Suporte",
    es419 = "Soporte",
    eses  = "Soporte",
    pl    = "Wsparcie",
    ru    = "Поддержка",
    sv    = "Stöd",
    nb    = "Støtte",
    de    = "Unterstützung",
    nlnl  = "Ondersteuning",
    frfr  = "Soutien",
    fi    = "Tuki",
    it    = "Supporto",
    zhcn  = "支援",
    ja    = "支援",
    ko    = "지원",
  },

  GamelibInfoPowerClassSpecial = {
    en    = "Special",
    ptbr  = "Especial",
    ptpt  = "Especial",
    es419 = "Especial",
    eses  = "Especial",
    pl    = "Specjalny",
    ru    = "Особый",
    sv    = "Speciell",
    nb    = "Spesiell",
    de    = "Spezial",
    nlnl  = "Speciaal",
    frfr  = "Spécial",
    fi    = "Erityinen",
    it    = "Speciale",
    zhcn  = "特殊",
    ja    = "特殊",
    ko    = "특수",
  },

  GamelibInfoManaVariable = {
    en    = "Variable",
    ptbr  = "Variável",
    ptpt  = "Variável",
    es419 = "Variable",
    eses  = "Variable",
    pl    = "Zmienna",
    ru    = "Переменная",
    sv    = "Variabel",
    nb    = "Variabel",
    de    = "Variabel",
    nlnl  = "Variabel",
    frfr  = "Variable",
    fi    = "Muuttuva",
    it    = "Variabile",
    zhcn  = "变量",
    ja    = "可変",
    ko    = "가변",
  },
})
