-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  ClientTopMenuFps = {
    en    = "FPS",
    ptbr  = "FPS",
    ptpt  = "FPS",
    es419 = "FPS",
    eses  = "FPS",
    pl    = "FPS",
    ru    = "FPS",
    sv    = "FPS",
    nb    = "FPS",
    de    = "FPS",
    nlnl  = "FPS",
    frfr  = "FPS",
    fi    = "FPS",
    it    = "FPS",
    zhcn  = "FPS",
    ja    = "FPS",
    ko    = "FPS",
  },

  ClientTopMenuFpsTooltip = {
    en    = "Min: %d\nAvg: %d\nMax: %d",
    ptbr  = "Mínimo: %d\nMédia: %d\nMáximo: %d",
    ptpt  = "Mínimo: %d\nMédia: %d\nMáximo: %d",
    es419 = "Mínimo: %d\nPromedio: %d\nMáximo: %d",
    eses  = "Mínimo: %d\nMedia: %d\nMáximo: %d",
    pl    = "Minimum: %d\nŚrednia: %d\nMaksimum: %d",
    ru    = "Минимум: %d\nСреднее: %d\nМаксимум: %d",
    sv    = "Minimum: %d\nMedel: %d\nMaximum: %d",
    nb    = "Minimum: %d\nGjennomsnitt: %d\nMaksimum: %d",
    de    = "Minimum: %d\nDurchschnitt: %d\nMaximum: %d",
    nlnl  = "Minimum: %d\nGemiddelde: %d\nMaximum: %d",
    frfr  = "Minimum : %d\nMoyenne : %d\nMaximum : %d",
    fi    = "Minimi: %d\nKeskiarvo: %d\nMaksimi: %d",
    it    = "Minimo: %d\nMedia: %d\nMassimo: %d",
    zhcn  = "最小值：%d\n平均值：%d\n最大值：%d",
    ja    = "最小値：%d\n平均値：%d\n最大値：%d",
    ko    = "최소: %d\n평균: %d\n최대: %d",
  },

  ClientTopMenuFpsInfoPing = {
    en    = "Ping",
    ptbr  = "Ping",
    ptpt  = "Ping",
    es419 = "Ping",
    eses  = "Ping",
    pl    = "Ping",
    ru    = "Ping",
    sv    = "Ping",
    nb    = "Ping",
    de    = "Ping",
    nlnl  = "Ping",
    frfr  = "Ping",
    fi    = "Ping",
    it    = "Ping",
    zhcn  = "Ping",
    ja    = "Ping",
    ko    = "Ping",
  },
})
