-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  KaClientUpdaterStarting = {
    en    = "Starting...",
    ptbr  = "Iniciando...",
    ptpt  = "Iniciando...",
    es419 = "Iniciando...",
    eses  = "Iniciando...",
    pl    = "Uruchamianie...",
    ru    = "Запуск...",
    sv    = "Startar...",
    nb    = "Starter...",
    de    = "Starten...",
    nlnl  = "Starten...",
    frfr  = "Démarrage...",
    fi    = "Käynnistetään...",
    it    = "Avvio...",
    zhcn  = "正在启动...",
    ja    = "開始中…",
    ko    = "시작 중...",
  },

  KaClientUpdaterDownloading = {
    en    = "Downloading: %s of %s files",
    ptbr  = "Baixando: %s de %s arquivos",
    ptpt  = "Baixando: %s de %s ficheiros",
    es419 = "Descargando: %s de %s archivos",
    eses  = "Descargando: %s de %s archivos",
    pl    = "Pobieranie: %s z %s plików",
    ru    = "Загрузка: %s из %s файлов",
    sv    = "Laddar ner: %s av %s filer",
    nb    = "Laster ned: %s av %s filer",
    de    = "Herunterladen: %s von %s Dateien",
    nlnl  = "Downloaden: %s van %s bestanden",
    frfr  = "Téléchargement : %s fichiers sur %s",
    fi    = "Ladataan: %s / %s tiedostoa",
    it    = "Download: %s di %s file",
    zhcn  = "下载中：%s / %s 个文件",
    ja    = "ダウンロード中：%s / %sファイル",
    ko    = "다운로드 중: %s / %s 파일",
  },

  KaClientUpdaterReceived = {
    en    = "Received: %.2f MB (%.2f %s/s)",
    ptbr  = "Recebido: %.2f MB (%.2f %s/s)",
    ptpt  = "Recebido: %.2f MB (%.2f %s/s)",
    es419 = "Recibido: %.2f MB (%.2f %s/s)",
    eses  = "Recibido: %.2f MB (%.2f %s/s)",
    pl    = "Otrzymano: %.2f MB (%.2f %s/s)",
    ru    = "Получено: %.2f МБ (%.2f %s/с)",
    sv    = "Mottaget: %.2f MB (%.2f %s/s)",
    nb    = "Mottatt: %.2f MB (%.2f %s/s)",
    de    = "Empfangen: %.2f MB (%.2f %s/s)",
    nlnl  = "Ontvangen: %.2f MB (%.2f %s/s)",
    frfr  = "Reçu : %.2f Mo (%.2f %s/s)",
    fi    = "Vastaanotettu: %.2f Mt (%.2f %s/s)",
    it    = "Ricevuti: %.2f MB (%.2f %s/s)",
    zhcn  = "已接收：%.2f MB（%.2f %s/秒）",
    ja    = "受信済み：%.2f MB（%.2f %s/s）",
    ko    = "수신됨: %.2f MB (%.2f %s/s)",
  },

  KaClientUpdaterEndTitle = {
    en    = "Update",
    ptbr  = "Atualizar",
    ptpt  = "Atualizar",
    es419 = "Actualizar",
    eses  = "Actualizar",
    pl    = "Aktualizacja",
    ru    = "Обновление",
    sv    = "Uppdatera",
    nb    = "Oppdater",
    de    = "Aktualisieren",
    nlnl  = "Bijwerken",
    frfr  = "Mise à jour",
    fi    = "Päivitys",
    it    = "Aggiornamento",
    zhcn  = "更新",
    ja    = "更新",
    ko    = "업데이트",
  },

  KaClientUpdaterEndMsg = {
    en    = "Your game has been updated. Confirm to restart.",
    ptbr  = "Seu jogo foi atualizado. Confirme para reiniciar.",
    ptpt  = "Seu jogo foi atualizado. Confirme para reiniciar.",
    es419 = "Tu juego ha sido actualizado. Confirma para reiniciar.",
    eses  = "Tu juego ha sido actualizado. Confirma para reiniciar.",
    pl    = "Twoja gra została zaktualizowana. Potwierdź, aby ją zrestartować.",
    ru    = "Ваша игра обновлена. Подтвердите, чтобы перезапустить её.",
    sv    = "Ditt spel har uppdaterats. Bekräfta för att starta om det.",
    nb    = "Spillet ditt er oppdatert. Bekreft for å starte det på nytt.",
    de    = "Ihr Spiel wurde aktualisiert. Bestätigen Sie, um es neu zu starten.",
    nlnl  = "Je spel is bijgewerkt. Bevestig om het opnieuw te starten.",
    frfr  = "Votre jeu a été mis à jour. Confirmez pour le redémarrer.",
    fi    = "Pelisi on päivitetty. Vahvista käynnistääksesi sen uudelleen.",
    it    = "Il tuo gioco è stato aggiornato. Conferma per riavviarlo.",
    zhcn  = "你的游戏已更新。确认以重新启动游戏。",
    ja    = "ゲームが更新されました。確認して再起動してください。",
    ko    = "게임이 업데이트되었습니다. 확인하여 게임을 다시 시작하세요.",
  },

  KaClientUpdaterLoading = {
    en    = "Loading...",
    ptbr  = "Carregando...",
    ptpt  = "Carregando...",
    es419 = "Cargando...",
    eses  = "Cargando...",
    pl    = "Ładowanie...",
    ru    = "Загрузка...",
    sv    = "Laddar...",
    nb    = "Laster...",
    de    = "Laden...",
    nlnl  = "Laden...",
    frfr  = "Chargement...",
    fi    = "Ladataan...",
    it    = "Caricamento...",
    zhcn  = "加载...",
    ja    = "読み込み中…",
    ko    = "로드 중...",
  },

  KaClientUpdaterLoadingRepPercent = {
    en    = "Loading repository: %.2f%%",
    ptbr  = "Carregando repositório: %.2f%%",
    ptpt  = "Carregando repositório: %.2f%%",
    es419 = "Cargando repositorio: %.2f%%",
    eses  = "Cargando repositorio: %.2f%%",
    pl    = "Ładowanie repozytorium: %.2f%%",
    ru    = "Загрузка репозитория: %.2f%%",
    sv    = "Laddar arkiv: %.2f%%",
    nb    = "Laster inn depot: %.2f%%",
    de    = "Repository wird geladen: %.2f%%",
    nlnl  = "Repository laden: %.2f%%",
    frfr  = "Chargement du dépôt : %.2f%%",
    fi    = "Ladataan säilöä: %.2f%%",
    it    = "Caricamento del repository: %.2f%%",
    zhcn  = "正在加载仓库：%.2f%%",
    ja    = "リポジトリを読み込み中：%.2f%%",
    ko    = "리포지토리 로드 중: %.2f%%",
  },

  KaClientUpdaterLoadingRep = {
    en    = "Loading repository...",
    ptbr  = "Carregando repositório...",
    ptpt  = "Carregando repositório...",
    es419 = "Cargando repositorio...",
    eses  = "Cargando repositorio...",
    pl    = "Ładowanie repozytorium...",
    ru    = "Загрузка репозитория...",
    sv    = "Laddar arkiv...",
    nb    = "Laster inn depot...",
    de    = "Repository wird geladen...",
    nlnl  = "Repository laden...",
    frfr  = "Chargement du dépôt...",
    fi    = "Ladataan säilöä...",
    it    = "Caricamento del repository...",
    zhcn  = "正在加载仓库...",
    ja    = "リポジトリを読み込み中…",
    ko    = "리포지토리 로드 중...",
  },

  KaClientUpdaterWaiting = {
    en    = "This may take a while%s",
    ptbr  = "Isso pode levar algum tempo%s",
    ptpt  = "Isso pode levar algum tempo%s",
    es419 = "Esto puede tardar un poco%s",
    eses  = "Esto puede tardar un poco%s",
    pl    = "To może chwilę potrwać%s",
    ru    = "Это может занять некоторое время%s",
    sv    = "Det kan ta en stund%s",
    nb    = "Dette kan ta litt tid%s",
    de    = "Dies kann eine Weile dauern%s",
    nlnl  = "Dit kan even duren%s",
    frfr  = "Cela peut prendre un certain temps%s",
    fi    = "Tämä voi kestää hetken%s",
    it    = "Potrebbe volerci un po’%s",
    zhcn  = "这可能需要一些时间%s",
    ja    = "しばらく時間がかかる場合があります%s",
    ko    = "시간이 걸릴 수 있습니다%s",
  },

})
