-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameHotkeyBarsDefaultTooltip = {
    en    = "Drag hotkeys (%s), items or powers (%s) to this bar.",
    ptbr  = "Arraste atalhos (%s), itens ou poderes (%s) para esta barra.",
    ptpt  = "Arraste atalhos (%s), itens ou poderes (%s) para esta barra.",
    es419 = "Arrastra atajos (%s), objetos o poderes (%s) a esta barra.",
    eses  = "Arrastra atajos (%s), objetos o poderes (%s) a esta barra.",
    pl    = "Przeciągnij skróty (%s), przedmioty lub moce (%s) na ten pasek.",
    ru    = "Перетащите быстрые клавиши (%s), предметы или силы (%s) на эту панель.",
    sv    = "Dra snabbtangenter (%s), föremål eller krafter (%s) till den här raden.",
    nb    = "Dra hurtigtaster (%s), gjenstander eller krefter (%s) til denne linjen.",
    de    = "Ziehen Sie Hotkeys (%s), Gegenstände oder Kräfte (%s) in diese Leiste.",
    nlnl  = "Sleep sneltoetsen (%s), voorwerpen of krachten (%s) naar deze balk.",
    frfr  = "Faites glisser les raccourcis (%s), les objets ou les pouvoirs (%s) vers cette barre.",
    fi    = "Vedä pikanäppäimet (%s), esineet tai voimat (%s) tähän palkkiin.",
    it    = "Trascina i tasti rapidi (%s), gli oggetti o i poteri (%s) su questa barra.",
    zhcn  = "将快捷键（%s）、物品或力量（%s）拖动到此栏。",
    ja    = "ホットキー（%s）、アイテム、パワー（%s）をこのバーへドラッグしてください。",
    ko    = "단축키(%s), 아이템 또는 능력(%s)을 이 바에 드래그하세요.",
  },

  GameHotkeyBarsButtonVisibilityHide = {
    en    = "Hide hotkey bar",
    ptbr  = "Ocultar barra de atalhos",
    ptpt  = "Ocultar barra de atalhos",
    es419 = "Ocultar barra de atajos",
    eses  = "Ocultar barra de atajos",
    pl    = "Ukryj pasek skrótów",
    ru    = "Скрыть панель быстрых клавиш",
    sv    = "Dölj snabbknappsraden",
    nb    = "Skjul hurtigtastlinjen",
    de    = "Hotkey-Leiste ausblenden",
    nlnl  = "Sneltoetsbalk verbergen",
    frfr  = "Masquer la barre de raccourcis",
    fi    = "Piilota pikanäppäinpalkki",
    it    = "Nascondi la barra dei tasti rapidi",
    zhcn  = "隐藏快捷键栏",
    ja    = "ホットキーバーを隠す",
    ko    = "단축키 바 숨기기",
  },

  GameHotkeyBarsButtonVisibilityShow = {
    en    = "Show hotkey bar",
    ptbr  = "Exibir barra de atalhos",
    ptpt  = "Exibir barra de atalhos",
    es419 = "Mostrar barra de atajos",
    eses  = "Mostrar barra de atajos",
    pl    = "Pokaż pasek skrótów",
    ru    = "Показать панель быстрых клавиш",
    sv    = "Visa snabbknappsraden",
    nb    = "Vis hurtigtastlinjen",
    de    = "Hotkey-Leiste anzeigen",
    nlnl  = "Sneltoetsbalk tonen",
    frfr  = "Afficher la barre de raccourcis",
    fi    = "Näytä pikanäppäinpalkki",
    it    = "Mostra la barra dei tasti rapidi",
    zhcn  = "显示快捷键栏",
    ja    = "ホットキーバーを表示",
    ko    = "단축키 바 표시",
  },

  GameHotkeyBarsInfoContainerTooltipSendMessage = {
    en    = "Send message",
    ptbr  = "Enviar mensagem",
    ptpt  = "Enviar mensagem",
    es419 = "Enviar mensaje",
    eses  = "Enviar mensaje",
    pl    = "Wyślij wiadomość",
    ru    = "Отправить сообщение",
    sv    = "Skicka meddelande",
    nb    = "Send melding",
    de    = "Nachricht senden",
    nlnl  = "Bericht verzenden",
    frfr  = "Envoyer un message",
    fi    = "Lähetä viesti",
    it    = "Invia messaggio",
    zhcn  = "发送消息",
    ja    = "メッセージを送信",
    ko    = "메시지 보내기",
  },

  GameHotkeyBarsInfoContainerTooltipAuto = {
    en    = "auto",
    ptbr  = "automático",
    ptpt  = "automático",
    es419 = "automático",
    eses  = "automático",
    pl    = "automatyczny",
    ru    = "автоматический",
    sv    = "automatisk",
    nb    = "automatisk",
    de    = "automatisch",
    nlnl  = "automatisch",
    frfr  = "automatique",
    fi    = "automaattinen",
    it    = "automatico",
    zhcn  = "自动",
    ja    = "自動",
    ko    = "자동",
  },

  GameHotkeyBarsInfoContainerTooltipLevel = {
    en    = "level %d",
    ptbr  = "nível %d",
    ptpt  = "nível %d",
    es419 = "nivel %d",
    eses  = "nivel %d",
    pl    = "poziom %d",
    ru    = "уровень %d",
    sv    = "nivå %d",
    nb    = "nivå %d",
    de    = "Stufe %d",
    nlnl  = "niveau %d",
    frfr  = "niveau %d",
    fi    = "taso %d",
    it    = "livello %d",
    zhcn  = "等级 %d",
    ja    = "レベル%d",
    ko    = "레벨 %d",
  },

  GameHotkeyBarsInfoContainerUseItem = {
    en    = "Use item",
    ptbr  = "Usar item",
    ptpt  = "Usar item",
    es419 = "Usar objeto",
    eses  = "Usar objeto",
    pl    = "Użyj przedmiotu",
    ru    = "Использовать предмет",
    sv    = "Använd föremål",
    nb    = "Bruk gjenstand",
    de    = "Gegenstand verwenden",
    nlnl  = "Item gebruiken",
    frfr  = "Utiliser l'objet",
    fi    = "Käytä esinettä",
    it    = "Usa oggetto",
    zhcn  = "使用物品",
    ja    = "アイテムを使用",
    ko    = "아이템 사용",
  },

  GameHotkeyBarsInfoContainerUseOnYourself = {
    en    = "Use on yourself",
    ptbr  = "Usar em si",
    ptpt  = "Usar em si",
    es419 = "Usar en ti",
    eses  = "Usar en ti",
    pl    = "Użyj na sobie",
    ru    = "Использовать на себе",
    sv    = "Använd på dig själv",
    nb    = "Bruk på deg selv",
    de    = "Auf sich selbst anwenden",
    nlnl  = "Op jezelf gebruiken",
    frfr  = "Utiliser sur soi-même",
    fi    = "Käytä itseesi",
    it    = "Usa su te stesso",
    zhcn  = "对自己使用",
    ja    = "自分に使用",
    ko    = "자신에게 사용",
  },

  GameHotkeyBarsInfoContainerUseOnTarget = {
    en    = "Use on target",
    ptbr  = "Usar no alvo",
    ptpt  = "Usar no alvo",
    es419 = "Usar en el objetivo",
    eses  = "Usar en el objetivo",
    pl    = "Użyj na celu",
    ru    = "Использовать на цели",
    sv    = "Använd på målet",
    nb    = "Bruk på målet",
    de    = "Auf das Ziel anwenden",
    nlnl  = "Op het doel gebruiken",
    frfr  = "Utiliser sur la cible",
    fi    = "Käytä kohteeseen",
    it    = "Usa sul bersaglio",
    zhcn  = "对目标使用",
    ja    = "対象に使用",
    ko    = "대상에게 사용",
  },

  GameHotkeyBarsInfoContainerUseWith = {
    en    = "Use with",
    ptbr  = "Usar com",
    ptpt  = "Usar com",
    es419 = "Usar con",
    eses  = "Usar con",
    pl    = "Użyj z",
    ru    = "Использовать с",
    sv    = "Använd med",
    nb    = "Bruk med",
    de    = "Verwenden mit",
    nlnl  = "Gebruiken met",
    frfr  = "Utiliser avec",
    fi    = "Käytä yhdessä",
    it    = "Usa con",
    zhcn  = "与其一起使用",
    ja    = "これと使用",
    ko    = "함께 사용",
  },
})
