-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GamePlayerDeathMsgYouAreDead = {
    en    = "You are dead",
    ptbr  = "Você está morto",
    ptpt  = "Está morto",
    es419 = "Estás muerto",
    eses  = "Estás muerto",
    pl    = "Nie żyjesz",
    ru    = "Вы мертвы",
    sv    = "Du är död",
    nb    = "Du er død",
    de    = "Du bist tot",
    nlnl  = "Je bent dood",
    frfr  = "Vous êtes mort",
    fi    = "Olet kuollut",
    it    = "Sei morto",
    zhcn  = "你死了",
    ja    = "あなたは死亡しました",
    ko    = "사망했습니다",
  },

  GamePlayerDeathMsgRegular = {
    en    = "Alas!\n\nBrave adventurer, you have met a sad fate.\nBut do not despair, for the gods will bring you back into this world in exchange for a small sacrifice.\n\nSimply click on Ok to resume your journeys!",
    ptbr  = "Oh não!\n\nBravo aventureiro, você encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta para este mundo em troca de um pequeno sacrifício.\n\nSimplesmente clique em Ok para retomar suas jornadas!",
    ptpt  = "Oh não!\n\nBravo aventureiro, encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta para este mundo em troca de um pequeno sacrifício.\n\nSimplesmente clique em Ok para retomar as suas jornadas!",
    es419 = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo a cambio de un pequeño sacrificio.\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    eses  = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo a cambio de un pequeño sacrificio.\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    pl    = "O nie!\n\nDzielny poszukiwaczu przygód, spotkał cię smutny los.\nAle nie rozpaczaj, bogowie przywrócą cię na ten świat w zamian za małą ofiarę.\n\nPo prostu kliknij OK, aby wznowić swoje podróże!",
    ru    = "О нет!\n\nХрабрый искатель приключений, вас постигла печальная судьба.\nНо не отчаивайтесь: боги вернут вас в этот мир в обмен на небольшую жертву.\n\nПросто нажмите «ОК», чтобы продолжить свои приключения!",
    sv    = "Åh nej!\n\nModige äventyrare, du har mött ett sorgligt öde.\nMen förtvivla inte, för gudarna kommer att återföra dig till denna värld i utbyte mot ett litet offer.\n\nKlicka helt enkelt på OK för att återuppta dina resor!",
    nb    = "Å nei!\n\nModige eventyrer, du har møtt en trist skjebne.\nMen fortvil ikke, for gudene vil bringe deg tilbake til denne verden i bytte mot et lite offer.\n\nKlikk ganske enkelt på OK for å fortsette dine reiser!",
    de    = "Oh nein!\n\nTapferer Abenteurer, dich hat ein trauriges Schicksal ereilt.\nAber verzweifle nicht, denn die Götter werden dich gegen ein kleines Opfer in diese Welt zurückbringen.\n\nKlicke einfach auf OK, um deine Reisen fortzusetzen!",
    nlnl  = "O nee!\n\nDappere avonturier, je bent een droevig lot tegemoetgegaan.\nMaar wanhoop niet, want de goden zullen je terugbrengen naar deze wereld in ruil voor een klein offer.\n\nKlik eenvoudig op OK om je reizen te hervatten!",
    frfr  = "Oh non !\n\nCourageux aventurier, vous avez connu un triste destin.\nMais ne désespérez pas, car les dieux vous ramèneront dans ce monde en échange d'un petit sacrifice.\n\nCliquez simplement sur OK pour reprendre vos aventures !",
    fi    = "Voi ei!\n\nUrhea seikkailija, olet kohdannut surullisen kohtalon.\nÄlä kuitenkaan vaivu epätoivoon, sillä jumalat palauttavat sinut tähän maailmaan pientä uhrausta vastaan.\n\nNapsauta vain OK jatkaaksesi seikkailujasi!",
    it    = "Oh no!\n\nCoraggioso avventuriero, hai incontrato un triste destino.\nMa non disperare: gli dèi ti riporteranno in questo mondo in cambio di un piccolo sacrificio.\n\nFai semplicemente clic su OK per riprendere i tuoi viaggi!",
    zhcn  = "哦，不！\n\n勇敢的冒险者，你遭遇了悲惨的命运。\n但不要绝望，诸神会让你以小小的牺牲回到这个世界。\n\n只需点击“确定”即可继续你的旅程！",
    ja    = "ああ！\n\n勇敢な冒険者よ、悲しい運命を迎えました。\nしかし絶望しないでください。神々は小さな犠牲と引き換えに、あなたをこの世界へ戻してくれます。\n\n「OK」をクリックして旅を再開してください！",
    ko    = "아, 안타깝습니다!\n\n용감한 모험가여, 슬픈 운명을 맞이했습니다.\n하지만 절망하지 마십시오. 신들은 작은 희생을 대가로 당신을 이 세상으로 다시 데려올 것입니다.\n\nOK를 클릭하여 여정을 계속하십시오!",
  },

  GamePlayerDeathMsgUnfair = {
    en    = "Alas!\n\nBrave adventurer, you have met a sad fate.\nBut do not despair, for the gods will bring you back into this world in exchange for a small sacrifice.\n\nThis death penalty has been reduced by %i%%.\n\nSimply click on Ok to resume your journeys!",
    ptbr  = "Oh não!\n\nBravo aventureiro, você encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta para este mundo em troca de um pequeno sacrifício.\n\nEsta penalidade de morte foi reduzida em %i%%.\n\nSimplesmente clique em Ok para retomar suas jornadas!",
    ptpt  = "Oh não!\n\nBravo aventureiro, encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta para este mundo em troca de um pequeno sacrifício.\n\nEsta penalidade de morte foi reduzida em %i%%.\n\nSimplesmente clique em Ok para retomar as suas jornadas!",
    es419 = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo a cambio de un pequeño sacrificio.\n\n¡Esta penalización por muerte se ha reducido en un %i%%!\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    eses  = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo a cambio de un pequeño sacrificio.\n\n¡Esta penalización por muerte se ha reducido en un %i%%!\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    pl    = "O nie!\n\nDzielny poszukiwaczu przygód, spotkał cię smutny los.\nAle nie rozpaczaj, bogowie przywrócą cię na ten świat w zamian za małą ofiarę.\n\nTa kara za śmierć została zmniejszona o %i%%.\n\nPo prostu kliknij OK, aby wznowić swoje podróże!",
    ru    = "О нет!\n\nХрабрый искатель приключений, вас постигла печальная судьба.\nНо не отчаивайтесь: боги вернут вас в этот мир в обмен на небольшую жертву.\n\nШтраф за смерть уменьшен на %i%%.\n\nПросто нажмите «ОК», чтобы продолжить свои приключения!",
    sv    = "Åh nej!\n\nModige äventyrare, du har mött ett sorgligt öde.\nMen förtvivla inte, för gudarna kommer att återföra dig till denna värld i utbyte mot ett litet offer.\n\nDödsstraffet har minskats med %i%%.\n\nKlicka helt enkelt på OK för att återuppta dina resor!",
    nb    = "Å nei!\n\nModige eventyrer, du har møtt en trist skjebne.\nMen fortvil ikke, for gudene vil bringe deg tilbake til denne verden i bytte mot et lite offer.\n\nDødsstraffen er redusert med %i%%.\n\nKlikk ganske enkelt på OK for å fortsette dine reiser!",
    de    = "Oh nein!\n\nTapferer Abenteurer, dich hat ein trauriges Schicksal ereilt.\nAber verzweifle nicht, denn die Götter werden dich gegen ein kleines Opfer in diese Welt zurückbringen.\n\nDiese Todesstrafe wurde um %i%% reduziert.\n\nKlicke einfach auf OK, um deine Reisen fortzusetzen!",
    nlnl  = "O nee!\n\nDappere avonturier, je bent een droevig lot tegemoetgegaan.\nMaar wanhoop niet, want de goden zullen je terugbrengen naar deze wereld in ruil voor een klein offer.\n\nDe straf voor je dood is met %i%% verminderd.\n\nKlik eenvoudig op OK om je reizen te hervatten!",
    frfr  = "Oh non !\n\nCourageux aventurier, vous avez connu un triste destin.\nMais ne désespérez pas, car les dieux vous ramèneront dans ce monde en échange d'un petit sacrifice.\n\nLa pénalité de mort a été réduite de %i%%.\n\nCliquez simplement sur OK pour reprendre vos aventures !",
    fi    = "Voi ei!\n\nUrhea seikkailija, olet kohdannut surullisen kohtalon.\nÄlä kuitenkaan vaivu epätoivoon, sillä jumalat palauttavat sinut tähän maailmaan pientä uhrausta vastaan.\n\nKuolemanrangaistusta on pienennetty %i%%.\n\nNapsauta vain OK jatkaaksesi seikkailujasi!",
    it    = "Oh no!\n\nCoraggioso avventuriero, hai incontrato un triste destino.\nMa non disperare: gli dèi ti riporteranno in questo mondo in cambio di un piccolo sacrificio.\n\nLa penalità di morte è stata ridotta del %i%%.\n\nFai semplicemente clic su OK per riprendere i tuoi viaggi!",
    zhcn  = "哦，不！\n\n勇敢的冒险者，你遭遇了悲惨的命运。\n但不要绝望，诸神会让你以小小的牺牲回到这个世界。\n\n死亡惩罚减少了 %i%%。\n\n只需点击“确定”即可继续你的旅程！",
    ja    = "ああ！\n\n勇敢な冒険者よ、悲しい運命を迎えました。\nしかし絶望しないでください。神々は小さな犠牲と引き換えに、あなたをこの世界へ戻してくれます。\n\nこの死亡ペナルティは%i%%軽減されました。\n\n「OK」をクリックして旅を再開してください！",
    ko    = "아, 안타깝습니다!\n\n용감한 모험가여, 슬픈 운명을 맞이했습니다.\n하지만 절망하지 마십시오. 신들은 작은 희생을 대가로 당신을 이 세상으로 다시 데려올 것입니다.\n\n사망 페널티가 %i%% 감소했습니다.\n\nOK를 클릭하여 여정을 계속하십시오!",
  },

  GamePlayerDeathMsgBlessed = {
    en    = "Alas!\n\nBrave adventurer, you have met a sad fate.\nBut do not despair, for the gods will bring you back into this world.\n\nThis death penalty has been reduced by 100%%.\n\nSimply click on Ok to resume your journeys!",
    ptbr  = "Oh não!\n\nBravo aventureiro, você encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta a este mundo.\n\nEsta penalidade de morte foi reduzida em 100%%.\n\nSimplesmente clique em Ok para retomar suas jornadas!",
    ptpt  = "Oh não!\n\nBravo aventureiro, encontrou um destino triste.\nMas não desespere, pois os deuses o trarão de volta a este mundo.\n\nEsta penalidade de morte foi reduzida em 100%%.\n\nSimplesmente clique em Ok para retomar as suas jornadas!",
    es419 = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo.\n\n¡Esta penalización por muerte se ha reducido en un 100%%!\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    eses  = "¡Oh, no!\n\nValiente aventurero, has encontrado un triste destino.\nPero no desesperes, porque los dioses te traerán de vuelta a este mundo.\n\n¡Esta penalización por muerte se ha reducido en un 100%%!\n\n¡Simplemente haz clic en Aceptar para reanudar tus viajes!",
    pl    = "O nie!\n\nDzielny poszukiwaczu przygód, spotkał cię smutny los.\nAle nie rozpaczaj, bogowie przywrócą cię na ten świat.\n\nKara za śmierć została zmniejszona o 100%%.\n\nPo prostu kliknij OK, aby wznowić swoje podróże!",
    ru    = "О нет!\n\nХрабрый искатель приключений, вас постигла печальная судьба.\nНо не отчаивайтесь: боги вернут вас в этот мир.\n\nШтраф за смерть уменьшен на 100%%.\n\nПросто нажмите «ОК», чтобы продолжить свои приключения!",
    sv    = "Åh nej!\n\nModige äventyrare, du har mött ett sorgligt öde.\nMen förtvivla inte, för gudarna kommer att återföra dig till denna värld.\n\nDödsstraffet har minskats med 100%%.\n\nKlicka helt enkelt på OK för att återuppta dina resor!",
    nb    = "Å nei!\n\nModige eventyrer, du har møtt en trist skjebne.\nMen fortvil ikke, for gudene vil bringe deg tilbake til denne verden.\n\nDødsstraffen er redusert med 100%%.\n\nKlikk ganske enkelt på OK for å fortsette dine reiser!",
    de    = "Oh nein!\n\nTapferer Abenteurer, dich hat ein trauriges Schicksal ereilt.\nAber verzweifle nicht, denn die Götter werden dich in diese Welt zurückbringen.\n\nDiese Todesstrafe wurde um 100%% reduziert.\n\nKlicke einfach auf OK, um deine Reisen fortzusetzen!",
    nlnl  = "O nee!\n\nDappere avonturier, je bent een droevig lot tegemoetgegaan.\nMaar wanhoop niet, want de goden zullen je terugbrengen naar deze wereld.\n\nDe straf voor je dood is met 100%% verminderd.\n\nKlik eenvoudig op OK om je reizen te hervatten!",
    frfr  = "Oh non !\n\nCourageux aventurier, vous avez connu un triste destin.\nMais ne désespérez pas, car les dieux vous ramèneront dans ce monde.\n\nLa pénalité de mort a été réduite de 100%%.\n\nCliquez simplement sur OK pour reprendre vos aventures !",
    fi    = "Voi ei!\n\nUrhea seikkailija, olet kohdannut surullisen kohtalon.\nÄlä kuitenkaan vaivu epätoivoon, sillä jumalat palauttavat sinut tähän maailmaan.\n\nKuolemanrangaistusta on pienennetty 100%%.\n\nNapsauta vain OK jatkaaksesi seikkailujasi!",
    it    = "Oh no!\n\nCoraggioso avventuriero, hai incontrato un triste destino.\nMa non disperare: gli dèi ti riporteranno in questo mondo.\n\nLa penalità di morte è stata ridotta del 100%%.\n\nFai semplicemente clic su OK per riprendere i tuoi viaggi!",
    zhcn  = "哦，不！\n\n勇敢的冒险者，你遭遇了悲惨的命运。\n但不要绝望，诸神会让你回到这个世界。\n\n死亡惩罚减少了 100%%。\n\n只需点击“确定”即可继续你的旅程！",
    ja    = "ああ！\n\n勇敢な冒険者よ、悲しい運命を迎えました。\nしかし絶望しないでください。神々はあなたをこの世界へ戻してくれます。\n\nこの死亡ペナルティは100%%軽減されました。\n\n「OK」をクリックして旅を再開してください！",
    ko    = "아, 안타깝습니다!\n\n용감한 모험가여, 슬픈 운명을 맞이했습니다.\n하지만 절망하지 마십시오. 신들은 당신을 이 세상으로 다시 데려올 것입니다.\n\n사망 페널티가 100%% 감소했습니다.\n\nOK를 클릭하여 여정을 계속하십시오!",
  },
})
