-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameUnjustifiedPointsWindowTitle = {
    en    = "Frags",
    ptbr  = "Abates",
    ptpt  = "Abates",
    es419 = "Abates",
    eses  = "Abates",
    pl    = "Zabójstwa",
    ru    = "Убийства",
    sv    = "Dödanden",
    nb    = "Drap",
    de    = "Tötungen",
    nlnl  = "Doden",
    frfr  = "Meurtres",
    fi    = "Tapot",
    it    = "Uccisioni",
    zhcn  = "击杀数",
    ja    = "キル数",
    ko    = "처치 수",
  },

  GameUnjustifiedPointsInfoFrags = {
    en    = "frags",
    ptbr  = "abates",
    ptpt  = "abates",
    es419 = "abates",
    eses  = "abates",
    pl    = "zabójstwa",
    ru    = "убийства",
    sv    = "dödanden",
    nb    = "drap",
    de    = "Tötungen",
    nlnl  = "doden",
    frfr  = "meurtres",
    fi    = "tapot",
    it    = "uccisioni",
    zhcn  = "击杀数",
    ja    = "キル数",
    ko    = "처치 수",
  },

  GameUnjustifiedPointsInfoNextFragTime = {
    en    = "Next frag will be lost in",
    ptbr  = "O próximo abate será perdido em",
    ptpt  = "O próximo abate será perdido em",
    es419 = "El próximo abate se perderá en",
    eses  = "El próximo abate se perderá en",
    pl    = "Następne zabójstwo zostanie utracone za",
    ru    = "Следующее убийство будет потеряно через",
    sv    = "Nästa dödande försvinner om",
    nb    = "Neste drapet forsvinner om",
    de    = "Der nächste Kill verfällt in",
    nlnl  = "De volgende kill vervalt over",
    frfr  = "Le prochain meurtre sera perdu dans",
    fi    = "Seuraava tappo menetetään",
    it    = "La prossima uccisione verrà persa tra",
    zhcn  = "下一个击杀将在以下时间后失效",
    ja    = "次のキルが失われるまで",
    ko    = "다음 처치 수가 사라지는 시간:",
  },

  GameUnjustifiedPointsInfoTotalFrags = {
    en    = "Total frags",
    ptbr  = "Abates totais",
    ptpt  = "Abates totais",
    es419 = "Abates totales",
    eses  = "Abates totales",
    pl    = "Łączna liczba zabójstw",
    ru    = "Всего убийств",
    sv    = "Totalt antal dödanden",
    nb    = "Totalt antall drap",
    de    = "Gesamtzahl der Tötungen",
    nlnl  = "Totaal aantal doden",
    frfr  = "Total des meurtres",
    fi    = "Tapot yhteensä",
    it    = "Totale uccisioni",
    zhcn  = "击杀总数",
    ja    = "キル合計",
    ko    = "총 처치 수",
  },

  GameUnjustifiedPointsInfoFragsRemainingTime = {
    en    = "All frags will be lost in",
    ptbr  = "Todos os abates serão perdidos em",
    ptpt  = "Todos os abates serão perdidos em",
    es419 = "Todos los abates se perderán en",
    eses  = "Todos los abates se perderán en",
    pl    = "Wszystkie zabójstwa zostaną utracone za",
    ru    = "Все убийства будут потеряны через",
    sv    = "Alla dödanden försvinner om",
    nb    = "Alle drap forsvinner om",
    de    = "Alle Tötungen verfallen in",
    nlnl  = "Alle doden vervallen over",
    frfr  = "Tous les meurtres seront perdus dans",
    fi    = "Kaikki tapot menetetään",
    it    = "Tutte le uccisioni verranno perse tra",
    zhcn  = "所有击杀将在以下时间后失效",
    ja    = "すべてのキルが失われるまで",
    ko    = "모든 처치 수가 사라지는 시간:",
  },

  GameUnjustifiedPointsInfoCurrentSkull = {
    en    = "Your current skull",
    ptbr  = "Sua caveira atual",
    ptpt  = "Sua caveira atual",
    es419 = "Tu calavera actual",
    eses  = "Tu calavera actual",
    pl    = "Twoja obecna czaszka",
    ru    = "Ваш текущий череп",
    sv    = "Din nuvarande skalle",
    nb    = "Din nåværende hodeskalle",
    de    = "Dein aktueller Totenkopf",
    nlnl  = "Je huidige schedel",
    frfr  = "Votre crâne actuel",
    fi    = "Nykyinen kallosi",
    it    = "Il tuo teschio attuale",
    zhcn  = "你当前的骷髅",
    ja    = "現在のスカル",
    ko    = "현재 해골",
  },

  GameUnjustifiedPointsInfoNoSkull = {
    en    = "You have no skull",
    ptbr  = "Você não tem caveira",
    ptpt  = "Você não tem caveira",
    es419 = "No tienes calavera",
    eses  = "No tienes calavera",
    pl    = "Nie masz czaszki",
    ru    = "У вас нет черепа",
    sv    = "Du har ingen skalle",
    nb    = "Du har ingen hodeskalle",
    de    = "Du hast keinen Totenkopf",
    nlnl  = "Je hebt geen schedel",
    frfr  = "Vous n'avez pas de crâne",
    fi    = "Sinulla ei ole kalloa",
    it    = "Non hai alcun teschio",
    zhcn  = "你没有骷髅",
    ja    = "スカルなし",
    ko    = "해골 없음",
  },

  GameUnjustifiedPointsInfoFragsUntilSkullRed = {
    en    = "Frags until red skull",
    ptbr  = "Abates até a caveira vermelha",
    ptpt  = "Abates até à caveira vermelha",
    es419 = "Abates hasta la calavera roja",
    eses  = "Abates hasta la calavera roja",
    pl    = "Zabójstwa do czerwonej czaszki",
    ru    = "Убийства до красного черепа",
    sv    = "Dödanden till röd skalle",
    nb    = "Drap til rød hodeskalle",
    de    = "Tötungen bis zum roten Totenkopf",
    nlnl  = "Doden tot de rode schedel",
    frfr  = "Meurtres avant le crâne rouge",
    fi    = "Tapot punaiseen kalloon asti",
    it    = "Uccisioni fino al teschio rosso",
    zhcn  = "距离红骷髅还需要的击杀数",
    ja    = "赤スカルまでのキル数",
    ko    = "붉은 해골까지 필요한 처치 수",
  },

  GameUnjustifiedPointsInfoFragsUntilSkullBlack = {
    en    = "Frags until black skull",
    ptbr  = "Abates até a caveira preta",
    ptpt  = "Abates até à caveira preta",
    es419 = "Abates hasta la calavera negra",
    eses  = "Abates hasta la calavera negra",
    pl    = "Zabójstwa do czarnej czaszki",
    ru    = "Убийства до чёрного черепа",
    sv    = "Dödanden till svart skalle",
    nb    = "Drap til svart hodeskalle",
    de    = "Tötungen bis zum schwarzen Totenkopf",
    nlnl  = "Doden tot de zwarte schedel",
    frfr  = "Meurtres avant le crâne noir",
    fi    = "Tapot mustaan kalloon asti",
    it    = "Uccisioni fino al teschio nero",
    zhcn  = "距离黑骷髅还需要的击杀数",
    ja    = "黒スカルまでのキル数",
    ko    = "검은 해골까지 필요한 처치 수",
  },
})
