-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  ClientStylesButtonLockTooltip = {
    en    = "Lock",
    ptbr  = "Travar",
    ptpt  = "Travar",
    es419 = "Bloquear",
    eses  = "Bloquear",
    pl    = "Zablokuj",
    ru    = "Заблокировать",
    sv    = "Lås",
    nb    = "Lås",
    de    = "Sperren",
    nlnl  = "Vergrendelen",
    frfr  = "Verrouiller",
    fi    = "Lukitse",
    it    = "Blocca",
    zhcn  = "锁定",
    ja    = "ロック",
    ko    = "잠금",
  },

  ClientStylesButtonUnlockTooltip = {
    en    = "Unlock",
    ptbr  = "Destravar",
    ptpt  = "Destravar",
    es419 = "Desbloquear",
    eses  = "Desbloquear",
    pl    = "Odblokuj",
    ru    = "Разблокировать",
    sv    = "Lås upp",
    nb    = "Lås opp",
    de    = "Entsperren",
    nlnl  = "Ontgrendelen",
    frfr  = "Déverrouiller",
    fi    = "Avaa lukitus",
    it    = "Sblocca",
    zhcn  = "解锁",
    ja    = "ロック解除",
    ko    = "잠금 해제",
  },

  ClientStylesButtonMinimizeTooltip = {
    en    = "Minimize",
    ptbr  = "Minimizar",
    ptpt  = "Minimizar",
    es419 = "Minimizar",
    eses  = "Minimizar",
    pl    = "Zminimalizuj",
    ru    = "Свернуть",
    sv    = "Minimera",
    nb    = "Minimer",
    de    = "Minimieren",
    nlnl  = "Minimaliseren",
    frfr  = "Réduire",
    fi    = "Pienennä",
    it    = "Riduci a icona",
    zhcn  = "最小化",
    ja    = "最小化",
    ko    = "최소화",
  },

  ClientStylesButtonMaximizeTooltip = {
    en    = "Maximize",
    ptbr  = "Maximizar",
    ptpt  = "Maximizar",
    es419 = "Maximizar",
    eses  = "Maximizar",
    pl    = "Zmaksymalizuj",
    ru    = "Развернуть",
    sv    = "Maximera",
    nb    = "Maksimer",
    de    = "Maximieren",
    nlnl  = "Maximaliseren",
    frfr  = "Agrandir",
    fi    = "Suurenna",
    it    = "Massimizza",
    zhcn  = "最大化",
    ja    = "最大化",
    ko    = "최대화",
  },

  ClientStylesMapInfoAddMark = {
    en    = "Add new map mark",
    ptbr  = "Adicionar nova marca no mapa",
    ptpt  = "Adicionar nova marca no mapa",
    es419 = "Agregar una nueva marca en el mapa",
    eses  = "Agregar una nueva marca en el mapa",
    pl    = "Dodaj nowy znacznik na mapie",
    ru    = "Добавить новую метку на карту",
    sv    = "Lägg till en ny kartmarkering",
    nb    = "Legg til en ny kartmarkering",
    de    = "Neue Kartenmarkierung hinzufügen",
    nlnl  = "Nieuwe kaartmarkering toevoegen",
    frfr  = "Ajouter un nouveau repère sur la carte",
    fi    = "Lisää uusi karttamerkki",
    it    = "Aggiungi un nuovo segnaposto sulla mappa",
    zhcn  = "添加新的地图标记",
    ja    = "新しい地図マークを追加",
    ko    = "새 지도 표시 추가",
  },

  ClientStylesMapInfoPosition = {
    en    = "Position",
    ptbr  = "Posição",
    ptpt  = "Posição",
    es419 = "Posición",
    eses  = "Posición",
    pl    = "Pozycja",
    ru    = "Позиция",
    sv    = "Position",
    nb    = "Posisjon",
    de    = "Position",
    nlnl  = "Positie",
    frfr  = "Position",
    fi    = "Sijainti",
    it    = "Posizione",
    zhcn  = "位置",
    ja    = "位置",
    ko    = "위치",
  },

  ClientStylesMapInfoEditMark = {
    en    = "Edit map mark",
    ptbr  = "Editar marca do mapa",
    ptpt  = "Editar marca do mapa",
    es419 = "Editar marca del mapa",
    eses  = "Editar marca del mapa",
    pl    = "Edytuj znacznik mapy",
    ru    = "Изменить метку на карте",
    sv    = "Redigera kartmarkering",
    nb    = "Rediger kartmarkering",
    de    = "Kartenmarkierung bearbeiten",
    nlnl  = "Kaartmarkering bewerken",
    frfr  = "Modifier le repère de la carte",
    fi    = "Muokkaa karttamerkkiä",
    it    = "Modifica il segnaposto sulla mappa",
    zhcn  = "编辑地图标记",
    ja    = "地図マークを編集",
    ko    = "지도 표시 편집",
  },
})
