-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameNpcTradeNpcWindowTitle = {
    en    = "NPC trade",
    ptbr  = "Comércio com NPC",
    ptpt  = "Comércio com NPC",
    es419 = "Comercio con NPC",
    eses  = "Comercio con NPC",
    pl    = "Handel z NPC",
    ru    = "Торговля с NPC",
    sv    = "Handel med NPC",
    nb    = "Handel med NPC",
    de    = "Handel mit NPC",
    nlnl  = "Handel met NPC",
    frfr  = "Commerce avec un PNJ",
    fi    = "Kaupankäynti NPC:n kanssa",
    it    = "Commercio con NPC",
    zhcn  = "与 NPC 交易",
    ja    = "NPCとの取引",
    ko    = "NPC와 거래",
  },

  GameNpcTradeButtonTrade = {
    en    = "Buy",
    ptbr  = "Comprar",
    ptpt  = "Comprar",
    es419 = "Comprar",
    eses  = "Comprar",
    pl    = "Kup",
    ru    = "Купить",
    sv    = "Köp",
    nb    = "Kjøp",
    de    = "Kaufen",
    nlnl  = "Kopen",
    frfr  = "Acheter",
    fi    = "Osta",
    it    = "Compra",
    zhcn  = "购买",
    ja    = "購入",
    ko    = "구매",
  },

  GameNpcTradeButtonSellAll = {
    en    = "Sell all",
    ptbr  = "Vender tudo",
    ptpt  = "Vender tudo",
    es419 = "Vender todo",
    eses  = "Vender todo",
    pl    = "Sprzedaj wszystko",
    ru    = "Продать всё",
    sv    = "Sälj allt",
    nb    = "Selg alt",
    de    = "Alles verkaufen",
    nlnl  = "Alles verkopen",
    frfr  = "Tout vendre",
    fi    = "Myy kaikki",
    it    = "Vendi tutto",
    zhcn  = "全部出售",
    ja    = "すべて売却",
    ko    = "모두 판매",
  },

  GameNpcTradeSearchLabel = {
    en    = "Search",
    ptbr  = "Buscar",
    ptpt  = "Buscar",
    es419 = "Buscar",
    eses  = "Buscar",
    pl    = "Szukaj",
    ru    = "Поиск",
    sv    = "Sök",
    nb    = "Søk",
    de    = "Suchen",
    nlnl  = "Zoeken",
    frfr  = "Rechercher",
    fi    = "Haku",
    it    = "Cerca",
    zhcn  = "搜索",
    ja    = "検索",
    ko    = "검색",
  },

  GameNpcTradeBankTrade = {
    en    = "Use bank money/KAps",
    ptbr  = "Usar dinheiro/KAps do banco",
    ptpt  = "Usar dinheiro/KAps do banco",
    es419 = "Usar dinero/KAps del banco",
    eses  = "Usar dinero/KAps del banco",
    pl    = "Użyj pieniędzy/KAps z banku",
    ru    = "Использовать деньги/KAps из банка",
    sv    = "Använd pengar/KAps från banken",
    nb    = "Bruk penger/KAps fra banken",
    de    = "Bankgeld/KAps verwenden",
    nlnl  = "Geld/KAps van de bank gebruiken",
    frfr  = "Utiliser l'argent/les KAps de la banque",
    fi    = "Käytä pankin rahaa/KAps-pisteitä",
    it    = "Usa il denaro/KAps della banca",
    zhcn  = "使用银行资金/KAps",
    ja    = "銀行のお金/KApsを使用",
    ko    = "은행의 돈/KAps 사용",
  },

  GameNpcTradeBuyWithBackpack = {
    en    = "Buy with backpack",
    ptbr  = "Comprar com mochila",
    ptpt  = "Comprar com mochila",
    es419 = "Comprar con mochila",
    eses  = "Comprar con mochila",
    pl    = "Kup z plecakiem",
    ru    = "Купить с рюкзаком",
    sv    = "Köp med ryggsäck",
    nb    = "Kjøp med ryggsekk",
    de    = "Mit Rucksack kaufen",
    nlnl  = "Kopen met rugzak",
    frfr  = "Acheter avec le sac à dos",
    fi    = "Osta repun kanssa",
    it    = "Compra con lo zaino",
    zhcn  = "使用背包购买",
    ja    = "バックパック付きで購入",
    ko    = "배낭과 함께 구매",
  },

  GameNpcTradeIgnoreCapacity = {
    en    = "Ignore capacity",
    ptbr  = "Ignorar capacidade",
    ptpt  = "Ignorar capacidade",
    es419 = "Ignorar capacidad",
    eses  = "Ignorar capacidad",
    pl    = "Ignoruj pojemność",
    ru    = "Игнорировать вместимость",
    sv    = "Ignorera kapacitet",
    nb    = "Ignorer kapasitet",
    de    = "Kapazität ignorieren",
    nlnl  = "Capaciteit negeren",
    frfr  = "Ignorer la capacité",
    fi    = "Ohita kapasiteetti",
    it    = "Ignora la capacità",
    zhcn  = "忽略容量",
    ja    = "容量を無視",
    ko    = "용량 무시",
  },

  GameNpcTradeShowAllItems = {
    en    = "Show all items",
    ptbr  = "Mostrar todos os itens",
    ptpt  = "Mostrar todos os itens",
    es419 = "Mostrar todos los ítems",
    eses  = "Mostrar todos los objetos",
    pl    = "Pokaż wszystkie przedmioty",
    ru    = "Показывать все предметы",
    sv    = "Visa alla föremål",
    nb    = "Vis alle gjenstander",
    de    = "Alle Gegenstände anzeigen",
    nlnl  = "Alle items tonen",
    frfr  = "Afficher tous les objets",
    fi    = "Näytä kaikki esineet",
    it    = "Mostra tutti gli oggetti",
    zhcn  = "显示所有物品",
    ja    = "すべてのアイテムを表示",
    ko    = "모든 아이템 표시",
  },

  GameNpcTradePriceDesc = {
    en    = "Price",
    ptbr  = "Preço",
    ptpt  = "Preço",
    es419 = "Precio",
    eses  = "Precio",
    pl    = "Cena",
    ru    = "Цена",
    sv    = "Pris",
    nb    = "Pris",
    de    = "Preis",
    nlnl  = "Prijs",
    frfr  = "Prix",
    fi    = "Hinta",
    it    = "Prezzo",
    zhcn  = "价格",
    ja    = "価格",
    ko    = "가격",
  },

  GameNpcTradeWeightDesc = {
    en    = "Weight",
    ptbr  = "Peso",
    ptpt  = "Peso",
    es419 = "Peso",
    eses  = "Peso",
    pl    = "Waga",
    ru    = "Вес",
    sv    = "Vikt",
    nb    = "Vekt",
    de    = "Gewicht",
    nlnl  = "Gewicht",
    frfr  = "Poids",
    fi    = "Paino",
    it    = "Peso",
    zhcn  = "重量",
    ja    = "重量",
    ko    = "무게",
  },

  GameNpcTradeMoneyDesc = {
    en    = "Money",
    ptbr  = "Dinheiro",
    ptpt  = "Dinheiro",
    es419 = "Dinero",
    eses  = "Dinero",
    pl    = "Pieniądze",
    ru    = "Деньги",
    sv    = "Pengar",
    nb    = "Penger",
    de    = "Geld",
    nlnl  = "Geld",
    frfr  = "Argent",
    fi    = "Raha",
    it    = "Denaro",
    zhcn  = "金钱",
    ja    = "お金",
    ko    = "돈",
  },

  GameNpcTradeKapsDesc = {
    en    = "KAps",
    ptbr  = "KAps",
    ptpt  = "KAps",
    es419 = "KAps",
    eses  = "KAps",
    pl    = "KAps",
    ru    = "KAps",
    sv    = "KAps",
    nb    = "KAps",
    de    = "KAps",
    nlnl  = "KAps",
    frfr  = "KAps",
    fi    = "KAps",
    it    = "KAps",
    zhcn  = "KAps",
    ja    = "KAps",
    ko    = "KAps",
  },

  GameNpcTradeCapacityDesc = {
    en    = "Capacity",
    ptbr  = "Capacidade",
    ptpt  = "Capacidade",
    es419 = "Capacidad",
    eses  = "Capacidad",
    pl    = "Pojemność",
    ru    = "Вместимость",
    sv    = "Kapacitet",
    nb    = "Kapasitet",
    de    = "Kapazität",
    nlnl  = "Capaciteit",
    frfr  = "Capacité",
    fi    = "Kantokyky",
    it    = "Capacità",
    zhcn  = "容量",
    ja    = "容量",
    ko    = "소지 용량",
  },

  GameNpcTradeTrustDesc = {
    en    = "Trust",
    ptbr  = "Confiança",
    ptpt  = "Confiança",
    es419 = "Confianza",
    eses  = "Confianza",
    pl    = "Zaufanie",
    ru    = "Доверие",
    sv    = "Förtroende",
    nb    = "Tillit",
    de    = "Vertrauen",
    nlnl  = "Vertrouwen",
    frfr  = "Confiance",
    fi    = "Luottamus",
    it    = "Fiducia",
    zhcn  = "信任",
    ja    = "信頼度",
    ko    = "신뢰",
  },

  GameNpcTradeNameDescTooltip = {
    en    = "Item name",
    ptbr  = "Nome do item",
    ptpt  = "Nome do item",
    es419 = "Nombre del ítem",
    eses  = "Nombre del objeto",
    pl    = "Nazwa przedmiotu",
    ru    = "Название предмета",
    sv    = "Föremålsnamn",
    nb    = "Gjenstandsnavn",
    de    = "Gegenstandsname",
    nlnl  = "Itemnaam",
    frfr  = "Nom de l'objet",
    fi    = "Esineen nimi",
    it    = "Nome dell'oggetto",
    zhcn  = "物品名称",
    ja    = "アイテム名",
    ko    = "아이템 이름",
  },

  GameNpcTradePriceDescTooltip = {
    en    = "Item price",
    ptbr  = "Preço do item",
    ptpt  = "Preço do item",
    es419 = "Precio del ítem",
    eses  = "Precio del objeto",
    pl    = "Cena przedmiotu",
    ru    = "Цена предмета",
    sv    = "Föremålets pris",
    nb    = "Gjenstandens pris",
    de    = "Preis des Gegenstands",
    nlnl  = "Prijs van het item",
    frfr  = "Prix de l'objet",
    fi    = "Esineen hinta",
    it    = "Prezzo dell'oggetto",
    zhcn  = "物品价格",
    ja    = "アイテムの価格",
    ko    = "아이템 가격",
  },

  GameNpcTradeWeightDescTooltip = {
    en    = "Item weight",
    ptbr  = "Peso do item",
    ptpt  = "Peso do item",
    es419 = "Peso del ítem",
    eses  = "Peso del objeto",
    pl    = "Waga przedmiotu",
    ru    = "Вес предмета",
    sv    = "Föremålets vikt",
    nb    = "Gjenstandens vekt",
    de    = "Gewicht des Gegenstands",
    nlnl  = "Gewicht van het item",
    frfr  = "Poids de l'objet",
    fi    = "Esineen paino",
    it    = "Peso dell'oggetto",
    zhcn  = "物品重量",
    ja    = "アイテムの重量",
    ko    = "아이템 무게",
  },

  GameNpcTradeMoneyDescTooltip = {
    en    = "Your money",
    ptbr  = "Seu dinheiro",
    ptpt  = "Seu dinheiro",
    es419 = "Tu dinero",
    eses  = "Tu dinero",
    pl    = "Twoje pieniądze",
    ru    = "Ваши деньги",
    sv    = "Dina pengar",
    nb    = "Dine penger",
    de    = "Dein Geld",
    nlnl  = "Je geld",
    frfr  = "Votre argent",
    fi    = "Rahasi",
    it    = "Il tuo denaro",
    zhcn  = "你的钱",
    ja    = "所持金",
    ko    = "보유 금액",
  },

  GameNpcTradeKapsDescTooltip = { -- não traduza Kingdom Age
    en    = "Your KAps (Kingdom Age points)",
    ptbr  = "Seus KAps (pontos do Kingdom Age)",
    ptpt  = "Os seus KAps (pontos do Kingdom Age)",
    es419 = "Tus KAps (puntos de Kingdom Age)",
    eses  = "Tus KAps (puntos de Kingdom Age)",
    pl    = "Twoje KAps (punkty Kingdom Age)",
    ru    = "Ваши KAps (очки Kingdom Age)",
    sv    = "Dina KAps (Kingdom Age-poäng)",
    nb    = "Dine KAps (Kingdom Age-poeng)",
    de    = "Deine KAps (Kingdom Age-Punkte)",
    nlnl  = "Je KAps (Kingdom Age-punten)",
    frfr  = "Vos KAps (points de Kingdom Age)",
    fi    = "Sinun KAps-pisteesi (Kingdom Age -pisteet)",
    it    = "I tuoi KAps (punti di Kingdom Age)",
    zhcn  = "你的 KAps（Kingdom Age 点数）",
    ja    = "所持KAps（Kingdom Ageポイント）",
    ko    = "보유 KAps (Kingdom Age 포인트)",
  },

  GameNpcTradeCapacityDescTooltip = {
    en    = "Your capacity",
    ptbr  = "Sua capacidade",
    ptpt  = "A sua capacidade",
    es419 = "Tu capacidad",
    eses  = "Tu capacidad",
    pl    = "Twoja pojemność",
    ru    = "Ваша вместимость",
    sv    = "Din kapacitet",
    nb    = "Din kapasitet",
    de    = "Deine Kapazität",
    nlnl  = "Je capaciteit",
    frfr  = "Votre capacité",
    fi    = "Kantokykysi",
    it    = "La tua capacità",
    zhcn  = "你的容量",
    ja    = "所持容量",
    ko    = "보유 용량",
  },

  GameNpcTradeTrustDescTooltip = {
    en    = "Your trust in this city",
    ptbr  = "Sua confiança nesta cidade",
    ptpt  = "A sua confiança nesta cidade",
    es419 = "Tu confianza en esta ciudad",
    eses  = "Tu confianza en esta ciudad",
    pl    = "Twoje zaufanie do tego miasta",
    ru    = "Ваше доверие к этому городу",
    sv    = "Ditt förtroende för denna stad",
    nb    = "Din tillit til denne byen",
    de    = "Dein Vertrauen in diese Stadt",
    nlnl  = "Je vertrouwen in deze stad",
    frfr  = "Votre confiance en cette ville",
    fi    = "Luottamuksesi tähän kaupunkiin",
    it    = "La tua fiducia in questa città",
    zhcn  = "你对这座城市的信任度",
    ja    = "この街での信頼度",
    ko    = "이 도시에 대한 신뢰도",
  },

  GameNpcTradeTabBuy = {
    en    = "Buy",
    ptbr  = "Comprar",
    ptpt  = "Comprar",
    es419 = "Comprar",
    eses  = "Comprar",
    pl    = "Kup",
    ru    = "Купить",
    sv    = "Köp",
    nb    = "Kjøp",
    de    = "Kaufen",
    nlnl  = "Kopen",
    frfr  = "Acheter",
    fi    = "Osta",
    it    = "Compra",
    zhcn  = "购买",
    ja    = "購入",
    ko    = "구매",
  },

  GameNpcTradeTabSell = {
    en    = "Sell",
    ptbr  = "Vender",
    ptpt  = "Vender",
    es419 = "Vender",
    eses  = "Vender",
    pl    = "Sprzedaj",
    ru    = "Продать",
    sv    = "Sälj",
    nb    = "Selg",
    de    = "Verkaufen",
    nlnl  = "Verkopen",
    frfr  = "Vendre",
    fi    = "Myy",
    it    = "Vendi",
    zhcn  = "出售",
    ja    = "売却",
    ko    = "판매",
  },

  GameNpcTradeTabBuyTooltip = {
    en    = "List of items that you're able to buy",
    ptbr  = "Lista de itens que você pode comprar",
    ptpt  = "Lista de itens que pode comprar",
    es419 = "Lista de artículos que puedes comprar",
    eses  = "Lista de artículos que puedes comprar",
    pl    = "Lista przedmiotów, które możesz kupić",
    ru    = "Список предметов, которые вы можете купить",
    sv    = "Lista över föremål som du kan köpa",
    nb    = "Liste over gjenstander du kan kjøpe",
    de    = "Liste der Gegenstände, die du kaufen kannst",
    nlnl  = "Lijst met items die je kunt kopen",
    frfr  = "Liste des objets que vous pouvez acheter",
    fi    = "Luettelo esineistä, joita voit ostaa",
    it    = "Elenco degli oggetti che puoi acquistare",
    zhcn  = "你可以购买的物品列表",
    ja    = "購入できるアイテムの一覧",
    ko    = "구매할 수 있는 아이템 목록",
  },

  GameNpcTradeTabSellTooltip = {
    en    = "List of items that you're able to sell",
    ptbr  = "Lista de itens que você pode vender",
    ptpt  = "Lista de itens que pode vender",
    es419 = "Lista de artículos que puedes vender",
    eses  = "Lista de artículos que puedes vender",
    pl    = "Lista przedmiotów, które możesz sprzedać",
    ru    = "Список предметов, которые вы можете продать",
    sv    = "Lista över föremål som du kan sälja",
    nb    = "Liste over gjenstander du kan selge",
    de    = "Liste der Gegenstände, die du verkaufen kannst",
    nlnl  = "Lijst met items die je kunt verkopen",
    frfr  = "Liste des objets que vous pouvez vendre",
    fi    = "Luettelo esineistä, joita voit myydä",
    it    = "Elenco degli oggetti che puoi vendere",
    zhcn  = "你可以出售的物品列表",
    ja    = "売却できるアイテムの一覧",
    ko    = "판매할 수 있는 아이템 목록",
  },

  GameNpcTradeTrustLevel = {
    en    = "Level %d",
    ptbr  = "Nível %d",
    ptpt  = "Nível %d",
    es419 = "Nivel %d",
    eses  = "Nivel %d",
    pl    = "Poziom %d",
    ru    = "Уровень %d",
    sv    = "Nivå %d",
    nb    = "Nivå %d",
    de    = "Stufe %d",
    nlnl  = "Niveau %d",
    frfr  = "Niveau %d",
    fi    = "Taso %d",
    it    = "Livello %d",
    zhcn  = "等级 %d",
    ja    = "レベル%d",
    ko    = "레벨 %d",
  },

  GameNpcTradeGoodsFromBank = {
    en    = "from bank",
    ptbr  = "do banco",
    ptpt  = "do banco",
    es419 = "del banco",
    eses  = "del banco",
    pl    = "z banku",
    ru    = "из банка",
    sv    = "från banken",
    nb    = "fra banken",
    de    = "von der Bank",
    nlnl  = "van de bank",
    frfr  = "de la banque",
    fi    = "pankista",
    it    = "dalla banca",
    zhcn  = "从银行",
    ja    = "銀行から",
    ko    = "은행에서",
  },

  GameNpcTradeGoodsFromVipBank = {
    en    = "from VIP bank",
    ptbr  = "do banco VIP",
    ptpt  = "do banco VIP",
    es419 = "del banco VIP",
    eses  = "del banco VIP",
    pl    = "z banku VIP",
    ru    = "из VIP-банка",
    sv    = "från VIP-banken",
    nb    = "fra VIP-banken",
    de    = "von der VIP-Bank",
    nlnl  = "van de VIP-bank",
    frfr  = "de la banque VIP",
    fi    = "VIP-pankista",
    it    = "dalla banca VIP",
    zhcn  = "从 VIP 银行",
    ja    = "VIP銀行から",
    ko    = "VIP 은행에서",
  },

  GameNpcTradeGoodsHoldingMoney = {
    en    = "holding",
    ptbr  = "em mãos",
    ptpt  = "em mãos",
    es419 = "en mano",
    eses  = "en mano",
    pl    = "w ręku",
    ru    = "на руках",
    sv    = "i handen",
    nb    = "i hånden",
    de    = "in Händen",
    nlnl  = "in handen",
    frfr  = "en main",
    fi    = "hallussa",
    it    = "in mano",
    zhcn  = "手上持有",
    ja    = "手持ち",
    ko    = "소지 중",
  },

  GameNpcTradeGoodsTrustLevel = {
    en    = "Level %d (%s XP)",
    ptbr  = "Nível %d (%s XP)",
    ptpt  = "Nível %d (%s XP)",
    es419 = "Nivel %d (%s XP)",
    eses  = "Nivel %d (%s XP)",
    pl    = "Poziom %d (%s XP)",
    ru    = "Уровень %d (%s XP)",
    sv    = "Nivå %d (%s XP)",
    nb    = "Nivå %d (%s XP)",
    de    = "Stufe %d (%s XP)",
    nlnl  = "Niveau %d (%s XP)",
    frfr  = "Niveau %d (%s XP)",
    fi    = "Taso %d (%s XP)",
    it    = "Livello %d (%s XP)",
    zhcn  = "等级 %d（%s XP）",
    ja    = "レベル%d（%s XP）",
    ko    = "레벨 %d (%s XP)",
  },

  GameNpcTradeKapsWarning = {
    en    = "Your KAps (Kingdom Age points) may not be displayed correctly if they are added through the Website of Kingdom Age while keeping the trade window opened. Reopen it to update.",
    ptbr  = "Seus KAps (pontos do Kingdom Age) podem não ser exibidos corretamente se forem adicionados pelo site de Kingdom Age enquanto a janela de comércio estiver aberta. Reabra-a para atualizar.",
    ptpt  = "Os seus KAps (pontos do Kingdom Age) podem não ser exibidos corretamente se forem adicionados pelo site do Kingdom Age enquanto a janela de comércio estiver aberta. Reabra-a para atualizar.",
    es419 = "Tus KAps (puntos de Kingdom Age) pueden no mostrarse correctamente si se añaden a través del sitio web de Kingdom Age mientras la ventana de comercio está abierta. Vuelve a abrirla para actualizar.",
    eses  = "Tus KAps (puntos de Kingdom Age) pueden no mostrarse correctamente si se añaden a través del sitio web de Kingdom Age mientras la ventana de comercio está abierta. Vuelve a abrirla para actualizar.",
    pl    = "Twoje KAps (punkty Kingdom Age) mogą nie być wyświetlane poprawnie, jeśli zostaną dodane przez stronę internetową Kingdom Age, gdy okno handlu jest otwarte. Otwórz je ponownie, aby zaktualizować.",
    ru    = "Ваши KAps (очки Kingdom Age) могут отображаться некорректно, если они были добавлены через сайт Kingdom Age, пока окно торговли открыто. Откройте его снова, чтобы обновить данные.",
    sv    = "Dina KAps (Kingdom Age-poäng) kanske inte visas korrekt om de läggs till via Kingdom Ages webbplats medan handelsfönstret är öppet. Öppna det igen för att uppdatera.",
    nb    = "Dine KAps (Kingdom Age-poeng) vises kanskje ikke riktig hvis de legges til via Kingdom Age-nettstedet mens handelsvinduet er åpent. Åpne det på nytt for å oppdatere.",
    de    = "Deine KAps (Kingdom Age-Punkte) werden möglicherweise nicht korrekt angezeigt, wenn sie über die Website von Kingdom Age hinzugefügt werden, während das Handelsfenster geöffnet ist. Öffne es erneut, um es zu aktualisieren.",
    nlnl  = "Je KAps (Kingdom Age-punten) worden mogelijk niet correct weergegeven als ze via de website van Kingdom Age worden toegevoegd terwijl het handelsvenster geopend is. Open het opnieuw om het bij te werken.",
    frfr  = "Vos KAps (points de Kingdom Age) peuvent ne pas s'afficher correctement s'ils sont ajoutés via le site de Kingdom Age alors que la fenêtre d'échange est ouverte. Rouvrez-la pour actualiser.",
    fi    = "KAps-pisteesi (Kingdom Age -pisteet) eivät ehkä näy oikein, jos niitä lisätään Kingdom Agen verkkosivuston kautta kauppaikkunan ollessa auki. Päivitä tiedot avaamalla ikkuna uudelleen.",
    it    = "I tuoi KAps (punti di Kingdom Age) potrebbero non essere visualizzati correttamente se vengono aggiunti tramite il sito web di Kingdom Age mentre la finestra di scambio è aperta. Riaprila per aggiornare.",
    zhcn  = "如果在交易窗口保持打开状态时通过 Kingdom Age 网站添加你的 KAps（Kingdom Age 点数），它们可能无法正确显示。重新打开窗口以更新。",
    ja    = "取引ウィンドウを開いたままKingdom AgeのウェブサイトからKAps（Kingdom Ageポイント）を追加すると、正しく表示されない場合があります。更新するにはウィンドウを開き直してください。",
    ko    = "거래 창을 연 상태에서 Kingdom Age 웹사이트를 통해 KAps(Kingdom Age 포인트)를 추가하면 올바르게 표시되지 않을 수 있습니다. 업데이트하려면 창을 다시 여세요.",
  },

  GameNpcTradeTrustRemainingXp = {
    en    = "There is %.2f%% remaining (about %s XP) to advance to trust level %d%s.",
    ptbr  = "Faltam %.2f%% (cerca de %s XP) para avançar para o nível de confiança %d%s.",
    ptpt  = "Faltam %.2f%% (cerca de %s XP) para avançar para o nível de confiança %d%s.",
    es419 = "Falta %.2f%% (aproximadamente %s XP) para avanzar al nivel de confianza %d%s.",
    eses  = "Falta %.2f%% (aproximadamente %s XP) para avanzar al nivel de confianza %d%s.",
    pl    = "Brakuje %.2f%% (około %s XP), aby awansować na poziom zaufania %d%s.",
    ru    = "Осталось %.2f%% (около %s XP), чтобы перейти на уровень доверия %d%s.",
    sv    = "Det återstår %.2f%% (cirka %s XP) för att nå förtroendenivå %d%s.",
    nb    = "Det gjenstår %.2f%% (omtrent %s XP) for å nå tillitsnivå %d%s.",
    de    = "Es fehlen noch %.2f%% (etwa %s XP), um Vertrauensstufe %d%s zu erreichen.",
    nlnl  = "Er ontbreekt nog %.2f%% (ongeveer %s XP) om vertrouwensniveau %d%s te bereiken.",
    frfr  = "Il reste %.2f%% (environ %s XP) avant d'atteindre le niveau de confiance %d%s.",
    fi    = "Jäljellä on vielä %.2f%% (noin %s XP), jotta pääset luottamustasolle %d%s.",
    it    = "Mancano %.2f%% (circa %s XP) per avanzare al livello di fiducia %d%s.",
    zhcn  = "还需要 %.2f%%（约 %s XP）才能提升至信任等级 %d%s。",
    ja    = "残り%.2f%%（約%s XP）で、信頼度レベル%d%sに進みます。",
    ko    = "%.2f%%(%s XP 정도)가 남아 신뢰 레벨 %d%s로 올라갈 수 있습니다.",
  },

  GameNpcTradeTrustRemainingXpMax = {
    en    = "You are on the maximum trust level%s.",
    ptbr  = "Você está no nível máximo de confiança%s.",
    ptpt  = "Você está no nível máximo de confiança%s.",
    es419 = "Estás en el nivel máximo de confianza%s.",
    eses  = "Estás en el nivel máximo de confianza%s.",
    pl    = "Jesteś na maksymalnym poziomie zaufania%s.",
    ru    = "Вы достигли максимального уровня доверия%s.",
    sv    = "Du är på den maximala förtroendenivån%s.",
    nb    = "Du er på det maksimale tillitsnivået%s.",
    de    = "Du bist auf der maximalen Vertrauensstufe%s.",
    nlnl  = "Je hebt het maximale vertrouwensniveau%s bereikt.",
    frfr  = "Vous avez atteint le niveau de confiance maximal%s.",
    fi    = "Olet saavuttanut korkeimman luottamustason%s.",
    it    = "Hai raggiunto il livello massimo di fiducia%s.",
    zhcn  = "你已达到最高信任等级%s。",
    ja    = "最大信頼度レベル%sです。",
    ko    = "최대 신뢰 레벨%s에 도달했습니다.",
  },

  GameNpcTradeContextMenuLook = {
    en    = "Look",
    ptbr  = "Olhar",
    ptpt  = "Olhar",
    es419 = "Mirar",
    eses  = "Mirar",
    pl    = "Zobacz",
    ru    = "Осмотреть",
    sv    = "Titta",
    nb    = "Titta",
    de    = "Ansehen",
    nlnl  = "Bekijken",
    frfr  = "Regarder",
    fi    = "Katso",
    it    = "Guarda",
    zhcn  = "查看",
    ja    = "見る",
    ko    = "보기",
  },

  GameNpcTradeTrustXp = {
    en    = "trust exp",
    ptbr  = "exp de confiança",
    ptpt  = "exp de confiança",
    es419 = "exp. de confianza",
    eses  = "exp. de confianza",
    pl    = "doświadczenie zaufania",
    ru    = "опыт доверия",
    sv    = "förtroendeerfarenhet",
    nb    = "tillits-erfaring",
    de    = "Vertrauenserfahrung",
    nlnl  = "vertrouwens-ervaring",
    frfr  = "exp. de confiance",
    fi    = "luottamuskokemus",
    it    = "esperienza di fiducia",
    zhcn  = "信任经验",
    ja    = "信頼度経験値",
    ko    = "신뢰도 경험치",
  },

  GameNpcTradeTrustHowToTown = {
    en    = "Some items, like equipments, can be bought if you have enough money and trust experience.\nHigher trust levels unlocks access to buy new items.\nYour trust experience of each city increases individually by selling some items or accomplishing hunting tasks, and decreases over the time.",
    ptbr  = "Alguns itens, como equipamentos, podem ser comprados se você tiver dinheiro e experiência de confiança suficientes.\nNíveis mais altos de confiança desbloqueiam o acesso para comprar novos itens.\nSua experiência de confiança em cada cidade aumenta individualmente vendendo alguns itens ou completando tarefas de caça, e diminui ao longo do tempo.",
    ptpt  = "Alguns itens, como equipamentos, podem ser comprados se tiveres dinheiro e experiência de confiança suficientes.\nNíveis mais altos de confiança desbloqueiam o acesso à compra de novos itens.\nA tua experiência de confiança em cada cidade aumenta individualmente ao vender alguns itens ou completar tarefas de caça, e diminui ao longo do tempo.",
    es419 = "Algunos artículos, como el equipamiento, pueden comprarse si tienes suficiente dinero y experiencia de confianza.\nLos niveles de confianza más altos desbloquean el acceso a nuevos artículos.\nTu experiencia de confianza en cada ciudad aumenta individualmente al vender algunos artículos o completar tareas de caza, y disminuye con el tiempo.",
    eses  = "Algunos artículos, como el equipamiento, pueden comprarse si tienes suficiente dinero y experiencia de confianza.\nLos niveles de confianza más altos desbloquean el acceso a nuevos artículos.\nTu experiencia de confianza en cada ciudad aumenta individualmente al vender algunos artículos o completar tareas de caza, y disminuye con el tiempo.",
    pl    = "Niektóre przedmioty, takie jak wyposażenie, można kupić, jeśli masz wystarczająco dużo pieniędzy i doświadczenia zaufania.\nWyższe poziomy zaufania odblokowują dostęp do nowych przedmiotów.\nTwoje doświadczenie zaufania w każdym mieście rośnie niezależnie poprzez sprzedaż niektórych przedmiotów lub wykonywanie zadań łowieckich i z czasem maleje.",
    ru    = "Некоторые предметы, такие как снаряжение, можно купить, если у вас достаточно денег и опыта доверия.\nБолее высокие уровни доверия открывают доступ к покупке новых предметов.\nВаш опыт доверия в каждом городе увеличивается отдельно за продажу некоторых предметов или выполнение охотничьих заданий и со временем уменьшается.",
    sv    = "Vissa föremål, som utrustning, kan köpas om du har tillräckligt med pengar och förtroendeerfarenhet.\nHögre förtroendenivåer låser upp tillgången till nya föremål.\nDin förtroendeerfarenhet i varje stad ökar individuellt genom att sälja vissa föremål eller utföra jaktuppdrag och minskar med tiden.",
    nb    = "Noen gjenstander, som utstyr, kan kjøpes hvis du har nok penger og tillitserfaring.\nHøyere tillitsnivåer låser opp tilgang til å kjøpe nye gjenstander.\nTillitserfaringen din i hver by øker individuelt ved å selge enkelte gjenstander eller fullføre jaktoppdrag, og reduseres over tid.",
    de    = "Einige Gegenstände, wie Ausrüstung, können gekauft werden, wenn Sie genügend Geld und Vertrauenserfahrung haben.\nHöhere Vertrauensstufen schalten den Zugang zum Kauf neuer Gegenstände frei.\nIhre Vertrauenserfahrung in jeder Stadt erhöht sich individuell durch den Verkauf bestimmter Gegenstände oder das Abschließen von Jagdaufgaben und nimmt mit der Zeit ab.",
    nlnl  = "Sommige items, zoals uitrusting, kunnen worden gekocht als je genoeg geld en vertrouwens-ervaring hebt.\nHogere vertrouwensniveaus geven toegang tot nieuwe items.\nJe vertrouwens-ervaring in elke stad neemt afzonderlijk toe door bepaalde items te verkopen of jachttaken te voltooien, en neemt na verloop van tijd af.",
    frfr  = "Certains objets, comme l'équipement, peuvent être achetés si vous avez suffisamment d'argent et d'expérience de confiance.\nLes niveaux de confiance plus élevés débloquent l'accès à de nouveaux objets.\nVotre expérience de confiance dans chaque ville augmente individuellement en vendant certains objets ou en accomplissant des tâches de chasse, et diminue avec le temps.",
    fi    = "Joitakin esineitä, kuten varusteita, voi ostaa, jos sinulla on tarpeeksi rahaa ja luottamuskokemusta.\nKorkeammat luottamustasot avaavat pääsyn uusiin ostettaviin esineisiin.\nKunkin kaupungin luottamuskokemus kasvaa erikseen myymällä tiettyjä esineitä tai suorittamalla metsästystehtäviä ja vähenee ajan myötä.",
    it    = "Alcuni oggetti, come l'equipaggiamento, possono essere acquistati se hai abbastanza denaro ed esperienza di fiducia.\nLivelli di fiducia più alti sbloccano l'accesso a nuovi oggetti.\nLa tua esperienza di fiducia in ogni città aumenta individualmente vendendo alcuni oggetti o completando attività di caccia e diminuisce nel tempo.",
    zhcn  = "一些物品，例如装备，只要你有足够的金钱和信任经验就可以购买。\n更高的信任等级可以解锁购买新物品的权限。\n你在每个城市的信任经验会分别通过出售某些物品或完成狩猎任务来增加，并会随着时间推移而减少。",
    ja    = "装備など一部のアイテムは、十分なお金と信頼度経験値があれば購入できます。\n信頼度レベルが上がると、新しいアイテムを購入できるようになります。\n各都市の信頼度経験値は、アイテムの売却や狩猟任務の達成で個別に増加し、時間とともに減少します。",
    ko    = "장비와 같은 일부 아이템은 충분한 돈과 신뢰도 경험치가 있으면 구매할 수 있습니다.\n신뢰도 레벨이 높아지면 새로운 아이템을 구매할 수 있게 됩니다.\n각 도시의 신뢰도 경험치는 일부 아이템을 판매하거나 사냥 임무를 완료하면 개별적으로 증가하며 시간이 지나면 감소합니다.",
  },

  GameNpcTradeUnknownError = {
    en    = "You cannot trade this item.",
    ptbr  = "Você não pode negociar este item.",
    ptpt  = "Não pode negociar este item.",
    es419 = "No puedes comerciar este artículo.",
    eses  = "No puedes comerciar este artículo.",
    pl    = "Nie możesz handlować tym przedmiotem.",
    ru    = "Вы не можете обменять этот предмет.",
    sv    = "Du kan inte handla med detta föremål.",
    nb    = "Du kan ikke handle med denne gjenstanden.",
    de    = "Du kannst diesen Gegenstand nicht handeln.",
    nlnl  = "Je kunt dit item niet verhandelen.",
    frfr  = "Vous ne pouvez pas échanger cet objet.",
    fi    = "Et voi käydä kauppaa tällä esineellä.",
    it    = "Non puoi scambiare questo oggetto.",
    zhcn  = "你不能交易此物品。",
    ja    = "このアイテムは取引できません。",
    ko    = "이 아이템은 거래할 수 없습니다.",
  },

  GameNpcTradeErrorNoEnoughMoney = {
    en    = "You do not have enough money to trade this item.",
    ptbr  = "Você não tem dinheiro suficiente para negociar este item.",
    ptpt  = "Não tem dinheiro suficiente para negociar este item.",
    es419 = "No tienes suficiente dinero para comerciar este artículo.",
    eses  = "No tienes suficiente dinero para comerciar este artículo.",
    pl    = "Nie masz wystarczająco dużo pieniędzy, aby handlować tym przedmiotem.",
    ru    = "У вас недостаточно денег, чтобы обменять этот предмет.",
    sv    = "Du har inte tillräckligt med pengar för att handla med detta föremål.",
    nb    = "Du har ikke nok penger til å handle med denne gjenstanden.",
    de    = "Du hast nicht genug Geld, um diesen Gegenstand zu handeln.",
    nlnl  = "Je hebt niet genoeg geld om dit item te verhandelen.",
    frfr  = "Vous n'avez pas assez d'argent pour échanger cet objet.",
    fi    = "Sinulla ei ole tarpeeksi rahaa tämän esineen ostamiseen.",
    it    = "Non hai abbastanza denaro per scambiare questo oggetto.",
    zhcn  = "你没有足够的钱来交易此物品。",
    ja    = "このアイテムを取引するためのお金が足りません。",
    ko    = "이 아이템을 거래하기에 충분한 돈이 없습니다.",
  },

  GameNpcTradeErrorNoEnoughCapacity = {
    en    = "You do not have enough capacity to trade this item.",
    ptbr  = "Você não tem capacidade suficiente para negociar este item.",
    ptpt  = "Não tem capacidade suficiente para negociar este item.",
    es419 = "No tienes suficiente capacidad para comerciar este artículo.",
    eses  = "No tienes suficiente capacidad para comerciar este artículo.",
    pl    = "Nie masz wystarczającej pojemności, aby handlować tym przedmiotem.",
    ru    = "У вас недостаточно вместимости, чтобы обменять этот предмет.",
    sv    = "Du har inte tillräcklig kapacitet för att handla med detta föremål.",
    nb    = "Du har ikke nok kapasitet til å handle med denne gjenstanden.",
    de    = "Du hast nicht genug Kapazität, um diesen Gegenstand zu handeln.",
    nlnl  = "Je hebt niet genoeg capaciteit om dit item te verhandelen.",
    frfr  = "Vous n'avez pas assez de capacité pour échanger cet objet.",
    fi    = "Kantokykysi ei riitä tämän esineen hankkimiseen.",
    it    = "Non hai abbastanza capacità per scambiare questo oggetto.",
    zhcn  = "你没有足够的容量来交易此物品。",
    ja    = "このアイテムを取引するための容量が足りません。",
    ko    = "이 아이템을 거래할 충분한 용량이 없습니다.",
  },

  GameNpcTradeErrorNoEnoughTrust = {
    en    = "You do not have enough trust in this city to trade this item.",
    ptbr  = "Você não tem confiança suficiente nesta cidade para negociar este item.",
    ptpt  = "Não tem confiança suficiente nesta cidade para negociar este item.",
    es419 = "No tienes suficiente confianza en esta ciudad para comerciar este artículo.",
    eses  = "No tienes suficiente confianza en esta ciudad para comerciar este artículo.",
    pl    = "Nie masz wystarczającego zaufania w tym mieście, aby handlować tym przedmiotem.",
    ru    = "У вас недостаточно доверия в этом городе, чтобы обменять этот предмет.",
    sv    = "Du har inte tillräckligt med förtroende i denna stad för att handla med detta föremål.",
    nb    = "Du har ikke nok tillit i denne byen til å handle med denne gjenstanden.",
    de    = "Du hast nicht genug Vertrauen in dieser Stadt, um diesen Gegenstand zu handeln.",
    nlnl  = "Je hebt niet genoeg vertrouwen in deze stad om dit item te verhandelen.",
    frfr  = "Vous n'avez pas suffisamment de confiance dans cette ville pour échanger cet objet.",
    fi    = "Luottamuksesi tässä kaupungissa ei riitä tämän esineen hankkimiseen.",
    it    = "Non hai abbastanza fiducia in questa città per scambiare questo oggetto.",
    zhcn  = "你在这座城市的信任度不足，无法交易此物品。",
    ja    = "このアイテムを取引するための、この街での信頼度が足りません。",
    ko    = "이 아이템을 거래하기에 이 도시에서의 신뢰도가 충분하지 않습니다.",
  },

  GameNpcTradeErrorItemNotFound = {
    en    = "You do not have this item.",
    ptbr  = "Você não possui este item.",
    ptpt  = "Não possui este item.",
    es419 = "No tienes este artículo.",
    eses  = "No tienes este artículo.",
    pl    = "Nie masz tego przedmiotu.",
    ru    = "У вас нет этого предмета.",
    sv    = "Du har inte detta föremål.",
    nb    = "Du har ikke denne gjenstanden.",
    de    = "Du hast diesen Gegenstand nicht.",
    nlnl  = "Je hebt dit item niet.",
    frfr  = "Vous ne possédez pas cet objet.",
    fi    = "Sinulla ei ole tätä esinettä.",
    it    = "Non hai questo oggetto.",
    zhcn  = "你没有此物品。",
    ja    = "このアイテムを所持していません。",
    ko    = "이 아이템을 가지고 있지 않습니다.",
  },

  GameNpcTradeErrorInventoryItem = {
    en    = "You cannot sell items from your inventory.",
    ptbr  = "Você não pode vender itens do seu inventário.",
    ptpt  = "Não pode vender itens do seu inventário.",
    es419 = "No puedes vender artículos de tu inventario.",
    eses  = "No puedes vender artículos de tu inventario.",
    pl    = "Nie możesz sprzedawać przedmiotów ze swojego ekwipunku.",
    ru    = "Вы не можете продавать предметы из своего инвентаря.",
    sv    = "Du kan inte sälja föremål från ditt lager.",
    nb    = "Du kan ikke selge gjenstander fra lageret ditt.",
    de    = "Du kannst keine Gegenstände aus deinem Inventar verkaufen.",
    nlnl  = "Je kunt geen items uit je inventaris verkopen.",
    frfr  = "Vous ne pouvez pas vendre d'objets de votre inventaire.",
    fi    = "Et voi myydä esineitä varastostasi.",
    it    = "Non puoi vendere oggetti dal tuo inventario.",
    zhcn  = "你无法出售背包中的物品。",
    ja    = "インベントリのアイテムは売却できません。",
    ko    = "인벤토리의 아이템은 판매할 수 없습니다.",
  },

  GameNpcTradeTrust = {
    en    = "Trust",
    ptbr  = "Confiança",
    ptpt  = "Confiança",
    es419 = "Confianza",
    eses  = "Confianza",
    pl    = "Zaufanie",
    ru    = "Доверие",
    sv    = "Förtroende",
    nb    = "Tillit",
    de    = "Vertrauen",
    nlnl  = "Vertrouwen",
    frfr  = "Confiance",
    fi    = "Luottamus",
    it    = "Fiducia",
    zhcn  = "信任",
    ja    = "信頼度",
    ko    = "신뢰도",
  },

  GameNpcTradeInfoPrice = {
    en    = "Price",
    ptbr  = "Preço",
    ptpt  = "Preço",
    es419 = "Precio",
    eses  = "Precio",
    pl    = "Cena",
    ru    = "Цена",
    sv    = "Pris",
    nb    = "Pris",
    de    = "Preis",
    nlnl  = "Prijs",
    frfr  = "Prix",
    fi    = "Hinta",
    it    = "Prezzo",
    zhcn  = "价格",
    ja    = "価格",
    ko    = "가격",
  },

  GameNpcTradeInfoWeight = {
    en    = "Weight",
    ptbr  = "Peso",
    ptpt  = "Peso",
    es419 = "Peso",
    eses  = "Peso",
    pl    = "Waga",
    ru    = "Вес",
    sv    = "Vikt",
    nb    = "Vekt",
    de    = "Gewicht",
    nlnl  = "Gewicht",
    frfr  = "Poids",
    fi    = "Paino",
    it    = "Peso",
    zhcn  = "重量",
    ja    = "重量",
    ko    = "무게",
  },

  GameNpcTradeInfoCount = {
    en    = "Quantity",
    ptbr  = "Quantidade",
    ptpt  = "Quantidade",
    es419 = "Cantidad",
    eses  = "Cantidad",
    pl    = "Ilość",
    ru    = "Количество",
    sv    = "Antal",
    nb    = "Antall",
    de    = "Anzahl",
    nlnl  = "Aantal",
    frfr  = "Quantité",
    fi    = "Määrä",
    it    = "Quantità",
    zhcn  = "数量",
    ja    = "個数",
    ko    = "수량",
  },

  GameNpcTradeInfoTotalPrice = {
    en    = "Total price",
    ptbr  = "Preço total",
    ptpt  = "Preço total",
    es419 = "Precio total",
    eses  = "Precio total",
    pl    = "Cena całkowita",
    ru    = "Общая цена",
    sv    = "Totalpris",
    nb    = "Totalpris",
    de    = "Gesamtpreis",
    nlnl  = "Totale prijs",
    frfr  = "Prix total",
    fi    = "Kokonaishinta",
    it    = "Prezzo totale",
    zhcn  = "总价",
    ja    = "合計価格",
    ko    = "총 가격",
  },

  GameNpcTradeInfoTotalWeight = {
    en    = "Total weight",
    ptbr  = "Peso total",
    ptpt  = "Peso total",
    es419 = "Peso total",
    eses  = "Peso total",
    pl    = "Waga całkowita",
    ru    = "Общий вес",
    sv    = "Totalvikt",
    nb    = "Totalvekt",
    de    = "Gesamtgewicht",
    nlnl  = "Totaalgewicht",
    frfr  = "Poids total",
    fi    = "Kokonaispaino",
    it    = "Peso totale",
    zhcn  = "总重量",
    ja    = "合計重量",
    ko    = "총 무게",
  },

  GameNpcTradeInfoBpIncluded = {
    en    = "* %d backpacks included.",
    ptbr  = "* %d mochilas incluídas.",
    ptpt  = "* %d mochilas incluídas.",
    es419 = "* %d mochilas incluidas.",
    eses  = "* %d mochilas incluidas.",
    pl    = "* %d plecaków w zestawie.",
    ru    = "* Включено %d рюкзак(а/ов).",
    sv    = "* %d ryggsäckar ingår.",
    nb    = "* %d ryggsekker inkludert.",
    de    = "* %d Rucksäcke enthalten.",
    nlnl  = "* %d rugzakken inbegrepen.",
    frfr  = "* %d sacs à dos inclus.",
    fi    = "* Mukana %d reppua.",
    it    = "* %d zaini inclusi.",
    zhcn  = "* 包含 %d 个背包。",
    ja    = "* バックパック%d個を含む。",
    ko    = "* 배낭 %d개 포함.",
  },
})
