-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  ClientTerminalCommandNotFound = {
    en    = "Error - command not found",
    ptbr  = "Erro - comando não encontrado",
    ptpt  = "Erro - comando não encontrado",
    es419 = "Error - comando no encontrado",
    eses  = "Error - comando no encontrado",
    pl    = "Błąd - nie znaleziono polecenia",
    ru    = "Ошибка - команда не найдена",
    sv    = "Fel - kommandot hittades inte",
    nb    = "Feil - kommando ikke funnet",
    de    = "Fehler - Befehl nicht gefunden",
    nlnl  = "Fout - opdracht niet gevonden",
    frfr  = "Erreur - commande introuvable",
    fi    = "Virhe - komentoa ei löytynyt",
    it    = "Errore - comando non trovato",
    zhcn  = "错误 - 未找到命令",
    ja    = "エラー - コマンドが見つかりません",
    ko    = "오류 - 명령을 찾을 수 없습니다",
  },

  ClientTerminalIncorrectLuaSyntax = {
    en    = "Error - incorrect Lua syntax",
    ptbr  = "Erro - sintaxe Lua incorreta",
    ptpt  = "Erro - sintaxe Lua incorreta",
    es419 = "Error - sintaxis de Lua incorrecta",
    eses  = "Error - sintaxis de Lua incorrecta",
    pl    = "Błąd - niepoprawna składnia Lua",
    ru    = "Ошибка - некорректный синтаксис Lua",
    sv    = "Fel - felaktig Lua-syntax",
    nb    = "Feil - feilaktig Lua-syntaks",
    de    = "Fehler - falsche Lua-Syntax",
    nlnl  = "Fout - onjuiste Lua-syntaxis",
    frfr  = "Erreur - syntaxe Lua incorrecte",
    fi    = "Virhe - virheellinen Lua-syntaksi",
    it    = "Errore - sintassi Lua non corretta",
    zhcn  = "错误 - Lua 语法不正确",
    ja    = "エラー - Lua構文が正しくありません",
    ko    = "오류 - 잘못된 Lua 구문",
  },

  ClientTerminalCommandFailed = {
    en    = "Error - command failed",
    ptbr  = "Erro - comando falhou",
    ptpt  = "Erro - comando falhou",
    es419 = "Error - comando fallido",
    eses  = "Error - comando fallido",
    pl    = "Błąd - wykonanie polecenia nie powiodło się",
    ru    = "Ошибка - команда не выполнена",
    sv    = "Fel - kommandot misslyckades",
    nb    = "Feil - kommando mislyktes",
    de    = "Fehler - Befehl fehlgeschlagen",
    nlnl  = "Fout - opdracht mislukt",
    frfr  = "Erreur - échec de la commande",
    fi    = "Virhe - komento epäonnistui",
    it    = "Errore - comando non riuscito",
    zhcn  = "错误 - 命令执行失败",
    ja    = "エラー - コマンドの実行に失敗しました",
    ko    = "오류 - 명령 실행 실패",
  },

  ClientTerminalTitleBar = {
    en    = "Terminal",
    ptbr  = "Terminal",
    ptpt  = "Terminal",
    es419 = "Terminal",
    eses  = "Terminal",
    pl    = "Terminal",
    ru    = "Терминал",
    sv    = "Terminal",
    nb    = "Terminal",
    de    = "Terminal",
    nlnl  = "Terminal",
    frfr  = "Terminal",
    fi    = "Pääte",
    it    = "Terminale",
    zhcn  = "终端",
    ja    = "ターミナル",
    ko    = "터미널",
  },

  ClientTerminalClearButton = {
    en    = "Clear terminal",
    ptbr  = "Limpar terminal",
    ptpt  = "Limpar terminal",
    es419 = "Limpiar terminal",
    eses  = "Limpiar terminal",
    pl    = "Wyczyść terminal",
    ru    = "Очистить терминал",
    sv    = "Rensa terminalen",
    nb    = "Tøm terminalen",
    de    = "Terminal leeren",
    nlnl  = "Terminal wissen",
    frfr  = "Effacer le terminal",
    fi    = "Tyhjennä pääte",
    it    = "Pulisci il terminale",
    zhcn  = "清空终端",
    ja    = "ターミナルを消去",
    ko    = "터미널 지우기",
  },

  ClientTerminalPingStopped = {
    en    = "Ping stopped.",
    ptbr  = "Ping interrompido.",
    ptpt  = "Ping interrompido.",
    es419 = "Ping detenido.",
    eses  = "Ping detenido.",
    pl    = "Ping zatrzymany.",
    ru    = "Пинг остановлен.",
    sv    = "Ping stoppad.",
    nb    = "Ping stoppet.",
    de    = "Ping gestoppt.",
    nlnl  = "Ping gestopt.",
    frfr  = "Ping arrêté.",
    fi    = "Ping pysäytetty.",
    it    = "Ping arrestato.",
    zhcn  = "ping 已停止",
    ja    = "pingを停止しました。",
    ko    = "핑 중지됨.",
  },

  ClientTerminalErrorNotOnline = {
    en    = "Ping command is only allowed when online.",
    ptbr  = "O comando de ping só é permitido quando estiver online.",
    ptpt  = "O comando de ping só é permitido quando estiver online.",
    es419 = "El comando de ping solo está permitido cuando estás en línea.",
    eses  = "El comando de ping solo está permitido cuando estás en línea.",
    pl    = "Polecenie ping jest dozwolone tylko wtedy, gdy jesteś online.",
    ru    = "Команда ping разрешена только в режиме онлайн.",
    sv    = "Ping-kommandot är endast tillåtet när du är online.",
    nb    = "Ping-kommandoen er bare tillatt når du er pålogget.",
    de    = "Der Ping-Befehl ist nur online zulässig.",
    nlnl  = "De pingopdracht is alleen toegestaan wanneer je online bent.",
    frfr  = "La commande ping n'est autorisée que lorsque vous êtes en ligne.",
    fi    = "Ping-komento on sallittu vain online-tilassa.",
    it    = "Il comando ping è consentito solo quando sei online.",
    zhcn  = "只有在线时才能使用 ping 命令。",
    ja    = "pingコマンドはオンライン時のみ使用できます。",
    ko    = "핑 명령은 온라인 상태에서만 사용할 수 있습니다.",
  },

  ClientTerminalErrorPingNotSupported = {
    en    = "This server does not support ping.",
    ptbr  = "Este servidor não suporta ping.",
    ptpt  = "Este servidor não suporta ping.",
    es419 = "Este servidor no admite ping.",
    eses  = "Este servidor no admite ping.",
    pl    = "Ten serwer nie obsługuje pinga.",
    ru    = "Этот сервер не поддерживает ping.",
    sv    = "Den här servern stöder inte ping.",
    nb    = "Denne serveren støtter ikke ping.",
    de    = "Dieser Server unterstützt keinen Ping.",
    nlnl  = "Deze server ondersteunt ping niet.",
    frfr  = "Ce serveur ne prend pas en charge le ping.",
    fi    = "Tämä palvelin ei tue pingiä.",
    it    = "Questo server non supporta il ping.",
    zhcn  = "此服务器不支持 ping。",
    ja    = "このサーバーはpingに対応していません。",
    ko    = "이 서버는 핑을 지원하지 않습니다.",
  },

  ClientTerminalPingStarting = {
    en    = "Starting ping...",
    ptbr  = "Iniciando ping...",
    ptpt  = "Iniciando ping...",
    es419 = "Iniciando ping...",
    eses  = "Iniciando ping...",
    pl    = "Rozpoczynanie pinga...",
    ru    = "Запуск пинга...",
    sv    = "Startar ping...",
    nb    = "Starter ping...",
    de    = "Ping wird gestartet...",
    nlnl  = "Ping starten...",
    frfr  = "Démarrage du ping...",
    fi    = "Ping käynnistyy...",
    it    = "Avvio del ping...",
    zhcn  = "正在启动 ping...",
    ja    = "pingを開始中…",
    ko    = "핑 시작 중...",
  },

  ClientTerminalAboutVersionRevision = {
    en    = "Revision %s (%s)",
    ptbr  = "Revisão %s (%s)",
    ptpt  = "Revisão %s (%s)",
    es419 = "Revisión %s (%s)",
    eses  = "Revisión %s (%s)",
    pl    = "Rewizja %s (%s)",
    ru    = "Ревизия %s (%s)",
    sv    = "Revision %s (%s)",
    nb    = "Revisjon %s (%s)",
    de    = "Revision %s (%s)",
    nlnl  = "Revisie %s (%s)",
    frfr  = "Révision %s (%s)",
    fi    = "Versio %s (%s)",
    it    = "Revisione %s (%s)",
    zhcn  = "修订版本 %s (%s)",
    ja    = "リビジョン%s（%s）",
    ko    = "리비전 %s (%s)",
  },

  ClientTerminalAboutVersionBuilt = {
    en    = "Built on %s",
    ptbr  = "Gerado em %s",
    ptpt  = "Gerado em %s",
    es419 = "Generado el %s",
    eses  = "Generado el %s",
    pl    = "Zbudowano %s",
    ru    = "Собрано %s",
    sv    = "Byggd den %s",
    nb    = "Bygget %s",
    de    = "Erstellt am %s",
    nlnl  = "Gebouwd op %s",
    frfr  = "Compilé le %s",
    fi    = "Koottu %s",
    it    = "Compilato il %s",
    zhcn  = "构建于 %s",
    ja    = "%sにビルド",
    ko    = "%s에 빌드됨",
  },

  ClientTerminalAboutGraphicsVendor = {
    en    = "Vendor %s",
    ptbr  = "Fornecedor %s",
    ptpt  = "Fornecedor %s",
    es419 = "Proveedor %s",
    eses  = "Proveedor %s",
    pl    = "Dostawca %s",
    ru    = "Производитель %s",
    sv    = "Leverantör %s",
    nb    = "Leverandør %s",
    de    = "Anbieter %s",
    nlnl  = "Fabrikant %s",
    frfr  = "Fabricant %s",
    fi    = "Valmistaja %s",
    it    = "Produttore %s",
    zhcn  = "供应商 %s",
    ja    = "ベンダー%s",
    ko    = "공급업체 %s",
  },

  ClientTerminalAboutGraphicsRenderer = {
    en    = "Renderer %s",
    ptbr  = "Renderizador %s",
    ptpt  = "Renderizador %s",
    es419 = "Renderizador %s",
    eses  = "Renderizador %s",
    pl    = "Moduł renderujący %s",
    ru    = "Средство рендеринга %s",
    sv    = "Renderare %s",
    nb    = "Renderingsmotor %s",
    de    = "Renderer %s",
    nlnl  = "Renderengine %s",
    frfr  = "Moteur de rendu %s",
    fi    = "Renderöijä %s",
    it    = "Renderer %s",
    zhcn  = "渲染器 %s",
    ja    = "レンダラー%s",
    ko    = "렌더러 %s",
  },

  ClientTerminalAboutGraphicsVersion = {
    en    = "Version %s",
    ptbr  = "Versão %s",
    ptpt  = "Versão %s",
    es419 = "Versión %s",
    eses  = "Versión %s",
    pl    = "Wersja %s",
    ru    = "Версия %s",
    sv    = "Version %s",
    nb    = "Versjon %s",
    de    = "Version %s",
    nlnl  = "Versie %s",
    frfr  = "Version %s",
    fi    = "Versio %s",
    it    = "Versione %s",
    zhcn  = "版本 %s",
    ja    = "バージョン%s",
    ko    = "버전 %s",
  },

  ClientTerminalAboutModulesLoaded = {
    en    = "loaded",
    ptbr  = "carregado",
    ptpt  = "carregado",
    es419 = "cargado",
    eses  = "cargado",
    pl    = "załadowany",
    ru    = "загружен",
    sv    = "laddad",
    nb    = "lastet",
    de    = "geladen",
    nlnl  = "geladen",
    frfr  = "chargé",
    fi    = "ladattu",
    it    = "caricato",
    zhcn  = "已加载",
    ja    = "読み込み済み",
    ko    = "로드됨",
  },

  ClientTerminalAboutModulesNotLoaded = {
    en    = "not loaded",
    ptbr  = "não carregado",
    ptpt  = "não carregado",
    es419 = "no cargado",
    eses  = "no cargado",
    pl    = "niezaładowany",
    ru    = "не загружен",
    sv    = "inte laddad",
    nb    = "ikke lastet",
    de    = "nicht geladen",
    nlnl  = "niet geladen",
    frfr  = "non chargé",
    fi    = "ei ladattu",
    it    = "non caricato",
    zhcn  = "未加载",
    ja    = "未読み込み",
    ko    = "로드되지 않음",
  },
})
