-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameOutfitWindowTitle = {
    en    = "Select outfit",
    ptbr  = "Selecionar roupa",
    ptpt  = "Selecionar roupa",
    es419 = "Seleccionar ropa",
    eses  = "Seleccionar ropa",
    pl    = "Wybierz strój",
    ru    = "Выбрать одежду",
    sv    = "Välj klädsel",
    nb    = "Velg antrekk",
    de    = "Kleidung auswählen",
    nlnl  = "Kleding selecteren",
    frfr  = "Sélectionner une tenue",
    fi    = "Valitse asu",
    it    = "Seleziona abito",
    zhcn  = "选择服装",
    ja    = "衣装を選択",
    ko    = "복장 선택",
  },

  GameOutfitOutfitName = {
    en    = "No outfit",
    ptbr  = "Sem roupa",
    ptpt  = "Sem roupa",
    es419 = "Sin ropa",
    eses  = "Sin ropa",
    pl    = "Brak stroju",
    ru    = "Без одежды",
    sv    = "Ingen klädsel",
    nb    = "Ingen antrekk",
    de    = "Keine Kleidung",
    nlnl  = "Geen kleding",
    frfr  = "Aucune tenue",
    fi    = "Ei asua",
    it    = "Nessun abito",
    zhcn  = "无服装",
    ja    = "衣装なし",
    ko    = "복장 없음",
  },

  GameOutfitMountName = {
    en    = "No mount",
    ptbr  = "Sem montaria",
    ptpt  = "Sem montaria",
    es419 = "Sin montura",
    eses  = "Sin montura",
    pl    = "Brak wierzchowca",
    ru    = "Без ездового животного",
    sv    = "Ingen riddjur",
    nb    = "Ingen ridedyr",
    de    = "Kein Reittier",
    nlnl  = "Geen rijdier",
    frfr  = "Aucune monture",
    fi    = "Ei ratsua",
    it    = "Nessuna cavalcatura",
    zhcn  = "无坐骑",
    ja    = "騎乗なし",
    ko    = "탈것 없음",
  },

  GameOutfitAddon = {
    en    = "Addon",
    ptbr  = "Acessório",
    ptpt  = "Acessório",
    es419 = "Accesorio",
    eses  = "Accesorio",
    pl    = "Dodatek",
    ru    = "Аксессуар",
    sv    = "Tillbehör",
    nb    = "Tilbehør",
    de    = "Zubehör",
    nlnl  = "Accessoire",
    frfr  = "Accessoire",
    fi    = "Lisäosa",
    it    = "Accessorio",
    zhcn  = "附加装饰",
    ja    = "追加装備",
    ko    = "추가 장식",
  },

  GameOutfitHead = {
    en    = "Head",
    ptbr  = "Cabeça",
    ptpt  = "Cabeça",
    es419 = "Cabeza",
    eses  = "Cabeza",
    pl    = "Głowa",
    ru    = "Голова",
    sv    = "Huvud",
    nb    = "Hode",
    de    = "Kopf",
    nlnl  = "Hoofd",
    frfr  = "Tête",
    fi    = "Pää",
    it    = "Testa",
    zhcn  = "头部",
    ja    = "頭",
    ko    = "머리",
  },

  GameOutfitPrimary = {
    en    = "Primary",
    ptbr  = "Primário",
    ptpt  = "Primário",
    es419 = "Primario",
    eses  = "Primario",
    pl    = "Główny",
    ru    = "Основной",
    sv    = "Primär",
    nb    = "Primær",
    de    = "Primär",
    nlnl  = "Primair",
    frfr  = "Principal",
    fi    = "Ensisijainen",
    it    = "Primario",
    zhcn  = "主要",
    ja    = "メイン",
    ko    = "주",
  },

  GameOutfitSecondary = {
    en    = "Secondary",
    ptbr  = "Secundário",
    ptpt  = "Secundário",
    es419 = "Secundario",
    eses  = "Secundario",
    pl    = "Drugorzędny",
    ru    = "Вторичный",
    sv    = "Sekundär",
    nb    = "Sekundær",
    de    = "Sekundär",
    nlnl  = "Secundair",
    frfr  = "Secondaire",
    fi    = "Toissijainen",
    it    = "Secondario",
    zhcn  = "次要",
    ja    = "サブ",
    ko    = "보조",
  },

  GameOutfitDetail = {
    en    = "Detail",
    ptbr  = "Detalhe",
    ptpt  = "Detalhe",
    es419 = "Detalle",
    eses  = "Detalle",
    pl    = "Szczegół",
    ru    = "Деталь",
    sv    = "Detalj",
    nb    = "Detalj",
    de    = "Detail",
    nlnl  = "Detail",
    frfr  = "Détail",
    fi    = "Yksityiskohta",
    it    = "Dettaglio",
    zhcn  = "细节",
    ja    = "詳細",
    ko    = "상세",
  },

  GameOutfitRandomizeButton = {
    en    = "Randomize",
    ptbr  = "Aleatorizar",
    ptpt  = "Aleatorizar",
    es419 = "Aleatorizar",
    eses  = "Aleatorizar",
    pl    = "Losuj",
    ru    = "Случайный выбор",
    sv    = "Slumpa",
    nb    = "Tilfeldig",
    de    = "Zufällige Auswahl",
    nlnl  = "Willekeurig",
    frfr  = "Aléatoire",
    fi    = "Satunnaista",
    it    = "Casualizza",
    zhcn  = "随机",
    ja    = "ランダム化",
    ko    = "무작위",
  },

  GameOutfitRandomizeButtonTooltip = {
    en    = "Randomize characters outfit",
    ptbr  = "Aleatorizar a roupa do personagem",
    ptpt  = "Aleatorizar a roupa do personagem",
    es419 = "Aleatorizar la ropa del personaje",
    eses  = "Aleatorizar la ropa del personaje",
    pl    = "Losuj strój postaci",
    ru    = "Случайно выбрать одежду персонажа",
    sv    = "Slumpa karaktärens klädsel",
    nb    = "Velg et tilfeldig antrekk for figuren",
    de    = "Kleidung des Charakters zufällig auswählen",
    nlnl  = "De kleding van het personage willekeurig kiezen",
    frfr  = "Choisir une tenue aléatoire pour le personnage",
    fi    = "Valitse hahmolle satunnainen asu",
    it    = "Scegli casualmente l'abito del personaggio",
    zhcn  = "随机选择角色服装",
    ja    = "キャラクターの衣装をランダムに選択",
    ko    = "캐릭터의 복장을 무작위로 선택",
  },
})
