-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameAttributesWindowTitle = {
    en    = "Attributes",
    ptbr  = "Atributos",
    ptpt  = "Atributos",
    es419 = "Atributos",
    eses  = "Atributos",
    pl    = "Atrybuty",
    ru    = "Характеристики",
    sv    = "Egenskaper",
    nb    = "Egenskaper",
    de    = "Attribute",
    nlnl  = "Attributen",
    frfr  = "Attributs",
    fi    = "Ominaisuudet",
    it    = "Attributi",
    zhcn  = "属性",
    ja    = "属性",
    ko    = "속성",
  },

  GameAttributesButtonInfoTooltip = {
    en    = "1. 'Distribution' are points that you distributed manually.\n\n2. 'Alignment' are recommended points that were distributed automatically due to your vocation.\n\n3. 'Quest' are points that you can acquire on quests (golden statue, stray faeries, capsules).\n\n4. 'Buff/Debuff' are points that were increased or decreased temporarily due to Powers.",
    ptbr  = "1. 'Distribuição' são pontos que você distribuiu manualmente.\n\n2. 'Alinhamento' são pontos recomendados que foram distribuídos automaticamente devido à sua vocação.\n\n3. 'Missão' são pontos que você pode adquirir em missões (estátua dourada, fadas errantes, cápsulas).\n\n4. 'Buff/Debuff' são pontos que foram aumentados ou diminuídos temporariamente devido a Poderes.",
    ptpt  = "1. 'Distribuição' são pontos que distribuiu manualmente.\n\n2. 'Alinhamento' são pontos recomendados que foram distribuídos automaticamente devido à sua vocação.\n\n3. 'Missão' são pontos que pode adquirir em missões (estátua dourada, fadas errantes, cápsulas).\n\n4. 'Buff/Debuff' são pontos que foram aumentados ou diminuídos temporariamente devido a Poderes.",
    es419 = "1. 'Distribución' son puntos que has distribuido manualmente.\n\n2. 'Alineación' son puntos recomendados que se distribuyeron automáticamente debido a tu vocación.\n\n3. 'Misión' son puntos que puedes adquirir en misiones (estatua dorada, hadas errantes, cápsulas).\n\n4. 'Buff/Debuff' son puntos que aumentaron o disminuyeron temporalmente debido a los Poderes.",
    eses  = "1. 'Distribución' son puntos que has distribuido manualmente.\n\n2. 'Alineación' son puntos recomendados que se distribuyeron automáticamente debido a tu vocación.\n\n3. 'Misión' son puntos que puedes adquirir en misiones (estatua dorada, hadas errantes, cápsulas).\n\n4. 'Buff/Debuff' son puntos que aumentaron o disminuyeron temporalmente debido a los Poderes.",
    pl    = "1. 'Dystrybucja' to punkty, które rozdzieliłeś ręcznie.\n\n2. 'Wyrównanie' to zalecane punkty, które zostały automatycznie rozdzielone ze względu na twoją profesję.\n\n3. 'Misja' to punkty, które możesz zdobyć podczas misji (złota statua, wędrujące wróżki, kapsuły).\n\n4. 'Buff/Debuff' to punkty, które zostały tymczasowo zwiększone lub zmniejszone przez Moce.",
    ru    = "1. «Распределение» — это очки, которые вы распределили вручную.\n\n2. «Выравнивание» — это рекомендуемые очки, которые были распределены автоматически в зависимости от вашей профессии.\n\n3. «Задание» — это очки, которые вы можете получить за задания (золотая статуя, заблудившиеся феи, капсулы).\n\n4. «Бафф/Дебафф» — это очки, которые были временно увеличены или уменьшены из-за Сил.",
    sv    = "1. 'Fördelning' är poäng som du har fördelat manuellt.\n\n2. 'Justering' är rekommenderade poäng som fördelades automatiskt på grund av din vocation.\n\n3. 'Uppdrag' är poäng som du kan få genom uppdrag (gyllene staty, vilsegångna älvor, kapslar).\n\n4. 'Buff/Debuff' är poäng som tillfälligt ökades eller minskades på grund av Krafter.",
    nb    = "1. 'Fordeling' er poeng som du har fordelt manuelt.\n\n2. 'Justering' er anbefalte poeng som ble fordelt automatisk på grunn av din profesjon.\n\n3. 'Oppdrag' er poeng som du kan få gjennom oppdrag (gyllen statue, bortkomne feer, kapsler).\n\n4. 'Buff/Debuff' er poeng som midlertidig ble økt eller redusert på grunn av Krefter.",
    de    = "1. 'Verteilung' sind Punkte, die Sie manuell verteilt haben.\n\n2. 'Ausrichtung' sind empfohlene Punkte, die aufgrund Ihrer Berufung automatisch verteilt wurden.\n\n3. 'Quest' sind Punkte, die Sie bei Quests erhalten können (goldene Statue, umherirrende Feen, Kapseln).\n\n4. 'Buff/Debuff' sind Punkte, die aufgrund von Kräften vorübergehend erhöht oder verringert wurden.",
    nlnl  = "1. 'Verdeling' zijn punten die je handmatig hebt verdeeld.\n\n2. 'Afstemming' zijn aanbevolen punten die automatisch zijn verdeeld op basis van je beroep.\n\n3. 'Missie' zijn punten die je tijdens missies kunt verkrijgen (gouden standbeeld, verdwaalde feeën, capsules).\n\n4. 'Buff/Debuff' zijn punten die tijdelijk door Krachten zijn verhoogd of verlaagd.",
    frfr  = "1. « Distribution » correspond aux points que vous avez distribués manuellement.\n\n2. « Alignement » correspond aux points recommandés qui ont été distribués automatiquement en fonction de votre vocation.\n\n3. « Quête » correspond aux points que vous pouvez obtenir lors des quêtes (statue dorée, fées errantes, capsules).\n\n4. « Buff/Debuff » correspond aux points qui ont été temporairement augmentés ou diminués par les Pouvoirs.",
    fi    = "1. « Jakelu » tarkoittaa pisteitä, jotka olet jakanut manuaalisesti.\n\n2. « Kohdistus » tarkoittaa suositeltuja pisteitä, jotka jaettiin automaattisesti ammattisi perusteella.\n\n3. « Tehtävä » tarkoittaa pisteitä, joita voit saada tehtävistä (kultainen patsas, harhailevat keijut, kapselit).\n\n4. « Tehoste/heikennys » tarkoittaa pisteitä, joita Voimat ovat väliaikaisesti lisänneet tai vähentäneet.",
    it    = "1. 'Distribuzione' indica i punti che hai distribuito manualmente.\n\n2. 'Allineamento' indica i punti consigliati che sono stati distribuiti automaticamente in base alla tua vocazione.\n\n3. 'Missione' indica i punti che puoi ottenere dalle missioni (statua d'oro, fate erranti, capsule).\n\n4. 'Buff/Debuff' indica i punti che sono stati temporaneamente aumentati o diminuiti a causa dei Poteri.",
    zhcn  = "1. “分配”是指你手动分配的点数。\n\n2. “对齐”是指根据你的职业自动分配的推荐点数。\n\n3. “任务”是指你可以通过任务获得的点数（金色雕像、流浪仙女、胶囊）。\n\n4. “增益/减益”是指因力量而暂时增加或减少的点数。",
    ja    = "1.「配分」は手動で割り振ったポイントです。\n\n2.「適性」は職業に応じて自動で割り振られた推奨ポイントです。\n\n3.「クエスト」はクエスト（黄金の像、迷子の妖精、カプセル）で獲得できるポイントです。\n\n4.「バフ/デバフ」はパワーによって一時的に増減したポイントです。",
    ko    = "1. '분배'는 직접 수동으로 분배한 포인트입니다.\n\n2. '정렬'은 직업에 따라 자동으로 분배된 추천 포인트입니다.\n\n3. '퀘스트'는 퀘스트(황금 동상, 떠도는 요정, 캡슐)를 통해 획득할 수 있는 포인트입니다.\n\n4. '버프/디버프'는 능력으로 인해 일시적으로 증가하거나 감소한 포인트입니다.",
  },

  GameAttributesLabelAttribute = {
    en    = "Attribute",
    ptbr  = "Atributo",
    ptpt  = "Atributo",
    es419 = "Atributo",
    eses  = "Atributo",
    pl    = "Atrybut",
    ru    = "Характеристика",
    sv    = "Egenskap",
    nb    = "Egenskap",
    de    = "Attribut",
    nlnl  = "Attribuut",
    frfr  = "Attribut",
    fi    = "Ominaisuus",
    it    = "Attributo",
    zhcn  = "属性",
    ja    = "属性",
    ko    = "속성",
  },

  GameAttributesLabelAct = {
    en    = "Actual",
    ptbr  = "Atual",
    ptpt  = "Atual",
    es419 = "Actual",
    eses  = "Actual",
    pl    = "Aktualny",
    ru    = "Текущее",
    sv    = "Aktuellt",
    nb    = "Gjeldende",
    de    = "Aktuell",
    nlnl  = "Actueel",
    frfr  = "Actuel",
    fi    = "Nykyinen",
    it    = "Attuale",
    zhcn  = "当前",
    ja    = "現在値",
    ko    = "현재",
  },

  GameAttributesLabelActTooltip = {
    en    = "Actual effective points of the specific attribute",
    ptbr  = "Pontos efetivos atuais do atributo específico",
    ptpt  = "Pontos efetivos atuais do atributo específico",
    es419 = "Puntos efectivos actuales del atributo específico",
    eses  = "Puntos efectivos actuales del atributo específico",
    pl    = "Aktualne efektywne punkty konkretnego atrybutu",
    ru    = "Текущие эффективные очки конкретной характеристики",
    sv    = "Aktuella effektiva poäng för den specifika egenskapen",
    nb    = "Gjeldende effektive poeng for den spesifikke egenskapen",
    de    = "Aktuelle effektive Punkte des jeweiligen Attributs",
    nlnl  = "Huidige effectieve punten van het specifieke attribuut",
    frfr  = "Points effectifs actuels de l'attribut spécifique",
    fi    = "Tietyn ominaisuuden nykyiset tehokkaat pisteet",
    it    = "Punti effettivi attuali dell'attributo specifico",
    zhcn  = "特定属性的当前有效点数",
    ja    = "特定の属性の現在の有効ポイント",
    ko    = "특정 속성의 현재 유효 포인트",
  },

  GameAttributesAttackAttributeLabel = {
    en    = "Attack",
    ptbr  = "Ataque",
    ptpt  = "Ataque",
    es419 = "Ataque",
    eses  = "Ataque",
    pl    = "Atak",
    ru    = "Атака",
    sv    = "Attack",
    nb    = "Angrep",
    de    = "Angriff",
    nlnl  = "Aanval",
    frfr  = "Attaque",
    fi    = "Hyökkäys",
    it    = "Attacco",
    zhcn  = "攻击",
    ja    = "攻撃",
    ko    = "공격",
  },

  GameAttributesDefenseAttributeLabel = {
    en    = "Defense",
    ptbr  = "Defesa",
    ptpt  = "Defesa",
    es419 = "Defensa",
    eses  = "Defensa",
    pl    = "Obrona",
    ru    = "Защита",
    sv    = "Försvar",
    nb    = "Forsvar",
    de    = "Abwehr",
    nlnl  = "Verdediging",
    frfr  = "Défense",
    fi    = "Puolustus",
    it    = "Difesa",
    zhcn  = "防御",
    ja    = "防御",
    ko    = "방어력",
  },

  GameAttributesMagicDefenseAttributeLabel = {
    en    = "Magic Def",
    ptbr  = "Def mágica",
    ptpt  = "Def mágica",
    es419 = "Def mágica",
    eses  = "Def mágica",
    pl    = "Obr. Mag.",
    ru    = "Маг. защ.",
    sv    = "Magiförsvar",
    nb    = "Magiforsvar",
    de    = "Magieabw.",
    nlnl  = "Mag. def.",
    frfr  = "Déf. mag.",
    fi    = "Taikapuol.",
    it    = "Dif. mag.",
    zhcn  = "魔法防御",
    ja    = "魔法防御",
    ko    = "마법 방어",
  },

  GameAttributesVitalityAttributeLabel = {
    en    = "Vitality",
    ptbr  = "Vitalidade",
    ptpt  = "Vitalidade",
    es419 = "Vitalidad",
    eses  = "Vitalidad",
    pl    = "Witalność",
    ru    = "Живучесть",
    sv    = "Vitalitet",
    nb    = "Vitalitet",
    de    = "Vitalität",
    nlnl  = "Vitaliteit",
    frfr  = "Vitalité",
    fi    = "Elinvoima",
    it    = "Vitalità",
    zhcn  = "活力",
    ja    = "生命力",
    ko    = "활력",
  },

  GameAttributesWillPowerAttributeLabel = {
    en    = "Will",
    ptbr  = "Vontade",
    ptpt  = "Vontade",
    es419 = "Voluntad",
    eses  = "Voluntad",
    pl    = "Wola",
    ru    = "Воля",
    sv    = "Vilja",
    nb    = "Vilje",
    de    = "Willenskraft",
    nlnl  = "Wilskracht",
    frfr  = "Volonté",
    fi    = "Tahto",
    it    = "Volontà",
    zhcn  = "意志",
    ja    = "意志",
    ko    = "의지",
  },

  GameAttributesAgilityAttributeLabel = {
    en    = "Agility",
    ptbr  = "Agilidade",
    ptpt  = "Agilidade",
    es419 = "Agilidad",
    eses  = "Agilidad",
    pl    = "Zwinność",
    ru    = "Ловкость",
    sv    = "Smidighet",
    nb    = "Smidighet",
    de    = "Bewegung",
    nlnl  = "Behendigheid",
    frfr  = "Agilité",
    fi    = "Ketteryys",
    it    = "Agilità",
    zhcn  = "敏捷",
    ja    = "敏捷",
    ko    = "민첩",
  },

  GameAttributesDodgeAttributeLabel = {
    en    = "Dodge",
    ptbr  = "Esquiva",
    ptpt  = "Esquiva",
    es419 = "Esquiva",
    eses  = "Esquiva",
    pl    = "Unik",
    ru    = "Уклонение",
    sv    = "Undvika",
    nb    = "Unnvik",
    de    = "Ausweichen",
    nlnl  = "Ontwijken",
    frfr  = "Esquive",
    fi    = "Väistö",
    it    = "Schivata",
    zhcn  = "闪避",
    ja    = "回避",
    ko    = "회피",
  },

  GameAttributesWalkingAttributeLabel = {
    en    = "Walking",
    ptbr  = "Caminhada",
    ptpt  = "Caminhada",
    es419 = "Caminar",
    eses  = "Caminar",
    pl    = "Chodzenie",
    ru    = "Ходьба",
    sv    = "Gå",
    nb    = "Gå",
    de    = "Gehen",
    nlnl  = "Lopen",
    frfr  = "Marche",
    fi    = "Kävely",
    it    = "Cammino",
    zhcn  = "行走",
    ja    = "移動",
    ko    = "걷기",
  },

  GameAttributesLuckAttributeLabel = {
    en    = "Luck",
    ptbr  = "Sorte",
    ptpt  = "Sorte",
    es419 = "Suerte",
    eses  = "Suerte",
    pl    = "Szczęście",
    ru    = "Удача",
    sv    = "Tur",
    nb    = "Tur",
    de    = "Glück",
    nlnl  = "Geluk",
    frfr  = "Chance",
    fi    = "Onni",
    it    = "Fortuna",
    zhcn  = "幸运",
    ja    = "運",
    ko    = "운",
  },

  GameAttributesButtonAddTooltip = {
    en    = "Add a distribution point",
    ptbr  = "Adicionar um ponto de distribuição",
    ptpt  = "Adicionar um ponto de distribuição",
    es419 = "Añadir un punto de distribución",
    eses  = "Añadir un punto de distribución",
    pl    = "Dodaj punkt dystrybucji",
    ru    = "Добавить очко распределения",
    sv    = "Lägg till en fördelningspoäng",
    nb    = "Legg til et fordelingspoeng",
    de    = "Einen Verteilungspunkt hinzufügen",
    nlnl  = "Een verdelingspunt toevoegen",
    frfr  = "Ajouter un point de distribution",
    fi    = "Lisää jakopiste",
    it    = "Aggiungi un punto di distribuzione",
    zhcn  = "添加分配点",
    ja    = "配分ポイントを追加",
    ko    = "분배 포인트 추가",
  },

  GameAttributesInfoPoints = {
    en    = "Points",
    ptbr  = "Pontos",
    ptpt  = "Pontos",
    es419 = "Puntos",
    eses  = "Puntos",
    pl    = "Punkty",
    ru    = "Очки",
    sv    = "Poäng",
    nb    = "Poeng",
    de    = "Punkte",
    nlnl  = "Punten",
    frfr  = "Points",
    fi    = "Pisteet",
    it    = "Punti",
    zhcn  = "点数",
    ja    = "ポイント",
    ko    = "포인트",
  },

  GameAttributesInfoCost = {
    en    = "Cost",
    ptbr  = "Custo",
    ptpt  = "Custo",
    es419 = "Costo",
    eses  = "Coste",
    pl    = "Koszt",
    ru    = "Стоимость",
    sv    = "Kostnad",
    nb    = "Kostnad",
    de    = "Kosten",
    nlnl  = "Kosten",
    frfr  = "Coût",
    fi    = "Hinta",
    it    = "Costo",
    zhcn  = "消耗",
    ja    = "コスト",
    ko    = "비용",
  },

  GameAttributesInfoUsedWithCost = {
    en    = "Used points with cost",
    ptbr  = "Pontos usados com custo",
    ptpt  = "Pontos usados com custo",
    es419 = "Puntos usados con costo",
    eses  = "Puntos usados con coste",
    pl    = "Wykorzystane punkty z kosztem",
    ru    = "Использованные очки с затратами",
    sv    = "Använda poäng med kostnad",
    nb    = "Brukte poeng med kostnad",
    de    = "Verwendete Punkte mit Kosten",
    nlnl  = "Gebruikte punten met kosten",
    frfr  = "Points utilisés avec un coût",
    fi    = "Käytetyt pisteet kustannuksella",
    it    = "Punti utilizzati con costo",
    zhcn  = "已使用的消耗点数",
    ja    = "コスト付き使用ポイント",
    ko    = "비용이 있는 사용 포인트",
  },

  GameAttributesInfoUsedWithoutCost = {
    en    = "Points used without cost",
    ptbr  = "Pontos usados sem custo",
    ptpt  = "Pontos usados sem custo",
    es419 = "Puntos usados sin costo",
    eses  = "Puntos usados sin coste",
    pl    = "Wykorzystane punkty bez kosztu",
    ru    = "Очки, использованные без затрат",
    sv    = "Poäng som används utan kostnad",
    nb    = "Poeng brukt uten kostnad",
    de    = "Verwendete Punkte ohne Kosten",
    nlnl  = "Gebruikte punten zonder kosten",
    frfr  = "Points utilisés sans coût",
    fi    = "Ilman kustannuksia käytetyt pisteet",
    it    = "Punti usati senza costo",
    zhcn  = "无需消耗的已使用点数",
    ja    = "コストなしで使用したポイント",
    ko    = "비용 없이 사용한 포인트",
  },

  GameAttributesInfoPointsToIncreaseCost = {
    en    = "Points to increase cost",
    ptbr  = "Pontos para aumentar o custo",
    ptpt  = "Pontos para aumentar o custo",
    es419 = "Puntos para aumentar el costo",
    eses  = "Puntos para aumentar el coste",
    pl    = "Punkty zwiększające koszt",
    ru    = "Очки для увеличения стоимости",
    sv    = "Poäng för att öka kostnaden",
    nb    = "Poeng for å øke kostnaden",
    de    = "Punkte zur Erhöhung der Kosten",
    nlnl  = "Punten om de kosten te verhogen",
    frfr  = "Points pour augmenter le coût",
    fi    = "Pisteet kustannusten lisäämiseen",
    it    = "Punti per aumentare il costo",
    zhcn  = "用于增加消耗的点数",
    ja    = "コストを増加させるポイント",
    ko    = "비용을 증가시키는 포인트",
  },

  GameAttributesInfoPointsEarnedPerLevel = {
    en    = "Points earned per level",
    ptbr  = "Pontos ganhos por nível",
    ptpt  = "Pontos ganhos por nível",
    es419 = "Puntos obtenidos por nivel",
    eses  = "Puntos obtenidos por nivel",
    pl    = "Punkty zdobywane na poziom",
    ru    = "Очки, получаемые за уровень",
    sv    = "Poäng som tjänas per nivå",
    nb    = "Poeng tjent per nivå",
    de    = "Punkte pro Level",
    nlnl  = "Punten verdiend per level",
    frfr  = "Points gagnés par niveau",
    fi    = "Tasoa kohden ansaitut pisteet",
    it    = "Punti guadagnati per livello",
    zhcn  = "每级获得的点数",
    ja    = "レベルごとの獲得ポイント",
    ko    = "레벨당 획득 포인트",
  },

  GameAttributesInfoDistribution = {
    en    = "Distribution",
    ptbr  = "Distribuição",
    ptpt  = "Distribuição",
    es419 = "Distribución",
    eses  = "Distribución",
    pl    = "Dystrybucja",
    ru    = "Распределение",
    sv    = "Fördelning",
    nb    = "Fordeling",
    de    = "Verteilung",
    nlnl  = "Verdeling",
    frfr  = "Répartition",
    fi    = "Jakelu",
    it    = "Distribuzione",
    zhcn  = "分配",
    ja    = "配分",
    ko    = "분배",
  },

  GameAttributesInfoOfMax = {
    en    = "of",
    ptbr  = "de",
    ptpt  = "de",
    es419 = "de",
    eses  = "de",
    pl    = "z",
    ru    = "из",
    sv    = "av",
    nb    = "av",
    de    = "von",
    nlnl  = "van",
    frfr  = "sur",
    fi    = "enintään",
    it    = "di",
    zhcn  = "的",
    ja    = "/",
    ko    = "의",
  },

  GameAttributesInfoPointsPerLevel = {
    en    = "%s per level",
    ptbr  = "%s por nível",
    ptpt  = "%s por nível",
    es419 = "%s por nivel",
    eses  = "%s por nivel",
    pl    = "%s na poziom",
    ru    = "%s за уровень",
    sv    = "%s per nivå",
    nb    = "%s per nivå",
    de    = "%s pro Stufe",
    nlnl  = "%s per niveau",
    frfr  = "%s par niveau",
    fi    = "%s tasoa kohden",
    it    = "%s per livello",
    zhcn  = "%s 每级",
    ja    = "レベルごとに%s",
    ko    = "레벨당 %s",
  },

  GameAttributesInfoUntilLevel = {
    en    = "until level %d",
    ptbr  = "até o nível %d",
    ptpt  = "até o nível %d",
    es419 = "hasta el nivel %d",
    eses  = "hasta el nivel %d",
    pl    = "do poziomu %d",
    ru    = "до уровня %d",
    sv    = "till nivå %d",
    nb    = "til nivå %d",
    de    = "bis Stufe %d",
    nlnl  = "tot niveau %d",
    frfr  = "jusqu'au niveau %d",
    fi    = "tasolle %d asti",
    it    = "fino al livello %d",
    zhcn  = "直到第 %d 级",
    ja    = "レベル%dまで",
    ko    = "%d레벨까지",
  },

  GameAttributesInfoAlignment = {
    en    = "Alignment",
    ptbr  = "Alinhamento",
    ptpt  = "Alinhamento",
    es419 = "Alineación",
    eses  = "Alineación",
    pl    = "Dostosowanie",
    ru    = "Выравнивание",
    sv    = "Justering",
    nb    = "Justering",
    de    = "Ausrichtung",
    nlnl  = "Afstemming",
    frfr  = "Alignement",
    fi    = "Kohdistus",
    it    = "Allineamento",
    zhcn  = "对齐",
    ja    = "適性",
    ko    = "정렬",
  },

  GameAttributesInfoQuest = {
    en    = "Quest",
    ptbr  = "Missão",
    ptpt  = "Missão",
    es419 = "Misión",
    eses  = "Misión",
    pl    = "Misja",
    ru    = "Задание",
    sv    = "Uppdrag",
    nb    = "Oppdrag",
    de    = "Quest",
    nlnl  = "Missie",
    frfr  = "Quête",
    fi    = "Tehtävä",
    it    = "Missione",
    zhcn  = "任务",
    ja    = "クエスト",
    ko    = "퀘스트",
  },

  GameAttributesInfoBuffDebuff = {
    en    = "Buff/Debuff",
    ptbr  = "Buff/Debuff",
    ptpt  = "Buff/Debuff",
    es419 = "Buff/Debuff",
    eses  = "Buff/Debuff",
    pl    = "Wzmocnienie/Osłabienie",
    ru    = "Бафф/Дебафф",
    sv    = "Förstärkning/Försvagning",
    nb    = "Forsterkning/Svekkelse",
    de    = "Buff/Debuff",
    nlnl  = "Buff/Debuff",
    frfr  = "Bonus/Malus",
    fi    = "Tehoste/heikennys",
    it    = "Buff/Debuff",
    zhcn  = "增益/减益",
    ja    = "バフ/デバフ",
    ko    = "버프/디버프",
  },

  GameAttributesInfoTotal = {
    en    = "Total",
    ptbr  = "Total",
    ptpt  = "Total",
    es419 = "Total",
    eses  = "Total",
    pl    = "Łącznie",
    ru    = "Всего",
    sv    = "Totalt",
    nb    = "Totalt",
    de    = "Gesamt",
    nlnl  = "Totaal",
    frfr  = "Total",
    fi    = "Yhteensä",
    it    = "Totale",
    zhcn  = "总计",
    ja    = "合計",
    ko    = "합계",
  },

  GameAttributesInfoExceededMax = {
    en    = "exceeded the maximum value",
    ptbr  = "excedeu o valor máximo",
    ptpt  = "excedeu o valor máximo",
    es419 = "superó el valor máximo",
    eses  = "superó el valor máximo",
    pl    = "przekroczył maksymalną wartość",
    ru    = "превысило максимальное значение",
    sv    = "överskred det maximala värdet",
    nb    = "overskred maksimumsverdien",
    de    = "hat den Höchstwert überschritten",
    nlnl  = "heeft de maximale waarde overschreden",
    frfr  = "a dépassé la valeur maximale",
    fi    = "ylitti enimmäisarvon",
    it    = "ha superato il valore massimo",
    zhcn  = "超过最大值",
    ja    = "最大値を超えました",
    ko    = "최대값을 초과했습니다",
  },
})
