-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  ClientGraphicsCardNotDetectedTitle = {
    en    = "Graphics card driver not detected",
    ptbr  = "Driver da placa gráfica não detectado",
    ptpt  = "Driver da placa gráfica não detectado",
    es419 = "Controlador de tarjeta gráfica no detectado",
    eses  = "Controlador de tarjeta gráfica no detectado",
    pl    = "Nie wykryto sterownika karty graficznej",
    ru    = "Драйвер видеокарты не обнаружен",
    sv    = "Grafikkortsdrivrutin upptäcktes inte",
    nb    = "Grafikkortdriver ble ikke oppdaget",
    de    = "Grafikkartentreiber nicht erkannt",
    nlnl  = "Stuurprogramma voor grafische kaart niet gedetecteerd",
    frfr  = "Pilote de carte graphique non détecté",
    fi    = "Näytönohjaimen ajuria ei havaittu",
    it    = "Driver della scheda grafica non rilevato",
    zhcn  = "未检测到显卡驱动",
    ja    = "グラフィックカードのドライバーが検出されません",
    ko    = "그래픽 카드 드라이버가 감지되지 않았습니다",
  },

  ClientGraphicsCardNotDetectedMessage = {
    en    = "No graphics card detected. Everything will be drawn using the CPU,\nthus the performance will be really bad.\nUpdate your graphics driver to have a better performance.",
    ptbr  = "Nenhuma placa gráfica detectada. Tudo será renderizado usando a CPU,\nportanto, o desempenho será muito ruim.\nAtualize seu driver gráfico para obter um melhor desempenho.",
    ptpt  = "Nenhuma placa gráfica detectada. Tudo será renderizado usando a CPU,\nportanto, o desempenho será muito ruim.\nAtualize o seu controlador gráfico para obter um melhor desempenho.",
    es419 = "No se detectó ninguna tarjeta gráfica. Todo se renderizará usando la CPU,\npor lo tanto, el rendimiento será muy malo.\nActualiza tu controlador gráfico para mejorar el rendimiento.",
    eses  = "No se detectó ninguna tarjeta gráfica. Todo se renderizará usando la CPU,\npor lo tanto, el rendimiento será muy malo.\nActualiza tu controlador gráfico para mejorar el rendimiento.",
    pl    = "Nie wykryto karty graficznej. Wszystko będzie renderowane przy użyciu procesora,\nwięc wydajność będzie bardzo słaba.\nZaktualizuj sterownik karty graficznej, aby uzyskać lepszą wydajność.",
    ru    = "Видеокарта не обнаружена. Всё будет отрисовываться с помощью процессора,\nпоэтому производительность будет очень низкой.\nОбновите драйвер видеокарты для повышения производительности.",
    sv    = "Inget grafikkort upptäcktes. Allt kommer att renderas med CPU:n,\nså prestandan blir väldigt dålig.\nUppdatera grafikdrivrutinen för bättre prestanda.",
    nb    = "Ingen grafikkortdriver ble oppdaget. Alt vil bli gjengitt med CPU-en,\nså ytelsen blir veldig dårlig.\nOppdater grafikkortdriveren for bedre ytelse.",
    de    = "Keine Grafikkarte erkannt. Alles wird über die CPU gerendert,\ndaher wird die Leistung sehr schlecht sein.\nAktualisieren Sie Ihren Grafikkartentreiber für eine bessere Leistung.",
    nlnl  = "Geen grafische kaart gevonden. Alles wordt met de CPU weergegeven,\ndaarom zullen de prestaties erg slecht zijn.\nWerk het stuurprogramma van je grafische kaart bij voor betere prestaties.",
    frfr  = "Aucune carte graphique détectée. Tout sera rendu par le processeur,\nles performances seront donc très mauvaises.\nMettez à jour le pilote de votre carte graphique pour améliorer les performances.",
    fi    = "Näytönohjainta ei havaittu. Kaikki piirretään suorittimella,\njoten suorituskyky on erittäin heikko.\nPäivitä näytönohjaimen ajuri suorituskyvyn parantamiseksi.",
    it    = "Nessuna scheda grafica rilevata. Tutto verrà renderizzato usando la CPU,\nquindi le prestazioni saranno molto scarse.\nAggiorna il driver grafico per migliorare le prestazioni.",
    zhcn  = "未检测到显卡。所有内容将使用 CPU 渲染，\n因此性能会非常差。\n请更新显卡驱动以获得更好的性能。",
    ja    = "グラフィックカードが検出されません。すべてCPUで描画されるため、\nパフォーマンスが非常に低下します。\nグラフィックドライバーを更新して、パフォーマンスを向上させてください。",
    ko    = "그래픽 카드가 감지되지 않았습니다. 모든 것이 CPU를 사용하여 렌더링되므로,\n성능이 매우 저하됩니다.\n더 나은 성능을 위해 그래픽 카드 드라이버를 업데이트하세요.",
  },

  ClientLoadingBoxMessage = {
    en    = "Loading files...",
    ptbr  = "Carregando arquivos...",
    ptpt  = "Carregando ficheiros...",
    es419 = "Cargando archivos...",
    eses  = "Cargando archivos...",
    pl    = "Ładowanie plików...",
    ru    = "Загрузка файлов...",
    sv    = "Laddar filer...",
    nb    = "Laster filer...",
    de    = "Dateien werden geladen...",
    nlnl  = "Bestanden laden...",
    frfr  = "Chargement des fichiers...",
    fi    = "Ladataan tiedostoja...",
    it    = "Caricamento dei file...",
    zhcn  = "正在加载文件……",
    ja    = "ファイルを読み込み中…",
    ko    = "파일을 불러오는 중...",
  },

  ClientUnableToLoadDat = {
    en    = "Unable to load dat file. Place a valid dat in '%s'.",
    ptbr  = "Não foi possível carregar o arquivo dat. Insira um dat válido em '%s'.",
    ptpt  = "Não foi possível carregar o ficheiro dat. Insira um dat válido em '%s'.",
    es419 = "No se puede cargar el archivo dat. Coloca un dat válido en '%s'.",
    eses  = "No se puede cargar el archivo dat. Coloca un dat válido en '%s'.",
    pl    = "Nie można załadować pliku dat. Umieść prawidłowy plik dat w '%s'.",
    ru    = "Не удалось загрузить файл dat. Поместите корректный файл dat в '%s'.",
    sv    = "Det gick inte att ladda dat-filen. Placera en giltig dat-fil i '%s'.",
    nb    = "Kan ikke laste inn dat-filen. Plasser en gyldig dat-fil i '%s'.",
    de    = "Die Dat-Datei konnte nicht geladen werden. Platzieren Sie eine gültige Dat-Datei in '%s'.",
    nlnl  = "Kan het dat-bestand niet laden. Plaats een geldig dat-bestand in '%s'.",
    frfr  = "Impossible de charger le fichier dat. Placez un fichier dat valide dans « %s ».",
    fi    = "Dat-tiedostoa ei voitu ladata. Sijoita kelvollinen dat-tiedosto hakemistoon \"%s\".",
    it    = "Impossibile caricare il file dat. Inserisci un file dat valido in '%s'.",
    zhcn  = "无法加载 dat 文件。请将有效的 dat 文件放入“%s”。",
    ja    = "datファイルを読み込めません。有効なdatファイルを%sに配置してください。",
    ko    = "dat 파일을 불러올 수 없습니다. '%s'에 유효한 dat 파일을 넣어주세요.",
  },

  ClientUnableToLoadSpr = {
    en    = "Unable to load spr file. Place a valid spr in '%s'.",
    ptbr  = "Não foi possível carregar o arquivo spr. Insira um spr válido em '%s'.",
    ptpt  = "Não foi possível carregar o ficheiro spr. Insira um spr válido em '%s'.",
    es419 = "No se puede cargar el archivo spr. Coloca un spr válido en '%s'.",
    eses  = "No se puede cargar el archivo spr. Coloca un spr válido en '%s'.",
    pl    = "Nie można załadować pliku spr. Umieść prawidłowy plik spr w '%s'.",
    ru    = "Не удалось загрузить файл spr. Поместите корректный файл spr в '%s'.",
    sv    = "Det gick inte att ladda spr-filen. Placera en giltig spr-fil i '%s'.",
    nb    = "Kan ikke laste inn spr-filen. Plasser en gyldig spr-fil i '%s'.",
    de    = "Die Spr-Datei konnte nicht geladen werden. Platzieren Sie eine gültige Spr-Datei in '%s'.",
    nlnl  = "Kan het spr-bestand niet laden. Plaats een geldig spr-bestand in '%s'.",
    frfr  = "Impossible de charger le fichier spr. Placez un fichier spr valide dans « %s ».",
    fi    = "Spr-tiedostoa ei voitu ladata. Sijoita kelvollinen spr-tiedosto hakemistoon \"%s\".",
    it    = "Impossibile caricare il file spr. Inserisci un file spr valido in '%s'.",
    zhcn  = "无法加载 spr 文件。请将有效的 spr 文件放入“%s”。",
    ja    = "sprファイルを読み込めません。有効なsprファイルを%sに配置してください。",
    ko    = "spr 파일을 불러올 수 없습니다. '%s'에 유효한 spr 파일을 넣어주세요.",
  },

})
