-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameInterfaceButtonJobSkillsTooltip = {
    en    = "Job skills",
    ptbr  = "Habilidades de trabalho",
    ptpt  = "Habilidades de trabalho",
    es419 = "Habilidades de oficio",
    eses  = "Habilidades de oficio",
    pl    = "Umiejętności zawodowe",
    ru    = "Профессиональные навыки",
    sv    = "Jobbfärdigheter",
    nb    = "Jobbferdigheter",
    de    = "Berufsfertigkeiten",
    nlnl  = "Beroepsvaardigheden",
    frfr  = "Compétences professionnelles",
    fi    = "Ammattitaidot",
    it    = "Abilità professionali",
    zhcn  = "职业技能",
    ja    = "職業スキル",
    ko    = "직업 기술",
  },

  GameInterfaceFYI = {
    en    = "For your information",
    ptbr  = "Para sua informação",
    ptpt  = "Para sua informação",
    es419 = "Para su información",
    eses  = "Para su información",
    pl    = "Dla twojej informacji",
    ru    = "Для вашей информации",
    sv    = "För din information",
    nb    = "Til din informasjon",
    de    = "Zu Ihrer Information",
    nlnl  = "Ter informatie",
    frfr  = "Pour votre information",
    fi    = "Tiedoksi",
    it    = "Per tua informazione",
    zhcn  = "供您参考",
    ja    = "参考情報",
    ko    = "참고",
  },

  GameInterfaceExitWindowMsg = {
    en    = "If you shut down the game, your character might stay connected.",
    ptbr  = "Se você encerrar o jogo, seu personagem pode permanecer conectado.",
    ptpt  = "Se você encerrar o jogo, o seu personagem pode permanecer conectado.",
    es419 = "Si cierras el juego, tu personaje podría permanecer conectado.",
    eses  = "Si cierras el juego, tu personaje podría permanecer conectado.",
    pl    = "Jeśli zamkniesz grę, twoja postać może pozostać połączona.",
    ru    = "Если закрыть игру, ваш персонаж может остаться подключённым.",
    sv    = "Om du stänger spelet kan din karaktär förbli ansluten.",
    nb    = "Hvis du avslutter spillet, kan figuren din forbli tilkoblet.",
    de    = "Wenn du das Spiel beendest, bleibt dein Charakter möglicherweise verbunden.",
    nlnl  = "Als je het spel afsluit, kan je personage verbonden blijven.",
    frfr  = "Si vous fermez le jeu, votre personnage peut rester connecté.",
    fi    = "Jos suljet pelin, hahmosi saattaa jäädä yhdistetyksi.",
    it    = "Se chiudi il gioco, il tuo personaggio potrebbe rimanere connesso.",
    zhcn  = "如果关闭游戏，你的角色可能仍保持在线。",
    ja    = "ゲームを終了すると、キャラクターが接続されたままになる場合があります。",
    ko    = "게임을 종료하면 캐릭터가 연결된 상태로 남아 있을 수 있습니다.",
  },

  GameInterfaceExitWindowButtonForceExit = {
    en    = "Force exit",
    ptbr  = "Forçar saída",
    ptpt  = "Forçar saída",
    es419 = "Forzar salida",
    eses  = "Forzar salida",
    pl    = "Wymuś wyjście",
    ru    = "Принудительный выход",
    sv    = "Tvinga avslut",
    nb    = "Tving avslutning",
    de    = "Beenden erzwingen",
    nlnl  = "Geforceerd afsluiten",
    frfr  = "Forcer la fermeture",
    fi    = "Pakota poistuminen",
    it    = "Forza uscita",
    zhcn  = "强制退出",
    ja    = "強制終了",
    ko    = "강제 종료",
  },

  GameInterfaceExitWindowButtonForceExitTooltip = {
    en    = "Exit the game without logging out your character",
    ptbr  = "Saia do jogo sem desconectar seu personagem",
    ptpt  = "Saia do jogo sem desconectar a sua personagem",
    es419 = "Sal del juego sin desconectar a tu personaje",
    eses  = "Sal del juego sin desconectar a tu personaje",
    pl    = "Wyjdź z gry bez rozłączania swojej postaci",
    ru    = "Выйдите из игры, не отключая своего персонажа",
    sv    = "Avsluta spelet utan att koppla från din karaktär",
    nb    = "Avslutt spillet uten å koble fra figuren din",
    de    = "Beenden Sie das Spiel, ohne Ihren Charakter zu trennen",
    nlnl  = "Sluit het spel af zonder je personage te verbreken",
    frfr  = "Quittez le jeu sans déconnecter votre personnage",
    fi    = "Poistu pelistä katkaisematta yhteyttä hahmoosi",
    it    = "Esci dal gioco senza disconnettere il tuo personaggio",
    zhcn  = "退出游戏而不让你的角色断开连接",
    ja    = "キャラクターを切断せずにゲームを終了する",
    ko    = "캐릭터의 연결을 끊지 않고 게임을 종료합니다",
  },

  GameInterfaceLogoutWindowFailingConnectionMsg = {
    en    = "Your connection is failing. If you logout now, your\ncharacter will be still online. Do you want to\nforce logout?",
    ptbr  = "Sua conexão está falhando. Se você sair agora, seu\npersonagem ainda estará online. Deseja\nforçar a desconexão?",
    ptpt  = "A sua ligação está a falhar. Se sair agora, o seu\npersonagem continuará online. Deseja\nforçar a desconexão?",
    es419 = "Tu conexión está fallando. Si cierras sesión ahora, tu\npersonaje seguirá en línea. ¿Quieres\nforzar la desconexión?",
    eses  = "Tu conexión está fallando. Si cierras sesión ahora, tu\npersonaje seguirá en línea. ¿Quieres\nforzar la desconexión?",
    pl    = "Twoje połączenie jest niestabilne. Jeśli wylogujesz się teraz, twoja\npostać nadal będzie online. Czy chcesz\nwymusić wylogowanie?",
    ru    = "Ваше соединение нестабильно. Если выйти сейчас, ваш\nперсонаж останется онлайн. Хотите\nпринудительно отключиться?",
    sv    = "Din anslutning fungerar inte. Om du loggar ut nu kommer din\nkaraktär fortfarande vara online. Vill du\ntvinga fram utloggning?",
    nb    = "Tilkoblingen din fungerer ikke som den skal. Hvis du logger ut nå, vil\nfiguren din fortsatt være online. Vil du\ntvinge frem utlogging?",
    de    = "Deine Verbindung funktioniert nicht richtig. Wenn du dich jetzt abmeldest, bleibt dein\nCharakter weiterhin online. Möchtest du die\nAbmeldung erzwingen?",
    nlnl  = "Je verbinding werkt niet goed. Als je nu uitlogt,\nblijft je personage online. Wil je\nhet uitloggen forceren?",
    frfr  = "Votre connexion fonctionne mal. Si vous vous déconnectez maintenant, votre\npersonnage restera en ligne. Voulez-vous\nforcer la déconnexion ?",
    fi    = "Yhteytesi ei toimi kunnolla. Jos kirjaudut ulos nyt,\nhahmosi jää online-tilaan. Haluatko\npakottaa uloskirjautumisen?",
    it    = "La connessione non funziona correttamente. Se ti disconnetti ora, il tuo\npersonaggio resterà online. Vuoi\nforzare la disconnessione?",
    zhcn  = "你的连接出现问题。如果现在登出，你的\n角色仍会在线。是否要\n强制登出？",
    ja    = "接続に問題があります。今ログアウトすると、\nキャラクターはオンラインのままになります。\n強制ログアウトしますか？",
    ko    = "연결 상태가 좋지 않습니다. 지금 로그아웃하면\n캐릭터가 계속 온라인 상태로 남습니다.\n강제로 로그아웃하시겠습니까?",
  },

  GameInterfaceLogoutWindowRequestMsg = {
    en    = "Are you sure you want to logout?",
    ptbr  = "Tem certeza de que deseja sair?",
    ptpt  = "Tem a certeza de que deseja sair?",
    es419 = "¿Estás seguro de que deseas cerrar sesión?",
    eses  = "¿Estás seguro de que deseas cerrar sesión?",
    pl    = "Czy na pewno chcesz się wylogować?",
    ru    = "Вы уверены, что хотите выйти?",
    sv    = "Är du säker på att du vill logga ut?",
    nb    = "Er du sikker på at du vil logge ut?",
    de    = "Bist du sicher, dass du dich abmelden möchtest?",
    nlnl  = "Weet je zeker dat je wilt uitloggen?",
    frfr  = "Voulez-vous vraiment vous déconnecter ?",
    fi    = "Haluatko varmasti kirjautua ulos?",
    it    = "Sei sicuro di voler uscire?",
    zhcn  = "确定要登出吗？",
    ja    = "ログアウトしますか？",
    ko    = "정말 로그아웃하시겠습니까?",
  },

  GameInterfaceContextMenuUnwrap = {
    en    = "Unwrap",
    ptbr  = "Desembrulhar",
    ptpt  = "Desembrulhar",
    es419 = "Desenvolver",
    eses  = "Desenvolver",
    pl    = "Rozpakować",
    ru    = "Развернуть",
    sv    = "Packa upp",
    nb    = "Pakke opp",
    de    = "Auspacken",
    nlnl  = "Uitpakken",
    frfr  = "Déballer",
    fi    = "Avaa pakkaus",
    it    = "Scartare",
    zhcn  = "拆包",
    ja    = "開封",
    ko    = "포장 풀기",
  },

  GameInterfaceContextMenuWrap = {
    en    = "Wrap",
    ptbr  = "Embrulhar",
    ptpt  = "Embrulhar",
    es419 = "Envolver",
    eses  = "Envolver",
    pl    = "Zapakować",
    ru    = "Упаковать",
    sv    = "Slå in",
    nb    = "Pakke inn",
    de    = "Einwickeln",
    nlnl  = "Inpakken",
    frfr  = "Emballer",
    fi    = "Pakkaa",
    it    = "Impacchettare",
    zhcn  = "打包",
    ja    = "包む",
    ko    = "포장하기",
  },

  GameInterfaceContextMenuOpenInNewWindow = {
    en    = "Open in new window",
    ptbr  = "Abrir em nova janela",
    ptpt  = "Abrir numa nova janela",
    es419 = "Abrir en una nueva ventana",
    eses  = "Abrir en una nueva ventana",
    pl    = "Otwórz w nowym oknie",
    ru    = "Открыть в новом окне",
    sv    = "Öppna i nytt fönster",
    nb    = "Åpne i et nytt vindu",
    de    = "In neuem Fenster öffnen",
    nlnl  = "In nieuw venster openen",
    frfr  = "Ouvrir dans une nouvelle fenêtre",
    fi    = "Avaa uuteen ikkunaan",
    it    = "Apri in una nuova finestra",
    zhcn  = "在新窗口中打开",
    ja    = "新しいウィンドウで開く",
    ko    = "새 창에서 열기",
  },

  GameInterfaceContextMenuUseWith = {
    en    = "Use with...",
    ptbr  = "Usar com...",
    ptpt  = "Usar com...",
    es419 = "Usar con...",
    eses  = "Usar con...",
    pl    = "Użyj z...",
    ru    = "Использовать с...",
    sv    = "Använd med...",
    nb    = "Bruk med...",
    de    = "Benutzen mit...",
    nlnl  = "Gebruiken met...",
    frfr  = "Utiliser avec...",
    fi    = "Käytä yhdessä...",
    it    = "Usa con...",
    zhcn  = "与……一起使用",
    ja    = "これと使用…",
    ko    = "다음과 함께 사용...",
  },

  GameInterfaceContextMenuUse = {
    en    = "Use",
    ptbr  = "Usar",
    ptpt  = "Usar",
    es419 = "Usar",
    eses  = "Usar",
    pl    = "Użyj",
    ru    = "Использовать",
    sv    = "Använd",
    nb    = "Bruk",
    de    = "Benutzen",
    nlnl  = "Gebruiken",
    frfr  = "Utiliser",
    fi    = "Käytä",
    it    = "Usa",
    zhcn  = "使用",
    ja    = "使用",
    ko    = "사용",
  },

  GameInterfaceContextMenuRotate = {
    en    = "Rotate",
    ptbr  = "Girar",
    ptpt  = "Girar",
    es419 = "Girar",
    eses  = "Girar",
    pl    = "Obróć",
    ru    = "Повернуть",
    sv    = "Rotera",
    nb    = "Roter",
    de    = "Drehen",
    nlnl  = "Draaien",
    frfr  = "Faire pivoter",
    fi    = "Kierrä",
    it    = "Ruota",
    zhcn  = "旋转",
    ja    = "回転",
    ko    = "회전",
  },

  GameInterfaceContextMenuTradeWith = {
    en    = "Trade with...",
    ptbr  = "Comerciar com...",
    ptpt  = "Comerciar com...",
    es419 = "Comerciar con...",
    eses  = "Comerciar con...",
    pl    = "Handluj z...",
    ru    = "Торговать с...",
    sv    = "Handla med...",
    nb    = "Handle med...",
    de    = "Handeln mit...",
    nlnl  = "Handelen met...",
    frfr  = "Échanger avec...",
    fi    = "Käy kauppaa...",
    it    = "Commercia con...",
    zhcn  = "与……交易",
    ja    = "これと取引…",
    ko    = "거래하기...",
  },

  GameInterfaceContextMenuMoveUp = {
    en    = "Move up",
    ptbr  = "Mover para cima",
    ptpt  = "Mover para cima",
    es419 = "Mover arriba",
    eses  = "Mover arriba",
    pl    = "Przenieś w górę",
    ru    = "Переместить вверх",
    sv    = "Flytta uppåt",
    nb    = "Flytt opp",
    de    = "Nach oben bewegen",
    nlnl  = "Omhoog verplaatsen",
    frfr  = "Déplacer vers le haut",
    fi    = "Siirrä ylös",
    it    = "Sposta su",
    zhcn  = "向上移动",
    ja    = "上へ移動",
    ko    = "위로 이동",
  },

  GameInterfaceContextMenuSetOutfit = {
    en    = "Set outfit",
    ptbr  = "Definir traje",
    ptpt  = "Definir traje",
    es419 = "Establecer atuendo",
    eses  = "Establecer atuendo",
    pl    = "Ustaw strój",
    ru    = "Выбрать наряд",
    sv    = "Välj outfit",
    nb    = "Velg antrekk",
    de    = "Outfit festlegen",
    nlnl  = "Uitrusting instellen",
    frfr  = "Définir la tenue",
    fi    = "Aseta asu",
    it    = "Imposta aspetto",
    zhcn  = "设置外观",
    ja    = "衣装を設定",
    ko    = "복장 설정",
  },

  GameInterfaceContextMenuMount = {
    en    = "Mount",
    ptbr  = "Montar",
    ptpt  = "Montar",
    es419 = "Montar",
    eses  = "Montar",
    pl    = "Wsiąść",
    ru    = "Сесть на маунта",
    sv    = "Rida",
    nb    = "Ri",
    de    = "Aufsteigen",
    nlnl  = "Berijden",
    frfr  = "Monter",
    fi    = "Ratsasta",
    it    = "Monta",
    zhcn  = "骑乘",
    ja    = "騎乗",
    ko    = "탑승",
  },

  GameInterfaceContextMenuDismount = {
    en    = "Dismount",
    ptbr  = "Desmontar",
    ptpt  = "Desmontar",
    es419 = "Desmontar",
    eses  = "Desmontar",
    pl    = "Zsiąść",
    ru    = "Слезть с маунта",
    sv    = "Stig av",
    nb    = "Stig av",
    de    = "Absteigen",
    nlnl  = "Afstijgen",
    frfr  = "Descendre",
    fi    = "Nouse ratsailta",
    it    = "Smonta",
    zhcn  = "下坐骑",
    ja    = "騎乗解除",
    ko    = "내리기",
  },

  GameInterfaceContextMenuSharedXPDisable = {
    en    = "Disable shared XP",
    ptbr  = "Desativar XP compartilhado",
    ptpt  = "Desativar XP partilhado",
    es419 = "Desactivar XP compartida",
    eses  = "Desactivar XP compartida",
    pl    = "Wyłącz wspólne XP",
    ru    = "Отключить общий XP",
    sv    = "Inaktivera delad XP",
    nb    = "Deaktiver delt XP",
    de    = "Geteilte XP deaktivieren",
    nlnl  = "Gedeelde XP uitschakelen",
    frfr  = "Désactiver l'XP partagée",
    fi    = "Poista jaettu XP käytöstä",
    it    = "Disattiva XP condivisa",
    zhcn  = "禁用共享XP",
    ja    = "共有XPを無効化",
    ko    = "공유 XP 비활성화",
  },

  GameInterfaceContextMenuSharedXPEnable = {
    en    = "Enable shared XP",
    ptbr  = "Ativar XP compartilhado",
    ptpt  = "Ativar XP partilhado",
    es419 = "Activar XP compartida",
    eses  = "Activar XP compartida",
    pl    = "Włącz wspólne XP",
    ru    = "Включить общий XP",
    sv    = "Aktivera delad XP",
    nb    = "Aktiver delt XP",
    de    = "Geteilte XP aktivieren",
    nlnl  = "Gedeelde XP inschakelen",
    frfr  = "Activer l'XP partagée",
    fi    = "Ota jaettu XP käyttöön",
    it    = "Attiva XP condivisa",
    zhcn  = "启用共享XP",
    ja    = "共有XPを有効化",
    ko    = "공유 XP 활성화",
  },

  GameInterfaceContextMenuLeaveParty = {
    en    = "Leave party",
    ptbr  = "Sair da equipe",
    ptpt  = "Sair da equipa",
    es419 = "Salir del equipo",
    eses  = "Salir del equipo",
    pl    = "Opuść drużynę",
    ru    = "Покинуть группу",
    sv    = "Lämna gruppen",
    nb    = "Forlat gruppen",
    de    = "Gruppe verlassen",
    nlnl  = "Groep verlaten",
    frfr  = "Quitter le groupe",
    fi    = "Poistu ryhmästä",
    it    = "Lascia il gruppo",
    zhcn  = "离开队伍",
    ja    = "パーティーを離脱",
    ko    = "파티 탈퇴",
  },

  GameInterfaceContextMenuRuleViolations = {
    en    = "View rule violations",
    ptbr  = "Ver violações de regras",
    ptpt  = "Ver violações das regras",
    es419 = "Ver infracciones de las reglas",
    eses  = "Ver infracciones de las reglas",
    pl    = "Zobacz naruszenia zasad",
    ru    = "Просмотреть нарушения правил",
    sv    = "Visa regelöverträdelser",
    nb    = "Vis regelbrudd",
    de    = "Regelverstöße anzeigen",
    nlnl  = "Regelovertredingen bekijken",
    frfr  = "Voir les infractions",
    fi    = "Näytä sääntörikkomukset",
    it    = "Visualizza violazioni delle regole",
    zhcn  = "查看违规行为",
    ja    = "ルール違反を表示",
    ko    = "규칙 위반 보기",
  },

  GameInterfaceContextMenuAttack = {
    en    = "Attack",
    ptbr  = "Atacar",
    ptpt  = "Atacar",
    es419 = "Atacar",
    eses  = "Atacar",
    pl    = "Atakuj",
    ru    = "Атаковать",
    sv    = "Attackera",
    nb    = "Angrip",
    de    = "Angreifen",
    nlnl  = "Aanvallen",
    frfr  = "Attaquer",
    fi    = "Hyökkää",
    it    = "Attacca",
    zhcn  = "攻击",
    ja    = "攻撃",
    ko    = "공격",
  },

  GameInterfaceContextMenuAttackStop = {
    en    = "Stop attack",
    ptbr  = "Parar ataque",
    ptpt  = "Parar ataque",
    es419 = "Detener ataque",
    eses  = "Detener ataque",
    pl    = "Zatrzymaj atak",
    ru    = "Остановить атаку",
    sv    = "Stoppa attacken",
    nb    = "Stopp angrep",
    de    = "Angriff stoppen",
    nlnl  = "Aanval stoppen",
    frfr  = "Arrêter l'attaque",
    fi    = "Lopeta hyökkäys",
    it    = "Ferma attacco",
    zhcn  = "停止攻击",
    ja    = "攻撃を停止",
    ko    = "공격 중지",
  },

  GameInterfaceContextMenuFollow = {
    en    = "Follow",
    ptbr  = "Seguir",
    ptpt  = "Seguir",
    es419 = "Seguir",
    eses  = "Seguir",
    pl    = "Podążaj za",
    ru    = "Следовать",
    sv    = "Följ",
    nb    = "Følg",
    de    = "Folgen",
    nlnl  = "Volgen",
    frfr  = "Suivre",
    fi    = "Seuraa",
    it    = "Segui",
    zhcn  = "跟随",
    ja    = "追跡",
    ko    = "따라가기",
  },

  GameInterfaceContextMenuFollowStop = {
    en    = "Stop follow",
    ptbr  = "Parar de seguir",
    ptpt  = "Parar de seguir",
    es419 = "Dejar de seguir",
    eses  = "Dejar de seguir",
    pl    = "Przestań śledzić",
    ru    = "Перестать следовать",
    sv    = "Sluta följa",
    nb    = "Slutt å følge",
    de    = "Folgen stoppen",
    nlnl  = "Volgen stoppen",
    frfr  = "Arrêter de suivre",
    fi    = "Lopeta seuraaminen",
    it    = "Smetti di seguire",
    zhcn  = "停止跟随",
    ja    = "追跡を停止",
    ko    = "따라가기 중지",
  },

  GameInterfaceContextMenuTrack = {
    en    = "Track",
    ptbr  = "Rastrear",
    ptpt  = "Rastrear",
    es419 = "Rastrear",
    eses  = "Rastrear",
    pl    = "Śledź",
    ru    = "Отслеживать",
    sv    = "Spåra",
    nb    = "Spor",
    de    = "Verfolgen",
    nlnl  = "Volgen",
    frfr  = "Suivre",
    fi    = "Seuraa sijaintia",
    it    = "Traccia",
    zhcn  = "跟踪",
    ja    = "追跡",
    ko    = "추적",
  },

  GameInterfaceContextMenuTrackStop = {
    en    = "Stop track",
    ptbr  = "Parar rastreamento",
    ptpt  = "Parar rastreamento",
    es419 = "Detener rastreo",
    eses  = "Detener rastreo",
    pl    = "Zatrzymaj śledzenie",
    ru    = "Прекратить отслеживание",
    sv    = "Stoppa spårning",
    nb    = "Stopp sporing",
    de    = "Verfolgung stoppen",
    nlnl  = "Volgen stoppen",
    frfr  = "Arrêter le suivi",
    fi    = "Lopeta seuranta",
    it    = "Ferma tracciamento",
    zhcn  = "停止跟踪",
    ja    = "追跡を停止",
    ko    = "추적 중지",
  },

  GameInterfaceContextMenuTrackEdit = {
    en    = "Edit track",
    ptbr  = "Editar rastreamento",
    ptpt  = "Editar rastreamento",
    es419 = "Editar rastreo",
    eses  = "Editar rastreo",
    pl    = "Edytuj śledzenie",
    ru    = "Изменить отслеживание",
    sv    = "Redigera spårning",
    nb    = "Rediger sporing",
    de    = "Verfolgung bearbeiten",
    nlnl  = "Volgen bewerken",
    frfr  = "Modifier le suivi",
    fi    = "Muokkaa seurantaa",
    it    = "Modifica tracciamento",
    zhcn  = "编辑跟踪",
    ja    = "追跡を編集",
    ko    = "추적 편집",
  },

  GameInterfaceContextMenuTalk = {
    en    = "Talk",
    ptbr  = "Falar",
    ptpt  = "Falar",
    es419 = "Hablar",
    eses  = "Hablar",
    pl    = "Rozmawiać",
    ru    = "Говорить",
    sv    = "Tala",
    nb    = "Snakk",
    de    = "Sprechen",
    nlnl  = "Praten",
    frfr  = "Parler",
    fi    = "Puhu",
    it    = "Parla",
    zhcn  = "交谈",
    ja    = "話す",
    ko    = "대화",
  },

  GameInterfaceContextMenuMsgTo = {
    en    = "Message to %s",
    ptbr  = "Mensagem para %s",
    ptpt  = "Mensagem para %s",
    es419 = "Mensaje para %s",
    eses  = "Mensaje para %s",
    pl    = "Wiadomość do %s",
    ru    = "Сообщение для %s",
    sv    = "Meddelande till %s",
    nb    = "Melding til %s",
    de    = "Nachricht an %s",
    nlnl  = "Bericht aan %s",
    frfr  = "Message à %s",
    fi    = "Viesti pelaajalle %s",
    it    = "Messaggio per %s",
    zhcn  = "发送消息给 %s",
    ja    = "%sへのメッセージ",
    ko    = "%s에게 메시지",
  },

  GameInterfaceContextMenuPrivateChatInvite = {
    en    = "Invite to private chat",
    ptbr  = "Convidar para chat privado",
    ptpt  = "Convidar para chat privado",
    es419 = "Invitar al chat privado",
    eses  = "Invitar al chat privado",
    pl    = "Zaproś do prywatnego czatu",
    ru    = "Пригласить в приватный чат",
    sv    = "Bjud in till privat chatt",
    nb    = "Inviter til privat chat",
    de    = "Zum privaten Chat einladen",
    nlnl  = "Uitnodigen voor privéchat",
    frfr  = "Inviter à une discussion privée",
    fi    = "Kutsu yksityiseen chatiin",
    it    = "Invita alla chat privata",
    zhcn  = "邀请加入私人聊天",
    ja    = "プライベートチャットに招待",
    ko    = "비공개 채팅에 초대",
  },

  GameInterfaceContextMenuPrivateChatExclude = {
    en    = "Exclude from private chat",
    ptbr  = "Excluir do chat privado",
    ptpt  = "Excluir do chat privado",
    es419 = "Excluir del chat privado",
    eses  = "Excluir del chat privado",
    pl    = "Wyklucz z prywatnego czatu",
    ru    = "Исключить из приватного чата",
    sv    = "Uteslut från privat chatt",
    nb    = "Ekskluder fra privat chat",
    de    = "Aus dem privaten Chat ausschließen",
    nlnl  = "Uit privéchat verwijderen",
    frfr  = "Exclure de la discussion privée",
    fi    = "Poista yksityisestä chatista",
    it    = "Escludi dalla chat privata",
    zhcn  = "从私人聊天中移除",
    ja    = "プライベートチャットから除外",
    ko    = "비공개 채팅에서 제외",
  },

  GameInterfaceContextMenuVipListAdd = {
    en    = "Add to contacts",
    ptbr  = "Adicionar aos contatos",
    ptpt  = "Adicionar aos contactos",
    es419 = "Añadir a los contactos",
    eses  = "Añadir a los contactos",
    pl    = "Dodaj do kontaktów",
    ru    = "Добавить в контакты",
    sv    = "Lägg till i kontakter",
    nb    = "Legg til i kontakter",
    de    = "Zu den Kontakten hinzufügen",
    nlnl  = "Aan contacten toevoegen",
    frfr  = "Ajouter aux contacts",
    fi    = "Lisää yhteystietoihin",
    it    = "Aggiungi ai contatti",
    zhcn  = "添加到联系人",
    ja    = "連絡先に追加",
    ko    = "연락처에 추가",
  },

  GameInterfaceContextMenuPlayerUnignore = {
    en    = "Unignore %s",
    ptbr  = "Deixar de ignorar %s",
    ptpt  = "Deixar de ignorar %s",
    es419 = "Dejar de ignorar a %s",
    eses  = "Dejar de ignorar a %s",
    pl    = "Przestań ignorować %s",
    ru    = "Перестать игнорировать %s",
    sv    = "Sluta ignorera %s",
    nb    = "Slutt å ignorere %s",
    de    = "%s nicht mehr ignorieren",
    nlnl  = "%s niet meer negeren",
    frfr  = "Ne plus ignorer %s",
    fi    = "Lopeta pelaajan %s ohittaminen",
    it    = "Smetti di ignorare %s",
    zhcn  = "取消忽略 %s",
    ja    = "%sの無視を解除",
    ko    = "%s 무시 해제",
  },

  GameInterfaceContextMenuPlayerIgnore = {
    en    = "Ignore %s",
    ptbr  = "Ignorar %s",
    ptpt  = "Ignorar %s",
    es419 = "Ignorar a %s",
    eses  = "Ignorar a %s",
    pl    = "Ignoruj %s",
    ru    = "Игнорировать %s",
    sv    = "Ignorera %s",
    nb    = "Ignorer %s",
    de    = "%s ignorieren",
    nlnl  = "%s negeren",
    frfr  = "Ignorer %s",
    fi    = "Ohita pelaaja %s",
    it    = "Ignora %s",
    zhcn  = "忽略 %s",
    ja    = "%sを無視",
    ko    = "%s 무시",
  },

  GameInterfaceContextMenuPartyJoin = {
    en    = "Join party of %s",
    ptbr  = "Entrar no grupo de %s",
    ptpt  = "Entrar no grupo de %s",
    es419 = "Unirse al grupo de %s",
    eses  = "Unirse al grupo de %s",
    pl    = "Dołącz do grupy %s",
    ru    = "Присоединиться к группе %s",
    sv    = "Gå med i gruppen %s",
    nb    = "Bli med i gruppen til %s",
    de    = "Der Gruppe von %s beitreten",
    nlnl  = "Deelnemen aan de groep van %s",
    frfr  = "Rejoindre le groupe de %s",
    fi    = "Liity pelaajan %s ryhmään",
    it    = "Unisciti al gruppo di %s",
    zhcn  = "加入 %s 的队伍",
    ja    = "%sのパーティーに参加",
    ko    = "%s의 파티에 참가",
  },

  GameInterfaceContextMenuPartyInvite = {
    en    = "Invite to party",
    ptbr  = "Convidar para grupo",
    ptpt  = "Convidar para grupo",
    es419 = "Invitar al grupo",
    eses  = "Invitar al grupo",
    pl    = "Zaproś do grupy",
    ru    = "Пригласить в группу",
    sv    = "Bjud in till grupp",
    nb    = "Inviter til gruppe",
    de    = "In die Gruppe einladen",
    nlnl  = "Voor de groep uitnodigen",
    frfr  = "Inviter dans le groupe",
    fi    = "Kutsu ryhmään",
    it    = "Invita nel gruppo",
    zhcn  = "邀请加入队伍",
    ja    = "パーティーに招待",
    ko    = "파티에 초대",
  },

  GameInterfaceContextMenuPartyRevokeInvitation = {
    en    = "Revoke invitation of %s",
    ptbr  = "Revogar convite de %s",
    ptpt  = "Revogar convite de %s",
    es419 = "Revocar la invitación de %s",
    eses  = "Revocar la invitación de %s",
    pl    = "Cofnij zaproszenie dla %s",
    ru    = "Отозвать приглашение для %s",
    sv    = "Återkalla inbjudan till %s",
    nb    = "Trekk tilbake invitasjonen til %s",
    de    = "Einladung von %s widerrufen",
    nlnl  = "Uitnodiging van %s intrekken",
    frfr  = "Révoquer l'invitation de %s",
    fi    = "Peruuta pelaajalle %s lähetetty kutsu",
    it    = "Revoca l'invito di %s",
    zhcn  = "撤回对 %s 的邀请",
    ja    = "%sへの招待を取り消す",
    ko    = "%s에 대한 초대 취소",
  },

  GameInterfaceContextMenuPartyPassLeadership = {
    en    = "Pass leadership to %s",
    ptbr  = "Passar a liderança para %s",
    ptpt  = "Passar a liderança para %s",
    es419 = "Pasar el liderazgo a %s",
    eses  = "Pasar el liderazgo a %s",
    pl    = "Przekaż przywództwo %s",
    ru    = "Передать лидерство %s",
    sv    = "Överför ledarskapet till %s",
    nb    = "Overfør lederskapet til %s",
    de    = "Führung an %s übergeben",
    nlnl  = "Leiderschap aan %s overdragen",
    frfr  = "Transférer le commandement à %s",
    fi    = "Siirrä johtajuus pelaajalle %s",
    it    = "Passa la leadership a %s",
    zhcn  = "将队长职位交给 %s",
    ja    = "%sにリーダー権を渡す",
    ko    = "%s에게 리더십 넘기기",
  },

  GameInterfaceContextMenuAddRuleViolation = {
    en    = "Add rule violation",
    ptbr  = "Adicionar infração de regra",
    ptpt  = "Adicionar infração de regra",
    es419 = "Agregar infracción de regla",
    eses  = "Agregar infracción de regla",
    pl    = "Dodaj naruszenie zasad",
    ru    = "Добавить нарушение правила",
    sv    = "Lägg till regelbrott",
    nb    = "Legg til regelbrudd",
    de    = "Regelverstoß hinzufügen",
    nlnl  = "Regelovertreding toevoegen",
    frfr  = "Ajouter une infraction",
    fi    = "Lisää sääntörikkomus",
    it    = "Aggiungi violazione delle regole",
    zhcn  = "添加规则违规",
    ja    = "ルール違反を追加",
    ko    = "규칙 위반 추가",
  },

  GameInterfaceContextMenuReportName = {
    en    = "Report name",
    ptbr  = "Denunciar nome",
    ptpt  = "Denunciar nome",
    es419 = "Denunciar nombre",
    eses  = "Denunciar nombre",
    pl    = "Zgłoś nazwę",
    ru    = "Пожаловаться на имя",
    sv    = "Rapportera namn",
    nb    = "Rapporter navn",
    de    = "Namen melden",
    nlnl  = "Naam melden",
    frfr  = "Signaler le nom",
    fi    = "Ilmoita nimestä",
    it    = "Segnala nome",
    zhcn  = "举报名称",
    ja    = "名前を報告",
    ko    = "이름 신고",
  },

  GameInterfaceContextMenuReportViolation = {
    en    = "Report violation",
    ptbr  = "Denunciar infração",
    ptpt  = "Denunciar infração",
    es419 = "Denunciar infracción",
    eses  = "Denunciar infracción",
    pl    = "Zgłoś naruszenie",
    ru    = "Пожаловаться на нарушение",
    sv    = "Rapportera överträdelse",
    nb    = "Rapporter overtredelse",
    de    = "Verstoß melden",
    nlnl  = "Overtreding melden",
    frfr  = "Signaler une infraction",
    fi    = "Ilmoita rikkomuksesta",
    it    = "Segnala una violazione",
    zhcn  = "举报违规",
    ja    = "違反を報告",
    ko    = "위반 신고",
  },

  GameInterfaceContextMenuCopyName = {
    en    = "Copy name",
    ptbr  = "Copiar nome",
    ptpt  = "Copiar nome",
    es419 = "Copiar nombre",
    eses  = "Copiar nombre",
    pl    = "Skopiuj nazwę",
    ru    = "Копировать имя",
    sv    = "Kopiera namn",
    nb    = "Kopier navn",
    de    = "Namen kopieren",
    nlnl  = "Naam kopiëren",
    frfr  = "Copier le nom",
    fi    = "Kopioi nimi",
    it    = "Copia nome",
    zhcn  = "复制名称",
    ja    = "名前をコピー",
    ko    = "이름 복사",
  },

  GameInterfaceTopMenuButtonHide = {
    en    = "Hide top menu (%s)",
    ptbr  = "Ocultar menu superior (%s)",
    ptpt  = "Ocultar menu superior (%s)",
    es419 = "Ocultar menú superior (%s)",
    eses  = "Ocultar menú superior (%s)",
    pl    = "Ukryj górne menu (%s)",
    ru    = "Скрыть верхнее меню (%s)",
    sv    = "Dölj toppmenyn (%s)",
    nb    = "Skjul toppmenyen (%s)",
    de    = "Oberes Menü ausblenden (%s)",
    nlnl  = "Bovenmenu verbergen (%s)",
    frfr  = "Masquer le menu supérieur (%s)",
    fi    = "Piilota ylävalikko (%s)",
    it    = "Nascondi menu superiore (%s)",
    zhcn  = "隐藏顶部菜单（%s）",
    ja    = "トップメニューを隠す（%s）",
    ko    = "상단 메뉴 숨기기 (%s)",
  },

  GameInterfaceTopMenuButtonShow = {
    en    = "Show top menu (%s)",
    ptbr  = "Exibir menu superior (%s)",
    ptpt  = "Exibir menu superior (%s)",
    es419 = "Mostrar menú superior (%s)",
    eses  = "Mostrar menú superior (%s)",
    pl    = "Pokaż górne menu (%s)",
    ru    = "Показать верхнее меню (%s)",
    sv    = "Visa toppmenyn (%s)",
    nb    = "Vis toppmenyen (%s)",
    de    = "Oberes Menü anzeigen (%s)",
    nlnl  = "Bovenmenu tonen (%s)",
    frfr  = "Afficher le menu supérieur (%s)",
    fi    = "Näytä ylävalikko (%s)",
    it    = "Mostra menu superiore (%s)",
    zhcn  = "显示顶部菜单（%s）",
    ja    = "トップメニューを表示（%s）",
    ko    = "상단 메뉴 표시 (%s)",
  },

  GameInterfaceLeftPanelButtonHide = {
    en    = "Hide enabled left panels (%s)",
    ptbr  = "Ocultar painéis esquerdos habilitados (%s)",
    ptpt  = "Ocultar painéis esquerdos habilitados (%s)",
    es419 = "Ocultar paneles izquierdos habilitados (%s)",
    eses  = "Ocultar paneles izquierdos habilitados (%s)",
    pl    = "Ukryj włączone lewe panele (%s)",
    ru    = "Скрыть включённые левые панели (%s)",
    sv    = "Dölj aktiverade vänstra paneler (%s)",
    nb    = "Skjul aktiverte venstre paneler (%s)",
    de    = "Aktivierte linke Panels ausblenden (%s)",
    nlnl  = "Ingeschakelde linkerpanelen verbergen (%s)",
    frfr  = "Masquer les panneaux gauches activés (%s)",
    fi    = "Piilota käytössä olevat vasemmat paneelit (%s)",
    it    = "Nascondi i pannelli sinistri abilitati (%s)",
    zhcn  = "隐藏已启用的左侧面板（%s）",
    ja    = "有効な左パネルを隠す（%s）",
    ko    = "활성화된 왼쪽 패널 숨기기 (%s)",
  },

  GameInterfaceLeftPanelButtonShow = {
    en    = "Show enabled left panels (%s)",
    ptbr  = "Exibir painéis esquerdos habilitados (%s)",
    ptpt  = "Exibir painéis esquerdos habilitados (%s)",
    es419 = "Mostrar paneles izquierdos habilitados (%s)",
    eses  = "Mostrar paneles izquierdos habilitados (%s)",
    pl    = "Pokaż włączone lewe panele (%s)",
    ru    = "Показать включённые левые панели (%s)",
    sv    = "Visa aktiverade vänstra paneler (%s)",
    nb    = "Vis aktiverte venstre paneler (%s)",
    de    = "Aktivierte linke Panels anzeigen (%s)",
    nlnl  = "Ingeschakelde linkerpanelen tonen (%s)",
    frfr  = "Afficher les panneaux gauches activés (%s)",
    fi    = "Näytä käytössä olevat vasemmat paneelit (%s)",
    it    = "Mostra i pannelli sinistri abilitati (%s)",
    zhcn  = "显示已启用的左侧面板（%s）",
    ja    = "有効な左パネルを表示（%s）",
    ko    = "활성화된 왼쪽 패널 표시 (%s)",
  },

  GameInterfaceRightPanelButtonHide = {
    en    = "Hide enabled right panels (%s)",
    ptbr  = "Ocultar painéis direitos habilitados (%s)",
    ptpt  = "Ocultar painéis direitos habilitados (%s)",
    es419 = "Ocultar paneles derechos habilitados (%s)",
    eses  = "Ocultar paneles derechos habilitados (%s)",
    pl    = "Ukryj włączone prawe panele (%s)",
    ru    = "Скрыть включённые правые панели (%s)",
    sv    = "Dölj aktiverade högra paneler (%s)",
    nb    = "Skjul aktiverte høyre paneler (%s)",
    de    = "Aktivierte rechte Panels ausblenden (%s)",
    nlnl  = "Ingeschakelde rechterpanelen verbergen (%s)",
    frfr  = "Masquer les panneaux droits activés (%s)",
    fi    = "Piilota käytössä olevat oikeat paneelit (%s)",
    it    = "Nascondi i pannelli destri abilitati (%s)",
    zhcn  = "隐藏已启用的右侧面板（%s）",
    ja    = "有効な右パネルを隠す（%s）",
    ko    = "활성화된 오른쪽 패널 숨기기 (%s)",
  },

  GameInterfaceRightPanelButtonShow = {
    en    = "Show enabled right panels (%s)",
    ptbr  = "Exibir painéis direitos habilitados (%s)",
    ptpt  = "Exibir painéis direitos habilitados (%s)",
    es419 = "Mostrar paneles derechos habilitados (%s)",
    eses  = "Mostrar paneles derechos habilitados (%s)",
    pl    = "Pokaż włączone prawe panele (%s)",
    ru    = "Показать включённые правые панели (%s)",
    sv    = "Visa aktiverade högra paneler (%s)",
    nb    = "Vis aktiverte høyre paneler (%s)",
    de    = "Aktivierte rechte Panels anzeigen (%s)",
    nlnl  = "Ingeschakelde rechterpanelen tonen (%s)",
    frfr  = "Afficher les panneaux droits activés (%s)",
    fi    = "Näytä käytössä olevat oikeat paneelit (%s)",
    it    = "Mostra i pannelli destri abilitati (%s)",
    zhcn  = "显示已启用的右侧面板（%s）",
    ja    = "有効な右パネルを表示（%s）",
    ko    = "활성화된 오른쪽 패널 표시 (%s)",
  },

  GameInterfacePanelAddButton = {
    en    = "Add panel",
    ptbr  = "Adicionar painel",
    ptpt  = "Adicionar painel",
    es419 = "Agregar panel",
    eses  = "Agregar panel",
    pl    = "Dodaj panel",
    ru    = "Добавить панель",
    sv    = "Lägg till panel",
    nb    = "Legg til panel",
    de    = "Panel hinzufügen",
    nlnl  = "Paneel toevoegen",
    frfr  = "Ajouter un panneau",
    fi    = "Lisää paneeli",
    it    = "Aggiungi pannello",
    zhcn  = "添加面板",
    ja    = "パネルを追加",
    ko    = "패널 추가",
  },

  GameInterfacePanelRemoveButton = {
    en    = "Remove panel",
    ptbr  = "Remover painel",
    ptpt  = "Remover painel",
    es419 = "Eliminar panel",
    eses  = "Eliminar panel",
    pl    = "Usuń panel",
    ru    = "Удалить панель",
    sv    = "Ta bort panel",
    nb    = "Fjern panel",
    de    = "Panel entfernen",
    nlnl  = "Paneel verwijderen",
    frfr  = "Supprimer le panneau",
    fi    = "Poista paneeli",
    it    = "Rimuovi pannello",
    zhcn  = "移除面板",
    ja    = "パネルを削除",
    ko    = "패널 삭제",
  },

  GameInterfaceChatButtonHide = {
    en    = "Hide chat (%s)",
    ptbr  = "Ocultar chat (%s)",
    ptpt  = "Ocultar chat (%s)",
    es419 = "Ocultar chat (%s)",
    eses  = "Ocultar chat (%s)",
    pl    = "Ukryj czat (%s)",
    ru    = "Скрыть чат (%s)",
    sv    = "Dölj chatten (%s)",
    nb    = "Skjul chatten (%s)",
    de    = "Chat ausblenden (%s)",
    nlnl  = "Chat verbergen (%s)",
    frfr  = "Masquer le chat (%s)",
    fi    = "Piilota chat (%s)",
    it    = "Nascondi chat (%s)",
    zhcn  = "隐藏聊天（%s）",
    ja    = "チャットを隠す（%s）",
    ko    = "채팅 숨기기 (%s)",
  },

  GameInterfaceChatButtonShow = {
    en    = "Show chat (%s)",
    ptbr  = "Exibir chat (%s)",
    ptpt  = "Exibir chat (%s)",
    es419 = "Mostrar chat (%s)",
    eses  = "Mostrar chat (%s)",
    pl    = "Pokaż czat (%s)",
    ru    = "Показать чат (%s)",
    sv    = "Visa chatten (%s)",
    nb    = "Vis chatten (%s)",
    de    = "Chat anzeigen (%s)",
    nlnl  = "Chat tonen (%s)",
    frfr  = "Afficher le chat (%s)",
    fi    = "Näytä chat (%s)",
    it    = "Mostra chat (%s)",
    zhcn  = "显示聊天（%s）",
    ja    = "チャットを表示（%s）",
    ko    = "채팅 표시 (%s)",
  },

  GameInterfaceCountWindowTitle = {
    en    = "Move stackable item",
    ptbr  = "Mover item empilhável",
    ptpt  = "Mover item empilhável",
    es419 = "Mover objeto apilable",
    eses  = "Mover objeto apilable",
    pl    = "Przenieś przedmiot, który można układać",
    ru    = "Переместить складываемый предмет",
    sv    = "Flytta stapelbart föremål",
    nb    = "Flytt stablegjenstand",
    de    = "Stapelbares Objekt verschieben",
    nlnl  = "Stapelbaar item verplaatsen",
    frfr  = "Déplacer l'objet empilable",
    fi    = "Siirrä pinottava esine",
    it    = "Sposta oggetto impilabile",
    zhcn  = "移动可堆叠物品",
    ja    = "スタック可能なアイテムを移動",
    ko    = "겹칠 수 있는 아이템 이동",
  },
})
