-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  CorelibInfoOk = {
    en    = "Ok",
    ptbr  = "Confirmar",
    ptpt  = "Ok",
    es419 = "Confirmar",
    eses  = "Confirmar",
    pl    = "Potwierdź",
    ru    = "Подтвердить",
    sv    = "Bekräfta",
    nb    = "Bekreft",
    de    = "Bestätigen",
    nlnl  = "Bevestigen",
    frfr  = "Confirmer",
    fi    = "Vahvista",
    it    = "Conferma",
    zhcn  = "确认",
    ja    = "確認",
    ko    = "확인",
  },

  CorelibInfoCancel = {
    en    = "Cancel",
    ptbr  = "Cancelar",
    ptpt  = "Cancelar",
    es419 = "Cancelar",
    eses  = "Cancelar",
    pl    = "Anuluj",
    ru    = "Отмена",
    sv    = "Avbryt",
    nb    = "Avbryt",
    de    = "Abbrechen",
    nlnl  = "Annuleren",
    frfr  = "Annuler",
    fi    = "Peruuta",
    it    = "Annulla",
    zhcn  = "取消",
    ja    = "キャンセル",
    ko    = "취소",
  },

  CorelibInfoOpen = {
    en    = "Open",
    ptbr  = "Abrir",
    ptpt  = "Abrir",
    es419 = "Abrir",
    eses  = "Abrir",
    pl    = "Otwórz",
    ru    = "Открыть",
    sv    = "Öppna",
    nb    = "Åpne",
    de    = "Öffnen",
    nlnl  = "Openen",
    frfr  = "Ouvrir",
    fi    = "Avaa",
    it    = "Apri",
    zhcn  = "打开",
    ja    = "開く",
    ko    = "열기",
  },

  CorelibInfoClose = {
    en    = "Close",
    ptbr  = "Fechar",
    ptpt  = "Fechar",
    es419 = "Cerrar",
    eses  = "Cerrar",
    pl    = "Zamknij",
    ru    = "Закрыть",
    sv    = "Stäng",
    nb    = "Lukk",
    de    = "Schließen",
    nlnl  = "Sluiten",
    frfr  = "Fermer",
    fi    = "Sulje",
    it    = "Chiudi",
    zhcn  = "关闭",
    ja    = "閉じる",
    ko    = "닫기",
  },

  CorelibInfoAdd = {
    en    = "Add",
    ptbr  = "Adicionar",
    ptpt  = "Adicionar",
    es419 = "Añadir",
    eses  = "Añadir",
    pl    = "Dodaj",
    ru    = "Добавить",
    sv    = "Lägg till",
    nb    = "Legg til",
    de    = "Hinzufügen",
    nlnl  = "Toevoegen",
    frfr  = "Ajouter",
    fi    = "Lisää",
    it    = "Aggiungi",
    zhcn  = "添加",
    ja    = "追加",
    ko    = "추가",
  },

  CorelibInfoRemove = {
    en    = "Remove",
    ptbr  = "Remover",
    ptpt  = "Remover",
    es419 = "Eliminar",
    eses  = "Eliminar",
    pl    = "Usuń",
    ru    = "Удалить",
    sv    = "Ta bort",
    nb    = "Ta bort",
    de    = "Entfernen",
    nlnl  = "Verwijderen",
    frfr  = "Supprimer",
    fi    = "Poista",
    it    = "Rimuovi",
    zhcn  = "移除",
    ja    = "削除",
    ko    = "삭제",
  },

  CorelibInfoApply = {
    en    = "Apply",
    ptbr  = "Aplicar",
    ptpt  = "Aplicar",
    es419 = "Aplicar",
    eses  = "Aplicar",
    pl    = "Zastosuj",
    ru    = "Применить",
    sv    = "Tillämpa",
    nb    = "Bruk",
    de    = "Anwenden",
    nlnl  = "Toepassen",
    frfr  = "Appliquer",
    fi    = "Käytä",
    it    = "Applica",
    zhcn  = "应用",
    ja    = "適用",
    ko    = "적용",
  },

  CorelibInfoReset = {
    en    = "Reset",
    ptbr  = "Redefinir",
    ptpt  = "Redefinir",
    es419 = "Restablecer",
    eses  = "Restablecer",
    pl    = "Zresetuj",
    ru    = "Сбросить",
    sv    = "Återställ",
    nb    = "Tilbakestill",
    de    = "Zurücksetzen",
    nlnl  = "Resetten",
    frfr  = "Réinitialiser",
    fi    = "Palauta",
    it    = "Reimposta",
    zhcn  = "重置",
    ja    = "リセット",
    ko    = "초기화",
  },

  CorelibInfoYes = {
    en    = "Yes",
    ptbr  = "Sim",
    ptpt  = "Sim",
    es419 = "Sí",
    eses  = "Sí",
    pl    = "Tak",
    ru    = "Да",
    sv    = "Ja",
    nb    = "Ja",
    de    = "Ja",
    nlnl  = "Ja",
    frfr  = "Oui",
    fi    = "Kyllä",
    it    = "Sì",
    zhcn  = "是",
    ja    = "はい",
    ko    = "예",
  },

  CorelibInfoNo = {
    en    = "No",
    ptbr  = "Não",
    ptpt  = "Não",
    es419 = "No",
    eses  = "No",
    pl    = "Nie",
    ru    = "Нет",
    sv    = "Nej",
    nb    = "Nei",
    de    = "Nein",
    nlnl  = "Nee",
    frfr  = "Non",
    fi    = "Ei",
    it    = "No",
    zhcn  = "否",
    ja    = "いいえ",
    ko    = "아니요",
  },

  CorelibInfoError = {
    en    = "Error",
    ptbr  = "Erro",
    ptpt  = "Erro",
    es419 = "Error",
    eses  = "Error",
    pl    = "Błąd",
    ru    = "Ошибка",
    sv    = "Fel",
    nb    = "Feil",
    de    = "Fehler",
    nlnl  = "Fout",
    frfr  = "Erreur",
    fi    = "Virhe",
    it    = "Errore",
    zhcn  = "错误",
    ja    = "エラー",
    ko    = "오류",
  },

  CorelibInfoNone = {
    en    = "None",
    ptbr  = "Nenhum",
    ptpt  = "Nenhum",
    es419 = "Ninguno",
    eses  = "Ninguno",
    pl    = "Brak",
    ru    = "Нет",
    sv    = "Ingen",
    nb    = "Ingen",
    de    = "Keiner",
    nlnl  = "Geen",
    frfr  = "Aucun",
    fi    = "Ei mitään",
    it    = "Nessuno",
    zhcn  = "无",
    ja    = "なし",
    ko    = "없음",
  },

  CorelibInfoDescription = {
    en    = "Description",
    ptbr  = "Descrição",
    ptpt  = "Descrição",
    es419 = "Descripción",
    eses  = "Descripción",
    pl    = "Opis",
    ru    = "Описание",
    sv    = "Beskrivning",
    nb    = "Beskrivelse",
    de    = "Beschreibung",
    nlnl  = "Beschrijving",
    frfr  = "Description",
    fi    = "Kuvaus",
    it    = "Descrizione",
    zhcn  = "描述",
    ja    = "説明",
    ko    = "설명",
  },

  CorelibInfoAll = {
    en    = "All",
    ptbr  = "Todos",
    ptpt  = "Todos",
    es419 = "Todos",
    eses  = "Todos",
    pl    = "Wszyscy",
    ru    = "Все",
    sv    = "Alla",
    nb    = "Alle",
    de    = "Alle",
    nlnl  = "Alles",
    frfr  = "Tous",
    fi    = "Kaikki",
    it    = "Tutti",
    zhcn  = "全部",
    ja    = "すべて",
    ko    = "전체",
  },

  CorelibInfoName = {
    en    = "Name",
    ptbr  = "Nome",
    ptpt  = "Nome",
    es419 = "Nombre",
    eses  = "Nombre",
    pl    = "Nazwa",
    ru    = "Имя",
    sv    = "Namn",
    nb    = "Navn",
    de    = "Name",
    nlnl  = "Naam",
    frfr  = "Nom",
    fi    = "Nimi",
    it    = "Nome",
    zhcn  = "名称",
    ja    = "名前",
    ko    = "이름",
  },

  CorelibInfoClass = {
    en    = "Class",
    ptbr  = "Classe",
    ptpt  = "Classe",
    es419 = "Clase",
    eses  = "Clase",
    pl    = "Klasa",
    ru    = "Класс",
    sv    = "Klass",
    nb    = "Klasse",
    de    = "Klasse",
    nlnl  = "Klasse",
    frfr  = "Classe",
    fi    = "Luokka",
    it    = "Classe",
    zhcn  = "类",
    ja    = "クラス",
    ko    = "분류",
  },

  CorelibInfoLevel = {
    en    = "Level",
    ptbr  = "Nível",
    ptpt  = "Nível",
    es419 = "Nivel",
    eses  = "Nivel",
    pl    = "Poziom",
    ru    = "Уровень",
    sv    = "Nivå",
    nb    = "Nivå",
    de    = "Stufe",
    nlnl  = "Niveau",
    frfr  = "Niveau",
    fi    = "Taso",
    it    = "Livello",
    zhcn  = "等级",
    ja    = "レベル",
    ko    = "레벨",
  },

  CorelibInfoDistance = {
    en    = "Distance",
    ptbr  = "Distância",
    ptpt  = "Distância",
    es419 = "Distancia",
    eses  = "Distancia",
    pl    = "Dystans",
    ru    = "Расстояние",
    sv    = "Avstånd",
    nb    = "Avstand",
    de    = "Entfernung",
    nlnl  = "Afstand",
    frfr  = "Distance",
    fi    = "Etäisyys",
    it    = "Distanza",
    zhcn  = "距离",
    ja    = "距離",
    ko    = "거리",
  },

  CorelibInfoStatus = {
    en    = "Status",
    ptbr  = "Estado",
    ptpt  = "Status",
    es419 = "Estado",
    eses  = "Estado",
    pl    = "Status",
    ru    = "Статус",
    sv    = "Status",
    nb    = "Status",
    de    = "Status",
    nlnl  = "Status",
    frfr  = "État",
    fi    = "Tila",
    it    = "Stato",
    zhcn  = "状态",
    ja    = "状態",
    ko    = "상태",
  },

  CorelibInfoType = {
    en    = "Type",
    ptbr  = "Tipo",
    ptpt  = "Tipo",
    es419 = "Tipo",
    eses  = "Tipo",
    pl    = "Typ",
    ru    = "Тип",
    sv    = "Typ",
    nb    = "Type",
    de    = "Typ",
    nlnl  = "Type",
    frfr  = "Type",
    fi    = "Tyyppi",
    it    = "Tipo",
    zhcn  = "类型",
    ja    = "種類",
    ko    = "유형",
  },

  CorelibInfoLoading = {
    en    = "Loading",
    ptbr  = "Carregando",
    ptpt  = "Carregando",
    es419 = "Cargando",
    eses  = "Cargando",
    pl    = "Ładowanie",
    ru    = "Загрузка",
    sv    = "Laddar",
    nb    = "Laster",
    de    = "Laden",
    nlnl  = "Laden",
    frfr  = "Chargement",
    fi    = "Ladataan",
    it    = "Caricamento",
    zhcn  = "加载",
    ja    = "読み込み中",
    ko    = "로드 중",
  },

  CorelibInfoAscending = {
    en    = "Ascending",
    ptbr  = "Crescente",
    ptpt  = "Crescente",
    es419 = "Ascendente",
    eses  = "Ascendente",
    pl    = "Rosnąco",
    ru    = "По возрастанию",
    sv    = "Stigande",
    nb    = "Stigende",
    de    = "Aufsteigend",
    nlnl  = "Oplopend",
    frfr  = "Croissant",
    fi    = "Nouseva",
    it    = "Crescente",
    zhcn  = "升序",
    ja    = "昇順",
    ko    = "오름차순",
  },

  CorelibInfoDescending = {
    en    = "Descending",
    ptbr  = "Decrescente",
    ptpt  = "Decrescente",
    es419 = "Descendente",
    eses  = "Descendente",
    pl    = "Malejąco",
    ru    = "По убыванию",
    sv    = "Fallande",
    nb    = "Synkende",
    de    = "Absteigend",
    nlnl  = "Aflopend",
    frfr  = "Décroissant",
    fi    = "Laskeva",
    it    = "Decrescente",
    zhcn  = "降序",
    ja    = "降順",
    ko    = "내림차순",
  },

  CorelibInfoSortingBy = {
    en    = "Sorted by",
    ptbr  = "Ordenado por",
    ptpt  = "Ordenado por",
    es419 = "Ordenado por",
    eses  = "Ordenado por",
    pl    = "Sortowanie według",
    ru    = "Отсортировано по",
    sv    = "Sorterat efter",
    nb    = "Sortert etter",
    de    = "Sortiert nach",
    nlnl  = "Gesorteerd op",
    frfr  = "Trié par",
    fi    = "Lajitteluperuste",
    it    = "Ordinato per",
    zhcn  = "排序依据",
    ja    = "並べ替え：",
    ko    = "정렬 기준",
  },

  CorelibInfoSortBy = {
    en    = "Sort by",
    ptbr  = "Ordenar por",
    ptpt  = "Ordenar por",
    es419 = "Ordenar por",
    eses  = "Ordenar por",
    pl    = "Sortuj według",
    ru    = "Сортировать по",
    sv    = "Sortera efter",
    nb    = "Sorter etter",
    de    = "Sortieren nach",
    nlnl  = "Sorteren op",
    frfr  = "Trier par",
    fi    = "Lajittele",
    it    = "Ordina per",
    zhcn  = "排序方式",
    ja    = "並べ替え",
    ko    = "정렬 기준",
  },

  CorelibInfoShowOptions = {
    en    = "Show options",
    ptbr  = "Exibir opções",
    ptpt  = "Mostrar opções",
    es419 = "Mostrar opciones",
    eses  = "Mostrar opciones",
    pl    = "Pokaż opcje",
    ru    = "Показать параметры",
    sv    = "Visa alternativ",
    nb    = "Vis alternativer",
    de    = "Optionen anzeigen",
    nlnl  = "Opties tonen",
    frfr  = "Afficher les options",
    fi    = "Näytä asetukset",
    it    = "Mostra opzioni",
    zhcn  = "显示选项",
    ja    = "オプションを表示",
    ko    = "옵션 표시",
  },

  CorelibInfoHideOptions = {
    en    = "Hide options",
    ptbr  = "Ocultar opções",
    ptpt  = "Ocultar opções",
    es419 = "Ocultar opciones",
    eses  = "Ocultar opciones",
    pl    = "Ukryj opcje",
    ru    = "Скрыть параметры",
    sv    = "Dölj alternativ",
    nb    = "Skjul alternativer",
    de    = "Optionen verbergen",
    nlnl  = "Opties verbergen",
    frfr  = "Masquer les options",
    fi    = "Piilota asetukset",
    it    = "Nascondi opzioni",
    zhcn  = "隐藏选项",
    ja    = "オプションを隠す",
    ko    = "옵션 숨기기",
  },

  CorelibInfoDefault = {
    en    = "Default",
    ptbr  = "Padrão",
    ptpt  = "Padrão",
    es419 = "Predeterminado",
    eses  = "Predeterminado",
    pl    = "Domyślny",
    ru    = "По умолчанию",
    sv    = "Standard",
    nb    = "Standard",
    de    = "Standard",
    nlnl  = "Standaard",
    frfr  = "Par défaut",
    fi    = "Oletus",
    it    = "Predefinito",
    zhcn  = "默认",
    ja    = "デフォルト",
    ko    = "기본",
  },

  CorelibInfoLogout = {
    en    = "Logout",
    ptbr  = "Desconectar-se",
    ptpt  = "Sair",
    es419 = "Cerrar sesión",
    eses  = "Cerrar sesión",
    pl    = "Wyloguj",
    ru    = "Выйти",
    sv    = "Logga ut",
    nb    = "Logg ut",
    de    = "Abmelden",
    nlnl  = "Uitloggen",
    frfr  = "Se déconnecter",
    fi    = "Kirjaudu ulos",
    it    = "Disconnetti",
    zhcn  = "登出",
    ja    = "ログアウト",
    ko    = "로그아웃",
  },

  CorelibInfoLogoutTooltip = {
    en    = "Properly logs out of the game",
    ptbr  = "Saia do jogo corretamente",
    ptpt  = "Saia do jogo corretamente",
    es419 = "Sal del juego correctamente",
    eses  = "Sal del juego correctamente",
    pl    = "Wyjdź z gry prawidłowo",
    ru    = "Правильно выйдите из игры",
    sv    = "Logga ut ur spelet korrekt",
    nb    = "Logg ut av spillet på riktig måte",
    de    = "Verlasse das Spiel ordnungsgemäß",
    nlnl  = "Verlaat het spel op de juiste manier",
    frfr  = "Quittez correctement le jeu",
    fi    = "Poistu pelistä oikein",
    it    = "Esci correttamente dal gioco",
    zhcn  = "正确退出游戏",
    ja    = "ゲームから正しくログアウトしてください",
    ko    = "게임에서 정상적으로 로그아웃하세요",
  },

  CorelibInfoExit = {
    en    = "Exit game",
    ptbr  = "Sair do jogo",
    ptpt  = "Sair do jogo",
    es419 = "Salir del juego",
    eses  = "Salir del juego",
    pl    = "Wyjdź z gry",
    ru    = "Выйти из игры",
    sv    = "Avsluta spelet",
    nb    = "Avslutt spillet",
    de    = "Spiel beenden",
    nlnl  = "Spel afsluiten",
    frfr  = "Quitter le jeu",
    fi    = "Poistu pelistä",
    it    = "Esci dal gioco",
    zhcn  = "退出游戏",
    ja    = "ゲームを終了",
    ko    = "게임 종료",
  },

  CorelibInfoMs = {
    en    = "ms",
    ptbr  = "ms",
    ptpt  = "ms",
    es419 = "ms",
    eses  = "ms",
    pl    = "ms",
    ru    = "мс",
    sv    = "ms",
    nb    = "ms",
    de    = "ms",
    nlnl  = "ms",
    frfr  = "ms",
    fi    = "ms",
    it    = "ms",
    zhcn  = "毫秒",
    ja    = "ミリ秒",
    ko    = "ms",
  },

  CorelibInfoOz = {
    en    = "oz",
    ptbr  = "oz",
    ptpt  = "oz",
    es419 = "oz",
    eses  = "oz",
    pl    = "oz",
    ru    = "унц.",
    sv    = "oz",
    nb    = "oz",
    de    = "oz",
    nlnl  = "oz",
    frfr  = "oz",
    fi    = "oz",
    it    = "oz",
    zhcn  = "盎司",
    ja    = "オンス",
    ko    = "oz",
  },

  CorelibViewModeNormal = {
    en    = "Normal",
    ptbr  = "Normal",
    ptpt  = "Normal",
    es419 = "Normal",
    eses  = "Normal",
    pl    = "Normalny",
    ru    = "Обычный",
    sv    = "Normal",
    nb    = "Normal",
    de    = "Normal",
    nlnl  = "Normaal",
    frfr  = "Normal",
    fi    = "Normaali",
    it    = "Normale",
    zhcn  = "普通",
    ja    = "通常",
    ko    = "일반",
  },

  CorelibViewModeCrop = {
    en    = "Crop",
    ptbr  = "Cortar",
    ptpt  = "Cortar",
    es419 = "Recortar",
    eses  = "Recortar",
    pl    = "Przycięcie",
    ru    = "Обрезать",
    sv    = "Beskär",
    nb    = "Beskjær",
    de    = "Zuschneiden",
    nlnl  = "Bijsnijden",
    frfr  = "Rogner",
    fi    = "Rajaa",
    it    = "Ritaglia",
    zhcn  = "裁剪",
    ja    = "切り抜き",
    ko    = "자르기",
  },

  CorelibViewModeCropFull = {
    en    = "Crop full",
    ptbr  = "Cortar totalmente",
    ptpt  = "Cortar totalmente",
    es419 = "Recortar completamente",
    eses  = "Recortar completamente",
    pl    = "Przyciąć w całości",
    ru    = "Обрезать полностью",
    sv    = "Beskär helt",
    nb    = "Beskjær helt",
    de    = "Vollständig zuschneiden",
    nlnl  = "Volledig bijsnijden",
    frfr  = "Rogner entièrement",
    fi    = "Rajaa kokonaan",
    it    = "Ritaglia completamente",
    zhcn  = "完全裁剪",
    ja    = "全体を切り抜き",
    ko    = "전체 자르기",
  },

  CorelibViewModeFull = {
    en    = "Full",
    ptbr  = "Cheio",
    ptpt  = "Cheio",
    es419 = "Completo",
    eses  = "Completo",
    pl    = "Pełny",
    ru    = "Полный",
    sv    = "Full",
    nb    = "Full",
    de    = "Vollständig",
    nlnl  = "Volledig",
    frfr  = "Complet",
    fi    = "Täysi",
    it    = "Completo",
    zhcn  = "完整",
    ja    = "全体",
    ko    = "전체",
  },

  CorelibPanelStickerOptions = {
    en    = "Sticker %d",
    ptbr  = "Adesivo %d",
    ptpt  = "Adesivo %d",
    es419 = "Pegatina %d",
    eses  = "Pegatina %d",
    pl    = "Naklejka %d",
    ru    = "Наклейка %d",
    sv    = "Klistermärke %d",
    nb    = "Klistremerke %d",
    de    = "Aufkleber %d",
    nlnl  = "Sticker %d",
    frfr  = "Autocollant %d",
    fi    = "Tarra %d",
    it    = "Adesivo %d",
    zhcn  = "贴纸 %d",
    ja    = "ステッカー %d",
    ko    = "스티커 %d",
  },

  CorelibNetInfoConnectionServerOffOrRestarting = {
    en    = "Connection refused. The server might be offline or restarting.\nTry again later.",
    ptbr  = "Sua conexão foi recusada. O servidor pode estar fora do ar ou reiniciando.\nTente novamente mais tarde.",
    ptpt  = "A sua ligação foi recusada. O servidor pode estar fora do ar ou a reiniciar.\nTente novamente mais tarde.",
    es419 = "Tu conexión fue rechazada. El servidor puede estar fuera de servicio o reiniciándose.\nInténtalo de nuevo más tarde.",
    eses  = "Tu conexión fue rechazada. El servidor puede estar fuera de servicio o reiniciándose.\nInténtalo de nuevo más tarde.",
    pl    = "Twoje połączenie zostało odrzucone. Serwer może być niedostępny lub może być uruchamiany ponownie.\nSpróbuj ponownie później.",
    ru    = "Ваше соединение было отклонено. Сервер может быть недоступен или перезапускается.\nПопробуйте снова позже.",
    sv    = "Din anslutning nekades. Servern kan vara offline eller startas om.\nFörsök igen senare.",
    nb    = "Tilkoblingen din ble avvist. Serveren kan være nede eller starte på nytt.\nPrøv igjen senere.",
    de    = "Ihre Verbindung wurde abgelehnt. Der Server ist möglicherweise offline oder wird neu gestartet.\nVersuchen Sie es später erneut.",
    nlnl  = "Je verbinding is geweigerd. De server is mogelijk offline of wordt opnieuw gestart.\nProbeer het later opnieuw.",
    frfr  = "Votre connexion a été refusée. Le serveur est peut-être hors ligne ou redémarre.\nRéessayez plus tard.",
    fi    = "Yhteytesi evättiin. Palvelin saattaa olla offline-tilassa tai käynnistymässä uudelleen.\nYritä myöhemmin uudelleen.",
    it    = "La tua connessione è stata rifiutata. Il server potrebbe essere offline o in fase di riavvio.\nRiprova più tardi.",
    zhcn  = "您的连接被拒绝。服务器可能已离线或正在重启。\n请稍后再试。",
    ja    = "接続が拒否されました。サーバーがオフラインか再起動中の可能性があります。\n後でもう一度お試しください。",
    ko    = "연결이 거부되었습니다. 서버가 오프라인 상태이거나 재시작 중일 수 있습니다.\n나중에 다시 시도해 주세요.",
  },

  CorelibNetInfoConnectionFailingOrServerOff = {
    en    = "Connection timed out. Either your network is failing or the server is offline.",
    ptbr  = "Sua conexão expirou. Sua rede está falhando ou o servidor está fora do ar.",
    ptpt  = "A sua ligação expirou. A sua rede está com problemas ou o servidor está fora do ar.",
    es419 = "Tu conexión agotó el tiempo de espera. Tu red está fallando o el servidor está fuera de servicio.",
    eses  = "Tu conexión agotó el tiempo de espera. Tu red está fallando o el servidor está fuera de servicio.",
    pl    = "Przekroczono limit czasu połączenia. Twoja sieć nie działa prawidłowo lub serwer jest niedostępny.",
    ru    = "Время ожидания соединения истекло. Ваша сеть работает с перебоями или сервер недоступен.",
    sv    = "Anslutningen tog för lång tid. Antingen fungerar ditt nätverk inte som det ska eller så är servern offline.",
    nb    = "Tilkoblingen fikk tidsavbrudd. Enten har nettverket ditt problemer, eller så er serveren nede.",
    de    = "Zeitüberschreitung der Verbindung. Entweder funktioniert Ihr Netzwerk nicht ordnungsgemäß oder der Server ist offline.",
    nlnl  = "Time-out bij de verbinding. Je netwerk werkt mogelijk niet goed of de server is offline.",
    frfr  = "Délai de connexion dépassé. Votre réseau rencontre peut-être des problèmes ou le serveur est hors ligne.",
    fi    = "Yhteys aikakatkaistiin. Verkkoyhteydessäsi voi olla ongelmia tai palvelin on offline-tilassa.",
    it    = "La connessione ha raggiunto il timeout. La tua rete potrebbe avere problemi oppure il server è offline.",
    zhcn  = "连接超时。您的网络可能出现故障，或者服务器已离线。",
    ja    = "接続がタイムアウトしました。ネットワークに問題があるか、サーバーがオフラインの可能性があります。",
    ko    = "연결 시간이 초과되었습니다. 네트워크에 문제가 있거나 서버가 오프라인 상태일 수 있습니다.",
  },

  CorelibNetInfoConnectionServerAddressNotFound = {
    en    = "Connection failed. The server address does not exist.",
    ptbr  = "Sua conexão falhou. O endereço do servidor não existe.",
    ptpt  = "A sua ligação falhou. O endereço do servidor não existe.",
    es419 = "Tu conexión falló. La dirección del servidor no existe.",
    eses  = "Tu conexión falló. La dirección del servidor no existe.",
    pl    = "Połączenie nie powiodło się. Adres serwera nie istnieje.",
    ru    = "Соединение не удалось. Адрес сервера не существует.",
    sv    = "Anslutningen misslyckades. Serveradressen finns inte.",
    nb    = "Tilkoblingen mislyktes. Serveradressen finnes ikke.",
    de    = "Die Verbindung ist fehlgeschlagen. Die Serveradresse existiert nicht.",
    nlnl  = "De verbinding is mislukt. Het serveradres bestaat niet.",
    frfr  = "La connexion a échoué. L'adresse du serveur n'existe pas.",
    fi    = "Yhteys epäonnistui. Palvelimen osoitetta ei ole olemassa.",
    it    = "La connessione non è riuscita. L'indirizzo del server non esiste.",
    zhcn  = "连接失败。服务器地址不存在。",
    ja    = "接続に失敗しました。サーバーアドレスが存在しません。",
    ko    = "연결에 실패했습니다. 서버 주소가 존재하지 않습니다.",
  },

  CorelibNetInfoConnectionFailed = {
    en    = "Connection failed.",
    ptbr  = "Sua conexão falhou.",
    ptpt  = "A sua ligação falhou.",
    es419 = "Tu conexión falló.",
    eses  = "Tu conexión falló.",
    pl    = "Twoje połączenie nie powiodło się.",
    ru    = "Ваше соединение не удалось.",
    sv    = "Din anslutning misslyckades.",
    nb    = "Tilkoblingen din mislyktes.",
    de    = "Ihre Verbindung ist fehlgeschlagen.",
    nlnl  = "Je verbinding is mislukt.",
    frfr  = "Votre connexion a échoué.",
    fi    = "Yhteytesi epäonnistui.",
    it    = "La tua connessione non è riuscita.",
    zhcn  = "您的连接失败了。",
    ja    = "接続に失敗しました。",
    ko    = "연결에 실패했습니다.",
  },

  CorelibTooltipInfoUnknown = {
    en    = "Unknown",
    ptbr  = "Desconhecido",
    ptpt  = "Desconhecido",
    es419 = "Desconocido",
    eses  = "Desconocido",
    pl    = "Nieznany",
    ru    = "Неизвестно",
    sv    = "Okänd",
    nb    = "Ukjent",
    de    = "Unbekannt",
    nlnl  = "Onbekend",
    frfr  = "Inconnu",
    fi    = "Tuntematon",
    it    = "Sconosciuto",
    zhcn  = "未知",
    ja    = "不明",
    ko    = "알 수 없음",
  },

  CorelibTooltipInfoSeconds = {
    en    = "%s seconds",
    ptbr  = "%s segundos",
    ptpt  = "%s segundos",
    es419 = "%s segundos",
    eses  = "%s segundos",
    pl    = "%s sekund",
    ru    = "%s секунд",
    sv    = "%s sekunder",
    nb    = "%s sekunder",
    de    = "%s Sekunden",
    nlnl  = "%s seconden",
    frfr  = "%s secondes",
    fi    = "%s sekuntia",
    it    = "%s secondi",
    zhcn  = "%s 秒",
    ja    = "%s秒",
    ko    = "%s 초",
  },

  CorelibTooltipInfoAggressive = {
    en    = "Aggressive",
    ptbr  = "Agressivo",
    ptpt  = "Agressivo",
    es419 = "Agresivo",
    eses  = "Agresivo",
    pl    = "Agresywny",
    ru    = "Агрессивный",
    sv    = "Aggressiv",
    nb    = "Aggressiv",
    de    = "Aggressiv",
    nlnl  = "Agressief",
    frfr  = "Agressif",
    fi    = "Hyökkäävä",
    it    = "Aggressivo",
    zhcn  = "攻击型",
    ja    = "攻撃的",
    ko    = "공격적",
  },

  CorelibTooltipInfoNonAggressive = {
    en    = "Non-aggressive",
    ptbr  = "Não agressivo",
    ptpt  = "Não agressivo",
    es419 = "No agresivo",
    eses  = "No agresivo",
    pl    = "Nieagresywny",
    ru    = "Неагрессивный",
    sv    = "Icke-aggressiv",
    nb    = "Ikke-aggressiv",
    de    = "Nicht aggressiv",
    nlnl  = "Niet-agressief",
    frfr  = "Non agressif",
    fi    = "Ei-aggressiivinen",
    it    = "Non aggressivo",
    zhcn  = "非攻击型",
    ja    = "非攻撃的",
    ko    = "비공격적",
  },

  CorelibTooltipInfoVocations = {
    en    = "Vocations",
    ptbr  = "Vocações",
    ptpt  = "Vocações",
    es419 = "Vocaciones",
    eses  = "Vocaciones",
    pl    = "Zawody",
    ru    = "Профессии",
    sv    = "Yrken",
    nb    = "Yrker",
    de    = "Berufe",
    nlnl  = "Beroepen",
    frfr  = "Vocations",
    fi    = "Ammatit",
    it    = "Vocazioni",
    zhcn  = "职业",
    ja    = "職業",
    ko    = "직업",
  },

  CorelibTooltipInfoManaCost = {
    en    = "Mana cost",
    ptbr  = "Custo de mana",
    ptpt  = "Custo de mana",
    es419 = "Costo de maná",
    eses  = "Coste de maná",
    pl    = "Koszt many",
    ru    = "Стоимость маны",
    sv    = "Manakostnad",
    nb    = "Manakostnad",
    de    = "Manakosten",
    nlnl  = "Manakosten",
    frfr  = "Coût en mana",
    fi    = "Manan hinta",
    it    = "Costo di mana",
    zhcn  = "法力值消耗",
    ja    = "マナコスト",
    ko    = "마나 비용",
  },

  CorelibTooltipInfoCooldown = {
    en    = "Cooldown",
    ptbr  = "Tempo de recarga",
    ptpt  = "Tempo de recarga",
    es419 = "Tiempo de recarga",
    eses  = "Tiempo de recarga",
    pl    = "Czas odnowienia",
    ru    = "Время перезарядки",
    sv    = "Återhämtningstid",
    nb    = "Nedkjølingstid",
    de    = "Abklingzeit",
    nlnl  = "Hersteltijd",
    frfr  = "Temps de recharge",
    fi    = "Latausaika",
    it    = "Tempo di recupero",
    zhcn  = "冷却时间",
    ja    = "クールダウン",
    ko    = "재사용 대기시간",
  },

  CorelibTooltipInfoPremium = {
    en    = "Premium",
    ptbr  = "Premium",
    ptpt  = "Premium",
    es419 = "Premium",
    eses  = "Premium",
    pl    = "Premium",
    ru    = "Премиум",
    sv    = "Premium",
    nb    = "Premium",
    de    = "Premium",
    nlnl  = "Premium",
    frfr  = "Premium",
    fi    = "Premium",
    it    = "Premium",
    zhcn  = "高级",
    ja    = "プレミアム",
    ko    = "프리미엄",
  },

  CorelibTooltipInfoCombat = {
    en    = "Combat",
    ptbr  = "Combate",
    ptpt  = "Combate",
    es419 = "Combate",
    eses  = "Combate",
    pl    = "Walka",
    ru    = "Бой",
    sv    = "Strid",
    nb    = "Kamp",
    de    = "Kampf",
    nlnl  = "Gevecht",
    frfr  = "Combat",
    fi    = "Taistelu",
    it    = "Combattimento",
    zhcn  = "战斗",
    ja    = "戦闘",
    ko    = "전투",
  },

  CorelibTooltipInfoBoost = {
    en    = "Boost",
    ptbr  = "Impulso",
    ptpt  = "Impulso",
    es419 = "Impulso",
    eses  = "Impulso",
    pl    = "Wzmocnienie",
    ru    = "Усиление",
    sv    = "Förstärkning",
    nb    = "Forsterkning",
    de    = "Verstärkung",
    nlnl  = "Versterking",
    frfr  = "Renforcement",
    fi    = "Tehostus",
    it    = "Potenziamento",
    zhcn  = "增强",
    ja    = "強化",
    ko    = "강화",
  },

  CorelibTooltipInfoAttribute = {
    en    = "Attribute",
    ptbr  = "Atributo",
    ptpt  = "Atributo",
    es419 = "Atributo",
    eses  = "Atributo",
    pl    = "Atrybut",
    ru    = "Характеристика",
    sv    = "Attribut",
    nb    = "Attributt",
    de    = "Attribut",
    nlnl  = "Attribuut",
    frfr  = "Attribut",
    fi    = "Ominaisuus",
    it    = "Attributo",
    zhcn  = "属性",
    ja    = "属性",
    ko    = "속성",
  },

  CorelibTooltipInfoDuration = {
    en    = "Duration",
    ptbr  = "Duração",
    ptpt  = "Duração",
    es419 = "Duración",
    eses  = "Duración",
    pl    = "Czas trwania",
    ru    = "Длительность",
    sv    = "Varaktighet",
    nb    = "Varighet",
    de    = "Dauer",
    nlnl  = "Duur",
    frfr  = "Durée",
    fi    = "Kesto",
    it    = "Durata",
    zhcn  = "持续时间",
    ja    = "持続時間",
    ko    = "지속 시간",
  },

  CorelibTooltipInfoCreatedBy = {
    en    = "Created by",
    ptbr  = "Criado por",
    ptpt  = "Criado por",
    es419 = "Creado por",
    eses  = "Creado por",
    pl    = "Stworzone przez",
    ru    = "Создано",
    sv    = "Skapad av",
    nb    = "Opprettet av",
    de    = "Erstellt von",
    nlnl  = "Gemaakt door",
    frfr  = "Créé par",
    fi    = "Luonut",
    it    = "Creato da",
    zhcn  = "创建者",
    ja    = "作成者",
    ko    = "작성자",
  },

  CorelibInfoMax = {
    en    = "max",
    ptbr  = "máx",
    ptpt  = "máx",
    es419 = "máx",
    eses  = "máx",
    pl    = "maks",
    ru    = "макс",
    sv    = "max",
    nb    = "maks",
    de    = "max",
    nlnl  = "max",
    frfr  = "max",
    fi    = "maks",
    it    = "max",
    zhcn  = "最大",
    ja    = "最大",
    ko    = "최대",
  },

  CorelibInfoMin = {
    en    = "min",
    ptbr  = "mín",
    ptpt  = "mín",
    es419 = "mín",
    eses  = "mín",
    pl    = "min",
    ru    = "мин",
    sv    = "min",
    nb    = "min",
    de    = "min",
    nlnl  = "min",
    frfr  = "min",
    fi    = "min",
    it    = "min",
    zhcn  = "最小",
    ja    = "最小",
    ko    = "최소",
  },

  CorelibSkillsWindowTitle = {
    en    = "Stats",
    ptbr  = "Estatísticas",
    ptpt  = "Estatísticas",
    es419 = "Estadísticas",
    eses  = "Estadísticas",
    pl    = "Statystyki",
    ru    = "Статистика",
    sv    = "Statistik",
    nb    = "Statistikk",
    de    = "Werte",
    nlnl  = "Statistieken",
    frfr  = "Statistiques",
    fi    = "Tilastot",
    it    = "Statistiche",
    zhcn  = "统计",
    ja    = "ステータス",
    ko    = "능력치",
  },

  CorelibConditionsWindowTitle = {
    en    = "Conditions",
    ptbr  = "Condições",
    ptpt  = "Condições",
    es419 = "Condiciones",
    eses  = "Condiciones",
    pl    = "Warunki",
    ru    = "Условия",
    sv    = "Tillstånd",
    nb    = "Tilstander",
    de    = "Zustände",
    nlnl  = "Toestanden",
    frfr  = "Conditions",
    fi    = "Tilat",
    it    = "Condizioni",
    zhcn  = "状态",
    ja    = "状態",
    ko    = "상태 효과",
  },
})
