-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameMinimapTitle = {
    en    = "Minimap",
    ptbr  = "Minimapa",
    ptpt  = "Minimapa",
    es419 = "Minimapa",
    eses  = "Minimapa",
    pl    = "Minimapa",
    ru    = "Миникарта",
    sv    = "Minikarta",
    nb    = "Minikart",
    de    = "MiniKarte",
    nlnl  = "Minikaart",
    frfr  = "Minicarte",
    fi    = "Minikartta",
    it    = "Minimappa",
    zhcn  = "小地图",
    ja    = "ミニマップ",
    ko    = "미니맵",
  },

  GameMinimapButtonShowControllers = {
    en    = "Show controllers",
    ptbr  = "Exibir controladores",
    ptpt  = "Exibir controladores",
    es419 = "Mostrar controladores",
    eses  = "Mostrar controladores",
    pl    = "Pokaż kontrolery",
    ru    = "Показывать контроллеры",
    sv    = "Visa kontroller",
    nb    = "Vis kontroller",
    de    = "Controller anzeigen",
    nlnl  = "Besturingselementen tonen",
    frfr  = "Afficher les contrôleurs",
    fi    = "Näytä ohjaimet",
    it    = "Mostra controller",
    zhcn  = "显示控制器",
    ja    = "コントローラーを表示",
    ko    = "컨트롤러 표시",
  },

  GameMinimapButtonHideControllers = {
    en    = "Hide controllers",
    ptbr  = "Ocultar controladores",
    ptpt  = "Ocultar controladores",
    es419 = "Ocultar controladores",
    eses  = "Ocultar controladores",
    pl    = "Ukryj kontrolery",
    ru    = "Скрывать контроллеры",
    sv    = "Dölj kontroller",
    nb    = "Skjul kontroller",
    de    = "Controller ausblenden",
    nlnl  = "Besturingselementen verbergen",
    frfr  = "Masquer les contrôleurs",
    fi    = "Piilota ohjaimet",
    it    = "Nascondi controller",
    zhcn  = "隐藏控制器",
    ja    = "コントローラーを隠す",
    ko    = "컨트롤러 숨기기",
  },

  GameMinimapButtonInfo = {
    en    = "Hold the left mouse button and drag-and-drop or press the '%s' holding '%s' for navigate.\n\nScroll the mouse wheel for zoom. Do the same holding '%s' for change the floor level.\n\nPress the right mouse button for create map marks.\n\nPress '%s' for view the entire game map.",
    ptbr  = "Segure o botão esquerdo do mouse e arraste ou pressione '%s' enquanto segura '%s' para navegar.\n\nRole a roda do mouse para ampliar. Faça o mesmo segurando '%s' para mudar o nível do andar.\n\nPressione o botão direito do mouse para criar marcas no mapa.\n\nPressione '%s' para ver todo o mapa do jogo.",
    ptpt  = "Segure o botão esquerdo do rato e arraste ou prima '%s' enquanto segura '%s' para navegar.\n\nRole a roda do rato para ampliar. Faça o mesmo segurando '%s' para mudar o nível do andar.\n\nPrima o botão direito do rato para criar marcas no mapa.\n\nPrima '%s' para ver todo o mapa do jogo.",
    es419 = "Mantén presionado el botón izquierdo del ratón y arrastra o presiona '%s' mientras mantienes '%s' para navegar.\n\nDesplaza la rueda del ratón para ampliar. Haz lo mismo manteniendo '%s' para cambiar el nivel del piso.\n\nPresiona el botón derecho del ratón para crear marcas en el mapa.\n\nPresiona '%s' para ver todo el mapa del juego.",
    eses  = "Mantén pulsado el botón izquierdo del ratón y arrastra o pulsa '%s' mientras mantienes '%s' para navegar.\n\nDesplaza la rueda del ratón para ampliar. Haz lo mismo manteniendo '%s' para cambiar el nivel de la planta.\n\nPulsa el botón derecho del ratón para crear marcas en el mapa.\n\nPulsa '%s' para ver todo el mapa del juego.",
    pl    = "Przytrzymaj lewy przycisk myszy i przeciągnij lub naciśnij '%s', trzymając '%s', aby nawigować.\n\nPrzewiń kółko myszy, aby powiększyć. Zrób to samo, trzymając '%s', aby zmienić poziom piętra.\n\nNaciśnij prawy przycisk myszy, aby tworzyć znaczniki na mapie.\n\nNaciśnij '%s', aby wyświetlić całą mapę gry.",
    ru    = "Удерживайте левую кнопку мыши и перетаскивайте или нажмите '%s', удерживая '%s', чтобы перемещаться.\n\nПрокручивайте колесо мыши для масштабирования. Сделайте то же самое, удерживая '%s', чтобы изменить уровень этажа.\n\nНажмите правую кнопку мыши, чтобы создать отметки на карте.\n\nНажмите '%s', чтобы просмотреть всю карту игры.",
    sv    = "Håll ned vänster musknapp och dra eller tryck på '%s' medan du håller '%s' för att navigera.\n\nRulla mushjulet för att zooma. Gör samma sak medan du håller '%s' för att ändra våningsnivån.\n\nTryck på höger musknapp för att skapa markeringar på kartan.\n\nTryck på '%s' för att visa hela spelkartan.",
    nb    = "Hold nede venstre museknapp og dra, eller trykk på '%s' mens du holder '%s' for å navigere.\n\nRull med musehjulet for å zoome. Gjør det samme mens du holder '%s' for å endre etasjenivået.\n\nTrykk på høyre museknapp for å opprette markeringer på kartet.\n\nTrykk på '%s' for å vise hele spillkartet.",
    de    = "Halten Sie die linke Maustaste gedrückt und ziehen Sie oder drücken Sie '%s', während Sie '%s' gedrückt halten, um zu navigieren.\n\nScrollen Sie mit dem Mausrad zum Vergrößern. Machen Sie dasselbe, während Sie '%s' gedrückt halten, um die Etagenebene zu ändern.\n\nDrücken Sie die rechte Maustaste, um Markierungen auf der Karte zu erstellen.\n\nDrücken Sie '%s', um die gesamte Spielkarte anzuzeigen.",
    nlnl  = "Houd de linkermuisknop ingedrukt en sleep, of druk op '%s' terwijl je '%s' ingedrukt houdt om te navigeren.\n\nGebruik het muiswiel om in te zoomen. Doe hetzelfde terwijl je '%s' ingedrukt houdt om van verdieping te veranderen.\n\nDruk op de rechtermuisknop om markeringen op de kaart te maken.\n\nDruk op '%s' om de volledige spelkaart te bekijken.",
    frfr  = "Maintenez le bouton gauche de la souris enfoncé et faites glisser, ou appuyez sur « %s » tout en maintenant « %s » pour naviguer.\n\nFaites défiler la molette de la souris pour zoomer. Faites de même en maintenant « %s » pour changer de niveau.\n\nCliquez avec le bouton droit de la souris pour créer des repères sur la carte.\n\nAppuyez sur « %s » pour voir toute la carte du jeu.",
    fi    = "Pidä hiiren vasenta painiketta painettuna ja vedä tai paina \"%s\" samalla kun pidät \"%s\"-näppäintä painettuna navigoidaksesi.\n\nZoomaa hiiren rullalla. Tee sama pitämällä \"%s\" painettuna vaihtaaksesi kerrosta.\n\nLuo karttamerkintöjä hiiren oikealla painikkeella.\n\nNäytä koko pelin kartta painamalla \"%s\".",
    it    = "Tieni premuto il pulsante sinistro del mouse e trascina, oppure premi '%s' tenendo premuto '%s' per navigare.\n\nUsa la rotellina del mouse per ingrandire. Fai lo stesso tenendo premuto '%s' per cambiare il livello del piano.\n\nPremi il pulsante destro del mouse per creare segnaposto sulla mappa.\n\nPremi '%s' per visualizzare l'intera mappa del gioco.",
    zhcn  = "按住鼠标左键并拖动，或按住 '%s' 的同时按下 '%s' 进行移动。\n\n滚动鼠标滚轮进行缩放。按住 '%s' 的同时进行相同操作可更改楼层。\n\n按下鼠标右键可在地图上创建标记。\n\n按下 '%s' 可查看完整的游戏地图。",
    ja    = "マウスの左ボタンを押したままドラッグするか、「%s」を「%s」を押しながら操作して移動します。\n\nマウスホイールを回して拡大します。「%s」を押しながら同じ操作をすると階層を変更できます。\n\nマウスの右ボタンを押して地図にマークを作成します。\n\n「%s」を押すとゲームマップ全体を表示します。",
    ko    = "마우스 왼쪽 버튼을 누른 채 드래그하거나 '%s'를 '%s'를 누른 상태에서 눌러 이동합니다.\n\n마우스 휠을 스크롤하여 확대합니다. '%s'를 누른 상태에서 같은 동작을 하면 층을 변경할 수 있습니다.\n\n마우스 오른쪽 버튼을 눌러 지도에 표시를 만듭니다.\n\n'%s'를 눌러 전체 게임 지도를 봅니다.",
  },

  GameMinimapButtonInfoArrowKeys = {
    en    = "Arrow keys",
    ptbr  = "Teclas de seta",
    ptpt  = "Teclas de seta",
    es419 = "Teclas de flecha",
    eses  = "Teclas de flecha",
    pl    = "Klawisze strzałek",
    ru    = "Клавиши со стрелками",
    sv    = "Piltangenter",
    nb    = "Piltaster",
    de    = "Pfeiltasten",
    nlnl  = "Pijltjestoetsen",
    frfr  = "Touches fléchées",
    fi    = "Nuolinäppäimet",
    it    = "Tasti freccia",
    zhcn  = "方向键",
    ja    = "矢印キー",
    ko    = "화살표 키",
  },

  GameMinimapButtonExtraIconsShow = {
    en    = "Show minimap extra icons (for example, title labels and party player icons).",
    ptbr  = "Exibir ícones extras no minimapa (por exemplo, rótulos de título e ícones de jogadores da festa).",
    ptpt  = "Exibir ícones extras no minimapa (por exemplo, rótulos de título e ícones de jogadores do grupo).",
    es419 = "Mostrar iconos adicionales en el minimapa (por ejemplo, etiquetas de título e iconos de jugadores del grupo).",
    eses  = "Mostrar iconos adicionales en el minimapa (por ejemplo, etiquetas de título e iconos de jugadores del grupo).",
    pl    = "Pokaż dodatkowe ikony na minimapie (np. etykiety tytułów i ikony graczy z drużyny).",
    ru    = "Показывать дополнительные значки на мини-карте (например, названия и значки игроков группы).",
    sv    = "Visa extra ikoner på minikartan (t.ex. titeletiketter och ikoner för gruppspelare).",
    nb    = "Vis ekstra ikoner på minikartet (f.eks. titteletiketter og ikoner for gruppespillere).",
    de    = "Zusätzliche Symbole auf der Minikarte anzeigen (z. B. Titelbezeichnungen und Symbole von Gruppenmitgliedern).",
    nlnl  = "Extra pictogrammen op de minikaart tonen (bijvoorbeeld titels en pictogrammen van groepsspelers).",
    frfr  = "Afficher les icônes supplémentaires sur la mini-carte (par exemple, les libellés de titre et les icônes des joueurs du groupe).",
    fi    = "Näytä minikartan lisäkuvakkeet (esimerkiksi otsikkotunnisteet ja ryhmän pelaajien kuvakkeet).",
    it    = "Mostra icone extra sulla minimappa (ad esempio, etichette dei titoli e icone dei giocatori del gruppo).",
    zhcn  = "显示小地图上的额外图标（例如标题标签和队伍玩家图标）。",
    ja    = "ミニマップの追加アイコン（タイトルラベルやパーティープレイヤーアイコンなど）を表示します。",
    ko    = "미니맵에 추가 아이콘을 표시합니다(예: 칭호 레이블 및 파티 플레이어 아이콘).",
  },

  GameMinimapButtonExtraIconsHide = {
    en    = "Hide minimap extra icons (for example, title labels and party player icons).",
    ptbr  = "Ocultar ícones extras no minimapa (por exemplo, rótulos de título e ícones de jogadores da festa).",
    ptpt  = "Ocultar ícones extras no minimapa (por exemplo, rótulos de título e ícones de jogadores do grupo).",
    es419 = "Ocultar iconos adicionales en el minimapa (por ejemplo, etiquetas de título e iconos de jugadores del grupo).",
    eses  = "Ocultar iconos adicionales en el minimapa (por ejemplo, etiquetas de título e iconos de jugadores del grupo).",
    pl    = "Ukryj dodatkowe ikony na minimapie (np. etykiety tytułów i ikony graczy z drużyny).",
    ru    = "Скрывать дополнительные значки на мини-карте (например, названия и значки игроков группы).",
    sv    = "Dölj extra ikoner på minikartan (t.ex. titeletiketter och ikoner för gruppspelare).",
    nb    = "Skjul ekstra ikoner på minikartet (f.eks. titteletiketter og ikoner for gruppespillere).",
    de    = "Zusätzliche Symbole auf der Minikarte ausblenden (z. B. Titelbezeichnungen und Symbole von Gruppenmitgliedern).",
    nlnl  = "Extra pictogrammen op de minikaart verbergen (bijvoorbeeld titels en pictogrammen van groepsspelers).",
    frfr  = "Masquer les icônes supplémentaires sur la mini-carte (par exemple, les libellés de titre et les icônes des joueurs du groupe).",
    fi    = "Piilota minikartan lisäkuvakkeet (esimerkiksi otsikkotunnisteet ja ryhmän pelaajien kuvakkeet).",
    it    = "Nascondi le icone extra sulla minimappa (ad esempio, le etichette dei titoli e le icone dei giocatori del gruppo).",
    zhcn  = "隐藏小地图上的额外图标（例如标题标签和队伍玩家图标）。",
    ja    = "ミニマップの追加アイコン（タイトルラベルやパーティープレイヤーアイコンなど）を非表示にします。",
    ko    = "미니맵에 추가 아이콘을 숨깁니다(예: 칭호 레이블 및 파티 플레이어 아이콘).",
  },

  GameMinimapButtonMoveNorth = {
    en    = "Move to north",
    ptbr  = "Mover para o norte",
    ptpt  = "Mover para o norte",
    es419 = "Mover hacia el norte",
    eses  = "Mover hacia el norte",
    pl    = "Przesuń się na północ",
    ru    = "Переместиться на север",
    sv    = "Flytta norrut",
    nb    = "Flytt nordover",
    de    = "Nach Norden bewegen",
    nlnl  = "Naar het noorden verplaatsen",
    frfr  = "Aller vers le nord",
    fi    = "Siirry pohjoiseen",
    it    = "Spostati a nord",
    zhcn  = "向北移动",
    ja    = "北へ移動",
    ko    = "북쪽으로 이동",
  },

  GameMinimapButtonFullMapShow = {
    en    = "Show entire game map (%s)",
    ptbr  = "Exibir todo o mapa do jogo (%s)",
    ptpt  = "Exibir todo o mapa do jogo (%s)",
    es419 = "Mostrar todo el mapa del juego (%s)",
    eses  = "Mostrar todo el mapa del juego (%s)",
    pl    = "Pokaż całą mapę gry (%s)",
    ru    = "Показывать всю карту игры (%s)",
    sv    = "Visa hela spelkartan (%s)",
    nb    = "Vis hele spillkartet (%s)",
    de    = "Die gesamte Spielkarte anzeigen (%s)",
    nlnl  = "De volledige spelkaart tonen (%s)",
    frfr  = "Afficher toute la carte du jeu (%s)",
    fi    = "Näytä koko pelin kartta (%s)",
    it    = "Mostra l'intera mappa del gioco (%s)",
    zhcn  = "显示完整的游戏地图（%s）",
    ja    = "ゲームマップ全体を表示（%s）",
    ko    = "전체 게임 지도 표시 (%s)",
  },

  GameMinimapButtonFullMapHide = {
    en    = "Hide entire game map (%s)",
    ptbr  = "Ocultar todo o mapa do jogo (%s)",
    ptpt  = "Ocultar todo o mapa do jogo (%s)",
    es419 = "Ocultar todo o mapa do jogo (%s)",
    eses  = "Ocultar todo o mapa do jogo (%s)",
    pl    = "Ukryj całą mapę gry (%s)",
    ru    = "Скрыть всю карту игры (%s)",
    sv    = "Dölj hela spelkartan (%s)",
    nb    = "Skjul hele spillkartet (%s)",
    de    = "Die gesamte Spielkarte ausblenden (%s)",
    nlnl  = "De volledige spelkaart verbergen (%s)",
    frfr  = "Masquer toute la carte du jeu (%s)",
    fi    = "Piilota koko pelin kartta (%s)",
    it    = "Nascondi l'intera mappa del gioco (%s)",
    zhcn  = "隐藏完整的游戏地图（%s）",
    ja    = "ゲームマップ全体を非表示にする（%s）",
    ko    = "전체 게임 지도를 숨깁니다 (%s)",
  },

  GameMinimapButtonWorldChannel = {
    en    = "Change world channel",
    ptbr  = "Alterar canal do mundo",
    ptpt  = "Alterar canal do mundo",
    es419 = "Cambiar canal del mundo",
    eses  = "Cambiar canal del mundo",
    pl    = "Zmień kanał świata",
    ru    = "Изменить мировой канал",
    sv    = "Byt världskanal",
    nb    = "Bytt verdenskanal",
    de    = "Weltkanal wechseln",
    nlnl  = "Wereldkanaal wijzigen",
    frfr  = "Changer de canal du monde",
    fi    = "Vaihda maailmakanavaa",
    it    = "Cambia il canale del mondo",
    zhcn  = "更改世界频道",
    ja    = "ワールドチャンネルを変更",
    ko    = "월드 채널 변경",
  },

  GameMinimapButtonMoveWest = {
    en    = "Move to west",
    ptbr  = "Mover para o oeste",
    ptpt  = "Mover para o oeste",
    es419 = "Mover hacia el oeste",
    eses  = "Mover hacia el oeste",
    pl    = "Przesuń się na zachód",
    ru    = "Переместиться на запад",
    sv    = "Flytta västerut",
    nb    = "Flytt vestover",
    de    = "Nach Westen bewegen",
    nlnl  = "Naar het westen verplaatsen",
    frfr  = "Aller vers l'ouest",
    fi    = "Siirry länteen",
    it    = "Sposta a ovest",
    zhcn  = "向西移动",
    ja    = "西へ移動",
    ko    = "서쪽으로 이동",
  },

  GameMinimapButtonMoveCenter = {
    en    = "Move to centralized position",
    ptbr  = "Mover para a posição centralizada",
    ptpt  = "Mover para a posição centralizada",
    es419 = "Mover a la posición centralizada",
    eses  = "Mover a la posición centralizada",
    pl    = "Przesuń się do pozycji centralnej",
    ru    = "Переместиться в центральное положение",
    sv    = "Flytta till den centrerade positionen",
    nb    = "Flytt til den sentraliserte posisjonen",
    de    = "Zur zentrierten Position bewegen",
    nlnl  = "Naar de gecentreerde positie verplaatsen",
    frfr  = "Aller à la position centrée",
    fi    = "Siirry keskitettyyn sijaintiin",
    it    = "Sposta alla posizione centrale",
    zhcn  = "移动到居中位置",
    ja    = "中央の位置へ移動",
    ko    = "중앙 위치로 이동",
  },

  GameMinimapButtonMoveEast = {
    en    = "Move to east",
    ptbr  = "Mover para o leste",
    ptpt  = "Mover para o leste",
    es419 = "Mover hacia el este",
    eses  = "Mover hacia el este",
    pl    = "Przesuń się na wschód",
    ru    = "Переместиться на восток",
    sv    = "Flytta österut",
    nb    = "Flytt østover",
    de    = "Nach Osten bewegen",
    nlnl  = "Naar het oosten verplaatsen",
    frfr  = "Aller vers l'est",
    fi    = "Siirry itään",
    it    = "Sposta a est",
    zhcn  = "向东移动",
    ja    = "東へ移動",
    ko    = "동쪽으로 이동",
  },

  GameMinimapButtonMoveSouth = {
    en    = "Move to south",
    ptbr  = "Mover para o sul",
    ptpt  = "Mover para o sul",
    es419 = "Mover hacia el sur",
    eses  = "Mover hacia el sur",
    pl    = "Przesuń się na południe",
    ru    = "Переместиться на юг",
    sv    = "Flytta söderut",
    nb    = "Flytt sørover",
    de    = "Nach Süden bewegen",
    nlnl  = "Naar het zuiden verplaatsen",
    frfr  = "Aller vers le sud",
    fi    = "Siirry etelään",
    it    = "Sposta a sud",
    zhcn  = "向南移动",
    ja    = "南へ移動",
    ko    = "남쪽으로 이동",
  },

  GameMinimapButtonZoomOut = {
    en    = "Zoom out",
    ptbr  = "Afastar zoom",
    ptpt  = "Afastar zoom",
    es419 = "Alejar el zoom",
    eses  = "Alejar el zoom",
    pl    = "Oddal",
    ru    = "Уменьшить масштаб",
    sv    = "Zooma ut",
    nb    = "Zoome ut",
    de    = "Verkleinern",
    nlnl  = "Uitzoomen",
    frfr  = "Dézoomer",
    fi    = "Loitonna",
    it    = "Riduci lo zoom",
    zhcn  = "缩小",
    ja    = "縮小",
    ko    = "축소",
  },

  GameMinimapButtonZoomIn = {
    en    = "Zoom in",
    ptbr  = "Aproximar zoom",
    ptpt  = "Aproximar zoom",
    es419 = "Acercar el zoom",
    eses  = "Acercar el zoom",
    pl    = "Przybliż",
    ru    = "Увеличить масштаб",
    sv    = "Zooma in",
    nb    = "Zoome inn",
    de    = "Vergrößern",
    nlnl  = "Inzoomen",
    frfr  = "Zoomer",
    fi    = "Lähennä",
    it    = "Aumenta lo zoom",
    zhcn  = "放大",
    ja    = "拡大",
    ko    = "확대",
  },

  GameMinimapButtonFloorDown = {
    en    = "Down floor",
    ptbr  = "Descer andar",
    ptpt  = "Descer andar",
    es419 = "Bajar de piso",
    eses  = "Bajar de planta",
    pl    = "Zejdź piętro niżej",
    ru    = "Спуститься на этаж ниже",
    sv    = "Gå ner en våning",
    nb    = "Gå ned en etasje",
    de    = "Eine Etage tiefer",
    nlnl  = "Een verdieping omlaag",
    frfr  = "Descendre d'un étage",
    fi    = "Siirry alempaan kerrokseen",
    it    = "Scendi di piano",
    zhcn  = "下降一层",
    ja    = "下の階層へ移動",
    ko    = "아래층으로 이동",
  },

  GameMinimapButtonFloorUp = {
    en    = "Up floor",
    ptbr  = "Subir andar",
    ptpt  = "Subir andar",
    es419 = "Subir de piso",
    eses  = "Subir de planta",
    pl    = "Wejdź piętro wyżej",
    ru    = "Подняться на этаж выше",
    sv    = "Gå upp en våning",
    nb    = "Gå opp en etasje",
    de    = "Eine Etage höher",
    nlnl  = "Een verdieping omhoog",
    frfr  = "Monter d'un étage",
    fi    = "Siirry ylempään kerrokseen",
    it    = "Sali di piano",
    zhcn  = "上升一层",
    ja    = "上の階層へ移動",
    ko    = "위층으로 이동",
  },

  GameMinimapMinimapNotAvailable = {
    en    = "Mini map not available",
    ptbr  = "Mini mapa não disponível",
    ptpt  = "Mini mapa não disponível",
    es419 = "Mini mapa no disponible",
    eses  = "Mini mapa no disponible",
    pl    = "Mini mapa niedostępna",
    ru    = "Мини-карта недоступна",
    sv    = "Minikarta ej tillgänglig",
    nb    = "Minikart ikke tilgjengelig",
    de    = "Minikarte nicht verfügbar",
    nlnl  = "Minikaart niet beschikbaar",
    frfr  = "Minicarte indisponible",
    fi    = "Minikartta ei ole käytettävissä",
    it    = "Minimappa non disponibile",
    zhcn  = "小地图不可用",
    ja    = "ミニマップは利用できません",
    ko    = "미니맵을 사용할 수 없습니다",
  },

  GameMinimapButtonTrackEdit = {
    en    = "Edit tracking",
    ptbr  = "Editar rastreamento",
    ptpt  = "Editar rastreamento",
    es419 = "Editar seguimiento",
    eses  = "Editar seguimiento",
    pl    = "Edytuj śledzenie",
    ru    = "Изменить отслеживание",
    sv    = "Redigera spårning",
    nb    = "Rediger sporing",
    de    = "Verfolgung bearbeiten",
    nlnl  = "Volgen bewerken",
    frfr  = "Modifier le suivi",
    fi    = "Muokkaa seurantaa",
    it    = "Modifica il tracciamento",
    zhcn  = "编辑追踪",
    ja    = "追跡を編集",
    ko    = "추적 편집",
  },

  GameMinimapButtonTrackStop = {
    en    = "Stop tracking",
    ptbr  = "Parar rastreamento",
    ptpt  = "Parar rastreamento",
    es419 = "Detener seguimiento",
    eses  = "Detener seguimiento",
    pl    = "Zatrzymaj śledzenie",
    ru    = "Остановить отслеживание",
    sv    = "Stoppa spårning",
    nb    = "Stopp sporing",
    de    = "Verfolgung stoppen",
    nlnl  = "Volgen stoppen",
    frfr  = "Arrêter le suivi",
    fi    = "Lopeta seuranta",
    it    = "Ferma il tracciamento",
    zhcn  = "停止跟踪",
    ja    = "追跡を停止",
    ko    = "추적 중지",
  },
})
