-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameQuestLogWindowTitle = {
    en    = "Quest log",
    ptbr  = "Registro de missões",
    ptpt  = "Registo de missões",
    es419 = "Registro de misiones",
    eses  = "Registro de misiones",
    pl    = "Dziennik zadań",
    ru    = "Журнал заданий",
    sv    = "Uppdragslogg",
    nb    = "Oppdragslogg",
    de    = "Questlog",
    nlnl  = "Missielogboek",
    frfr  = "Journal des quêtes",
    fi    = "Tehtäväloki",
    it    = "Diario delle missioni",
    zhcn  = "任务日志",
    ja    = "クエストログ",
    ko    = "퀘스트 일지",
  },

  GameQuestLogDescriptionLabel = {
    en    = "Description",
    ptbr  = "Descrição",
    ptpt  = "Descrição",
    es419 = "Descripción",
    eses  = "Descripción",
    pl    = "Opis",
    ru    = "Описание",
    sv    = "Beskrivning",
    nb    = "Beskrivelse",
    de    = "Beschreibung",
    nlnl  = "Beschrijving",
    frfr  = "Description",
    fi    = "Kuvaus",
    it    = "Descrizione",
    zhcn  = "描述",
    ja    = "説明",
    ko    = "설명",
  },

  GameQuestLogRewardsLabel = {
    en    = "Rewards",
    ptbr  = "Recompensas",
    ptpt  = "Recompensas",
    es419 = "Recompensas",
    eses  = "Recompensas",
    pl    = "Nagrody",
    ru    = "Награды",
    sv    = "Belöningar",
    nb    = "Belønninger",
    de    = "Belohnungen",
    nlnl  = "Beloningen",
    frfr  = "Récompenses",
    fi    = "Palkinnot",
    it    = "Ricompense",
    zhcn  = "奖励",
    ja    = "報酬",
    ko    = "보상",
  },

  GameQuestLogItemsButton = {
    en    = "Items",
    ptbr  = "Itens",
    ptpt  = "Itens",
    es419 = "Ítems",
    eses  = "Objetos",
    pl    = "Przedmioty",
    ru    = "Предметы",
    sv    = "Föremål",
    nb    = "Gjenstander",
    de    = "Gegenstände",
    nlnl  = "Voorwerpen",
    frfr  = "Objets",
    fi    = "Esineet",
    it    = "Oggetti",
    zhcn  = "物品",
    ja    = "アイテム",
    ko    = "아이템",
  },

  GameQuestLogTeleportButton = {
    en    = "Teleport",
    ptbr  = "Teleportar",
    ptpt  = "Teleportar",
    es419 = "Teletransportar",
    eses  = "Teletransportar",
    pl    = "Teleportuj",
    ru    = "Телепортироваться",
    sv    = "Teleportera",
    nb    = "Teleporter",
    de    = "Teleportieren",
    nlnl  = "Telepor­teren",
    frfr  = "Téléporter",
    fi    = "Teleporttaa",
    it    = "Teletrasporta",
    zhcn  = "传送",
    ja    = "テレポート",
    ko    = "순간이동",
  },

  GameQuestLogItemsButtonTooltip = {
    en    = "See it on loot window",
    ptbr  = "Ver na janela de saque",
    ptpt  = "Ver na janela de saque",
    es419 = "Ver en la ventana de botín",
    eses  = "Ver en la ventana de botín",
    pl    = "Zobacz w oknie łupu",
    ru    = "Посмотреть в окне добычи",
    sv    = "Se i plundringsfönstret",
    nb    = "Se i byttevinduet",
    de    = "Im Beutefenster anzeigen",
    nlnl  = "Bekijk dit in het buitvenster",
    frfr  = "Voir dans la fenêtre de butin",
    fi    = "Näytä ryöstöikkunassa",
    it    = "Vedi nella finestra del bottino",
    zhcn  = "在战利品窗口中查看",
    ja    = "戦利品ウィンドウで見る",
    ko    = "전리품 창에서 보기",
  },

  GameQuestLogMain = {
    en    = "Main",
    ptbr  = "Principal",
    ptpt  = "Principal",
    es419 = "Principal",
    eses  = "Principal",
    pl    = "Główna",
    ru    = "Основной",
    sv    = "Huvud",
    nb    = "Hoved",
    de    = "Haupt",
    nlnl  = "Hoofd",
    frfr  = "Principale",
    fi    = "Päätehtävä",
    it    = "Principale",
    zhcn  = "主要",
    ja    = "メイン",
    ko    = "주요",
  },

  GameQuestLogSide = {
    en    = "Side quest",
    ptbr  = "Missão secundária",
    ptpt  = "Missão secundária",
    es419 = "Misión secundaria",
    eses  = "Misión secundaria",
    pl    = "Misja poboczna",
    ru    = "Побочное задание",
    sv    = "Sidouppdrag",
    nb    = "Sideoppdrag",
    de    = "Nebenquest",
    nlnl  = "Zijmissie",
    frfr  = "Quête secondaire",
    fi    = "Sivutehtävä",
    it    = "Missione secondaria",
    zhcn  = "支线任务",
    ja    = "サイドクエスト",
    ko    = "보조 퀘스트",
  },

  GameQuestLogDaily = {
    en    = "Daily",
    ptbr  = "Diária",
    ptpt  = "Diária",
    es419 = "Diaria",
    eses  = "Diaria",
    pl    = "Codzienna",
    ru    = "Ежедневная",
    sv    = "Daglig",
    nb    = "Daglig",
    de    = "Täglich",
    nlnl  = "Dagelijks",
    frfr  = "Quotidienne",
    fi    = "Päivittäinen",
    it    = "Giornaliera",
    zhcn  = "每日",
    ja    = "デイリー",
    ko    = "일일",
  },

  GameQuestLogWeekly = {
    en    = "Weekly",
    ptbr  = "Semanal",
    ptpt  = "Semanal",
    es419 = "Semanal",
    eses  = "Semanal",
    pl    = "Cotygodniowa",
    ru    = "Еженедельная",
    sv    = "Veckovis",
    nb    = "Ukentlig",
    de    = "Wöchentlich",
    nlnl  = "Wekelijks",
    frfr  = "Hebdomadaire",
    fi    = "Viikoittainen",
    it    = "Settimanale",
    zhcn  = "每周",
    ja    = "ウィークリー",
    ko    = "주간",
  },

  GameQuestLogMonthly = {
    en    = "Monthly",
    ptbr  = "Mensal",
    ptpt  = "Mensal",
    es419 = "Mensual",
    eses  = "Mensual",
    pl    = "Comiesięczna",
    ru    = "Ежемесячная",
    sv    = "Månadsvis",
    nb    = "Månedlig",
    de    = "Monatlich",
    nlnl  = "Maandelijks",
    frfr  = "Mensuelle",
    fi    = "Kuukausittainen",
    it    = "Mensile",
    zhcn  = "每月",
    ja    = "マンスリー",
    ko    = "월간",
  },

  GameQuestLogGuild = {
    en    = "Guild",
    ptbr  = "Guilda",
    ptpt  = "Guilda",
    es419 = "Gremio",
    eses  = "Gremio",
    pl    = "Gildia",
    ru    = "Гильдия",
    sv    = "Gille",
    nb    = "Laug",
    de    = "Gilde",
    nlnl  = "Gilde",
    frfr  = "Guilde",
    fi    = "Kilta",
    it    = "Gilda",
    zhcn  = "公会",
    ja    = "ギルド",
    ko    = "길드",
  },

  GameQuestLogDialogTeleportTitle = {
    en    = "Quest teleport",
    ptbr  = "Teleporte de missão",
    ptpt  = "Teleporte de missão",
    es419 = "Teletransporte de misión",
    eses  = "Teletransporte de misión",
    pl    = "Teleportacja zadania",
    ru    = "Телепортация по заданию",
    sv    = "Uppdragsteleport",
    nb    = "Oppdragsteleport",
    de    = "Quest-Teleport",
    nlnl  = "Missieteleportatie",
    frfr  = "Téléportation de quête",
    fi    = "Tehtäväteleportti",
    it    = "Teletrasporto della missione",
    zhcn  = "任务传送",
    ja    = "クエストテレポート",
    ko    = "퀘스트 순간이동",
  },

  GameQuestLogDialogTeleportMsg = {
    en    = "Are you sure that you want to teleport?",
    ptbr  = "Você tem certeza que deseja se teleportar?",
    ptpt  = "Você tem certeza que deseja se teleportar?",
    es419 = "¿Estás seguro de que quieres teletransportarte?",
    eses  = "¿Estás seguro de que quieres teletransportarte?",
    pl    = "Czy na pewno chcesz się teleportować?",
    ru    = "Вы уверены, что хотите телепортироваться?",
    sv    = "Är du säker på att du vill teleportera?",
    nb    = "Er du sikker på at du vil teleportere?",
    de    = "Bist du sicher, dass du dich teleportieren möchtest?",
    nlnl  = "Weet je zeker dat je wilt teleporteren?",
    frfr  = "Voulez-vous vraiment vous téléporter ?",
    fi    = "Haluatko varmasti teleportata?",
    it    = "Sei sicuro di voler usare il teletrasporto?",
    zhcn  = "确定要传送吗？",
    ja    = "テレポートしますか？",
    ko    = "정말 순간이동하시겠습니까?",
  },

  GameQuestLogInfoLevel = {
    en    = "Level %d",
    ptbr  = "Nível %d",
    ptpt  = "Nível %d",
    es419 = "Nivel %d",
    eses  = "Nivel %d",
    pl    = "Poziom %d",
    ru    = "Уровень %d",
    sv    = "Nivå %d",
    nb    = "Nivå %d",
    de    = "Stufe %d",
    nlnl  = "Niveau %d",
    frfr  = "Niveau %d",
    fi    = "Taso %d",
    it    = "Livello %d",
    zhcn  = "等级 %d",
    ja    = "レベル%d",
    ko    = "레벨 %d",
  },

})
