-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameTextWindowReadWrittenBy = {
    en    = "You read the following, written by\n%s",
    ptbr  = "Você lê o seguinte, escrito por\n%s",
    ptpt  = "Você lê o seguinte, escrito por\n%s",
    es419 = "Lees lo siguiente, escrito por\n%s",
    eses  = "Lees lo siguiente, escrito por\n%s",
    pl    = "Czytasz następujący tekst, napisany przez\n%s",
    ru    = "Вы читаете следующий текст, написанный\n%s",
    sv    = "Du läser följande, skrivet av\n%s",
    nb    = "Du leser følgende, skrevet av\n%s",
    de    = "Du liest Folgendes, geschrieben von\n%s",
    nlnl  = "Je leest het volgende, geschreven door\n%s",
    frfr  = "Vous lisez le texte suivant, écrit par\n%s",
    fi    = "Luet seuraavan tekstin, jonka on kirjoittanut\n%s",
    it    = "Leggi quanto segue, scritto da\n%s",
    zhcn  = "你读到以下内容，作者是\n%s",
    ja    = "次の文章を読みました。執筆者：\n%s",
    ko    = "다음 내용을 읽습니다. 작성자:\n%s",
  },

  GameTextWindowReadWrittenByOn = {
    en    = " on %s.\n",
    ptbr  = " em %s.\n",
    ptpt  = " em %s.\n",
    es419 = " en %s.\n",
    eses  = " en %s.\n",
    pl    = " dnia %s.\n",
    ru    = " %s.\n",
    sv    = " den %s.\n",
    nb    = " den %s.\n",
    de    = " am %s.\n",
    nlnl  = " op %s.\n",
    frfr  = " le %s.\n",
    fi    = " %s.\n",
    it    = " il %s.\n",
    zhcn  = " 于 %s。\n",
    ja    = "（%s）。\n",
    ko    = " %s에 작성됨.\n",
  },

  GameTextWindowReadWrittenOn = {
    en    = "You read the following, written on %s.\n",
    ptbr  = "Você lê o seguinte, escrito em %s.\n",
    ptpt  = "Você lê o seguinte, escrito em %s.\n",
    es419 = "Lees lo siguiente, escrito el %s.\n",
    eses  = "Lees lo siguiente, escrito el %s.\n",
    pl    = "Czytasz następujący tekst, napisany %s.\n",
    ru    = "Вы читаете следующий текст, написанный %s.\n",
    sv    = "Du läser följande, skrivet den %s.\n",
    nb    = "Du leser følgende, skrevet den %s.\n",
    de    = "Du liest Folgendes, geschrieben am %s.\n",
    nlnl  = "Je leest het volgende, geschreven op %s.\n",
    frfr  = "Vous lisez le texte suivant, écrit le %s.\n",
    fi    = "Luet seuraavan tekstin, joka on kirjoitettu %s.\n",
    it    = "Leggi quanto segue, scritto il %s.\n",
    zhcn  = "你读到以下内容，写于 %s。\n",
    ja    = "次の文章を読みました。作成日：%s\n",
    ko    = "다음 내용을 읽습니다. 작성일: %s.\n",
  },

  GameTextWindowInfoItsEmpty = {
    en    = "It is empty.",
    ptbr  = "Está vazio.",
    ptpt  = "Está vazio.",
    es419 = "Está vacío.",
    eses  = "Está vacío.",
    pl    = "Jest puste.",
    ru    = "Пусто.",
    sv    = "Det är tomt.",
    nb    = "Det er tomt.",
    de    = "Es ist leer.",
    nlnl  = "Het is leeg.",
    frfr  = "C'est vide.",
    fi    = "Se on tyhjä.",
    it    = "È vuoto.",
    zhcn  = "是空的。",
    ja    = "空です。",
    ko    = "비어 있습니다.",
  },

  GameTextWindowInfoEnterNewText = {
    en    = "You can enter new text.",
    ptbr  = "Você pode inserir um novo texto.",
    ptpt  = "Você pode inserir um novo texto.",
    es419 = "Puedes ingresar un nuevo texto.",
    eses  = "Puedes introducir un nuevo texto.",
    pl    = "Możesz wprowadzić nowy tekst.",
    ru    = "Вы можете ввести новый текст.",
    sv    = "Du kan ange ny text.",
    nb    = "Du kan skrive inn ny tekst.",
    de    = "Du kannst einen neuen Text eingeben.",
    nlnl  = "Je kunt nieuwe tekst invoeren.",
    frfr  = "Vous pouvez saisir un nouveau texte.",
    fi    = "Voit kirjoittaa uutta tekstiä.",
    it    = "Puoi inserire un nuovo testo.",
    zhcn  = "你可以输入新文本。",
    ja    = "新しいテキストを入力できます。",
    ko    = "새 텍스트를 입력할 수 있습니다.",
  },

  GameTextWindowInfoShowText = {
    en    = "Show text",
    ptbr  = "Mostrar texto",
    ptpt  = "Mostrar texto",
    es419 = "Mostrar texto",
    eses  = "Mostrar texto",
    pl    = "Pokaż tekst",
    ru    = "Показать текст",
    sv    = "Visa text",
    nb    = "Vis tekst",
    de    = "Text anzeigen",
    nlnl  = "Tekst tonen",
    frfr  = "Afficher le texte",
    fi    = "Näytä teksti",
    it    = "Mostra testo",
    zhcn  = "显示文本",
    ja    = "テキストを表示",
    ko    = "텍스트 표시",
  },

  GameTextWindowInfoEditText = {
    en    = "Edit text",
    ptbr  = "Editar texto",
    ptpt  = "Editar texto",
    es419 = "Editar texto",
    eses  = "Editar texto",
    pl    = "Edytuj tekst",
    ru    = "Изменить текст",
    sv    = "Redigera text",
    nb    = "Rediger tekst",
    de    = "Text bearbeiten",
    nlnl  = "Tekst bewerken",
    frfr  = "Modifier le texte",
    fi    = "Muokkaa tekstiä",
    it    = "Modifica testo",
    zhcn  = "编辑文本",
    ja    = "テキストを編集",
    ko    = "텍스트 편집",
  },

  GameTextWindowInfoEnterPerLine = {
    en    = "Enter one name per line.",
    ptbr  = "Insira um nome por linha.",
    ptpt  = "Insira um nome por linha.",
    es419 = "Ingresa un nombre por línea.",
    eses  = "Introduce un nombre por línea.",
    pl    = "Wpisz jedno imię w każdej linii.",
    ru    = "Введите одно имя в каждой строке.",
    sv    = "Ange ett namn per rad.",
    nb    = "Skriv inn ett navn per linje.",
    de    = "Gib einen Namen pro Zeile ein.",
    nlnl  = "Voer één naam per regel in.",
    frfr  = "Saisissez un nom par ligne.",
    fi    = "Kirjoita yksi nimi riville.",
    it    = "Inserisci un nome per riga.",
    zhcn  = "每行输入一个名称。",
    ja    = "1行に1つの名前を入力してください。",
    ko    = "한 줄에 하나의 이름을 입력하세요.",
  },

  GameTextWindowInfoEditList = {
    en    = "Edit list",
    ptbr  = "Editar lista",
    ptpt  = "Editar lista",
    es419 = "Editar lista",
    eses  = "Editar lista",
    pl    = "Edytuj listę",
    ru    = "Изменить список",
    sv    = "Redigera lista",
    nb    = "Rediger liste",
    de    = "Liste bearbeiten",
    nlnl  = "Lijst bewerken",
    frfr  = "Modifier la liste",
    fi    = "Muokkaa listaa",
    it    = "Modifica lista",
    zhcn  = "编辑列表",
    ja    = "一覧を編集",
    ko    = "목록 편집",
  },
})
