-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GamePlayerTradeWindowTitle = {
    en    = "Trade",
    ptbr  = "Comércio",
    ptpt  = "Comércio",
    es419 = "Comercio",
    eses  = "Comercio",
    pl    = "Handel",
    ru    = "Торговля",
    sv    = "Handel",
    nb    = "Handel",
    de    = "Handel",
    nlnl  = "Handel",
    frfr  = "Échange",
    fi    = "Kauppa",
    it    = "Scambio",
    zhcn  = "交易",
    ja    = "取引",
    ko    = "거래",
  },

  GamePlayerTradeButtonAccept = {
    en    = "Accept",
    ptbr  = "Aceitar",
    ptpt  = "Aceitar",
    es419 = "Aceptar",
    eses  = "Aceptar",
    pl    = "Akceptuj",
    ru    = "Принять",
    sv    = "Acceptera",
    nb    = "Godta",
    de    = "Annehmen",
    nlnl  = "Accepteren",
    frfr  = "Accepter",
    fi    = "Hyväksy",
    it    = "Accetta",
    zhcn  = "接受",
    ja    = "承諾",
    ko    = "수락",
  },

  GamePlayerTradeButtonReject = {
    en    = "Reject",
    ptbr  = "Rejeitar",
    ptpt  = "Rejeitar",
    es419 = "Rechazar",
    eses  = "Rechazar",
    pl    = "Odrzuć",
    ru    = "Отклонить",
    sv    = "Avvisa",
    nb    = "Avslå",
    de    = "Ablehnen",
    nlnl  = "Weigeren",
    frfr  = "Refuser",
    fi    = "Hylkää",
    it    = "Rifiuta",
    zhcn  = "拒绝",
    ja    = "拒否",
    ko    = "거부",
  },
})
