-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameEmotesButtonMainTooltip = {
    en    = "Toggle emoticon panel",
    ptbr  = "Alternar painel de emoticons",
    ptpt  = "Alternar painel de emoticons",
    es419 = "Alternar panel de emoticonos",
    eses  = "Alternar panel de emoticonos",
    pl    = "Przełącz panel emotikon",
    ru    = "Переключить панель смайликов",
    sv    = "Visa eller dölj emotikonpanelen",
    nb    = "Vis eller skjul emotikonpanelet",
    de    = "Emoticon-Panel ein-/ausblenden",
    nlnl  = "Emoticonpaneel aan/uitzetten",
    frfr  = "Afficher ou masquer le panneau des émoticônes",
    fi    = "Näytä tai piilota hymiöpaneeli",
    it    = "Mostra/nascondi pannello emoticon",
    zhcn  = "切换表情面板",
    ja    = "感情アイコンパネルを切り替える",
    ko    = "이모티콘 패널 전환",
  },

  GameEmotesIconStone = {
    en    = "Stone",
    ptbr  = "Pedra",
    ptpt  = "Pedra",
    es419 = "Piedra",
    eses  = "Piedra",
    pl    = "Kamień",
    ru    = "Камень",
    sv    = "Sten",
    nb    = "Stein",
    de    = "Stein",
    nlnl  = "Steen",
    frfr  = "Pierre",
    fi    = "Kivi",
    it    = "Pietra",
    zhcn  = "石头",
    ja    = "石",
    ko    = "돌",
  },

  GameEmotesIconPaper = {
    en    = "Paper",
    ptbr  = "Papel",
    ptpt  = "Papel",
    es419 = "Papel",
    eses  = "Papel",
    pl    = "Papier",
    ru    = "Бумага",
    sv    = "Papper",
    nb    = "Papir",
    de    = "Papier",
    nlnl  = "Papier",
    frfr  = "Papier",
    fi    = "Paperi",
    it    = "Carta",
    zhcn  = "纸",
    ja    = "紙",
    ko    = "보",
  },

  GameEmotesIconScissors = {
    en    = "Scissors",
    ptbr  = "Tesoura",
    ptpt  = "Tesoura",
    es419 = "Tijeras",
    eses  = "Tijeras",
    pl    = "Nożyczki",
    ru    = "Ножницы",
    sv    = "Sax",
    nb    = "Saks",
    de    = "Schere",
    nlnl  = "Schaar",
    frfr  = "Ciseaux",
    fi    = "Sakset",
    it    = "Forbici",
    zhcn  = "剪刀",
    ja    = "はさみ",
    ko    = "가위",
  },

  GameEmotesIconExclamation = {
    en    = "Exclamation",
    ptbr  = "Exclamação",
    ptpt  = "Exclamação",
    es419 = "Exclamación",
    eses  = "Exclamación",
    pl    = "Wykrzyknik",
    ru    = "Восклицание",
    sv    = "Utropstecken",
    nb    = "Utropstegn",
    de    = "Ausruf",
    nlnl  = "Uitroep",
    frfr  = "Exclamation",
    fi    = "Huudahdus",
    it    = "Esclamazione",
    zhcn  = "感叹",
    ja    = "感嘆",
    ko    = "감탄",
  },

  GameEmotesIconQuestion = {
    en    = "Question",
    ptbr  = "Interrogação",
    ptpt  = "Interrogação",
    es419 = "Interrogación",
    eses  = "Interrogación",
    pl    = "Pytanie",
    ru    = "Вопрос",
    sv    = "Fråga",
    nb    = "Spørsmål",
    de    = "Frage",
    nlnl  = "Vraag",
    frfr  = "Question",
    fi    = "Kysymys",
    it    = "Domanda",
    zhcn  = "疑问",
    ja    = "疑問",
    ko    = "질문",
  },

  GameEmotesIconThanks = {
    en    = "Thanks",
    ptbr  = "Obrigado",
    ptpt  = "Obrigado",
    es419 = "Gracias",
    eses  = "Gracias",
    pl    = "Dziękuję",
    ru    = "Спасибо",
    sv    = "Tack",
    nb    = "Takk",
    de    = "Danke",
    nlnl  = "Bedankt",
    frfr  = "Merci",
    fi    = "Kiitos",
    it    = "Grazie",
    zhcn  = "感谢",
    ja    = "感謝",
    ko    = "감사",
  },

  GameEmotesIconSorry = {
    en    = "Sorry",
    ptbr  = "Desculpe",
    ptpt  = "Desculpe",
    es419 = "Lo siento",
    eses  = "Lo siento",
    pl    = "Przepraszam",
    ru    = "Извините",
    sv    = "Förlåt",
    nb    = "Beklager",
    de    = "Entschuldigung",
    nlnl  = "Sorry",
    frfr  = "Désolé",
    fi    = "Anteeksi",
    it    = "Scusa",
    zhcn  = "抱歉",
    ja    = "ごめん",
    ko    = "미안",
  },

  GameEmotesIconEmbarassed = {
    en    = "Embarassed",
    ptbr  = "Envergonhado",
    ptpt  = "Envergonhado",
    es419 = "Avergonzado",
    eses  = "Avergonzado",
    pl    = "Zawstydzony",
    ru    = "Смущённый",
    sv    = "Generad",
    nb    = "Flau",
    de    = "Verlegen",
    nlnl  = "Beschaamd",
    frfr  = "Embarrassé",
    fi    = "Hämmentynyt",
    it    = "Imbarazzato",
    zhcn  = "尴尬",
    ja    = "照れ",
    ko    = "당황",
  },

  GameEmotesIconKiss = {
    en    = "Kiss",
    ptbr  = "Beijo",
    ptpt  = "Beijo",
    es419 = "Beso",
    eses  = "Beso",
    pl    = "Całus",
    ru    = "Поцелуй",
    sv    = "Kyss",
    nb    = "Kyss",
    de    = "Kuss",
    nlnl  = "Kus",
    frfr  = "Bisou",
    fi    = "Suudelma",
    it    = "Bacio",
    zhcn  = "亲吻",
    ja    = "キス",
    ko    = "키스",
  },

  GameEmotesIconPassionate = {
    en    = "Passionate",
    ptbr  = "Apaixonado",
    ptpt  = "Apaixonado",
    es419 = "Apasionado",
    eses  = "Apasionado",
    pl    = "Namiętny",
    ru    = "Страстный",
    sv    = "Passionerad",
    nb    = "Lidenskapelig",
    de    = "Leidenschaftlich",
    nlnl  = "Hartstochtelijk",
    frfr  = "Passionné",
    fi    = "Intohimoinen",
    it    = "Appassionato",
    zhcn  = "热情",
    ja    = "情熱的",
    ko    = "열정",
  },

  GameEmotesIconEvil = {
    en    = "Evil",
    ptbr  = "Maligno",
    ptpt  = "Maligno",
    es419 = "Malvado",
    eses  = "Malvado",
    pl    = "Zły",
    ru    = "Злой",
    sv    = "Ond",
    nb    = "Ond",
    de    = "Böse",
    nlnl  = "Kwaadaardig",
    frfr  = "Maléfique",
    fi    = "Paha",
    it    = "Malvagio",
    zhcn  = "邪恶",
    ja    = "邪悪",
    ko    = "악",
  },

  GameEmotesIconPretty = {
    en    = "Pretty",
    ptbr  = "Bonito",
    ptpt  = "Bonito",
    es419 = "Bonito",
    eses  = "Bonito",
    pl    = "Ładny",
    ru    = "Красивый",
    sv    = "Snygg",
    nb    = "Snygg",
    de    = "Hübsch",
    nlnl  = "Mooi",
    frfr  = "Joli",
    fi    = "Kaunis",
    it    = "Carino",
    zhcn  = "漂亮",
    ja    = "かわいい",
    ko    = "예쁨",
  },

  GameEmotesIconAngry = {
    en    = "Angry",
    ptbr  = "Bravo",
    ptpt  = "Bravo",
    es419 = "Enojado",
    eses  = "Enojado",
    pl    = "Zły",
    ru    = "Злой",
    sv    = "Arg",
    nb    = "Sint",
    de    = "Wütend",
    nlnl  = "Boos",
    frfr  = "En colère",
    fi    = "Vihainen",
    it    = "Arrabbiato",
    zhcn  = "生气",
    ja    = "怒り",
    ko    = "화남",
  },

  GameEmotesIconDistracted = {
    en    = "Distracted",
    ptbr  = "Distrair",
    ptpt  = "Distrair",
    es419 = "Distraerse",
    eses  = "Distraerse",
    pl    = "Rozpraszać",
    ru    = "Отвлекаться",
    sv    = "Distrahera",
    nb    = "Distrahere",
    de    = "Ablenken",
    nlnl  = "Afleiden",
    frfr  = "Distraire",
    fi    = "Häiritä",
    it    = "Distrarre",
    zhcn  = "分心",
    ja    = "気を散らす",
    ko    = "산만하게 하다",
  },

  GameEmotesIconLaugh = {
    en    = "Laugh",
    ptbr  = "Rir",
    ptpt  = "Rir",
    es419 = "Reír",
    eses  = "Reír",
    pl    = "Śmiać się",
    ru    = "Смеяться",
    sv    = "Skratta",
    nb    = "Le",
    de    = "Lachen",
    nlnl  = "Lachen",
    frfr  = "Rire",
    fi    = "Nauraa",
    it    = "Ridire",
    zhcn  = "大笑",
    ja    = "笑う",
    ko    = "웃다",
  },

  GameEmotesIconConfused = {
    en    = "Confused",
    ptbr  = "Confuso",
    ptpt  = "Confuso",
    es419 = "Confundido",
    eses  = "Confundido",
    pl    = "Zdezorientowany",
    ru    = "Растерянный",
    sv    = "Förvirrad",
    nb    = "Forvirret",
    de    = "Verwirrt",
    nlnl  = "Verward",
    frfr  = "Confus",
    fi    = "Hämmentynyt",
    it    = "Confuso",
    zhcn  = "困惑",
    ja    = "困惑",
    ko    = "혼란스러운",
  },

  GameEmotesIconLiked = {
    en    = "Liked",
    ptbr  = "Gostou",
    ptpt  = "Gostou",
    es419 = "Le gustó",
    eses  = "Le gustó",
    pl    = "Polubiono",
    ru    = "Понравилось",
    sv    = "Gillade",
    nb    = "Likte",
    de    = "Gefällt",
    nlnl  = "Leuk gevonden",
    frfr  = "Aimé",
    fi    = "Tykkäsi",
    it    = "È piaciuto",
    zhcn  = "喜欢",
    ja    = "気に入った",
    ko    = "좋아함",
  },

  GameEmotesIconHungry = {
    en    = "Hungry",
    ptbr  = "Faminto",
    ptpt  = "Faminto",
    es419 = "Hambriento",
    eses  = "Hambriento",
    pl    = "Głodny",
    ru    = "Голодный",
    sv    = "Hungrig",
    nb    = "Sulten",
    de    = "Hungrig",
    nlnl  = "Hongerig",
    frfr  = "Affamé",
    fi    = "Nälkäinen",
    it    = "Affamato",
    zhcn  = "饥饿",
    ja    = "お腹が空いた",
    ko    = "배고픈",
  },

  GameEmotesIconSleepy = {
    en    = "Sleepy",
    ptbr  = "Sonolento",
    ptpt  = "Sonolento",
    es419 = "Somnoliento",
    eses  = "Somnoliento",
    pl    = "Senny",
    ru    = "Сонный",
    sv    = "Sömnig",
    nb    = "Søvnig",
    de    = "Schläfrig",
    nlnl  = "Slaperig",
    frfr  = "Somnolent",
    fi    = "Uninen",
    it    = "Assonnato",
    zhcn  = "困倦",
    ja    = "眠い",
    ko    = "졸린",
  },

  GameEmotesIconImpressed = {
    en    = "Impressed",
    ptbr  = "Impressionado",
    ptpt  = "Impressionado",
    es419 = "Impresionado",
    eses  = "Impresionado",
    pl    = "Pod wrażeniem",
    ru    = "Впечатлён",
    sv    = "Imponerad",
    nb    = "Imponert",
    de    = "Beeindruckt",
    nlnl  = "Onder de indruk",
    frfr  = "Impressionné",
    fi    = "Vaikuttunut",
    it    = "Impressionato",
    zhcn  = "印象深刻",
    ja    = "感心した",
    ko    = "감탄한",
  },

  GameEmotesIconScared = {
    en    = "Scared",
    ptbr  = "Assustado",
    ptpt  = "Assustado",
    es419 = "Asustado",
    eses  = "Asustado",
    pl    = "Przestraszony",
    ru    = "Испуганный",
    sv    = "Rädd",
    nb    = "Redd",
    de    = "Verängstigt",
    nlnl  = "Bang",
    frfr  = "Effrayé",
    fi    = "Pelokas",
    it    = "Spaventato",
    zhcn  = "害怕",
    ja    = "怖がっている",
    ko    = "무서워하는",
  },

  GameEmotesIconCrying = {
    en    = "Crying",
    ptbr  = "Chorando",
    ptpt  = "A chorar",
    es419 = "Llorando",
    eses  = "Llorando",
    pl    = "Płaczący",
    ru    = "Плачет",
    sv    = "Gråtande",
    nb    = "Gråter",
    de    = "Weinend",
    nlnl  = "Huilen",
    frfr  = "En train de pleurer",
    fi    = "Itkee",
    it    = "Piangendo",
    zhcn  = "哭泣",
    ja    = "泣いている",
    ko    = "울고 있음",
  },

  GameEmotesIconDrop = {
    en    = "Drop",
    ptbr  = "Soltar",
    ptpt  = "Largar",
    es419 = "Soltar",
    eses  = "Soltar",
    pl    = "Upuścić",
    ru    = "Бросить",
    sv    = "Släppa",
    nb    = "Slippe",
    de    = "Fallenlassen",
    nlnl  = "Loslaten",
    frfr  = "Lâcher",
    fi    = "Pudottaa",
    it    = "Lasciare",
    zhcn  = "放下",
    ja    = "落とす",
    ko    = "놓기",
  },

  GameEmotesIconMusic = {
    en    = "Music",
    ptbr  = "Música",
    ptpt  = "Música",
    es419 = "Música",
    eses  = "Música",
    pl    = "Muzyka",
    ru    = "Музыка",
    sv    = "Musik",
    nb    = "Musikk",
    de    = "Musik",
    nlnl  = "Muziek",
    frfr  = "Musique",
    fi    = "Musiikki",
    it    = "Musica",
    zhcn  = "音乐",
    ja    = "音楽",
    ko    = "음악",
  },

  GameEmotesIconStressed = {
    en    = "Stressed",
    ptbr  = "Estressado",
    ptpt  = "Stressado",
    es419 = "Estresado",
    eses  = "Estresado",
    pl    = "Zestresowany",
    ru    = "В состоянии стресса",
    sv    = "Stressad",
    nb    = "Stresset",
    de    = "Gestresst",
    nlnl  = "Gestrest",
    frfr  = "Stressé",
    fi    = "Stressaantunut",
    it    = "Stressato",
    zhcn  = "压力大",
    ja    = "ストレスを感じている",
    ko    = "스트레스받음",
  },

  GameEmotesIconHorny = {
    en    = "Horny",
    ptbr  = "Excitado",
    ptpt  = "Excitado",
    es419 = "Excitado",
    eses  = "Excitado",
    pl    = "Podniecony",
    ru    = "Возбуждённый",
    sv    = "Kåt",
    nb    = "Kåt",
    de    = "Erregt",
    nlnl  = "Geil",
    frfr  = "Excité",
    fi    = "Kiihottunut",
    it    = "Eccitato",
    zhcn  = "性兴奋",
    ja    = "ムラムラしている",
    ko    = "흥분함",
  },

  GameEmotesIconHeart = {
    en    = "Heart",
    ptbr  = "Coração",
    ptpt  = "Coração",
    es419 = "Corazón",
    eses  = "Corazón",
    pl    = "Serce",
    ru    = "Сердце",
    sv    = "Hjärta",
    nb    = "Hjerte",
    de    = "Herz",
    nlnl  = "Hart",
    frfr  = "Cœur",
    fi    = "Sydän",
    it    = "Cuore",
    zhcn  = "心形",
    ja    = "ハート",
    ko    = "하트",
  },

  GameEmotesIconTongue = {
    en    = "Tongue",
    ptbr  = "Língua",
    ptpt  = "Língua",
    es419 = "Lengua",
    eses  = "Lengua",
    pl    = "Język",
    ru    = "Язык",
    sv    = "Tunga",
    nb    = "Tunge",
    de    = "Zunge",
    nlnl  = "Tong",
    frfr  = "Langue",
    fi    = "Kieli",
    it    = "Lingua",
    zhcn  = "舌头",
    ja    = "舌",
    ko    = "혀",
  },

  GameEmotesIconIdea = {
    en    = "Idea",
    ptbr  = "Ideia",
    ptpt  = "Ideia",
    es419 = "Idea",
    eses  = "Idea",
    pl    = "Pomysł",
    ru    = "Идея",
    sv    = "Idé",
    nb    = "Idé",
    de    = "Idee",
    nlnl  = "Idee",
    frfr  = "Idée",
    fi    = "Idea",
    it    = "Idea",
    zhcn  = "想法",
    ja    = "ひらめき",
    ko    = "아이디어",
  },

  GameEmotesIconMoney = {
    en    = "Money",
    ptbr  = "Dinheiro",
    ptpt  = "Dinheiro",
    es419 = "Dinero",
    eses  = "Dinero",
    pl    = "Pieniądze",
    ru    = "Деньги",
    sv    = "Pengar",
    nb    = "Penger",
    de    = "Geld",
    nlnl  = "Geld",
    frfr  = "Argent",
    fi    = "Raha",
    it    = "Denaro",
    zhcn  = "金钱",
    ja    = "お金",
    ko    = "돈",
  },

  GameEmotesIconCreature = {
    en    = "Creature",
    ptbr  = "Criatura",
    ptpt  = "Criatura",
    es419 = "Criatura",
    eses  = "Criatura",
    pl    = "Stworzenie",
    ru    = "Существо",
    sv    = "Varelse",
    nb    = "Skapning",
    de    = "Kreatur",
    nlnl  = "Wezen",
    frfr  = "Créature",
    fi    = "Olento",
    it    = "Creatura",
    zhcn  = "生物",
    ja    = "クリーチャー",
    ko    = "생물",
  },

  GameEmotesIconBrazil = {
    en    = "Brazil",
    ptbr  = "Brasil",
    ptpt  = "Brasil",
    es419 = "Brasil",
    eses  = "Brasil",
    pl    = "Brazylia",
    ru    = "Бразилия",
    sv    = "Brasilien",
    nb    = "Brasil",
    de    = "Brasilien",
    nlnl  = "Brazilië",
    frfr  = "Brésil",
    fi    = "Brasilia",
    it    = "Brasile",
    zhcn  = "巴西",
    ja    = "ブラジル",
    ko    = "브라질",
  },

  GameEmotesIconGo = {
    en    = "Go!",
    ptbr  = "Vá!",
    ptpt  = "Vá!",
    es419 = "¡Ve!",
    eses  = "¡Ve!",
    pl    = "Idź!",
    ru    = "Вперёд!",
    sv    = "Gå!",
    nb    = "Gå!",
    de    = "Los!",
    nlnl  = "Ga!",
    frfr  = "Allez !",
    fi    = "Mene!",
    it    = "Vai!",
    zhcn  = "出发！",
    ja    = "行け！",
    ko    = "가자!",
  },
})
