-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GamePartyListWindowTitle = {
    en    = "Party list",
    ptbr  = "Lista de grupo",
    ptpt  = "Lista de grupo",
    es419 = "Lista de grupo",
    eses  = "Lista de grupo",
    pl    = "Lista drużyny",
    ru    = "Список группы",
    sv    = "Grupplista",
    nb    = "Gruppeliste",
    de    = "Gruppenliste",
    nlnl  = "Groepslijst",
    frfr  = "Liste du groupe",
    fi    = "Ryhmän lista",
    it    = "Lista del gruppo",
    zhcn  = "队伍列表",
    ja    = "グループ一覧",
    ko    = "그룹 목록",
  },

  GamePartyListInviteeLabel = {
    en    = "Invitees",
    ptbr  = "Convidados",
    ptpt  = "Convidados",
    es419 = "Invitados",
    eses  = "Invitados",
    pl    = "Zaproszeni",
    ru    = "Приглашённые",
    sv    = "Inbjudna",
    nb    = "Inviterte",
    de    = "Eingeladene",
    nlnl  = "Uitgenodigden",
    frfr  = "Invités",
    fi    = "Kutsutut",
    it    = "Invitati",
    zhcn  = "受邀者",
    ja    = "招待された人",
    ko    = "초대받은 사람",
  },

  GamePartyListPartyLabel = {
    en    = "Partners",
    ptbr  = "Parceiros",
    ptpt  = "Parceiros",
    es419 = "Compañeros",
    eses  = "Compañeros",
    pl    = "Partnerzy",
    ru    = "Партнёры",
    sv    = "Medlemmar",
    nb    = "Partnere",
    de    = "Partner",
    nlnl  = "Groepsleden",
    frfr  = "Partenaires",
    fi    = "Ryhmätoverit",
    it    = "Compagni",
    zhcn  = "伙伴",
    ja    = "パートナー",
    ko    = "파트너",
  },

  GamePartyListFilterKnightPlayersShow = {
    en    = "Show knight players",
    ptbr  = "Exibir jogadores cavaleiros",
    ptpt  = "Exibir jogadores cavaleiros",
    es419 = "Mostrar jugadores caballeros",
    eses  = "Mostrar jugadores caballeros",
    pl    = "Pokaż graczy rycerzy",
    ru    = "Показывать игроков-рыцарей",
    sv    = "Visa riddarspelare",
    nb    = "Vis ridder-spillere",
    de    = "Ritter-Spieler anzeigen",
    nlnl  = "Ridder-spelers tonen",
    frfr  = "Afficher les joueurs chevaliers",
    fi    = "Näytä ritaripelaajat",
    it    = "Mostra giocatori cavalieri",
    zhcn  = "显示骑士玩家",
    ja    = "ナイトのプレイヤーを表示",
    ko    = "기사 플레이어 표시",
  },

  GamePartyListFilterKnightPlayersHide = {
    en    = "Hide knight players",
    ptbr  = "Ocultar jogadores cavaleiros",
    ptpt  = "Ocultar jogadores cavaleiros",
    es419 = "Ocultar jugadores caballeros",
    eses  = "Ocultar jugadores caballeros",
    pl    = "Ukryj graczy rycerzy",
    ru    = "Скрыть игроков-рыцарей",
    sv    = "Dölj riddarspelare",
    nb    = "Skjul ridder-spillere",
    de    = "Ritter-Spieler ausblenden",
    nlnl  = "Ridder-spelers verbergen",
    frfr  = "Masquer les joueurs chevaliers",
    fi    = "Piilota ritaripelaajat",
    it    = "Nascondi i giocatori cavalieri",
    zhcn  = "隐藏骑士玩家",
    ja    = "ナイトのプレイヤーを隠す",
    ko    = "기사 플레이어 숨기기",
  },

  GamePartyListFilterPaladinPlayersShow = {
    en    = "Show paladin players",
    ptbr  = "Exibir jogadores paladinos",
    ptpt  = "Exibir jogadores paladinos",
    es419 = "Mostrar jugadores paladines",
    eses  = "Mostrar jugadores paladines",
    pl    = "Pokaż graczy paladynów",
    ru    = "Показывать игроков-паладинов",
    sv    = "Visa paladinspelare",
    nb    = "Vis paladin-spillere",
    de    = "Paladin-Spieler anzeigen",
    nlnl  = "Paladijn-spelers tonen",
    frfr  = "Afficher les joueurs paladins",
    fi    = "Näytä paladiinipelaajat",
    it    = "Mostra i giocatori paladini",
    zhcn  = "显示圣骑士玩家",
    ja    = "パラディンのプレイヤーを表示",
    ko    = "성기사 플레이어 표시",
  },

  GamePartyListFilterPaladinPlayersHide = {
    en    = "Hide paladin players",
    ptbr  = "Ocultar jogadores paladinos",
    ptpt  = "Ocultar jogadores paladinos",
    es419 = "Ocultar jugadores paladines",
    eses  = "Ocultar jugadores paladines",
    pl    = "Ukryj graczy paladynów",
    ru    = "Скрыть игроков-паладинов",
    sv    = "Dölj paladinspelare",
    nb    = "Skjul paladin-spillere",
    de    = "Paladin-Spieler ausblenden",
    nlnl  = "Paladijn-spelers verbergen",
    frfr  = "Masquer les joueurs paladins",
    fi    = "Piilota paladiinipelaajat",
    it    = "Nascondi i giocatori paladini",
    zhcn  = "隐藏圣骑士玩家",
    ja    = "パラディンのプレイヤーを隠す",
    ko    = "성기사 플레이어 숨기기",
  },

  GamePartyListFilterArcherPlayersShow = {
    en    = "Show archer players",
    ptbr  = "Exibir jogadores arqueiros",
    ptpt  = "Exibir jogadores arqueiros",
    es419 = "Mostrar jugadores arqueros",
    eses  = "Mostrar jugadores arqueros",
    pl    = "Pokaż graczy łuczników",
    ru    = "Показывать игроков-лучников",
    sv    = "Visa bågskyttespelare",
    nb    = "Vis bueskytter-spillere",
    de    = "Bogenschützen-Spieler anzeigen",
    nlnl  = "Boogschutter-spelers tonen",
    frfr  = "Afficher les joueurs archers",
    fi    = "Näytä jousiampujapelaajat",
    it    = "Mostra i giocatori arcieri",
    zhcn  = "显示弓箭手玩家",
    ja    = "アーチャーのプレイヤーを表示",
    ko    = "궁수 플레이어 표시",
  },

  GamePartyListFilterArcherPlayersHide = {
    en    = "Hide archer players",
    ptbr  = "Ocultar jogadores arqueiros",
    ptpt  = "Ocultar jogadores arqueiros",
    es419 = "Ocultar jugadores arqueros",
    eses  = "Ocultar jugadores arqueros",
    pl    = "Ukryj graczy łuczników",
    ru    = "Скрыть игроков-лучников",
    sv    = "Dölj bågskyttespelare",
    nb    = "Skjul bueskytterspillere",
    de    = "Bogenschützen-Spieler ausblenden",
    nlnl  = "Boogschutters verbergen",
    frfr  = "Masquer les joueurs archers",
    fi    = "Piilota jousiampujapelaajat",
    it    = "Nascondi i giocatori arcieri",
    zhcn  = "隐藏弓箭手玩家",
    ja    = "アーチャーのプレイヤーを隠す",
    ko    = "궁수 플레이어 숨기기",
  },

  GamePartyListFilterAssassinPlayersShow = {
    en    = "Show assassin players",
    ptbr  = "Exibir jogadores assassinos",
    ptpt  = "Exibir jogadores assassinos",
    es419 = "Mostrar jugadores asesinos",
    eses  = "Mostrar jugadores asesinos",
    pl    = "Pokaż graczy asasynów",
    ru    = "Показать игроков-ассасинов",
    sv    = "Visa lönnmördarspelare",
    nb    = "Vis leiemorderspillere",
    de    = "Assassinen-Spieler anzeigen",
    nlnl  = "Moordenaars tonen",
    frfr  = "Afficher les joueurs assassins",
    fi    = "Näytä salamurhaajapelaajat",
    it    = "Mostra i giocatori assassini",
    zhcn  = "显示刺客玩家",
    ja    = "アサシンのプレイヤーを表示",
    ko    = "암살자 플레이어 표시",
  },

  GamePartyListFilterAssassinPlayersHide = {
    en    = "Hide assassin players",
    ptbr  = "Ocultar jogadores assassinos",
    ptpt  = "Ocultar jogadores assassinos",
    es419 = "Ocultar jugadores asesinos",
    eses  = "Ocultar jugadores asesinos",
    pl    = "Ukryj graczy asasynów",
    ru    = "Скрыть игроков-ассасинов",
    sv    = "Dölj lönnmördarspelare",
    nb    = "Skjul leiemorderspillere",
    de    = "Assassinen-Spieler ausblenden",
    nlnl  = "Moordenaars verbergen",
    frfr  = "Masquer les joueurs assassins",
    fi    = "Piilota salamurhaajapelaajat",
    it    = "Nascondi i giocatori assassini",
    zhcn  = "隐藏刺客玩家",
    ja    = "アサシンのプレイヤーを隠す",
    ko    = "암살자 플레이어 숨기기",
  },

  GamePartyListFilterWizardPlayersShow = {
    en    = "Show wizard players",
    ptbr  = "Exibir jogadores magos",
    ptpt  = "Exibir jogadores magos",
    es419 = "Mostrar jugadores magos",
    eses  = "Mostrar jugadores magos",
    pl    = "Pokaż graczy czarodziejów",
    ru    = "Показать игроков-магoв",
    sv    = "Visa trollkarlar",
    nb    = "Vis trollmannspillere",
    de    = "Magier-Spieler anzeigen",
    nlnl  = "Tovenaars tonen",
    frfr  = "Afficher les joueurs mages",
    fi    = "Näytä velhopelaajat",
    it    = "Mostra i giocatori maghi",
    zhcn  = "显示法师玩家",
    ja    = "ウィザードのプレイヤーを表示",
    ko    = "마법사 플레이어 표시",
  },

  GamePartyListFilterWizardPlayersHide = {
    en    = "Hide wizard players",
    ptbr  = "Ocultar jogadores magos",
    ptpt  = "Ocultar jogadores magos",
    es419 = "Ocultar jugadores magos",
    eses  = "Ocultar jugadores magos",
    pl    = "Ukryj graczy-magów",
    ru    = "Скрыть игроков-магoв",
    sv    = "Dölj trollkarlar",
    nb    = "Skjul trollmenn",
    de    = "Magierspieler ausblenden",
    nlnl  = "Tovenaars verbergen",
    frfr  = "Masquer les joueurs mages",
    fi    = "Piilota velhopelaajat",
    it    = "Nascondi i giocatori maghi",
    zhcn  = "隐藏法师玩家",
    ja    = "ウィザードのプレイヤーを隠す",
    ko    = "마법사 플레이어 숨기기",
  },

  GamePartyListFilterBardPlayersShow = {
    en    = "Show bard players",
    ptbr  = "Exibir jogadores bardos",
    ptpt  = "Exibir jogadores bardos",
    es419 = "Mostrar jugadores bardos",
    eses  = "Mostrar jugadores bardos",
    pl    = "Pokaż graczy-bardów",
    ru    = "Показать игроков-бардов",
    sv    = "Visa bardspelare",
    nb    = "Vis bardspillere",
    de    = "Bardenspieler anzeigen",
    nlnl  = "Bardspelers tonen",
    frfr  = "Afficher les joueurs bardes",
    fi    = "Näytä bardipelaajat",
    it    = "Mostra i giocatori bardi",
    zhcn  = "显示吟游诗人玩家",
    ja    = "バードのプレイヤーを表示",
    ko    = "바드 플레이어 표시",
  },

  GamePartyListFilterBardPlayersHide = {
    en    = "Hide bard players",
    ptbr  = "Ocultar jogadores bardos",
    ptpt  = "Ocultar jogadores bardos",
    es419 = "Ocultar jugadores bardos",
    eses  = "Ocultar jugadores bardos",
    pl    = "Ukryj graczy-bardów",
    ru    = "Скрыть игроков-бардов",
    sv    = "Dölj bardspelare",
    nb    = "Skjul bardspillere",
    de    = "Bardenspieler ausblenden",
    nlnl  = "Bardspelers verbergen",
    frfr  = "Masquer les joueurs bardes",
    fi    = "Piilota bardipelaajat",
    it    = "Nascondi i giocatori bardi",
    zhcn  = "隐藏吟游诗人玩家",
    ja    = "バードのプレイヤーを隠す",
    ko    = "바드 플레이어 숨기기",
  },

  GamePartyListFilterPlayersShow = {
    en    = "Show players",
    ptbr  = "Exibir jogadores",
    ptpt  = "Exibir jogadores",
    es419 = "Mostrar jugadores",
    eses  = "Mostrar jugadores",
    pl    = "Pokaż graczy",
    ru    = "Показать игроков",
    sv    = "Visa spelare",
    nb    = "Vis spillere",
    de    = "Spieler anzeigen",
    nlnl  = "Spelers tonen",
    frfr  = "Afficher les joueurs",
    fi    = "Näytä pelaajat",
    it    = "Mostra i giocatori",
    zhcn  = "显示玩家",
    ja    = "プレイヤーを表示",
    ko    = "플레이어 표시",
  },

  GamePartyListFilterPlayersHide = {
    en    = "Hide players",
    ptbr  = "Ocultar jogadores",
    ptpt  = "Ocultar jogadores",
    es419 = "Ocultar jugadores",
    eses  = "Ocultar jugadores",
    pl    = "Ukryj graczy",
    ru    = "Скрыть игроков",
    sv    = "Dölj spelare",
    nb    = "Skjul spillere",
    de    = "Spieler ausblenden",
    nlnl  = "Spelers verbergen",
    frfr  = "Masquer les joueurs",
    fi    = "Piilota pelaajat",
    it    = "Nascondi giocatori",
    zhcn  = "隐藏玩家",
    ja    = "プレイヤーを隠す",
    ko    = "플레이어 숨기기",
  },

  GamePartyListFilterSummonsShow = {
    en    = "Show summons",
    ptbr  = "Exibir invocações",
    ptpt  = "Exibir invocações",
    es419 = "Mostrar invocaciones",
    eses  = "Mostrar invocaciones",
    pl    = "Pokaż przywołania",
    ru    = "Показывать призывы",
    sv    = "Visa kallelser",
    nb    = "Vis innkallinger",
    de    = "Beschwörungen anzeigen",
    nlnl  = "Oproepingen tonen",
    frfr  = "Afficher les invocations",
    fi    = "Näytä kutsutut olennot",
    it    = "Mostra evocazioni",
    zhcn  = "显示召唤物",
    ja    = "召喚獣を表示",
    ko    = "소환수 표시",
  },

  GamePartyListFilterSummonsHide = {
    en    = "Hide summons",
    ptbr  = "Ocultar invocações",
    ptpt  = "Ocultar invocações",
    es419 = "Ocultar invocaciones",
    eses  = "Ocultar invocaciones",
    pl    = "Ukryj przywołania",
    ru    = "Скрыть призывы",
    sv    = "Dölj kallelser",
    nb    = "Skjul innkallinger",
    de    = "Beschwörungen ausblenden",
    nlnl  = "Oproepingen verbergen",
    frfr  = "Masquer les invocations",
    fi    = "Piilota kutsutut olennot",
    it    = "Nascondi evocazioni",
    zhcn  = "隐藏召唤物",
    ja    = "召喚獣を隠す",
    ko    = "소환수 숨기기",
  },

  GamePartyListInviteeLabelTooltip = {
    en    = "Players that did not accept your request yet",
    ptbr  = "Jogadores que ainda não aceitaram seu pedido",
    ptpt  = "Jogadores que ainda não aceitaram seu pedido",
    es419 = "Jugadores que aún no han aceptado tu solicitud",
    eses  = "Jugadores que aún no han aceptado tu solicitud",
    pl    = "Gracze, którzy jeszcze nie zaakceptowali twojej prośby",
    ru    = "Игроки, которые ещё не приняли ваш запрос",
    sv    = "Spelare som ännu inte har accepterat din förfrågan",
    nb    = "Spillere som ennå ikke har godtatt forespørselen din",
    de    = "Spieler, die deine Anfrage noch nicht angenommen haben",
    nlnl  = "Spelers die je verzoek nog niet hebben geaccepteerd",
    frfr  = "Joueurs qui n'ont pas encore accepté votre demande",
    fi    = "Pelaajat, jotka eivät ole vielä hyväksyneet pyyntöäsi",
    it    = "Giocatori che non hanno ancora accettato la tua richiesta",
    zhcn  = "尚未接受你的请求的玩家",
    ja    = "まだあなたの申請を承諾していないプレイヤー",
    ko    = "아직 요청을 수락하지 않은 플레이어",
  },

  GamePartyListPartyLabelTooltip = {
    en    = "Effective party partners and their summons",
    ptbr  = "Parceiros de equipe e suas invocações",
    ptpt  = "Parceiros de equipa e suas invocações",
    es419 = "Compañeros de equipo y sus invocaciones",
    eses  = "Compañeros de equipo y sus invocaciones",
    pl    = "Partnerzy drużyny i ich przywołańcy",
    ru    = "Члены группы и их призванные существа",
    sv    = "Gruppmedlemmar och deras kallelser",
    nb    = "Gruppemedlemmer og deres påkallelser",
    de    = "Teammitglieder und ihre Beschwörungen",
    nlnl  = "Groepsleden en hun oproepingen",
    frfr  = "Membres du groupe et leurs invocations",
    fi    = "Ryhmän jäsenet ja heidän kutsunsa",
    it    = "Compagni di squadra e le loro evocazioni",
    zhcn  = "队伍成员及其召唤物",
    ja    = "パーティーメンバーとその召喚獣",
    ko    = "파티원과 그들의 소환수",
  },

  GamePartyListSortTypeHierarchy = {
    en    = "Hierarchy",
    ptbr  = "Hierarquia",
    ptpt  = "Hierarquia",
    es419 = "Jerarquía",
    eses  = "Jerarquía",
    pl    = "Hierarchia",
    ru    = "Иерархия",
    sv    = "Hierarki",
    nb    = "Hierarki",
    de    = "Hierarchie",
    nlnl  = "Hiërarchie",
    frfr  = "Hiérarchie",
    fi    = "Hierarkia",
    it    = "Gerarchia",
    zhcn  = "层级",
    ja    = "階層",
    ko    = "계층",
  },

  GamePartyListSortTypeDisplayTime = {
    en    = "Display time",
    ptbr  = "Tempo de exibição",
    ptpt  = "Tempo de exibição",
    es419 = "Tiempo de visualización",
    eses  = "Tiempo de visualización",
    pl    = "Czas wyświetlania",
    ru    = "Время отображения",
    sv    = "Visningstid",
    nb    = "Visningstid",
    de    = "Anzeigedauer",
    nlnl  = "Weergavetijd",
    frfr  = "Durée d'affichage",
    fi    = "Näyttöaika",
    it    = "Tempo di visualizzazione",
    zhcn  = "显示时间",
    ja    = "表示時間",
    ko    = "표시 시간",
  },

  GamePartyListSortTypeHitPoints = {
    en    = "Hit points",
    ptbr  = "Pontos de vida",
    ptpt  = "Pontos de vida",
    es419 = "Puntos de vida",
    eses  = "Puntos de vida",
    pl    = "Punkty życia",
    ru    = "Очки здоровья",
    sv    = "Livspoäng",
    nb    = "Livspoeng",
    de    = "Lebenspunkte",
    nlnl  = "Levenspunten",
    frfr  = "Points de vie",
    fi    = "Elämäpisteet",
    it    = "Punti salute",
    zhcn  = "生命值",
    ja    = "体力",
    ko    = "체력",
  },

  GamePartyListSortTypeManaPoints = {
    en    = "Mana points",
    ptbr  = "Pontos de mana",
    ptpt  = "Pontos de mana",
    es419 = "Puntos de maná",
    eses  = "Puntos de maná",
    pl    = "Punkty many",
    ru    = "Очки маны",
    sv    = "Manapoäng",
    nb    = "Manapoeng",
    de    = "Manapunkte",
    nlnl  = "Manapunten",
    frfr  = "Points de mana",
    fi    = "Manapisteet",
    it    = "Punti mana",
    zhcn  = "法力值",
    ja    = "マナポイント",
    ko    = "마나 포인트",
  },

  GamePartyListSortTypeVigorPoints = {
    en    = "Vigor points",
    ptbr  = "Pontos de vigor",
    ptpt  = "Pontos de vigor",
    es419 = "Puntos de vigor",
    eses  = "Puntos de vigor",
    pl    = "Punkty wigoru",
    ru    = "Очки энергии",
    sv    = "Vigorpoäng",
    nb    = "Vigorpoeng",
    de    = "Vigor-Punkte",
    nlnl  = "Vigorpunten",
    frfr  = "Points de vigueur",
    fi    = "Vireyspisteet",
    it    = "Punti vigore",
    zhcn  = "活力点数",
    ja    = "活力ポイント",
    ko    = "활력 포인트",
  },

  GamePartyListSortTypePing = {
    en    = "Ping",
    ptbr  = "Ping",
    ptpt  = "Ping",
    es419 = "Ping",
    eses  = "Ping",
    pl    = "Ping",
    ru    = "Пинг",
    sv    = "Ping",
    nb    = "Ping",
    de    = "Ping",
    nlnl  = "Ping",
    frfr  = "Ping",
    fi    = "Ping",
    it    = "Ping",
    zhcn  = "延迟",
    ja    = "接続遅延",
    ko    = "핑",
  },

  GamePartyListInfoDisableSharedXP = {
    en    = "Disable shared XP",
    ptbr  = "Desativar XP compartilhada",
    ptpt  = "Desativar XP partilhada",
    es419 = "Desactivar XP compartida",
    eses  = "Desactivar XP compartida",
    pl    = "Wyłącz współdzielenie XP",
    ru    = "Отключить общий XP",
    sv    = "Inaktivera delad XP",
    nb    = "Deaktiver delt XP",
    de    = "Geteilte XP deaktivieren",
    nlnl  = "Gedeelde XP uitschakelen",
    frfr  = "Désactiver l'XP partagée",
    fi    = "Poista jaettu XP käytöstä",
    it    = "Disattiva l'XP condivisa",
    zhcn  = "禁用共享XP",
    ja    = "共有XPを無効にする",
    ko    = "공유 XP 비활성화",
  },

  GamePartyListInfoEnableSharedXP = {
    en    = "Enable shared XP",
    ptbr  = "Ativar XP compartilhada",
    ptpt  = "Ativar XP partilhada",
    es419 = "Activar XP compartida",
    eses  = "Activar XP compartida",
    pl    = "Włącz współdzielenie XP",
    ru    = "Включить общий XP",
    sv    = "Aktivera delad XP",
    nb    = "Aktiver delt XP",
    de    = "Geteilte XP aktivieren",
    nlnl  = "Gedeelde XP inschakelen",
    frfr  = "Activer l'XP partagée",
    fi    = "Ota jaettu XP käyttöön",
    it    = "Attiva l'XP condivisa",
    zhcn  = "启用共享XP",
    ja    = "共有XPを有効にする",
    ko    = "공유 XP 활성화",
  },

  GamePartyListInfoLeaveParty = {
    en    = "Leave party",
    ptbr  = "Sair do grupo",
    ptpt  = "Sair do grupo",
    es419 = "Salir del grupo",
    eses  = "Salir del grupo",
    pl    = "Opuść grupę",
    ru    = "Покинуть группу",
    sv    = "Lämna gruppen",
    nb    = "Forlat gruppen",
    de    = "Gruppe verlassen",
    nlnl  = "Groep verlaten",
    frfr  = "Quitter le groupe",
    fi    = "Poistu ryhmästä",
    it    = "Lascia il gruppo",
    zhcn  = "离开队伍",
    ja    = "パーティーを離脱",
    ko    = "파티 탈퇴",
  },

  GamePartyListInfoRevokeInvitation = {
    en    = "Revoke invitation of %s",
    ptbr  = "Revogar convite de %s",
    ptpt  = "Revogar convite de %s",
    es419 = "Revocar la invitación de %s",
    eses  = "Revocar la invitación de %s",
    pl    = "Cofnij zaproszenie dla %s",
    ru    = "Отозвать приглашение у %s",
    sv    = "Återkalla inbjudan till %s",
    nb    = "Trekk tilbake invitasjonen til %s",
    de    = "Einladung von %s widerrufen",
    nlnl  = "Uitnodiging van %s intrekken",
    frfr  = "Révoquer l'invitation de %s",
    fi    = "Peruuta pelaajan %s kutsu",
    it    = "Revoca l'invito di %s",
    zhcn  = "撤销对 %s 的邀请",
    ja    = "%sへの招待を取り消す",
    ko    = "%s의 초대 취소",
  },

  GamePartyListInfoPassLeadership = {
    en    = "Pass leadership to %s",
    ptbr  = "Passar a liderança para %s",
    ptpt  = "Passar a liderança para %s",
    es419 = "Pasar el liderazgo a %s",
    eses  = "Pasar el liderazgo a %s",
    pl    = "Przekaż przywództwo graczowi %s",
    ru    = "Передать лидерство %s",
    sv    = "Överlämna ledarskapet till %s",
    nb    = "Overfør lederskapet til %s",
    de    = "Führung an %s übergeben",
    nlnl  = "Leiderschap aan %s overdragen",
    frfr  = "Transférer le commandement à %s",
    fi    = "Siirrä johtajuus pelaajalle %s",
    it    = "Passa la leadership a %s",
    zhcn  = "将队长职位转给 %s",
    ja    = "%sにリーダー権を渡す",
    ko    = "%s에게 리더십 넘기기",
  },

  GamePartyListInfoCopyName = {
    en    = "Copy name",
    ptbr  = "Copiar nome",
    ptpt  = "Copiar nome",
    es419 = "Copiar nombre",
    eses  = "Copiar nombre",
    pl    = "Skopiuj nazwę",
    ru    = "Копировать имя",
    sv    = "Kopiera namn",
    nb    = "Kopier navn",
    de    = "Namen kopieren",
    nlnl  = "Naam kopiëren",
    frfr  = "Copier le nom",
    fi    = "Kopioi nimi",
    it    = "Copia nome",
    zhcn  = "复制名称",
    ja    = "名前をコピー",
    ko    = "이름 복사",
  },

  GamePartyListInfoOrder = {
    en    = "%s order",
    ptbr  = "Ordem %s",
    ptpt  = "Ordem %s",
    es419 = "Orden %s",
    eses  = "Orden %s",
    pl    = "Kolejność %s",
    ru    = "Порядок %s",
    sv    = "Ordning %s",
    nb    = "Rekkefølge %s",
    de    = "Reihenfolge %s",
    nlnl  = "Volgorde %s",
    frfr  = "Ordre %s",
    fi    = "Järjestys %s",
    it    = "Ordine %s",
    zhcn  = "%s顺序",
    ja    = "%sの順番",
    ko    = "%s 순서",
  },

  GamePartyListInfoNotInParty = {
    en    = "You are not in party.",
    ptbr  = "Você não está em um grupo.",
    ptpt  = "Você não está num grupo.",
    es419 = "No estás en un grupo.",
    eses  = "No estás en un grupo.",
    pl    = "Nie jesteś w grupie.",
    ru    = "Вы не состоите в группе.",
    sv    = "Du är inte med i en grupp.",
    nb    = "Du er ikke med i en gruppe.",
    de    = "Du bist nicht in einer Gruppe.",
    nlnl  = "Je zit niet in een groep.",
    frfr  = "Vous n'êtes pas dans un groupe.",
    fi    = "Et kuulu ryhmään.",
    it    = "Non fai parte di un gruppo.",
    zhcn  = "你不在队伍中。",
    ja    = "パーティーに所属していません。",
    ko    = "파티에 속해 있지 않습니다.",
  },

  GamePartyListInfoNoPartners = {
    en    = "You have no partners in your party yet.",
    ptbr  = "Você ainda não tem parceiros no seu grupo.",
    ptpt  = "Você ainda não tem parceiros no seu grupo.",
    es419 = "Aún no tienes compañeros en tu grupo.",
    eses  = "Aún no tienes compañeros en tu grupo.",
    pl    = "Nie masz jeszcze partnerów w swojej grupie.",
    ru    = "У вас пока нет участников в группе.",
    sv    = "Du har ännu inga medlemmar i din grupp.",
    nb    = "Du har ingen andre medlemmer i gruppen ennå.",
    de    = "Du hast noch keine Partner in deiner Gruppe.",
    nlnl  = "Je hebt nog geen groepsleden.",
    frfr  = "Vous n'avez encore aucun partenaire dans votre groupe.",
    fi    = "Ryhmässäsi ei ole vielä muita jäseniä.",
    it    = "Non hai ancora compagni nel tuo gruppo.",
    zhcn  = "你的队伍中还没有其他成员。",
    ja    = "パーティーにまだメンバーがいません。",
    ko    = "파티에 아직 다른 구성원이 없습니다.",
  },

  GamePartyListInfoSharedExpLevelRange = {
    en    = "The required level range to enable shared experience in the party is between %d and %d.",
    ptbr  = "A faixa de nível necessária para ativar a experiência compartilhada no grupo é entre %d e %d.",
    ptpt  = "A faixa de nível necessária para ativar a experiência compartilhada no grupo é entre %d e %d.",
    es419 = "El rango de nivel necesario para activar la experiencia compartida en el grupo es entre %d y %d.",
    eses  = "El rango de nivel necesario para activar la experiencia compartida en el grupo es entre %d y %d.",
    pl    = "Wymagany zakres poziomów do włączenia wspólnego doświadczenia w grupie wynosi od %d do %d.",
    ru    = "Необходимый диапазон уровней для включения общего опыта в группе — от %d до %d.",
    sv    = "Det nödvändiga nivåintervallet för att aktivera delad erfarenhet i gruppen är mellan %d och %d.",
    nb    = "Det nødvendige nivåintervallet for å aktivere delt erfaring i gruppen er mellom %d og %d.",
    de    = "Der erforderliche Levelbereich zum Aktivieren der geteilten Erfahrung in der Gruppe liegt zwischen %d und %d.",
    nlnl  = "Het vereiste levelbereik om gedeelde ervaring in de groep in te schakelen ligt tussen %d en %d.",
    frfr  = "La plage de niveaux requise pour activer l'expérience partagée dans le groupe est comprise entre %d et %d.",
    fi    = "Jaetun kokemuksen aktivoimiseen ryhmässä vaadittava tasoalue on %d–%d.",
    it    = "L’intervallo di livelli richiesto per attivare l’esperienza condivisa nel gruppo è compreso tra %d e %d.",
    zhcn  = "在队伍中启用共享经验所需的等级范围为 %d 至 %d。",
    ja    = "パーティーで共有経験値を有効にするために必要なレベル範囲は%dから%dです。",
    ko    = "파티에서 공유 경험치를 활성화하는 데 필요한 레벨 범위는 %d에서 %d 사이입니다.",
  },

  GamePartyListTypeLevel = {
    en    = "Type a level.",
    ptbr  = "Digite um nível.",
    ptpt  = "Digite um nível.",
    es419 = "Escribe un nivel.",
    eses  = "Escribe un nivel.",
    pl    = "Wpisz poziom.",
    ru    = "Введите уровень.",
    sv    = "Ange en nivå.",
    nb    = "Skriv inn et nivå.",
    de    = "Gib eine Stufe ein.",
    nlnl  = "Voer een level in.",
    frfr  = "Saisissez un niveau.",
    fi    = "Syötä taso.",
    it    = "Inserisci un livello.",
    zhcn  = "输入等级。",
    ja    = "レベルを入力してください。",
    ko    = "레벨을 입력하세요.",
  },

  GamePartyListTypeLevelForCalculate = {
    en    = "Type a level to calculate the required level range to enable shared experience in the party.",
    ptbr  = "Digite um nível para calcular a faixa de nível necessária para ativar a experiência compartilhada no grupo.",
    ptpt  = "Digite um nível para calcular a faixa de nível necessária para ativar a experiência compartilhada no grupo.",
    es419 = "Escribe un nivel para calcular el rango de nivel necesario para activar la experiencia compartida en el grupo.",
    eses  = "Escribe un nivel para calcular el rango de nivel necesario para activar la experiencia compartida en el grupo.",
    pl    = "Wpisz poziom, aby obliczyć wymagany zakres poziomów do włączenia wspólnego doświadczenia w grupie.",
    ru    = "Введите уровень, чтобы рассчитать необходимый диапазон уровней для включения общего опыта в группе.",
    sv    = "Ange en nivå för att beräkna det nödvändiga nivåintervallet för att aktivera delad erfarenhet i gruppen.",
    nb    = "Skriv inn et nivå for å beregne det nødvendige nivåintervallet for å aktivere delt erfaring i gruppen.",
    de    = "Gib eine Stufe ein, um den erforderlichen Levelbereich zum Aktivieren der geteilten Erfahrung in der Gruppe zu berechnen.",
    nlnl  = "Voer een level in om het vereiste levelbereik voor het inschakelen van gedeelde ervaring in de groep te berekenen.",
    frfr  = "Saisissez un niveau pour calculer la plage de niveaux requise afin d'activer l'expérience partagée dans le groupe.",
    fi    = "Syötä taso laskeaksesi jaetun kokemuksen aktivoimiseen tarvittavan tasoalueen ryhmässä.",
    it    = "Inserisci un livello per calcolare l’intervallo di livelli richiesto per attivare l’esperienza condivisa nel gruppo.",
    zhcn  = "输入等级以计算在队伍中启用共享经验所需的等级范围。",
    ja    = "パーティーで共有経験値を有効にするために必要なレベル範囲を計算するには、レベルを入力してください。",
    ko    = "파티에서 공유 경험치를 활성화하는 데 필요한 레벨 범위를 계산하려면 레벨을 입력하세요.",
  },
})
