-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GamePowersWindowTitle = {
    en    = "Powers",
    ptbr  = "Poderes",
    ptpt  = "Poderes",
    es419 = "Poderes",
    eses  = "Poderes",
    pl    = "Moce",
    ru    = "Силы",
    sv    = "Krafter",
    nb    = "Krefter",
    de    = "Kräfte",
    nlnl  = "Krachten",
    frfr  = "Pouvoirs",
    fi    = "Voimat",
    it    = "Poteri",
    zhcn  = "力量",
    ja    = "パワー",
    ko    = "능력",
  },

  GamePowersButtonInfo = {
    en    = "1. Powers should be used on hotkeys. Open the hotkeys window (%s), select a hotkey row, then drag and drop a power row below into the hotkey slot.\n\n2. Power hotkeys can be pressed and held to boost their potency - this will also increase the mana cost.\n\n3. Some powers require the mouse to be on the game screen to target.\n\nNote: All powers show information according to your character's status. So, your attributes, equipment and other factors can change this information in real time. Also, damage may change according to the target's defense.",
    ptbr  = "1. Poderes devem ser usados nas teclas de atalho. Abra a janela de teclas de atalho (%s), selecione uma linha de atalho, depois arraste e solte uma linha de poder abaixo no slot de atalho.\n\n2. As teclas de atalho de poder podem ser pressionadas e seguradas para aumentar sua potência - isso também aumentará o custo de mana.\n\n3. Alguns poderes precisam do mouse na tela do jogo para mirar.\n\nNota: Todos os poderes mostram informações de acordo com o status do seu personagem. Assim, seus atributos, equipamentos e outros podem alterar essas informações em tempo real. Além disso, os danos podem variar de acordo com a defesa do alvo.",
    ptpt  = "1. Os poderes devem ser usados nas teclas de atalho. Abra a janela de teclas de atalho (%s), selecione uma linha de atalho e, em seguida, arraste e solte uma linha de poder abaixo no espaço da tecla de atalho.\n\n2. As teclas de atalho dos poderes podem ser pressionadas e mantidas para aumentar a sua potência — isto também aumentará o custo de mana.\n\n3. Alguns poderes precisam do rato no ecrã do jogo para apontar.\n\nNota: Todos os poderes apresentam informações de acordo com o estado da sua personagem. Assim, os seus atributos, equipamento e outros fatores podem alterar estas informações em tempo real. Além disso, os danos podem variar de acordo com a defesa do alvo.",
    es419 = "1. Los poderes deben usarse en las teclas de acceso rápido. Abre la ventana de teclas de acceso rápido (%s), selecciona una fila de teclas de acceso rápido y luego arrastra y suelta una fila de poder en el espacio de la tecla de acceso rápido.\n\n2. Las teclas de acceso rápido de los poderes pueden mantenerse presionadas para aumentar su potencia; esto también aumentará el costo de maná.\n\n3. Algunos poderes necesitan que el mouse esté en la pantalla del juego para apuntar.\n\nNota: Todos los poderes muestran información según el estado de tu personaje. Por lo tanto, tus atributos, equipo y otros factores pueden cambiar esta información en tiempo real. Además, el daño puede variar según la defensa del objetivo.",
    eses  = "1. Los poderes deben usarse en las teclas de acceso rápido. Abre la ventana de teclas de acceso rápido (%s), selecciona una fila de teclas de acceso rápido y luego arrastra y suelta una fila de poder en el espacio de la tecla de acceso rápido.\n\n2. Las teclas de acceso rápido de los poderes pueden mantenerse pulsadas para aumentar su potencia; esto también aumentará el coste de maná.\n\n3. Algunos poderes necesitan que el ratón esté en la pantalla del juego para apuntar.\n\nNota: Todos los poderes muestran información según el estado de tu personaje. Por lo tanto, tus atributos, equipo y otros factores pueden cambiar esta información en tiempo real. Además, el daño puede variar según la defensa del objetivo.",
    pl    = "1. Moce powinny być używane za pomocą klawiszy skrótów. Otwórz okno skrótów (%s), wybierz wiersz skrótu, a następnie przeciągnij i upuść poniższy wiersz mocy do miejsca skrótu.\n\n2. Klawisz skrótu mocy można nacisnąć i przytrzymać, aby zwiększyć jej moc — zwiększy to również koszt many.\n\n3. Niektóre moce wymagają umieszczenia myszy na ekranie gry w celu wybrania celu.\n\nUwaga: Wszystkie moce wyświetlają informacje zgodnie ze stanem twojej postaci. Twoje atrybuty, wyposażenie i inne czynniki mogą zmieniać te informacje w czasie rzeczywistym. Obrażenia mogą również zmieniać się w zależności od obrony celu.",
    ru    = "1. Силы следует использовать с помощью горячих клавиш. Откройте окно горячих клавиш (%s), выберите строку горячей клавиши, затем перетащите строку силы ниже в слот горячей клавиши.\n\n2. Горячую клавишу силы можно нажать и удерживать, чтобы увеличить её мощность — это также увеличит расход маны.\n\n3. Для некоторых сил необходимо навести мышь на экран игры, чтобы выбрать цель.\n\nПримечание: Все силы отображают информацию в соответствии с состоянием вашего персонажа. Поэтому ваши характеристики, экипировка и другие факторы могут изменять эту информацию в реальном времени. Кроме того, урон может изменяться в зависимости от защиты цели.",
    sv    = "1. Krafter bör användas med snabbknappar. Öppna snabbknappsfönstret (%s), välj en snabbknappsruta och dra sedan en kraftrad nedan till snabbknappsplatsen.\n\n2. Kraftens snabbknapp kan tryckas ned och hållas inne för att öka dess styrka — detta ökar även manakostnaden.\n\n3. Vissa krafter kräver att musen är på spelskärmen för att välja mål.\n\nObservera: Alla krafter visar information utifrån din karaktärs status. Dina attribut, din utrustning och andra faktorer kan ändra denna information i realtid. Skadan kan också variera beroende på målets försvar.",
    nb    = "1. Krefter bør brukes med hurtigtaster. Åpne hurtigtastvinduet (%s), velg en hurtigtastrad, og dra og slipp deretter en kraftrad nedenfor til hurtigtastplassen.\n\n2. Hurtigtasten for en kraft kan trykkes og holdes inne for å øke kraftens styrke — dette øker også manakostnaden.\n\n3. Noen krefter krever at musen er på spillskjermen for å velge mål.\n\nMerk: Alle krefter viser informasjon basert på karakterens status. Attributtene, utstyret og andre faktorer kan endre denne informasjonen i sanntid. Skaden kan også variere avhengig av målets forsvar.",
    de    = "1. Kräfte sollten über Hotkeys verwendet werden. Öffnen Sie das Hotkey-Fenster (%s), wählen Sie eine Hotkey-Zeile aus und ziehen Sie anschließend eine Kraftzeile von unten in den Hotkey-Slot.\n\n2. Kraft-Hotkeys können gedrückt gehalten werden, um ihre Stärke zu erhöhen — dadurch steigen auch die Manakosten.\n\n3. Bei einigen Kräften muss sich die Maus auf dem Spielbildschirm befinden, um ein Ziel auszuwählen.\n\nHinweis: Alle Kräfte zeigen Informationen entsprechend dem Status Ihres Charakters an. Ihre Attribute, Ausrüstung und andere Faktoren können diese Informationen in Echtzeit verändern. Auch der Schaden kann je nach Verteidigung des Ziels variieren.",
    nlnl  = "1. Krachten moeten met sneltoetsen worden gebruikt. Open het sneltoetsvenster (%s), selecteer een sneltoetsrij en sleep vervolgens een krachtregel hieronder naar de sneltoetspositie.\n\n2. Een sneltoets voor een kracht kan ingedrukt worden gehouden om de kracht ervan te verhogen; dit verhoogt ook de manakosten.\n\n3. Voor sommige krachten moet de muis zich op het spelscherm bevinden om een doelwit te kiezen.\n\nLet op: Alle krachten tonen informatie op basis van de status van je personage. Je attributen, uitrusting en andere factoren kunnen deze informatie in realtime wijzigen. Ook kan de schade variëren afhankelijk van de verdediging van het doelwit.",
    frfr  = "1. Les pouvoirs doivent être utilisés avec des raccourcis clavier. Ouvrez la fenêtre des raccourcis (%s), sélectionnez une ligne de raccourci, puis faites glisser une ligne de pouvoir ci-dessous vers l'emplacement du raccourci.\n\n2. Les raccourcis des pouvoirs peuvent être maintenus enfoncés pour augmenter leur puissance ; cela augmente également le coût en mana.\n\n3. Certains pouvoirs nécessitent que la souris soit sur l'écran de jeu pour viser.\n\nRemarque : Tous les pouvoirs affichent des informations en fonction de l'état de votre personnage. Vos attributs, votre équipement et d'autres facteurs peuvent modifier ces informations en temps réel. Les dégâts peuvent également varier en fonction de la défense de la cible.",
    fi    = "1. Voimia tulee käyttää pikanäppäimillä. Avaa pikanäppäinikkuna (%s), valitse pikanäppäinrivi ja vedä ja pudota sitten alla oleva voimarivi pikanäppäinpaikkaan.\n\n2. Voiman pikanäppäintä voi painaa ja pitää painettuna voiman tehon lisäämiseksi — tämä lisää myös manan kulutusta.\n\n3. Jotkin voimat edellyttävät, että hiiri on peliruudulla kohteen valitsemista varten.\n\nHuomautus: Kaikki voimat näyttävät tietoja hahmosi tilan perusteella. Ominaisuutesi, varusteesi ja muut tekijät voivat muuttaa näitä tietoja reaaliajassa. Myös vahinko voi vaihdella kohteen puolustuksen mukaan.",
    it    = "1. I poteri devono essere usati tramite i tasti di scelta rapida. Apri la finestra dei tasti di scelta rapida (%s), seleziona una riga di tasti di scelta rapida, quindi trascina e rilascia una riga del potere nello slot del tasto di scelta rapida.\n\n2. Il tasto di scelta rapida di un potere può essere premuto e tenuto premuto per aumentarne la potenza; questo aumenterà anche il costo in mana.\n\n3. Alcuni poteri richiedono che il mouse si trovi sullo schermo di gioco per mirare.\n\nNota: Tutti i poteri mostrano informazioni in base allo stato del tuo personaggio. I tuoi attributi, l'equipaggiamento e altri fattori possono modificare queste informazioni in tempo reale. Inoltre, i danni possono variare in base alla difesa del bersaglio.",
    zhcn  = "1. 力量应通过快捷键使用。打开快捷键窗口（%s），选择一个快捷键行，然后将下方的力量行拖放到快捷键槽中。\n\n2. 可以按住力量快捷键来提高其威力，这也会增加法力消耗。\n\n3. 一些力量需要将鼠标放在游戏画面上才能进行瞄准。\n\n注意：所有力量都会根据你角色的状态显示信息。因此，你的属性、装备和其他因素可能会实时改变这些信息。此外，伤害可能会根据目标的防御力而变化。",
    ja    = "1. パワーはホットキーで使用します。ホットキーウィンドウ（%s）を開き、ホットキーの行を選択してから、下にあるパワーの行をホットキースロットへドラッグ＆ドロップしてください。\n\n2. パワーのホットキーを押し続けると威力が上がります。これによりマナ消費量も増加します。\n\n3. 一部のパワーでは、対象を指定するためにゲーム画面上にマウスを置く必要があります。\n\n注意：すべてのパワーは、キャラクターの状態に応じた情報を表示します。そのため、属性や装備などによって情報がリアルタイムで変化する場合があります。また、ダメージは対象の防御力によって変化する場合があります。",
    ko    = "1. 능력은 단축키로 사용해야 합니다. 단축키 창(%s)을 열고 단축키 행을 선택한 다음, 아래의 능력 행을 단축키 슬롯으로 끌어다 놓으세요.\n\n2. 능력 단축키를 누른 채 유지하면 위력이 증가하며, 마나 소모량도 증가합니다.\n\n3. 일부 능력은 대상을 지정하려면 게임 화면에 마우스를 올려야 합니다.\n\n참고: 모든 능력은 캐릭터의 상태에 따라 정보를 표시합니다. 따라서 속성, 장비 및 기타 요소에 따라 이 정보가 실시간으로 변경될 수 있습니다. 또한 피해량은 대상의 방어력에 따라 달라질 수 있습니다.",
  },

  GamePowersTabOffensiveShow = {
    en    = "Show offensive powers",
    ptbr  = "Exibir poderes ofensivos",
    ptpt  = "Exibir poderes ofensivos",
    es419 = "Mostrar poderes ofensivos",
    eses  = "Mostrar poderes ofensivos",
    pl    = "Pokaż moce ofensywne",
    ru    = "Показывать атакующие силы",
    sv    = "Visa offensiva krafter",
    nb    = "Vis offensive krefter",
    de    = "Offensive Kräfte anzeigen",
    nlnl  = "Offensieve krachten tonen",
    frfr  = "Afficher les pouvoirs offensifs",
    fi    = "Näytä hyökkäysvoimat",
    it    = "Mostra poteri offensivi",
    zhcn  = "显示攻击力量",
    ja    = "攻撃パワーを表示",
    ko    = "공격 능력 표시",
  },

  GamePowersTabOffensiveHide = {
    en    = "Hide offensive powers",
    ptbr  = "Ocultar poderes ofensivos",
    ptpt  = "Ocultar poderes ofensivos",
    es419 = "Ocultar poderes ofensivos",
    eses  = "Ocultar poderes ofensivos",
    pl    = "Ukryj moce ofensywne",
    ru    = "Скрывать атакующие силы",
    sv    = "Dölj offensiva krafter",
    nb    = "Skjul offensive krefter",
    de    = "Offensive Kräfte verbergen",
    nlnl  = "Offensieve krachten verbergen",
    frfr  = "Masquer les pouvoirs offensifs",
    fi    = "Piilota hyökkäysvoimat",
    it    = "Nascondi poteri offensivi",
    zhcn  = "隐藏攻击力量",
    ja    = "攻撃パワーを隠す",
    ko    = "공격 능력 숨기기",
  },

  GamePowersTabDefensiveShow = {
    en    = "Show defensive powers",
    ptbr  = "Exibir poderes defensivos",
    ptpt  = "Exibir poderes defensivos",
    es419 = "Mostrar poderes defensivos",
    eses  = "Mostrar poderes defensivos",
    pl    = "Pokaż moce defensywne",
    ru    = "Показывать защитные силы",
    sv    = "Visa defensiva krafter",
    nb    = "Vis defensive krefter",
    de    = "Defensive Kräfte anzeigen",
    nlnl  = "Defensieve krachten tonen",
    frfr  = "Afficher les pouvoirs défensifs",
    fi    = "Näytä puolustusvoimat",
    it    = "Mostra poteri difensivi",
    zhcn  = "显示防御力量",
    ja    = "防御パワーを表示",
    ko    = "방어 능력 표시",
  },

  GamePowersTabDefensiveHide = {
    en    = "Hide defensive powers",
    ptbr  = "Ocultar poderes defensivos",
    ptpt  = "Ocultar poderes defensivos",
    es419 = "Ocultar poderes defensivos",
    eses  = "Ocultar poderes defensivos",
    pl    = "Ukryj moce defensywne",
    ru    = "Скрывать защитные силы",
    sv    = "Dölj defensiva krafter",
    nb    = "Skjul defensive krefter",
    de    = "Defensive Kräfte verbergen",
    nlnl  = "Defensieve krachten verbergen",
    frfr  = "Masquer les pouvoirs défensifs",
    fi    = "Piilota puolustusvoimat",
    it    = "Nascondi poteri difensivi",
    zhcn  = "隐藏防御力量",
    ja    = "防御パワーを隠す",
    ko    = "방어 능력 숨기기",
  },

  GamePowersTabNonPremiumShow = {
    en    = "Show non premium powers",
    ptbr  = "Exibir poderes não premium",
    ptpt  = "Exibir poderes não premium",
    es419 = "Mostrar poderes no premium",
    eses  = "Mostrar poderes no premium",
    pl    = "Pokaż moce niepremium",
    ru    = "Показывать непремиальные силы",
    sv    = "Visa icke-premiumkrafter",
    nb    = "Vis ikke-premiumkrefter",
    de    = "Nicht-Premium-Kräfte anzeigen",
    nlnl  = "Niet-premiumkrachten tonen",
    frfr  = "Afficher les pouvoirs non premium",
    fi    = "Näytä ei-premium-voimat",
    it    = "Mostra poteri non premium",
    zhcn  = "显示非高级力量",
    ja    = "非プレミアムパワーを表示",
    ko    = "비프리미엄 능력 표시",
  },

  GamePowersTabNonPremiumHide = {
    en    = "Hide non premium powers",
    ptbr  = "Ocultar poderes não premium",
    ptpt  = "Ocultar poderes não premium",
    es419 = "Ocultar poderes no premium",
    eses  = "Ocultar poderes no premium",
    pl    = "Ukryj moce niepremium",
    ru    = "Скрывать непремиальные силы",
    sv    = "Dölj icke-premiumkrafter",
    nb    = "Skjul ikke-premiumkrefter",
    de    = "Nicht-Premium-Kräfte verbergen",
    nlnl  = "Niet-premiumkrachten verbergen",
    frfr  = "Masquer les pouvoirs non premium",
    fi    = "Piilota ei-premium-voimat",
    it    = "Nascondi poteri non premium",
    zhcn  = "隐藏非高级力量",
    ja    = "非プレミアムパワーを隠す",
    ko    = "비프리미엄 능력 숨기기",
  },

  GamePowersTabPremiumShow = {
    en    = "Show premium powers",
    ptbr  = "Exibir poderes premium",
    ptpt  = "Exibir poderes premium",
    es419 = "Mostrar poderes premium",
    eses  = "Mostrar poderes premium",
    pl    = "Pokaż moce premium",
    ru    = "Показывать премиальные силы",
    sv    = "Visa premiumkrafter",
    nb    = "Vis premiumkrefter",
    de    = "Premium-Kräfte anzeigen",
    nlnl  = "Premiumkrachten tonen",
    frfr  = "Afficher les pouvoirs premium",
    fi    = "Näytä premium-voimat",
    it    = "Mostra poteri premium",
    zhcn  = "显示高级力量",
    ja    = "プレミアムパワーを表示",
    ko    = "프리미엄 능력 표시",
  },

  GamePowersTabPremiumHide = {
    en    = "Hide premium powers",
    ptbr  = "Ocultar poderes premium",
    ptpt  = "Ocultar poderes premium",
    es419 = "Ocultar poderes premium",
    eses  = "Ocultar poderes premium",
    pl    = "Ukryj moce premium",
    ru    = "Скрывать премиальные силы",
    sv    = "Dölj premiumkrafter",
    nb    = "Skjul premiumkrefter",
    de    = "Premium-Kräfte verbergen",
    nlnl  = "Premiumkrachten verbergen",
    frfr  = "Masquer les pouvoirs premium",
    fi    = "Piilota premium-voimat",
    it    = "Nascondi poteri premium",
    zhcn  = "隐藏高级力量",
    ja    = "プレミアムパワーを隠す",
    ko    = "프리미엄 능력 숨기기",
  },

  GamePowersInfoOrder = {
    en    = "%s order",
    ptbr  = "Ordem %s",
    ptpt  = "Ordem %s",
    es419 = "Orden %s",
    eses  = "Orden %s",
    pl    = "Kolejność %s",
    ru    = "Порядок %s",
    sv    = "Ordning %s",
    nb    = "Rekkefølge %s",
    de    = "Reihenfolge %s",
    nlnl  = "Volgorde %s",
    frfr  = "Ordre %s",
    fi    = "Järjestys %s",
    it    = "Ordine %s",
    zhcn  = "%s 顺序",
    ja    = "%sの順序",
    ko    = "%s 순서",
  },

  GamePowersInfoPowerListUpdated = {
    en    = "Your power list has been updated.",
    ptbr  = "Sua lista de poderes foi atualizada.",
    ptpt  = "A sua lista de poderes foi atualizada.",
    es419 = "Tu lista de poderes ha sido actualizada.",
    eses  = "Tu lista de poderes ha sido actualizada.",
    pl    = "Twoja lista mocy została zaktualizowana.",
    ru    = "Ваш список сил был обновлён.",
    sv    = "Din lista över krafter har uppdaterats.",
    nb    = "Listen over kreftene dine har blitt oppdatert.",
    de    = "Ihre Liste der Kräfte wurde aktualisiert.",
    nlnl  = "Je lijst met krachten is bijgewerkt.",
    frfr  = "Votre liste de pouvoirs a été mise à jour.",
    fi    = "Voimaluettelosi on päivitetty.",
    it    = "La tua lista dei poteri è stata aggiornata.",
    zhcn  = "你的力量列表已更新。",
    ja    = "パワー一覧が更新されました。",
    ko    = "능력 목록이 업데이트되었습니다.",
  },
})
