-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameVipListWindowTitle = {
    en    = "Contacts",
    ptbr  = "Contatos",
    ptpt  = "Contactos",
    es419 = "Contactos",
    eses  = "Contactos",
    pl    = "Kontakty",
    ru    = "Контакты",
    sv    = "Kontakter",
    nb    = "Kontakter",
    de    = "Kontakte",
    nlnl  = "Contacten",
    frfr  = "Contacts",
    fi    = "Yhteystiedot",
    it    = "Contatti",
    zhcn  = "联系人",
    ja    = "連絡先",
    ko    = "연락처",
  },

  GameVipListWindowTitleAdd = {
    en    = "Add to contacts",
    ptbr  = "Adicionar aos contatos",
    ptpt  = "Adicionar aos contactos",
    es419 = "Añadir a los contactos",
    eses  = "Añadir a los contactos",
    pl    = "Dodaj do kontaktów",
    ru    = "Добавить в контакты",
    sv    = "Lägg till i kontakter",
    nb    = "Legg til i kontakter",
    de    = "Zu Kontakten hinzufügen",
    nlnl  = "Aan contacten toevoegen",
    frfr  = "Ajouter aux contacts",
    fi    = "Lisää yhteystietoihin",
    it    = "Aggiungi ai contatti",
    zhcn  = "添加到联系人",
    ja    = "連絡先に追加",
    ko    = "연락처에 추가",
  },

  GameVipListInfoCharName = {
    en    = "Character name",
    ptbr  = "Nome do personagem",
    ptpt  = "Nome do personagem",
    es419 = "Nombre del personaje",
    eses  = "Nombre del personaje",
    pl    = "Nazwa postaci",
    ru    = "Имя персонажа",
    sv    = "Karaktärsnamn",
    nb    = "Figurnavn",
    de    = "Charaktername",
    nlnl  = "Naam van personage",
    frfr  = "Nom du personnage",
    fi    = "Hahmon nimi",
    it    = "Nome del personaggio",
    zhcn  = "角色名称",
    ja    = "キャラクター名",
    ko    = "캐릭터 이름",
  },

  GameVipListWindowTitleEdit = {
    en    = "Edit contacts",
    ptbr  = "Editar contatos",
    ptpt  = "Editar contactos",
    es419 = "Editar contactos",
    eses  = "Editar contactos",
    pl    = "Edytuj kontakty",
    ru    = "Редактировать контакты",
    sv    = "Redigera kontakter",
    nb    = "Rediger kontakter",
    de    = "Kontakte bearbeiten",
    nlnl  = "Contacten bewerken",
    frfr  = "Modifier les contacts",
    fi    = "Muokkaa yhteystietoja",
    it    = "Modifica contatti",
    zhcn  = "编辑联系人",
    ja    = "連絡先を編集",
    ko    = "연락처 편집",
  },

  GameVipListInfoNotifyLogin = {
    en    = "Notify login",
    ptbr  = "Notificar login",
    ptpt  = "Notificar início de sessão",
    es419 = "Notificar inicio de sesión",
    eses  = "Notificar inicio de sesión",
    pl    = "Powiadamiaj o logowaniu",
    ru    = "Уведомлять о входе",
    sv    = "Meddela vid inloggning",
    nb    = "Varsle om innlogging",
    de    = "Bei Anmeldung benachrichtigen",
    nlnl  = "Melden bij inloggen",
    frfr  = "Notifier la connexion",
    fi    = "Ilmoita kirjautumisesta",
    it    = "Notifica accesso",
    zhcn  = "通知登录",
    ja    = "ログインを通知",
    ko    = "로그인 알림",
  },

  GameVipListInfoPlayerLoggedIn = {
    en    = "%s has logged in.",
    ptbr  = "%s fez login.",
    ptpt  = "%s fez início de sessão.",
    es419 = "%s ha iniciado sesión.",
    eses  = "%s ha iniciado sesión.",
    pl    = "%s zalogował się.",
    ru    = "%s вошёл в игру.",
    sv    = "%s har loggat in.",
    nb    = "%s har logget inn.",
    de    = "%s hat sich angemeldet.",
    nlnl  = "%s is ingelogd.",
    frfr  = "%s s'est connecté.",
    fi    = "%s kirjautui sisään.",
    it    = "%s ha effettuato l’accesso.",
    zhcn  = "%s 已登录。",
    ja    = "%sがログインしました。",
    ko    = "%s님이 로그인했습니다.",
  },

  GameVipListInfoPlayerLoggedOut = {
    en    = "%s has logged out.",
    ptbr  = "%s saiu.",
    ptpt  = "%s saiu.",
    es419 = "%s ha cerrado sesión.",
    eses  = "%s ha cerrado sesión.",
    pl    = "%s wylogował się.",
    ru    = "%s вышел из игры.",
    sv    = "%s har loggat ut.",
    nb    = "%s har logget ut.",
    de    = "%s hat sich abgemeldet.",
    nlnl  = "%s is uitgelogd.",
    frfr  = "%s s'est déconnecté.",
    fi    = "%s kirjautui ulos.",
    it    = "%s si è disconnesso.",
    zhcn  = "%s 已退出登录。",
    ja    = "%sがログアウトしました。",
    ko    = "%s님이 로그아웃했습니다.",
  },

  GameVipListContextMenuAddVip = {
    en    = "Add new contact",
    ptbr  = "Adicionar novo contato",
    ptpt  = "Adicionar novo VIP",
    es419 = "Agregar nuevo contacto",
    eses  = "Agregar nuevo contacto",
    pl    = "Dodaj nowy kontakt",
    ru    = "Добавить новый контакт",
    sv    = "Lägg till ny kontakt",
    nb    = "Legg til ny kontakt",
    de    = "Neuen Kontakt hinzufügen",
    nlnl  = "Nieuw contact toevoegen",
    frfr  = "Ajouter un nouveau contact",
    fi    = "Lisää uusi yhteystieto",
    it    = "Aggiungi nuovo contatto",
    zhcn  = "添加新联系人",
    ja    = "新しい連絡先を追加",
    ko    = "새 연락처 추가",
  },

  GameVipListContextMenuOfflineHide = {
    en    = "Hide offline",
    ptbr  = "Ocultar offline",
    ptpt  = "Ocultar offline",
    es419 = "Ocultar desconectados",
    eses  = "Ocultar desconectados",
    pl    = "Ukryj osoby offline",
    ru    = "Скрыть офлайн",
    sv    = "Dölj offline",
    nb    = "Skjul offline",
    de    = "Offline ausblenden",
    nlnl  = "Offline verbergen",
    frfr  = "Masquer les personnes hors ligne",
    fi    = "Piilota offline olevat",
    it    = "Nascondi offline",
    zhcn  = "隐藏离线用户",
    ja    = "オフラインを非表示",
    ko    = "오프라인 숨기기",
  },

  GameVipListContextMenuOfflineShow = {
    en    = "Show offline",
    ptbr  = "Exibir offline",
    ptpt  = "Exibir offline",
    es419 = "Mostrar desconectados",
    eses  = "Mostrar desconectados",
    pl    = "Pokaż osoby offline",
    ru    = "Показать офлайн",
    sv    = "Visa offline",
    nb    = "Vis offline",
    de    = "Offline anzeigen",
    nlnl  = "Offline tonen",
    frfr  = "Afficher les personnes hors ligne",
    fi    = "Näytä offline olevat",
    it    = "Mostra offline",
    zhcn  = "显示离线用户",
    ja    = "オフラインを表示",
    ko    = "오프라인 표시",
  },

  GameVipListContextMenuSendMsg = {
    en    = "Send message",
    ptbr  = "Enviar mensagem",
    ptpt  = "Enviar mensagem",
    es419 = "Enviar mensaje",
    eses  = "Enviar mensaje",
    pl    = "Wyślij wiadomość",
    ru    = "Отправить сообщение",
    sv    = "Skicka meddelande",
    nb    = "Send melding",
    de    = "Nachricht senden",
    nlnl  = "Bericht verzenden",
    frfr  = "Envoyer un message",
    fi    = "Lähetä viesti",
    it    = "Invia messaggio",
    zhcn  = "发送消息",
    ja    = "メッセージを送信",
    ko    = "메시지 보내기",
  },

  GameVipListContextMenuVipAdd = {
    en    = "Add new contact",
    ptbr  = "Adicionar novo contato",
    ptpt  = "Adicionar novo VIP",
    es419 = "Agregar nuevo contacto",
    eses  = "Agregar nuevo contacto",
    pl    = "Dodaj nowy kontakt",
    ru    = "Добавить новый контакт",
    sv    = "Lägg till ny kontakt",
    nb    = "Legg til ny kontakt",
    de    = "Neuen Kontakt hinzufügen",
    nlnl  = "Nieuw contact toevoegen",
    frfr  = "Ajouter un nouveau contact",
    fi    = "Lisää uusi yhteystieto",
    it    = "Aggiungi nuovo contatto",
    zhcn  = "添加新联系人",
    ja    = "新しい連絡先を追加",
    ko    = "새 연락처 추가",
  },

  GameVipListContextMenuVipEdit = {
    en    = "Edit %s",
    ptbr  = "Editar %s",
    ptpt  = "Editar %s",
    es419 = "Editar %s",
    eses  = "Editar %s",
    pl    = "Edytuj %s",
    ru    = "Изменить %s",
    sv    = "Redigera %s",
    nb    = "Rediger %s",
    de    = "%s bearbeiten",
    nlnl  = "%s bewerken",
    frfr  = "Modifier %s",
    fi    = "Muokkaa %s",
    it    = "Modifica %s",
    zhcn  = "编辑 %s",
    ja    = "%sを編集",
    ko    = "%s 편집",
  },

  GameVipListContextMenuVipRemove = {
    en    = "Remove %s",
    ptbr  = "Remover %s",
    ptpt  = "Remover %s",
    es419 = "Eliminar %s",
    eses  = "Eliminar %s",
    pl    = "Usuń %s",
    ru    = "Удалить %s",
    sv    = "Ta bort %s",
    nb    = "Fjern %s",
    de    = "%s entfernen",
    nlnl  = "%s verwijderen",
    frfr  = "Supprimer %s",
    fi    = "Poista %s",
    it    = "Rimuovi %s",
    zhcn  = "移除 %s",
    ja    = "%sを削除",
    ko    = "%s 삭제",
  },

  GameVipListContextMenuCopyName = {
    en    = "Copy name",
    ptbr  = "Copiar nome",
    ptpt  = "Copiar nome",
    es419 = "Copiar nombre",
    eses  = "Copiar nombre",
    pl    = "Kopiuj nazwę",
    ru    = "Копировать имя",
    sv    = "Kopiera namn",
    nb    = "Kopier navn",
    de    = "Namen kopieren",
    nlnl  = "Naam kopiëren",
    frfr  = "Copier le nom",
    fi    = "Kopioi nimi",
    it    = "Copia nome",
    zhcn  = "复制名称",
    ja    = "名前をコピー",
    ko    = "이름 복사",
  },

  GameVipListContextMenuPrivateChatInvite = {
    en    = "Invite to private chat",
    ptbr  = "Convidar para bate-papo privado",
    ptpt  = "Convidar para bate-papo privado",
    es419 = "Invitar a chat privado",
    eses  = "Invitar a chat privado",
    pl    = "Zaproś do prywatnego czatu",
    ru    = "Пригласить в приватный чат",
    sv    = "Bjud in till privat chatt",
    nb    = "Inviter til privat chat",
    de    = "Zum privaten Chat einladen",
    nlnl  = "Uitnodigen voor privéchat",
    frfr  = "Inviter à une discussion privée",
    fi    = "Kutsu yksityiseen keskusteluun",
    it    = "Invita alla chat privata",
    zhcn  = "邀请加入私聊",
    ja    = "プライベートチャットに招待",
    ko    = "비공개 채팅에 초대",
  },

  GameVipListContextMenuPrivateChatExclude = {
    en    = "Exclude from private chat",
    ptbr  = "Excluir do bate-papo privado",
    ptpt  = "Excluir do bate-papo privado",
    es419 = "Excluir del chat privado",
    eses  = "Excluir del chat privado",
    pl    = "Wyklucz z prywatnego czatu",
    ru    = "Исключить из личного чата",
    sv    = "Exkludera från privat chatt",
    nb    = "Ekskluder fra privat chat",
    de    = "Vom privaten Chat ausschließen",
    nlnl  = "Uit privéchat verwijderen",
    frfr  = "Exclure de la discussion privée",
    fi    = "Poista yksityisestä chatista",
    it    = "Escludi dalla chat privata",
    zhcn  = "从私聊中排除",
    ja    = "プライベートチャットから除外",
    ko    = "비공개 채팅에서 제외",
  },

  GameVipListGroupNoGroup = {
    en    = "No group",
    ptbr  = "Sem grupo",
    ptpt  = "Sem grupo",
    es419 = "Sin grupo",
    eses  = "Sin grupo",
    pl    = "Brak grupy",
    ru    = "Нет группы",
    sv    = "Ingen grupp",
    nb    = "Ingen gruppe",
    de    = "Keine Gruppe",
    nlnl  = "Geen groep",
    frfr  = "Aucun groupe",
    fi    = "Ei ryhmää",
    it    = "Nessun gruppo",
    zhcn  = "无群组",
    ja    = "グループなし",
    ko    = "그룹 없음",
  },

  GameVipListContextMenuGroupAdd = {
    en    = "Add new group",
    ptbr  = "Adicionar novo grupo",
    ptpt  = "Adicionar novo grupo",
    es419 = "Agregar nuevo grupo",
    eses  = "Agregar nuevo grupo",
    pl    = "Dodaj nową grupę",
    ru    = "Добавить новую группу",
    sv    = "Lägg till ny grupp",
    nb    = "Legg til ny gruppe",
    de    = "Neue Gruppe hinzufügen",
    nlnl  = "Nieuwe groep toevoegen",
    frfr  = "Ajouter un nouveau groupe",
    fi    = "Lisää uusi ryhmä",
    it    = "Aggiungi nuovo gruppo",
    zhcn  = "添加新群组",
    ja    = "新しいグループを追加",
    ko    = "새 그룹 추가",
  },

  GameVipListContextMenuGroupShow = {
    en    = "Show groups",
    ptbr  = "Exibir grupos",
    ptpt  = "Exibir grupos",
    es419 = "Mostrar grupos",
    eses  = "Mostrar grupos",
    pl    = "Pokaż grupy",
    ru    = "Показывать группы",
    sv    = "Visa grupper",
    nb    = "Vis grupper",
    de    = "Gruppen anzeigen",
    nlnl  = "Groepen tonen",
    frfr  = "Afficher les groupes",
    fi    = "Näytä ryhmät",
    it    = "Mostra gruppi",
    zhcn  = "显示群组",
    ja    = "グループを表示",
    ko    = "그룹 표시",
  },

  GameVipListContextMenuGroupHide = {
    en    = "Hide groups",
    ptbr  = "Ocultar grupos",
    ptpt  = "Ocultar grupos",
    es419 = "Ocultar grupos",
    eses  = "Ocultar grupos",
    pl    = "Ukryj grupy",
    ru    = "Скрыть группы",
    sv    = "Dölj grupper",
    nb    = "Skjul grupper",
    de    = "Gruppen ausblenden",
    nlnl  = "Groepen verbergen",
    frfr  = "Masquer les groupes",
    fi    = "Piilota ryhmät",
    it    = "Nascondi gruppi",
    zhcn  = "隐藏群组",
    ja    = "グループを隠す",
    ko    = "그룹 숨기기",
  },

  GameVipListContextMenuGroupEdit = {
    en    = "Edit group",
    ptbr  = "Editar grupo",
    ptpt  = "Editar grupo",
    es419 = "Editar grupo",
    eses  = "Editar grupo",
    pl    = "Edytuj grupę",
    ru    = "Изменить группу",
    sv    = "Redigera grupp",
    nb    = "Rediger gruppe",
    de    = "Gruppe bearbeiten",
    nlnl  = "Groep bewerken",
    frfr  = "Modifier le groupe",
    fi    = "Muokkaa ryhmää",
    it    = "Modifica gruppo",
    zhcn  = "编辑群组",
    ja    = "グループを編集",
    ko    = "그룹 편집",
  },

  GameVipListContextMenuGroupRemove = {
    en    = "Remove group",
    ptbr  = "Remover grupo",
    ptpt  = "Remover grupo",
    es419 = "Eliminar grupo",
    eses  = "Eliminar grupo",
    pl    = "Usuń grupę",
    ru    = "Удалить группу",
    sv    = "Ta bort grupp",
    nb    = "Fjern gruppe",
    de    = "Gruppe entfernen",
    nlnl  = "Groep verwijderen",
    frfr  = "Supprimer le groupe",
    fi    = "Poista ryhmä",
    it    = "Rimuovi gruppo",
    zhcn  = "移除群组",
    ja    = "グループを削除",
    ko    = "그룹 삭제",
  },

  GameVipListGroupInfoTitle = {
    en    = "Groups",
    ptbr  = "Grupos",
    ptpt  = "Grupos",
    es419 = "Grupos",
    eses  = "Grupos",
    pl    = "Grupy",
    ru    = "Группы",
    sv    = "Grupper",
    nb    = "Grupper",
    de    = "Gruppen",
    nlnl  = "Groepen",
    frfr  = "Groupes",
    fi    = "Ryhmät",
    it    = "Gruppi",
    zhcn  = "群组",
    ja    = "グループ",
    ko    = "그룹",
  },

  GameVipListGroupInfoLimitReached = {
    en    = "You have reached the maximum number of groups.",
    ptbr  = "Você atingiu o número máximo de grupos.",
    ptpt  = "Você atingiu o número máximo de grupos.",
    es419 = "Has alcanzado el número máximo de grupos.",
    eses  = "Has alcanzado el número máximo de grupos.",
    pl    = "Osiągnięto maksymalną liczbę grup.",
    ru    = "Вы достигли максимального количества групп.",
    sv    = "Du har nått det maximala antalet grupper.",
    nb    = "Du har nådd det maksimale antallet grupper.",
    de    = "Du hast die maximale Anzahl an Gruppen erreicht.",
    nlnl  = "Je hebt het maximale aantal groepen bereikt.",
    frfr  = "Vous avez atteint le nombre maximal de groupes.",
    fi    = "Olet saavuttanut ryhmien enimmäismäärän.",
    it    = "Hai raggiunto il numero massimo di gruppi.",
    zhcn  = "你已达到群组数量上限。",
    ja    = "グループ数の上限に達しました。",
    ko    = "그룹 수가 최대치에 도달했습니다.",
  },

  GameVipListGroupWindowTitleAdd = {
    en    = "Add group",
    ptbr  = "Adicionar grupo",
    ptpt  = "Adicionar grupo",
    es419 = "Agregar grupo",
    eses  = "Agregar grupo",
    pl    = "Dodaj grupę",
    ru    = "Добавить группу",
    sv    = "Lägg till grupp",
    nb    = "Legg til gruppe",
    de    = "Gruppe hinzufügen",
    nlnl  = "Groep toevoegen",
    frfr  = "Ajouter un groupe",
    fi    = "Lisää ryhmä",
    it    = "Aggiungi gruppo",
    zhcn  = "添加群组",
    ja    = "グループを追加",
    ko    = "그룹 추가",
  },

  GameVipListGroupWindowTitleEdit = {
    en    = "Edit group",
    ptbr  = "Editar grupo",
    ptpt  = "Editar grupo",
    es419 = "Editar grupo",
    eses  = "Editar grupo",
    pl    = "Edytuj grupę",
    ru    = "Изменить группу",
    sv    = "Redigera grupp",
    nb    = "Rediger gruppe",
    de    = "Gruppe bearbeiten",
    nlnl  = "Groep bewerken",
    frfr  = "Modifier le groupe",
    fi    = "Muokkaa ryhmää",
    it    = "Modifica gruppo",
    zhcn  = "编辑群组",
    ja    = "グループを編集",
    ko    = "그룹 편집",
  },

  GameVipListGroupInfoName = {
    en    = "Group name",
    ptbr  = "Nome do grupo",
    ptpt  = "Nome do grupo",
    es419 = "Nombre del grupo",
    eses  = "Nombre del grupo",
    pl    = "Nazwa grupy",
    ru    = "Название группы",
    sv    = "Gruppnamn",
    nb    = "Gruppenavn",
    de    = "Gruppenname",
    nlnl  = "Groepsnaam",
    frfr  = "Nom du groupe",
    fi    = "Ryhmän nimi",
    it    = "Nome del gruppo",
    zhcn  = "群组名称",
    ja    = "グループ名",
    ko    = "그룹 이름",
  },

  GameVipListGroupInfoMember = {
    en    = "Member of the following groups:",
    ptbr  = "Membro dos seguintes grupos:",
    ptpt  = "Membro dos seguintes grupos:",
    es419 = "Miembro de los siguientes grupos:",
    eses  = "Miembro de los siguientes grupos:",
    pl    = "Członek następujących grup:",
    ru    = "Участник следующих групп:",
    sv    = "Medlem i följande grupper:",
    nb    = "Medlem i følgende grupper:",
    de    = "Mitglied der folgenden Gruppen:",
    nlnl  = "Lid van de volgende groepen:",
    frfr  = "Membre des groupes suivants :",
    fi    = "Seuraavien ryhmien jäsen:",
    it    = "Membro dei seguenti gruppi:",
    zhcn  = "以下群组的成员：",
    ja    = "次のグループのメンバー：",
    ko    = "다음 그룹의 멤버:",
  },

  GameVipListGroupWindowAddWithLimit = {
    en    = "Add group (%s left)",
    ptbr  = "Adicionar grupo (%s restantes)",
    ptpt  = "Adicionar grupo VIP (%s restantes)",
    es419 = "Agregar grupo VIP (%s restantes)",
    eses  = "Agregar grupo VIP (%s restantes)",
    pl    = "Dodaj grupę VIP (pozostało: %s)",
    ru    = "Добавить группу VIP (осталось: %s)",
    sv    = "Lägg till VIP-grupp (%s kvar)",
    nb    = "Legg til VIP-gruppe (%s igjen)",
    de    = "VIP-Gruppe hinzufügen (noch %s)",
    nlnl  = "VIP-groep toevoegen (%s resterend)",
    frfr  = "Ajouter un groupe VIP (%s restant(s))",
    fi    = "Lisää VIP-ryhmä (jäljellä %s)",
    it    = "Aggiungi gruppo VIP (%s rimanenti)",
    zhcn  = "添加VIP群组（剩余%s）",
    ja    = "VIPグループを追加（残り%s）",
    ko    = "VIP 그룹 추가 (%s 남음)",
  },

  GameVipListContextMenuGroupRemovePlayer = {
    en    = "Remove %s from %s group",
    ptbr  = "Remover %s do grupo %s",
    ptpt  = "Remover %s do grupo %s",
    es419 = "Eliminar %s del grupo %s",
    eses  = "Eliminar %s del grupo %s",
    pl    = "Usuń %s z grupy %s",
    ru    = "Удалить %s из группы %s",
    sv    = "Ta bort %s från gruppen %s",
    nb    = "Fjern %s fra gruppen %s",
    de    = "%s aus der Gruppe %s entfernen",
    nlnl  = "%s uit de groep %s verwijderen",
    frfr  = "Supprimer %s du groupe %s",
    fi    = "Poista %s ryhmästä %s",
    it    = "Rimuovi %s dal gruppo %s",
    zhcn  = "从%s组中移除%s",
    ja    = "%sを%sグループから削除",
    ko    = "%s을(를) %s 그룹에서 제거",
  },
})
