-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameHotkeysAssignWindow = {
    en    = "Assign button",
    ptbr  = "Atribuir botão",
    ptpt  = "Atribuir botão",
    es419 = "Asignar botón",
    eses  = "Asignar botón",
    pl    = "Przypisz przycisk",
    ru    = "Назначить кнопку",
    sv    = "Tilldela knapp",
    nb    = "Tilordne knapp",
    de    = "Taste zuweisen",
    nlnl  = "Knop toewijzen",
    frfr  = "Attribuer une touche",
    fi    = "Määritä näppäin",
    it    = "Assegna pulsante",
    zhcn  = "分配按钮",
    ja    = "ボタンを割り当てる",
    ko    = "버튼 지정",
  },

  GameHotkeysAssignWindowTip = {
    en    = "Press the key you want to add to the hotkey manager",
    ptbr  = "Pressione a tecla que deseja adicionar ao gerenciador de atalhos",
    ptpt  = "Prima a tecla que deseja adicionar ao gerenciador de atalhos",
    es419 = "Presiona la tecla que deseas agregar al gestor de atajos",
    eses  = "Pulsa la tecla que deseas agregar al gestor de atajos",
    pl    = "Naciśnij klawisz, który chcesz dodać do menedżera skrótów",
    ru    = "Нажмите клавишу, которую хотите добавить в менеджер горячих клавиш",
    sv    = "Tryck på knappen du vill lägga till i snabbkommandohanteraren",
    nb    = "Trykk på knappen du vil legge til i hurtigkommandohantereren",
    de    = "Drücken Sie die Taste, die Sie zum Hotkey-Manager hinzufügen möchten",
    nlnl  = "Druk op de toets die je aan de hotkeybeheerder wilt toevoegen",
    frfr  = "Appuyez sur la touche que vous souhaitez ajouter au gestionnaire de raccourcis",
    fi    = "Paina näppäintä, jonka haluat lisätä pikanäppäinten hallintaan",
    it    = "Premi il tasto che desideri aggiungere al gestore dei tasti rapidi",
    zhcn  = "按下要添加到快捷键管理器的按键",
    ja    = "ホットキーマネージャーに追加するキーを押してください",
    ko    = "단축키 관리자에 추가할 키를 누르세요",
  },

  GameHotkeysAssignWindowComboPreview = {
    en    = "Current hotkey to add",
    ptbr  = "Atalho atual a ser adicionado",
    ptpt  = "Atalho atual a ser adicionado",
    es419 = "Tecla rápida actual a agregar",
    eses  = "Tecla rápida actual a agregar",
    pl    = "Obecny skrót do dodania",
    ru    = "Текущая горячая клавиша для добавления",
    sv    = "Aktuellt snabbkommando att lägga till",
    nb    = "Gjeldende hurtigtast som skal legges til",
    de    = "Aktueller Hotkey zum Hinzufügen",
    nlnl  = "Huidige hotkey om toe te voegen",
    frfr  = "Raccourci actuel à ajouter",
    fi    = "Lisättävä nykyinen pikanäppäin",
    it    = "Tasto rapido attuale da aggiungere",
    zhcn  = "要添加的当前快捷键",
    ja    = "追加する現在のホットキー",
    ko    = "추가할 현재 단축키",
  },

  GameHotkeysWindowTip = {
    en    = "Drag and drop a row below into any hotkey bar",
    ptbr  = "Arraste e solte uma linha abaixo em qualquer barra de atalhos",
    ptpt  = "Arraste e solte uma linha abaixo em qualquer barra de atalhos",
    es419 = "Arrastra y suelta una fila de abajo en cualquier barra de atajos",
    eses  = "Arrastra y suelta una fila de abajo en cualquier barra de atajos",
    pl    = "Przeciągnij i upuść wiersz poniżej do dowolnego paska skrótów",
    ru    = "Перетащите строку ниже на любую панель горячих клавиш",
    sv    = "Dra och släpp en rad nedan till valfritt snabbkommandofält",
    nb    = "Dra og slipp en rad nedenfor til et hvilket som helst hurtigkommandofelt",
    de    = "Ziehen Sie eine Zeile unten in eine beliebige Hotkey-Leiste",
    nlnl  = "Sleep een rij hieronder naar een willekeurige hotkeybalk",
    frfr  = "Faites glisser une ligne ci-dessous vers n’importe quelle barre de raccourcis",
    fi    = "Vedä alla oleva rivi mihin tahansa pikanäppäinpalkkiin",
    it    = "Trascina e rilascia una riga in una qualsiasi barra dei tasti rapidi",
    zhcn  = "将下面的一行拖放到任意快捷键栏",
    ja    = "下の行を任意のホットキーバーへドラッグ＆ドロップしてください",
    ko    = "아래의 행을 원하는 단축키 바에 드래그 앤 드롭하세요",
  },

  GameHotkeysHotkeyItemLabel = {
    en    = "Item or power",
    ptbr  = "Item ou poder",
    ptpt  = "Item ou poder",
    es419 = "Ítem o poder",
    eses  = "Objeto o poder",
    pl    = "Przedmiot lub moc",
    ru    = "Предмет или способность",
    sv    = "Föremål eller kraft",
    nb    = "Gjenstand eller kraft",
    de    = "Gegenstand oder Fähigkeit",
    nlnl  = "Item of kracht",
    frfr  = "Objet ou pouvoir",
    fi    = "Esine tai voima",
    it    = "Oggetto o potere",
    zhcn  = "物品或能力",
    ja    = "アイテムまたはパワー",
    ko    = "아이템 또는 능력",
  },

  GameHotkeysUseOnSelf = {
    en    = "Use on yourself",
    ptbr  = "Usar em você",
    ptpt  = "Usar em você",
    es419 = "Usar en ti",
    eses  = "Usar en ti",
    pl    = "Użyj na sobie",
    ru    = "Использовать на себе",
    sv    = "Använd på dig själv",
    nb    = "Bruk på deg selv",
    de    = "Auf sich selbst anwenden",
    nlnl  = "Op jezelf gebruiken",
    frfr  = "Utiliser sur soi-même",
    fi    = "Käytä itseesi",
    it    = "Usa su te stesso",
    zhcn  = "对自己使用",
    ja    = "自分に使用",
    ko    = "자신에게 사용",
  },

  GameHotkeysUseOnTarget = {
    en    = "Use on target",
    ptbr  = "Usar no alvo",
    ptpt  = "Usar no alvo",
    es419 = "Usar en el objetivo",
    eses  = "Usar en el objetivo",
    pl    = "Użyj na celu",
    ru    = "Использовать на цели",
    sv    = "Använd på målet",
    nb    = "Bruk på målet",
    de    = "Auf das Ziel anwenden",
    nlnl  = "Op doelwit gebruiken",
    frfr  = "Utiliser sur la cible",
    fi    = "Käytä kohteeseen",
    it    = "Usa sul bersaglio",
    zhcn  = "对目标使用",
    ja    = "対象に使用",
    ko    = "대상에게 사용",
  },

  GameHotkeysUseWith = {
    en    = "With crosshair",
    ptbr  = "Com mira",
    ptpt  = "Com mira",
    es419 = "Con mira",
    eses  = "Con mira",
    pl    = "Z celownikiem",
    ru    = "С прицелом",
    sv    = "Med hårkors",
    nb    = "Med hårkors",
    de    = "Mit Fadenkreuz",
    nlnl  = "Met draadkruis",
    frfr  = "Avec le réticule",
    fi    = "Käytä tähtäimen kanssa",
    it    = "Con mirino",
    zhcn  = "使用准星",
    ja    = "照準を使用",
    ko    = "십자선 사용",
  },

  GameHotkeysUseAtCursor = {
    en    = "At cursor position",
    ptbr  = "Na posição do cursor",
    ptpt  = "Na posição do cursor",
    es419 = "En la posición del cursor",
    eses  = "En la posición del cursor",
    pl    = "W pozycji kursora",
    ru    = "В позиции курсора",
    sv    = "Vid markörens position",
    nb    = "Ved markørens posisjon",
    de    = "An der Kursorposition",
    nlnl  = "Op cursorpositie",
    frfr  = "À la position du curseur",
    fi    = "Kursorin kohdalla",
    it    = "Alla posizione del cursore",
    zhcn  = "在光标位置",
    ja    = "カーソル位置で使用",
    ko    = "커서 위치",
  },

  GameHotkeysHotkeyTextLabel = {
    en    = "Text",
    ptbr  = "Texto",
    ptpt  = "Texto",
    es419 = "Texto",
    eses  = "Texto",
    pl    = "Tekst",
    ru    = "Текст",
    sv    = "Text",
    nb    = "Tekst",
    de    = "Text",
    nlnl  = "Tekst",
    frfr  = "Texte",
    fi    = "Teksti",
    it    = "Testo",
    zhcn  = "文本",
    ja    = "テキスト",
    ko    = "텍스트",
  },

  GameHotkeysSendAutomatically = {
    en    = "Send automatically",
    ptbr  = "Enviar automaticamente",
    ptpt  = "Enviar automaticamente",
    es419 = "Enviar automáticamente",
    eses  = "Enviar automáticamente",
    pl    = "Wyślij automatycznie",
    ru    = "Отправить автоматически",
    sv    = "Skicka automatiskt",
    nb    = "Send automatisk",
    de    = "Automatisch senden",
    nlnl  = "Automatisch verzenden",
    frfr  = "Envoyer automatiquement",
    fi    = "Lähetä automaattisesti",
    it    = "Invia automaticamente",
    zhcn  = "自动发送",
    ja    = "自動送信",
    ko    = "자동 전송",
  },

  GameHotkeysApplyAllButton = {
    en    = "Apply all",
    ptbr  = "Aplicar tudo",
    ptpt  = "Aplicar tudo",
    es419 = "Aplicar todo",
    eses  = "Aplicar todo",
    pl    = "Zastosuj wszystko",
    ru    = "Применить все",
    sv    = "Tillämpa alla",
    nb    = "Bruk alle",
    de    = "Alles anwenden",
    nlnl  = "Alles toepassen",
    frfr  = "Tout appliquer",
    fi    = "Käytä kaikki",
    it    = "Applica tutto",
    zhcn  = "全部应用",
    ja    = "すべて適用",
    ko    = "모두 적용",
  },

  GameHotkeysResetButton = {
    en    = "Reset all",
    ptbr  = "Redefinir tudo",
    ptpt  = "Redefinir tudo",
    es419 = "Restablecer todo",
    eses  = "Restablecer todo",
    pl    = "Zresetuj wszystko",
    ru    = "Сбросить все",
    sv    = "Återställ alla",
    nb    = "Tilbakestill alle",
    de    = "Alles zurücksetzen",
    nlnl  = "Alles resetten",
    frfr  = "Tout réinitialiser",
    fi    = "Palauta kaikki",
    it    = "Reimposta tutto",
    zhcn  = "全部重置",
    ja    = "すべてリセット",
    ko    = "모두 초기화",
  },

  GameHotkeysAssignWindowOverwriteTitle = {
    en    = "Overwrite",
    ptbr  = "Sobrescrever",
    ptpt  = "Sobrescrever",
    es419 = "Sobrescribir",
    eses  = "Sobrescribir",
    pl    = "Nadpisz",
    ru    = "Перезаписать",
    sv    = "Skriv över",
    nb    = "Skriv over",
    de    = "Überschreiben",
    nlnl  = "Overschrijven",
    frfr  = "Remplacer",
    fi    = "Korvaa",
    it    = "Sovrascrivi",
    zhcn  = "覆盖",
    ja    = "上書き",
    ko    = "덮어쓰기",
  },

  GameHotkeysAssignWindowOverwriteMsg = {
    en    = "This hotkey is already set.\nAre you sure you want to overwrite it?",
    ptbr  = "Este atalho já está definido.\nVocê tem certeza de que deseja sobrescrevê-lo?",
    ptpt  = "Este atalho já está definido.\nVocê tem certeza de que deseja sobrescrevê-lo?",
    es419 = "Esta tecla de acceso rápido ya está configurada.\n¿Estás seguro de que deseas sobrescribirla?",
    eses  = "Esta tecla de acceso rápido ya está configurada.\n¿Estás seguro de que deseas sobrescribirla?",
    pl    = "Ten skrót jest już ustawiony.\nCzy na pewno chcesz go nadpisać?",
    ru    = "Эта горячая клавиша уже назначена.\nВы уверены, что хотите её перезаписать?",
    sv    = "Denna snabbknapp är redan inställd.\nÄr du säker på att du vill skriva över den?",
    nb    = "Denne hurtigtasten er allerede angitt.\nEr du sikker på at du vil skrive over den?",
    de    = "Dieser Hotkey ist bereits belegt.\nSind Sie sicher, dass Sie ihn überschreiben möchten?",
    nlnl  = "Deze hotkey is al ingesteld.\nWeet je zeker dat je deze wilt overschrijven?",
    frfr  = "Ce raccourci est déjà configuré.\nVoulez-vous vraiment le remplacer ?",
    fi    = "Tämä pikanäppäin on jo asetettu.\nHaluatko varmasti korvata sen?",
    it    = "Questo tasto rapido è già impostato.\nSei sicuro di volerlo sovrascrivere?",
    zhcn  = "此快捷键已设置。\n确定要覆盖它吗？",
    ja    = "このホットキーはすでに設定されています。\n上書きしますか？",
    ko    = "이 단축키는 이미 설정되어 있습니다.\n덮어쓰시겠습니까?",
  },

  GameHotkeysLabelText = {
    en    = "[Text] %s",
    ptbr  = "[Texto] %s",
    ptpt  = "[Texto] %s",
    es419 = "[Texto] %s",
    eses  = "[Texto] %s",
    pl    = "[Tekst] %s",
    ru    = "[Текст] %s",
    sv    = "[Text] %s",
    nb    = "[Tekst] %s",
    de    = "[Text] %s",
    nlnl  = "[Tekst] %s",
    frfr  = "[Texte] %s",
    fi    = "[Teksti] %s",
    it    = "[Testo] %s",
    zhcn  = "[文本] %s",
    ja    = "[テキスト] %s",
    ko    = "[텍스트] %s",
  },

  GameHotkeysItemAtCursor = {
    en    = "[Item] Use this object at cursor position.",
    ptbr  = "[Item] Use este objeto na posição do cursor.",
    ptpt  = "[Item] Use este objeto na posição do cursor.",
    es419 = "[Ítem] Usa este objeto en la posición del cursor.",
    eses  = "[Objeto] Usa este objeto en la posición del cursor.",
    pl    = "[Przedmiot] Użyj tego przedmiotu w pozycji kursora.",
    ru    = "[Предмет] Использовать этот объект в позиции курсора.",
    sv    = "[Föremål] Använd detta föremål vid markörens position.",
    nb    = "[Gjenstand] Bruk denne gjenstanden ved markørens posisjon.",
    de    = "[Gegenstand] Verwende diesen Gegenstand an der Kursorposition.",
    nlnl  = "[Item] Gebruik dit object op de cursorpositie.",
    frfr  = "[Objet] Utiliser cet objet à la position du curseur.",
    fi    = "[Esine] Käytä tätä esinettä kohdistimen sijainnissa.",
    it    = "[Oggetto] Usa questo oggetto alla posizione del cursore.",
    zhcn  = "[物品] 在光标位置使用此物品。",
    ja    = "[アイテム] このオブジェクトをカーソル位置で使用します。",
    ko    = "[아이템] 커서 위치에서 이 물체를 사용합니다.",
  },

  GameHotkeysItemCrosshair = {
    en    = "[Item] Use this object with crosshair.",
    ptbr  = "[Item] Use este objeto com mira.",
    ptpt  = "[Item] Use este objeto com mira.",
    es419 = "[Ítem] Usa este objeto con la mira.",
    eses  = "[Objeto] Usa este objeto con la mira.",
    pl    = "[Przedmiot] Użyj tego przedmiotu z celownikiem.",
    ru    = "[Предмет] Использовать этот объект с прицелом.",
    sv    = "[Föremål] Använd detta föremål med hårkors.",
    nb    = "[Gjenstand] Bruk denne gjenstanden med hårkors.",
    de    = "[Gegenstand] Verwende diesen Gegenstand mit dem Fadenkreuz.",
    nlnl  = "[Item] Gebruik dit object met het draadkruis.",
    frfr  = "[Objet] Utiliser cet objet avec le viseur.",
    fi    = "[Esine] Käytä tätä esinettä hiusristikon kanssa.",
    it    = "[Oggetto] Usa questo oggetto con il mirino.",
    zhcn  = "[物品] 使用此物品并配合准星。",
    ja    = "[アイテム] このオブジェクトを照準で使用します。",
    ko    = "[아이템] 이 물체를 십자선과 함께 사용합니다.",
  },

  GameHotkeysItemTarget = {
    en    = "[Item] Use this object on target.",
    ptbr  = "[Item] Use este objeto no alvo.",
    ptpt  = "[Item] Use este objeto no alvo.",
    es419 = "[Ítem] Usa este objeto en el objetivo.",
    eses  = "[Objeto] Usa este objeto en el objetivo.",
    pl    = "[Przedmiot] Użyj tego przedmiotu na celu.",
    ru    = "[Предмет] Использовать этот объект на цели.",
    sv    = "[Föremål] Använd detta föremål på målet.",
    nb    = "[Gjenstand] Bruk denne gjenstanden på målet.",
    de    = "[Gegenstand] Verwende diesen Gegenstand auf das Ziel.",
    nlnl  = "[Item] Gebruik dit object op het doelwit.",
    frfr  = "[Objet] Utiliser cet objet sur la cible.",
    fi    = "[Esine] Käytä tätä esinettä kohteeseen.",
    it    = "[Oggetto] Usa questo oggetto sul bersaglio.",
    zhcn  = "[物品] 对目标使用此物品。",
    ja    = "[アイテム] このオブジェクトを対象に使用します。",
    ko    = "[아이템] 이 물체를 대상에게 사용합니다.",
  },

  GameHotkeysItemYourself = {
    en    = "[Item] Use this object on yourself.",
    ptbr  = "[Item] Use este objeto em você.",
    ptpt  = "[Item] Use este objeto em você.",
    es419 = "[Ítem] Usa este objeto en ti mismo.",
    eses  = "[Objeto] Usa este objeto en ti mismo.",
    pl    = "[Przedmiot] Użyj tego przedmiotu na sobie.",
    ru    = "[Предмет] Использовать этот объект на себе.",
    sv    = "[Föremål] Använd detta föremål på dig själv.",
    nb    = "[Gjenstand] Bruk denne gjenstanden på deg selv.",
    de    = "[Gegenstand] Verwende diesen Gegenstand auf dich selbst.",
    nlnl  = "[Item] Gebruik dit object op jezelf.",
    frfr  = "[Objet] Utiliser cet objet sur vous-même.",
    fi    = "[Esine] Käytä tätä esinettä itseesi.",
    it    = "[Oggetto] Usa questo oggetto su te stesso.",
    zhcn  = "[物品] 对自己使用此物品。",
    ja    = "[アイテム] このオブジェクトを自分に使用します。",
    ko    = "[아이템] 이 물체를 자신에게 사용합니다.",
  },

  GameHotkeysItemUse = {
    en    = "[Item] Use this object.",
    ptbr  = "[Item] Use este objeto.",
    ptpt  = "[Item] Use este objeto.",
    es419 = "[Ítem] Usa este objeto.",
    eses  = "[Objeto] Usa este objeto.",
    pl    = "[Przedmiot] Użyj tego przedmiotu.",
    ru    = "[Предмет] Использовать этот объект.",
    sv    = "[Föremål] Använd detta föremål.",
    nb    = "[Gjenstand] Bruk denne gjenstanden.",
    de    = "[Gegenstand] Verwende diesen Gegenstand.",
    nlnl  = "[Item] Gebruik dit object.",
    frfr  = "[Objet] Utiliser cet objet.",
    fi    = "[Esine] Käytä tätä esinettä.",
    it    = "[Oggetto] Usa questo oggetto.",
    zhcn  = "[物品] 使用此物品。",
    ja    = "[アイテム] このオブジェクトを使用します。",
    ko    = "[아이템] 이 물체를 사용합니다.",
  },

  GameHotkeysPower = {
    en    = "[Power] %s (level %s)",
    ptbr  = "[Poder] %s (nível %s)",
    ptpt  = "[Poder] %s (nível %s)",
    es419 = "[Poder] %s (nivel %s)",
    eses  = "[Poder] %s (nivel %s)",
    pl    = "[Moc] %s (poziom %s)",
    ru    = "[Способность] %s (уровень %s)",
    sv    = "[Kraft] %s (nivå %s)",
    nb    = "[Kraft] %s (nivå %s)",
    de    = "[Fähigkeit] %s (Stufe %s)",
    nlnl  = "[Kracht] %s (niveau %s)",
    frfr  = "[Pouvoir] %s (niveau %s)",
    fi    = "[Voima] %s (taso %s)",
    it    = "[Potere] %s (livello %s)",
    zhcn  = "[能力] %s（等级 %s）",
    ja    = "[パワー] %s（レベル%s）",
    ko    = "[능력] %s (레벨 %s)",
  },

  GameHotkeysPowerNotApplicable = {
    en    = "[Power] N/A",
    ptbr  = "[Poder] N/A",
    ptpt  = "[Poder] N/A",
    es419 = "[Poder] N/D",
    eses  = "[Poder] N/D",
    pl    = "[Moc] N/A",
    ru    = "[Способность] Н/Д",
    sv    = "[Kraft] N/A",
    nb    = "[Kraft] I/T",
    de    = "[Fähigkeit] N/V",
    nlnl  = "[Kracht] n.v.t.",
    frfr  = "[Pouvoir] N/D",
    fi    = "[Voima] Ei käytettävissä",
    it    = "[Potere] N/D",
    zhcn  = "[能力] 不适用",
    ja    = "[パワー] 該当なし",
    ko    = "[능력] 해당 없음",
  },

  GameHotkeysAssignWindowCurrentHotkey = {
    en    = "Current hotkey to add",
    ptbr  = "Atalho atual a ser adicionado",
    ptpt  = "Atalho atual a ser adicionado",
    es419 = "Tecla de acceso rápido actual para agregar",
    eses  = "Tecla de acceso rápido actual para agregar",
    pl    = "Aktualny skrót do dodania",
    ru    = "Текущая горячая клавиша для добавления",
    sv    = "Nuvarande snabbknapp att lägga till",
    nb    = "Gjeldende hurtigtast som skal legges til",
    de    = "Aktueller Hotkey zum Hinzufügen",
    nlnl  = "Huidige hotkey om toe te voegen",
    frfr  = "Raccourci actuel à ajouter",
    fi    = "Lisättävä nykyinen pikanäppäin",
    it    = "Tasto rapido attuale da aggiungere",
    zhcn  = "要添加的当前快捷键",
    ja    = "追加する現在のホットキー",
    ko    = "추가할 현재 단축키",
  },
})
