-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  KalibInfoAttributeAttack = {
    en    = "Attack",
    ptbr  = "Ataque",
    ptpt  = "Ataque",
    es419 = "Ataque",
    eses  = "Ataque",
    pl    = "Atak",
    ru    = "Атака",
    sv    = "Attack",
    nb    = "Angrep",
    de    = "Angriff",
    nlnl  = "Aanval",
    frfr  = "Attaque",
    fi    = "Hyökkäys",
    it    = "Attacco",
    zhcn  = "攻击",
    ja    = "攻撃",
    ko    = "공격",
  },

  KalibInfoAttributeDefense = {
    en    = "Defense",
    ptbr  = "Defesa",
    ptpt  = "Defesa",
    es419 = "Defensa",
    eses  = "Defensa",
    pl    = "Obrona",
    ru    = "Защита",
    sv    = "Försvar",
    nb    = "Forsvar",
    de    = "Verteidigung",
    nlnl  = "Verdediging",
    frfr  = "Défense",
    fi    = "Puolustus",
    it    = "Difesa",
    zhcn  = "防御",
    ja    = "防御",
    ko    = "방어력",
  },

  KalibInfoAttributeMagicDefense = {
    en    = "Magic defense",
    ptbr  = "Defesa mágica",
    ptpt  = "Defesa mágica",
    es419 = "Defensa mágica",
    eses  = "Defensa mágica",
    pl    = "Obrona magiczna",
    ru    = "Магическая защита",
    sv    = "Magiskt försvar",
    nb    = "Magisk forsvar",
    de    = "Magische Verteidigung",
    nlnl  = "Magische verdediging",
    frfr  = "Défense magique",
    fi    = "Taikapuolustus",
    it    = "Difesa magica",
    zhcn  = "魔法防御",
    ja    = "魔法防御",
    ko    = "마법 방어력",
  },

  KalibInfoAttributeVitality = {
    en    = "Vitality",
    ptbr  = "Vitalidade",
    ptpt  = "Vitalidade",
    es419 = "Vitalidad",
    eses  = "Vitalidad",
    pl    = "Witalność",
    ru    = "Жизненная сила",
    sv    = "Vitalitet",
    nb    = "Vitalitet",
    de    = "Vitalität",
    nlnl  = "Vitaliteit",
    frfr  = "Vitalité",
    fi    = "Elinvoima",
    it    = "Vitalità",
    zhcn  = "生命力",
    ja    = "生命力",
    ko    = "활력",
  },

  KalibInfoAttributeWill = {
    en    = "Will",
    ptbr  = "Vontade",
    ptpt  = "Vontade",
    es419 = "Voluntad",
    eses  = "Voluntad",
    pl    = "Wola",
    ru    = "Воля",
    sv    = "Vilja",
    nb    = "Vilje",
    de    = "Willenskraft",
    nlnl  = "Wilskracht",
    frfr  = "Volonté",
    fi    = "Tahto",
    it    = "Volontà",
    zhcn  = "意志",
    ja    = "意志",
    ko    = "의지",
  },

  KalibInfoAttributeAgility = {
    en    = "Agility",
    ptbr  = "Agilidade",
    ptpt  = "Agilidade",
    es419 = "Agilidad",
    eses  = "Agilidad",
    pl    = "Zwinność",
    ru    = "Ловкость",
    sv    = "Smidighet",
    nb    = "Smidighet",
    de    = "Beweglichkeit",
    nlnl  = "Behendigheid",
    frfr  = "Agilité",
    fi    = "Ketteryys",
    it    = "Agilità",
    zhcn  = "敏捷",
    ja    = "敏捷",
    ko    = "민첩",
  },

  KalibInfoAttributeDodge = {
    en    = "Dodge",
    ptbr  = "Esquiva",
    ptpt  = "Esquiva",
    es419 = "Esquiva",
    eses  = "Esquiva",
    pl    = "Unik",
    ru    = "Уклонение",
    sv    = "Undvikande",
    nb    = "Unnvikelse",
    de    = "Ausweichen",
    nlnl  = "Ontwijken",
    frfr  = "Esquive",
    fi    = "Väistö",
    it    = "Schivata",
    zhcn  = "闪避",
    ja    = "回避",
    ko    = "회피",
  },

  KalibInfoAttributeWalking = {
    en    = "Walking",
    ptbr  = "Caminhada",
    ptpt  = "Caminhada",
    es419 = "Caminata",
    eses  = "Caminata",
    pl    = "Chodzenie",
    ru    = "Ходьба",
    sv    = "Gående",
    nb    = "Gåing",
    de    = "Gehen",
    nlnl  = "Lopen",
    frfr  = "Marche",
    fi    = "Kävely",
    it    = "Camminata",
    zhcn  = "行走",
    ja    = "歩行",
    ko    = "걷기",
  },

  KalibInfoAttributeLuck = {
    en    = "Luck",
    ptbr  = "Sorte",
    ptpt  = "Sorte",
    es419 = "Suerte",
    eses  = "Suerte",
    pl    = "Szczęście",
    ru    = "Удача",
    sv    = "Lycka",
    nb    = "Lykke",
    de    = "Glück",
    nlnl  = "Geluk",
    frfr  = "Chance",
    fi    = "Onni",
    it    = "Fortuna",
    zhcn  = "幸运",
    ja    = "運",
    ko    = "운",
  },

  KalibInfoRemainingXpToAdvance = {
    en    = "Remaining %d%% (about %s XP) to advance to level %s.",
    ptbr  = "Restante %d%% (cerca de %s XP) para avançar para o nível %s.",
    ptpt  = "Restam %d%% (cerca de %s XP) para avançar para o nível %s.",
    es419 = "Falta un %d%% (aproximadamente %s XP) para avanzar al nivel %s.",
    eses  = "Falta un %d%% (aproximadamente %s XP) para avanzar al nivel %s.",
    pl    = "Pozostało %d%% (około %s XP) do awansu na poziom %s.",
    ru    = "Осталось %d%% (около %s XP) до перехода на уровень %s.",
    sv    = "Det återstår %d%% (ungefär %s XP) för att nå nivå %s.",
    nb    = "Det gjenstår %d%% (omtrent %s XP) for å nå nivå %s.",
    de    = "Noch %d%% (etwa %s XP), um auf Level %s aufzusteigen.",
    nlnl  = "Nog %d%% (ongeveer %s XP) om level %s te bereiken.",
    frfr  = "Il reste %d%% (environ %s XP) pour passer au niveau %s.",
    fi    = "%d%% (noin %s XP) jäljellä tasolle %s siirtymiseen.",
    it    = "Manca il %d%% (circa %s XP) per avanzare al livello %s.",
    zhcn  = "还剩 %d%%（约 %s XP）即可升到 %s 级。",
    ja    = "残り%d%%（約%s XP）でレベル%sに到達します。",
    ko    = "레벨 %s로 올라가기까지 %d%%(%s XP 정도)가 남았습니다.",
  },

  KalibInfoXpPerHour = {
    en    = "%s XP per hour.",
    ptbr  = "%s XP por hora.",
    ptpt  = "%s XP por hora.",
    es419 = "%s XP por hora.",
    eses  = "%s XP por hora.",
    pl    = "%s XP na godzinę.",
    ru    = "%s XP в час.",
    sv    = "%s XP per timme.",
    nb    = "%s XP per time.",
    de    = "%s XP pro Stunde.",
    nlnl  = "%s XP per uur.",
    frfr  = "%s XP par heure.",
    fi    = "%s XP tunnissa.",
    it    = "%s XP all'ora.",
    zhcn  = "%s XP 每小时。",
    ja    = "1時間あたり%s XP。",
    ko    = "시간당 %s XP.",
  },

  KalibInfoRemainingTimeToAdvance = {
    en    = "Next level in %d hours and %d minutes.",
    ptbr  = "Próximo nível em %d horas e %d minutos.",
    ptpt  = "Próximo nível em %d horas e %d minutos.",
    es419 = "Próximo nivel en %d horas y %d minutos.",
    eses  = "Próximo nivel en %d horas y %d minutos.",
    pl    = "Następny poziom za %d godzin i %d minut.",
    ru    = "Следующий уровень через %d ч. %d мин.",
    sv    = "Nästa nivå om %d timmar och %d minuter.",
    nb    = "Neste nivå om %d timer og %d minutter.",
    de    = "Nächstes Level in %d Stunden und %d Minuten.",
    nlnl  = "Volgend level over %d uur en %d minuten.",
    frfr  = "Prochain niveau dans %d heures et %d minutes.",
    fi    = "Seuraava taso %d tunnin ja %d minuutin kuluttua.",
    it    = "Prossimo livello tra %d ore e %d minuti.",
    zhcn  = "再过 %d 小时 %d 分钟即可升到下一级。",
    ja    = "次のレベルまで%d時間%d分です。",
    ko    = "다음 레벨까지 %d시간 %d분 남았습니다.",
  },

})
