-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  CharacterListTitle = {
    en    = "Character list",
    ptbr  = "Lista de personagens",
    ptpt  = "Lista de personagens",
    es419 = "Lista de personajes",
    eses  = "Lista de personajes",
    pl    = "Lista postaci",
    ru    = "Список персонажей",
    sv    = "Karaktärslista",
    nb    = "Karakterliste",
    de    = "Charakterliste",
    nlnl  = "Personagelijst",
    frfr  = "Liste des personnages",
    fi    = "Hahmoluettelo",
    it    = "Lista personaggi",
    zhcn  = "角色列表",
    ja    = "キャラクター一覧",
    ko    = "캐릭터 목록",
  },

  CharacterListColumnCharacter = {
    en    = "Character",
    ptbr  = "Personagem",
    ptpt  = "Personagem",
    es419 = "Personaje",
    eses  = "Personaje",
    pl    = "Postać",
    ru    = "Персонаж",
    sv    = "Karaktär",
    nb    = "Figur",
    de    = "Charakter",
    nlnl  = "Personage",
    frfr  = "Personnage",
    fi    = "Hahmo",
    it    = "Personaggio",
    zhcn  = "角色",
    ja    = "キャラクター",
    ko    = "캐릭터",
  },

  CharacterListColumnLevel = {
    en    = "Level",
    ptbr  = "Nível",
    ptpt  = "Nível",
    es419 = "Nivel",
    eses  = "Nivel",
    pl    = "Poziom",
    ru    = "Уровень",
    sv    = "Nivå",
    nb    = "Nivå",
    de    = "Stufe",
    nlnl  = "Niveau",
    frfr  = "Niveau",
    fi    = "Taso",
    it    = "Livello",
    zhcn  = "等级",
    ja    = "レベル",
    ko    = "레벨",
  },

  CharacterListColumnVocation = {
    en    = "Vocation",
    ptbr  = "Vocação",
    ptpt  = "Vocação",
    es419 = "Vocación",
    eses  = "Vocación",
    pl    = "Profesja",
    ru    = "Профессия",
    sv    = "Yrke",
    nb    = "Yrke",
    de    = "Beruf",
    nlnl  = "Beroep",
    frfr  = "Vocation",
    fi    = "Ammatti",
    it    = "Vocazione",
    zhcn  = "职业",
    ja    = "職業",
    ko    = "직업",
  },

  CharacterListColumnWorld = {
    en    = "World",
    ptbr  = "Mundo",
    ptpt  = "Mundo",
    es419 = "Mundo",
    eses  = "Mundo",
    pl    = "Świat",
    ru    = "Мир",
    sv    = "Värld",
    nb    = "Verden",
    de    = "Welt",
    nlnl  = "Wereld",
    frfr  = "Monde",
    fi    = "Maailma",
    it    = "Mondo",
    zhcn  = "世界",
    ja    = "ワールド",
    ko    = "월드",
  },

  CharacterListAccountStatusLabel = {
    en    = "Account status",
    ptbr  = "Estado da conta",
    ptpt  = "Estado da conta",
    es419 = "Estado de la cuenta",
    eses  = "Estado de la cuenta",
    pl    = "Status konta",
    ru    = "Статус аккаунта",
    sv    = "Kontostatus",
    nb    = "Kontostatus",
    de    = "Kontostatus",
    nlnl  = "Accountstatus",
    frfr  = "État du compte",
    fi    = "Tilin tila",
    it    = "Stato dell’account",
    zhcn  = "账号状态",
    ja    = "アカウント状態",
    ko    = "계정 상태",
  },

  CharacterListAccountStatusValueFree = {
    en    = "Free account",
    ptbr  = "Conta gratuita",
    ptpt  = "Conta gratuita",
    es419 = "Cuenta gratuita",
    eses  = "Cuenta gratuita",
    pl    = "Darmowe konto",
    ru    = "Бесплатный аккаунт",
    sv    = "Gratis konto",
    nb    = "Gratis konto",
    de    = "Kostenloses Konto",
    nlnl  = "Gratis account",
    frfr  = "Compte gratuit",
    fi    = "Ilmainen tili",
    it    = "Account gratuito",
    zhcn  = "免费账号",
    ja    = "無料アカウント",
    ko    = "무료 계정",
  },

  CharacterListAccountStatusValuePremium = {
    en    = "Premium account",
    ptbr  = "Conta premium",
    ptpt  = "Conta premium",
    es419 = "Cuenta premium",
    eses  = "Cuenta premium",
    pl    = "Konto premium",
    ru    = "Премиум-аккаунт",
    sv    = "Premium konto",
    nb    = "Premium konto",
    de    = "Premium-Konto",
    nlnl  = "Premiumaccount",
    frfr  = "Compte premium",
    fi    = "Premium-tili",
    it    = "Account premium",
    zhcn  = "高级账号",
    ja    = "プレミアムアカウント",
    ko    = "프리미엄 계정",
  },

  CharacterListAccountStatusValuePremiumDaysLeft = {
    en    = "Days left",
    ptbr  = "Dias restantes",
    ptpt  = "Dias restantes",
    es419 = "Días restantes",
    eses  = "Días restantes",
    pl    = "Pozostało dni",
    ru    = "Осталось дней",
    sv    = "Dagar kvar",
    nb    = "Dager igjen",
    de    = "Verbleibende Tage",
    nlnl  = "Resterende dagen",
    frfr  = "Jours restants",
    fi    = "Päiviä jäljellä",
    it    = "Giorni rimanenti",
    zhcn  = "剩余天数",
    ja    = "残り日数",
    ko    = "남은 일수",
  },

  CharacterListAccountStatusValuePremiumLifetime = {
    en    = "Lifetime premium account",
    ptbr  = "Conta premium vitalícia",
    ptpt  = "Conta premium vitalícia",
    es419 = "Cuenta premium de por vida",
    eses  = "Cuenta premium de por vida",
    pl    = "Dożywotnie konto premium",
    ru    = "Пожизненный премиум-аккаунт",
    sv    = "Livstids premium-konto",
    nb    = "Livstids premium-konto",
    de    = "Lebenslanges Premium-Konto",
    nlnl  = "Levenslang premiumaccount",
    frfr  = "Compte premium à vie",
    fi    = "Elinikäinen premium-tili",
    it    = "Account premium a vita",
    zhcn  = "永久高级账号",
    ja    = "永久プレミアムアカウント",
    ko    = "영구 프리미엄 계정",
  },

  CharacterListWaitingListTitle = {
    en    = "Waiting list",
    ptbr  = "Lista de espera",
    ptpt  = "Lista de espera",
    es419 = "Lista de espera",
    eses  = "Lista de espera",
    pl    = "Lista oczekujących",
    ru    = "Очередь ожидания",
    sv    = "Väntelista",
    nb    = "Venteliste",
    de    = "Warteliste",
    nlnl  = "Wachtlijst",
    frfr  = "Liste d’attente",
    fi    = "Odotuslista",
    it    = "Lista d’attesa",
    zhcn  = "等待列表",
    ja    = "待機リスト",
    ko    = "대기 목록",
  },

  CharacterListWaitingListTimelabel = {
    en    = "Trying to reconnect in %s seconds.",
    ptbr  = "Tentando reconectar em %s segundos.",
    ptpt  = "A tentar reconectar em %s segundos.",
    es419 = "Intentando reconectar en %s segundos.",
    eses  = "Intentando reconectar en %s segundos.",
    pl    = "Próba ponownego połączenia za %s sekund.",
    ru    = "Попытка повторного подключения через %s сек.",
    sv    = "Försöker återansluta om %s sekunder.",
    nb    = "Prøver å koble til igjen om %s sekunder.",
    de    = "Versuche, in %s Sekunden erneut zu verbinden.",
    nlnl  = "Opnieuw verbinden over %s seconden.",
    frfr  = "Nouvelle tentative de connexion dans %s secondes.",
    fi    = "Yritetään yhdistää uudelleen %s sekunnin kuluttua.",
    it    = "Tentativo di riconnessione tra %s secondi.",
    zhcn  = "将在 %s 秒后尝试重新连接。",
    ja    = "%s秒後に再接続します。",
    ko    = "%s초 후에 다시 연결을 시도합니다.",
  },

  CharacterListConnectingMessage = {
    en    = "Connecting to game server...",
    ptbr  = "Conectando ao servidor do jogo...",
    ptpt  = "A ligar ao servidor do jogo...",
    es419 = "Conectando al servidor del juego...",
    eses  = "Conectando al servidor del juego...",
    pl    = "Łączenie z serwerem gry...",
    ru    = "Подключение к игровому серверу...",
    sv    = "Ansluter till spelservern...",
    nb    = "Kobler til spillserveren...",
    de    = "Verbindung zum Spielserver wird hergestellt...",
    nlnl  = "Verbinden met de gameserver...",
    frfr  = "Connexion au serveur de jeu...",
    fi    = "Yhdistetään pelipalvelimeen...",
    it    = "Connessione al server di gioco...",
    zhcn  = "正在连接游戏服务器……",
    ja    = "ゲームサーバーに接続中…",
    ko    = "게임 서버에 연결하는 중...",
  },

  CharacterListLoginErrorTitle = {
    en    = "Login error",
    ptbr  = "Erro de login",
    ptpt  = "Erro de início de sessão",
    es419 = "Error de inicio de sesión",
    eses  = "Error de inicio de sesión",
    pl    = "Błąd logowania",
    ru    = "Ошибка входа",
    sv    = "Inloggningsfel",
    nb    = "Påloggingsfeil",
    de    = "Anmeldefehler",
    nlnl  = "Aanmeldfout",
    frfr  = "Erreur de connexion",
    fi    = "Kirjautumisvirhe",
    it    = "Errore di accesso",
    zhcn  = "登录错误",
    ja    = "ログインエラー",
    ko    = "로그인 오류",
  },

  CharacterListLoginTokenTitle = {
    en    = "Two-factor authentication",
    ptbr  = "Autenticação de dois fatores",
    ptpt  = "Autenticação de dois fatores",
    es419 = "Autenticación de dos factores",
    eses  = "Autenticación de dos factores",
    pl    = "Uwierzytelnianie dwuskładnikowe",
    ru    = "Двухфакторная аутентификация",
    sv    = "Tvåfaktorsautentisering",
    nb    = "Tofaktorautentisering",
    de    = "Zwei-Faktor-Authentifizierung",
    nlnl  = "Tweefactorauthenticatie",
    frfr  = "Authentification à deux facteurs",
    fi    = "Kaksivaiheinen tunnistautuminen",
    it    = "Autenticazione a due fattori",
    zhcn  = "双因素认证",
    ja    = "二要素認証",
    ko    = "2단계 인증",
  },

  CharacterListLoginTokenMessage = {
    en    = "A new authentication token is required.\nLogin again.",
    ptbr  = "Um novo token de autenticação é necessário.\nAutentique-se novamente.",
    ptpt  = "É necessário um novo token de autenticação.\nInicie sessão novamente.",
    es419 = "Se requiere un nuevo token de autenticación.\nInicia sesión de nuevo.",
    eses  = "Se requiere un nuevo token de autenticación.\nInicia sesión de nuevo.",
    pl    = "Wymagany jest nowy token uwierzytelniania.\nZaloguj się ponownie.",
    ru    = "Требуется новый токен аутентификации.\nВыполните вход снова.",
    sv    = "En ny autentiseringstoken krävs.\nLogga in igen.",
    nb    = "Et nytt autentiseringstoken kreves.\nLogg inn igjen.",
    de    = "Ein neues Authentifizierungstoken wird benötigt.\nBitte erneut anmelden.",
    nlnl  = "Er is een nieuw authenticatietoken vereist.\nMeld je opnieuw aan.",
    frfr  = "Un nouveau jeton d’authentification est requis.\nReconnectez-vous.",
    fi    = "Uusi tunnistautumismerkki vaaditaan.\nKirjaudu uudelleen.",
    it    = "È richiesto un nuovo token di autenticazione.\nAccedi di nuovo.",
    zhcn  = "需要新的认证令牌。\n请重新登录。",
    ja    = "新しい認証トークンが必要です。\nもう一度ログインしてください。",
    ko    = "새 인증 토큰이 필요합니다.\n다시 로그인하세요.",
  },

  CharacterListConnectionErrorTitle = {
    en    = "Connection error",
    ptbr  = "Erro de conexão",
    ptpt  = "Erro de ligação",
    es419 = "Error de conexión",
    eses  = "Error de conexión",
    pl    = "Błąd połączenia",
    ru    = "Ошибка соединения",
    sv    = "Anslutningsfel",
    nb    = "Tilkoblingsfeil",
    de    = "Verbindungsfehler",
    nlnl  = "Verbindingsfout",
    frfr  = "Erreur de connexion",
    fi    = "Yhteysvirhe",
    it    = "Errore di connessione",
    zhcn  = "连接错误",
    ja    = "接続エラー",
    ko    = "연결 오류",
  },

  CharacterListUpdateNeededTitle = {
    en    = "Update needed",
    ptbr  = "Atualização necessária",
    ptpt  = "Atualização necessária",
    es419 = "Actualización necesaria",
    eses  = "Actualización necesaria",
    pl    = "Wymagana aktualizacja",
    ru    = "Требуется обновление",
    sv    = "Uppdatering behövs",
    nb    = "Oppdatering kreves",
    de    = "Update erforderlich",
    nlnl  = "Update vereist",
    frfr  = "Mise à jour requise",
    fi    = "Päivitys vaaditaan",
    it    = "Aggiornamento necessario",
    zhcn  = "需要更新",
    ja    = "更新が必要です",
    ko    = "업데이트 필요",
  },

  CharacterListUpdateNeededMessage = {
    en    = "Enter with your account again to update your client.",
    ptbr  = "Preencha novamente sua conta para atualizar o cliente.",
    ptpt  = "Entre novamente com a sua conta para atualizar o cliente.",
    es419 = "Ingresa nuevamente con tu cuenta para actualizar el cliente.",
    eses  = "Inicia sesión de nuevo con tu cuenta para actualizar el cliente.",
    pl    = "Wprowadź ponownie swoje dane konta, aby zaktualizować klienta.",
    ru    = "Войдите снова в свой аккаунт, чтобы обновить клиент.",
    sv    = "Logga in med ditt konto igen för att uppdatera klienten.",
    nb    = "Logg inn med kontoen din igjen for å oppdatere klienten.",
    de    = "Melden Sie sich erneut mit Ihrem Konto an, um den Client zu aktualisieren.",
    nlnl  = "Meld je opnieuw aan met je account om de client bij te werken.",
    frfr  = "Reconnectez-vous avec votre compte pour mettre à jour le client.",
    fi    = "Kirjaudu tililläsi uudelleen päivittääksesi asiakkaan.",
    it    = "Accedi di nuovo con il tuo account per aggiornare il client.",
    zhcn  = "请重新使用您的账号登录以更新客户端。",
    ja    = "クライアントを更新するには、もう一度アカウントでログインしてください。",
    ko    = "클라이언트를 업데이트하려면 계정으로 다시 로그인하세요.",
  },

  CharacterListCharSelectionErrorMessage = {
    en    = "You must select a character to login.",
    ptbr  = "Selecione um personagem para autenticar-se.",
    ptpt  = "Deve selecionar uma personagem para iniciar sessão.",
    es419 = "Debes seleccionar un personaje para autenticarte.",
    eses  = "Debes seleccionar un personaje para autenticarte.",
    pl    = "Musisz wybrać postać, aby się uwierzytelnić.",
    ru    = "Выберите персонажа для аутентификации.",
    sv    = "Du måste välja en karaktär för att autentisera dig.",
    nb    = "Du må velge en figur for å autentisere deg.",
    de    = "Sie müssen einen Charakter auswählen, um sich zu authentifizieren.",
    nlnl  = "Je moet een personage selecteren om je te authenticeren.",
    frfr  = "Vous devez sélectionner un personnage pour vous authentifier.",
    fi    = "Sinun on valittava hahmo todentaaksesi itsesi.",
    it    = "Devi selezionare un personaggio per autenticarti.",
    zhcn  = "请选择一个角色进行身份验证。",
    ja    = "認証するにはキャラクターを選択してください。",
    ko    = "인증하려면 캐릭터를 선택해야 합니다.",
  },

  EnterGameAccountLabel = {
    en    = "Account",
    ptbr  = "Conta",
    ptpt  = "Conta",
    es419 = "Cuenta",
    eses  = "Cuenta",
    pl    = "Konto",
    ru    = "Аккаунт",
    sv    = "Konto",
    nb    = "Konto",
    de    = "Konto",
    nlnl  = "Account",
    frfr  = "Compte",
    fi    = "Tili",
    it    = "Account",
    zhcn  = "账号",
    ja    = "アカウント",
    ko    = "계정",
  },

  EnterGamePasswordLabel = {
    en    = "Password",
    ptbr  = "Senha",
    ptpt  = "Palavra-passe",
    es419 = "Contraseña",
    eses  = "Contraseña",
    pl    = "Hasło",
    ru    = "Пароль",
    sv    = "Lösenord",
    nb    = "Passord",
    de    = "Passwort",
    nlnl  = "Wachtwoord",
    frfr  = "Mot de passe",
    fi    = "Salasana",
    it    = "Password",
    zhcn  = "密码",
    ja    = "パスワード",
    ko    = "비밀번호",
  },

  EnterGamePasswordRememberCheckBox = {
    en    = "Remember",
    ptbr  = "Lembrar",
    ptpt  = "Lembrar",
    es419 = "Recordar",
    eses  = "Recordar",
    pl    = "Zapamiętaj",
    ru    = "Запомнить",
    sv    = "Kom ihåg",
    nb    = "Husk",
    de    = "Merken",
    nlnl  = "Onthouden",
    frfr  = "Mémoriser",
    fi    = "Muista",
    it    = "Ricorda",
    zhcn  = "记住",
    ja    = "記憶する",
    ko    = "기억하기",
  },

  EnterGamePasswordRememberTooltip = {
    en    = "Remember account and password when starts client",
    ptbr  = "Lembrar conta e senha ao iniciar o cliente",
    ptpt  = "Lembrar conta e palavra-passe ao iniciar o cliente",
    es419 = "Recordar cuenta y contraseña al iniciar el cliente",
    eses  = "Recordar cuenta y contraseña al iniciar o cliente",
    pl    = "Zapamiętaj konto i hasło przy uruchomieniu klienta",
    ru    = "Запоминать аккаунт и пароль при запуске клиента",
    sv    = "Kom ihåg konto och lösenord när klienten startas",
    nb    = "Husk konto og passord når klienten startes",
    de    = "Konto und Passwort beim Start des Clients merken",
    nlnl  = "Account en wachtwoord onthouden bij het starten van de client",
    frfr  = "Se souvenir du compte et du mot de passe au démarrage du client",
    fi    = "Muista tili ja salasana asiakkaan käynnistyessä",
    it    = "Ricorda account e password all’avvio del client",
    zhcn  = "启动客户端时记住账号和密码",
    ja    = "クライアント起動時にアカウントとパスワードを記憶する",
    ko    = "클라이언트 시작 시 계정과 비밀번호 기억하기",
  },

  EnterGameAutoLoginCheckBox = {
    en    = "Auto login",
    ptbr  = "Login automático",
    ptpt  = "Início de sessão automático",
    es419 = "Inicio de sesión automático",
    eses  = "Inicio de sesión automático",
    pl    = "Automatyczne logowanie",
    ru    = "Автоматический вход",
    sv    = "Automatisk inloggning",
    nb    = "Automatisk innlogging",
    de    = "Automatische Anmeldung",
    nlnl  = "Automatisch aanmelden",
    frfr  = "Connexion automatique",
    fi    = "Automaattinen kirjautuminen",
    it    = "Accesso automatico",
    zhcn  = "自动登录",
    ja    = "自動ログイン",
    ko    = "자동 로그인",
  },

  EnterGameAutoLoginTooltip = {
    en    = "Open charlist automatically when starting client",
    ptbr  = "Abrir lista de personagens automaticamente ao iniciar o cliente",
    ptpt  = "Abrir a lista de personagens automaticamente ao iniciar o cliente",
    es419 = "Abrir la lista de personajes automáticamente al iniciar el cliente",
    eses  = "Abrir la lista de personajes automáticamente al iniciar el cliente",
    pl    = "Otwórz listę postaci automatycznie przy uruchomieniu klienta",
    ru    = "Автоматически открывать список персонажей при запуске клиента",
    sv    = "Öppna karaktärslistan automatiskt vid start av klienten",
    nb    = "Åpne karakterlisten automatisk ved start av klienten",
    de    = "Charakterliste automatisch beim Start des Clients öffnen",
    nlnl  = "Personagelijst automatisch openen bij het starten van de client",
    frfr  = "Ouvrir automatiquement la liste des personnages au démarrage du client",
    fi    = "Avaa hahmoluettelo automaattisesti asiakkaan käynnistyessä",
    it    = "Apri automaticamente la lista dei personaggi all’avvio del client",
    zhcn  = "启动客户端时自动打开角色列表",
    ja    = "クライアント起動時にキャラクター一覧を自動で開く",
    ko    = "클라이언트 시작 시 캐릭터 목록 자동으로 열기",
  },

  EnterGameEnterButton = {
    en    = "Enter",
    ptbr  = "Entrar",
    ptpt  = "Entrar",
    es419 = "Entrar",
    eses  = "Entrar",
    pl    = "Zaloguj się",
    ru    = "Войти",
    sv    = "Logga in",
    nb    = "Logg inn",
    de    = "Einloggen",
    nlnl  = "Aanmelden",
    frfr  = "Entrer",
    fi    = "Kirjaudu",
    it    = "Entra",
    zhcn  = "进入",
    ja    = "決定",
    ko    = "입장",
  },

  EnterGameMotdTitle = {
    en    = "Message of the day",
    ptbr  = "Mensagem do dia",
    ptpt  = "Mensagem do dia",
    es419 = "Mensaje del día",
    eses  = "Mensaje del día",
    pl    = "Wiadomość dnia",
    ru    = "Сообщение дня",
    sv    = "Dagens meddelande",
    nb    = "Dagens melding",
    de    = "Nachricht des Tages",
    nlnl  = "Bericht van de dag",
    frfr  = "Message du jour",
    fi    = "Päivän viesti",
    it    = "Messaggio del giorno",
    zhcn  = "每日消息",
    ja    = "本日のメッセージ",
    ko    = "오늘의 메시지",
  },

  EnterGameUpdateNeededTitle = {
    en    = "Update needed",
    ptbr  = "Atualização necessária",
    ptpt  = "Atualização necessária",
    es419 = "Actualización necesaria",
    eses  = "Actualización necesaria",
    pl    = "Wymagana aktualizacja",
    ru    = "Требуется обновление",
    sv    = "Uppdatering behövs",
    nb    = "Oppdatering kreves",
    de    = "Aktualisierung erforderlich",
    nlnl  = "Update vereist",
    frfr  = "Mise à jour requise",
    fi    = "Päivitys vaaditaan",
    it    = "Aggiornamento necessario",
    zhcn  = "需要更新",
    ja    = "更新が必要です",
    ko    = "업데이트 필요",
  },

  EnterGameUpdateNeededMessage = {
    en    = "Your client needs updating. Try redownloading it.",
    ptbr  = "Seu cliente precisa ser atualizado. Tente baixá-lo novamente.",
    ptpt  = "O seu cliente precisa de ser atualizado. Tente baixá-lo novamente.",
    es419 = "Tu cliente necesita ser actualizado. Intenta descargarlo nuevamente.",
    eses  = "Tu cliente necesita ser actualizado. Intenta descargarlo de nuevo.",
    pl    = "Twój klient wymaga aktualizacji. Spróbuj pobrać go ponownie.",
    ru    = "Ваш клиент нуждается в обновлении. Попробуйте скачать его заново.",
    sv    = "Din klient behöver uppdateras. Försök ladda ner den igen.",
    nb    = "Klienten din må oppdateres. Prøv å laste den ned på nytt.",
    de    = "Ihr Client muss aktualisiert werden. Versuchen Sie, ihn erneut herunterzuladen.",
    nlnl  = "Je client moet worden bijgewerkt. Probeer hem opnieuw te downloaden.",
    frfr  = "Votre client doit être mis à jour. Essayez de le télécharger à nouveau.",
    fi    = "Asiakas on päivitettävä. Yritä ladata se uudelleen.",
    it    = "Il client deve essere aggiornato. Prova a scaricarlo di nuovo.",
    zhcn  = "您的客户端需要更新。请尝试重新下载。",
    ja    = "クライアントを更新する必要があります。もう一度ダウンロードしてみてください。",
    ko    = "클라이언트를 업데이트해야 합니다. 다시 다운로드해 보세요.",
  },

  EnterGameClientModifiedTitle = {
    en    = "Info",
    ptbr  = "Informação",
    ptpt  = "Informação",
    es419 = "Información",
    eses  = "Información",
    pl    = "Informacja",
    ru    = "Информация",
    sv    = "Info",
    nb    = "Info",
    de    = "Info",
    nlnl  = "Info",
    frfr  = "Informations",
    fi    = "Tietoja",
    it    = "Informazioni",
    zhcn  = "信息",
    ja    = "情報",
    ko    = "정보",
  },

  EnterGameClientModifiedMessage = {
    en    = "Your client has been modified. Confirm to restart the client.",
    ptbr  = "Seu cliente foi modificado. Confirme para reiniciar o cliente.",
    ptpt  = "O seu cliente foi modificado. Confirme para reiniciar o cliente.",
    es419 = "Tu cliente ha sido modificado. Confirma para reiniciar el cliente.",
    eses  = "Tu cliente ha sido modificado. Confirma para reiniciar el cliente.",
    pl    = "Twój klient został zmodyfikowany. Potwierdź, aby ponownie uruchomić klienta.",
    ru    = "Ваш клиент был изменён. Подтвердите, чтобы перезапустить клиент.",
    sv    = "Din klient har ändrats. Bekräfta för att starta om klienten.",
    nb    = "Klienten din har blitt endret. Bekreft for å starte klienten på nytt.",
    de    = "Ihr Client wurde geändert. Bestätigen Sie, um den Client neu zu starten.",
    nlnl  = "Je client is gewijzigd. Bevestig om de client opnieuw te starten.",
    frfr  = "Votre client a été modifié. Confirmez pour redémarrer le client.",
    fi    = "Asiakasta on muokattu. Vahvista käynnistääksesi asiakkaan uudelleen.",
    it    = "Il client è stato modificato. Conferma per riavviare il client.",
    zhcn  = "您的客户端已被修改。请确认以重新启动客户端。",
    ja    = "クライアントが変更されています。確認してクライアントを再起動してください。",
    ko    = "클라이언트가 수정되었습니다. 확인하여 클라이언트를 다시 시작하세요.",
  },

  EnterGameLoggedAlreadyTitle = {
    en    = "Login error",
    ptbr  = "Erro de login",
    ptpt  = "Erro de início de sessão",
    es419 = "Error de inicio de sesión",
    eses  = "Error de inicio de sesión",
    pl    = "Błąd logowania",
    ru    = "Ошибка входа",
    sv    = "Inloggningsfel",
    nb    = "Påloggingsfeil",
    de    = "Anmeldefehler",
    nlnl  = "Aanmeldfout",
    frfr  = "Erreur de connexion",
    fi    = "Kirjautumisvirhe",
    it    = "Errore di accesso",
    zhcn  = "登录错误",
    ja    = "ログインエラー",
    ko    = "로그인 오류",
  },

  EnterGameLoggedAlreadyMessage = {
    en    = "Cannot login while already in game.",
    ptbr  = "Não é possível autenticar-se enquanto já estiver conectado no jogo.",
    ptpt  = "Não é possível iniciar sessão enquanto já estiver ligado ao jogo.",
    es419 = "No es posible autenticarse mientras ya estás conectado al juego.",
    eses  = "No es posible autenticarse mientras ya estás conectado al juego.",
    pl    = "Nie można się uwierzytelnić, gdy jesteś już połączony z grą.",
    ru    = "Невозможно пройти аутентификацию, уже находясь в игре.",
    sv    = "Det går inte att autentisera sig när du redan är ansluten till spelet.",
    nb    = "Kan ikke autentisere mens du allerede er tilkoblet spillet.",
    de    = "Eine Authentifizierung ist nicht möglich, während man bereits mit dem Spiel verbunden ist.",
    nlnl  = "Je kunt je niet authenticeren terwijl je al met het spel verbonden bent.",
    frfr  = "Impossible de s’authentifier lorsque vous êtes déjà connecté au jeu.",
    fi    = "Et voi todentaa itseäsi, kun olet jo yhteydessä peliin.",
    it    = "Non puoi autenticarti mentre sei già connesso al gioco.",
    zhcn  = "已连接到游戏时无法进行身份验证。",
    ja    = "すでにゲームに接続している間は認証できません。",
    ko    = "이미 게임에 연결된 상태에서는 인증할 수 없습니다.",
  },

  EnterGameConnectingToLoginServerMessage = {
    en    = "Connecting to login server...",
    ptbr  = "Conectando ao servidor de autenticação...",
    ptpt  = "A ligar ao servidor de autenticação...",
    es419 = "Conectando al servidor de autenticación...",
    eses  = "Conectando al servidor de autenticación...",
    pl    = "Łączenie z serwerem uwierzytelniania...",
    ru    = "Подключение к серверу аутентификации...",
    sv    = "Ansluter till autentiseringsservern...",
    nb    = "Kobler til autentiseringsserveren...",
    de    = "Verbindung zum Authentifizierungsserver wird hergestellt...",
    nlnl  = "Verbinden met de authenticatieserver...",
    frfr  = "Connexion au serveur d’authentification...",
    fi    = "Yhdistetään todennuspalvelimeen...",
    it    = "Connessione al server di autenticazione...",
    zhcn  = "正在连接认证服务器……",
    ja    = "認証サーバーに接続中…",
    ko    = "인증 서버에 연결하는 중...",
  },

  EnterGameLoginErrorTitle = {
    en    = "Login error",
    ptbr  = "Erro de login",
    ptpt  = "Erro de início de sessão",
    es419 = "Error de inicio de sesión",
    eses  = "Error de inicio de sesión",
    pl    = "Błąd logowania",
    ru    = "Ошибка входа",
    sv    = "Inloggningsfel",
    nb    = "Påloggingsfeil",
    de    = "Anmeldefehler",
    nlnl  = "Aanmeldfout",
    frfr  = "Erreur de connexion",
    fi    = "Kirjautumisvirhe",
    it    = "Errore di accesso",
    zhcn  = "登录错误",
    ja    = "ログインエラー",
    ko    = "로그인 오류",
  },

  EnterGameThingsNotLoadedTitle = {
    en    = "Login error",
    ptbr  = "Erro de login",
    ptpt  = "Erro de início de sessão",
    es419 = "Error de inicio de sesión",
    eses  = "Error de inicio de sesión",
    pl    = "Błąd logowania",
    ru    = "Ошибка входа",
    sv    = "Inloggningsfel",
    nb    = "Påloggingsfeil",
    de    = "Anmeldefehler",
    nlnl  = "Aanmeldfout",
    frfr  = "Erreur de connexion",
    fi    = "Kirjautumisvirhe",
    it    = "Errore di accesso",
    zhcn  = "登录错误",
    ja    = "ログインエラー",
    ko    = "로그인 오류",
  },

  EnterGameThingsNotLoadedMessage = {
    en    = "Things are not loaded. Put the spr and dat files in things/%d/<here>.",
    ptbr  = "Os arquivos não foram carregados. Insira os arquivos spr e dat em things/%d/<aqui>.",
    ptpt  = "Os ficheiros não foram carregados. Coloque os ficheiros spr e dat em things/%d/<aqui>.",
    es419 = "Los archivos no se cargaron. Coloca los archivos spr y dat en things/%d/<aquí>.",
    eses  = "Los archivos no se cargaron. Coloca los archivos spr y dat en things/%d/<aquí>.",
    pl    = "Pliki nie zostały załadowane. Umieść pliki spr i dat w things/%d/<tutaj>.",
    ru    = "Файлы не загружены. Поместите файлы spr и dat в things/%d/<сюда>.",
    sv    = "Filerna har inte laddats. Lägg spr- och dat-filerna i things/%d/<här>.",
    nb    = "Filene er ikke lastet inn. Legg spr- og dat-filene i things/%d/<her>.",
    de    = "Die Dateien wurden nicht geladen. Legen Sie die spr- und dat-Dateien in things/%d/<hier> ab.",
    nlnl  = "De bestanden zijn niet geladen. Plaats de spr- en dat-bestanden in things/%d/<hier>.",
    frfr  = "Les fichiers n’ont pas été chargés. Placez les fichiers spr et dat dans things/%d/<ici>.",
    fi    = "Tiedostoja ei ole ladattu. Sijoita spr- ja dat-tiedostot hakemistoon things/%d/<tänne>.",
    it    = "I file non sono stati caricati; inserisci i file spr e dat in things/%d/<qui>.",
    zhcn  = "文件未加载。请将 spr 和 dat 文件放入 things/%d/<这里>。",
    ja    = "ファイルが読み込まれていません。sprファイルとdatファイルをthings/%d/<ここ>に配置してください。",
    ko    = "파일이 로드되지 않았습니다. spr 및 dat 파일을 things/%d/<여기>에 넣으세요.",
  },

  EnterGamePreviewState = {
    en    = "Preview",
    ptbr  = "Pré-visualização",
    ptpt  = "Pré-visualização",
    es419 = "Vista previa",
    eses  = "Vista previa",
    pl    = "Podgląd",
    ru    = "Предпросмотр",
    sv    = "Förhandsgranskning",
    nb    = "Forhåndsvisning",
    de    = "Vorschau",
    nlnl  = "Voorbeeld",
    frfr  = "Aperçu",
    fi    = "Esikatselu",
    it    = "Anteprima",
    zhcn  = "预览",
    ja    = "プレビュー",
    ko    = "미리 보기",
  },
})
