-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameConditionsTabFilterDefaultTooltipShow = {
    en    = "Show default conditions",
    ptbr  = "Exibir condições padrão",
    ptpt  = "Exibir condições padrão",
    es419 = "Mostrar condiciones predeterminadas",
    eses  = "Mostrar condiciones predeterminadas",
    pl    = "Pokaż domyślne warunki",
    ru    = "Показывать стандартные состояния",
    sv    = "Visa standardtillstånd",
    nb    = "Vis standardtilstander",
    de    = "Standardzustände anzeigen",
    nlnl  = "Standaardtoestanden tonen",
    frfr  = "Afficher les conditions par défaut",
    fi    = "Näytä oletustilat",
    it    = "Mostra condizioni predefinite",
    zhcn  = "显示默认状态",
    ja    = "標準状態を表示",
    ko    = "기본 상태 표시",
  },

  GameConditionsTabFilterDefaultTooltipHide = {
    en    = "Hide default conditions",
    ptbr  = "Ocultar condições padrão",
    ptpt  = "Ocultar condições padrão",
    es419 = "Ocultar condiciones predeterminadas",
    eses  = "Ocultar condiciones predeterminadas",
    pl    = "Ukryj domyślne warunki",
    ru    = "Скрывать стандартные состояния",
    sv    = "Dölj standardtillstånd",
    nb    = "Skjul standardtilstander",
    de    = "Standardzustände ausblenden",
    nlnl  = "Standaardtoestanden verbergen",
    frfr  = "Masquer les conditions par défaut",
    fi    = "Piilota oletustilat",
    it    = "Nascondi condizioni predefinite",
    zhcn  = "隐藏默认状态",
    ja    = "標準状態を非表示",
    ko    = "기본 상태 숨기기",
  },

  GameConditionsTabFilterSelfPowersTooltipShow = {
    en    = "Show conditions caused by your powers",
    ptbr  = "Exibir condições causadas por seus poderes",
    ptpt  = "Exibir condições causadas pelos seus poderes",
    es419 = "Mostrar condiciones causadas por tus poderes",
    eses  = "Mostrar condiciones causadas por tus poderes",
    pl    = "Pokaż warunki spowodowane przez twoje moce",
    ru    = "Показывать состояния, вызванные вашими силами",
    sv    = "Visa tillstånd som orsakats av dina krafter",
    nb    = "Vis tilstander forårsaket av kreftene dine",
    de    = "Durch deine Kräfte verursachte Zustände anzeigen",
    nlnl  = "Toestanden veroorzaakt door je krachten tonen",
    frfr  = "Afficher les conditions causées par vos pouvoirs",
    fi    = "Näytä omien voimiesi aiheuttamat tilat",
    it    = "Mostra le condizioni causate dai tuoi poteri",
    zhcn  = "显示由你的力量造成的状态",
    ja    = "自分のパワーによる状態を表示",
    ko    = "자신의 능력으로 발생한 상태 표시",
  },

  GameConditionsTabFilterSelfPowersTooltipHide = {
    en    = "Hide conditions caused by your powers",
    ptbr  = "Ocultar condições causadas por seus poderes",
    ptpt  = "Ocultar condições causadas pelos seus poderes",
    es419 = "Ocultar condiciones causadas por tus poderes",
    eses  = "Ocultar condiciones causadas por tus poderes",
    pl    = "Ukryj warunki spowodowane przez twoje moce",
    ru    = "Скрывать состояния, вызванные вашими силами",
    sv    = "Dölj tillstånd som orsakats av dina krafter",
    nb    = "Skjul tilstander forårsaket av kreftene dine",
    de    = "Durch deine Kräfte verursachte Zustände ausblenden",
    nlnl  = "Toestanden veroorzaakt door je krachten verbergen",
    frfr  = "Masquer les conditions causées par vos pouvoirs",
    fi    = "Piilota omien voimiesi aiheuttamat tilat",
    it    = "Nascondi le condizioni causate dai tuoi poteri",
    zhcn  = "隐藏由你的力量造成的状态",
    ja    = "自分のパワーによる状態を非表示",
    ko    = "자신의 능력으로 발생한 상태 숨기기",
  },

  GameConditionsTabFilterOtherPowersTooltipShow = {
    en    = "Show conditions caused by powers from others",
    ptbr  = "Exibir condições causadas pelos poderes de outros",
    ptpt  = "Exibir condições causadas pelos poderes de outros",
    es419 = "Mostrar condiciones causadas por los poderes de otros",
    eses  = "Mostrar condiciones causadas por los poderes de otros",
    pl    = "Pokaż warunki spowodowane mocami innych",
    ru    = "Показывать состояния, вызванные силами других",
    sv    = "Visa tillstånd som orsakas av andras krafter",
    nb    = "Vis tilstander forårsaket av andres krefter",
    de    = "Bedingungen anzeigen, die durch die Kräfte anderer verursacht wurden",
    nlnl  = "Toestanden veroorzaakt door de krachten van anderen tonen",
    frfr  = "Afficher les conditions causées par les pouvoirs des autres",
    fi    = "Näytä muiden voimien aiheuttamat tilat",
    it    = "Mostra le condizioni causate dai poteri degli altri",
    zhcn  = "显示由他人的力量导致的状态",
    ja    = "他者のパワーによって引き起こされた状態を表示",
    ko    = "다른 사람의 능력으로 인해 발생한 상태 표시",
  },

  GameConditionsTabFilterOtherPowersTooltipHide = {
    en    = "Hide conditions caused by powers from others",
    ptbr  = "Ocultar condições causadas pelos poderes de outros",
    ptpt  = "Ocultar condições causadas pelos poderes de outros",
    es419 = "Ocultar condiciones causadas por los poderes de otros",
    eses  = "Ocultar condiciones causadas por los poderes de otros",
    pl    = "Ukryj warunki spowodowane mocami innych",
    ru    = "Скрывать состояния, вызванные силами других",
    sv    = "Dölj tillstånd som orsakas av andras krafter",
    nb    = "Skjul tilstander forårsaket av andres krefter",
    de    = "Bedingungen ausblenden, die durch die Kräfte anderer verursacht wurden",
    nlnl  = "Toestanden veroorzaakt door de krachten van anderen verbergen",
    frfr  = "Masquer les conditions causées par les pouvoirs des autres",
    fi    = "Piilota muiden voimien aiheuttamat tilat",
    it    = "Nascondi le condizioni causate dai poteri degli altri",
    zhcn  = "隐藏由他人的力量导致的状态",
    ja    = "他者のパワーによって引き起こされた状態を非表示",
    ko    = "다른 사람의 능력으로 인해 발생한 상태 숨기기",
  },

  GameConditionsTabFilterAggressiveTooltipShow = {
    en    = "Show aggressive conditions",
    ptbr  = "Exibir condições agressivas",
    ptpt  = "Exibir condições agressivas",
    es419 = "Mostrar condiciones agresivas",
    eses  = "Mostrar condiciones agresivas",
    pl    = "Pokaż agresywne warunki",
    ru    = "Показывать агрессивные состояния",
    sv    = "Visa aggressiva tillstånd",
    nb    = "Vis aggressive tilstander",
    de    = "Aggressive Bedingungen anzeigen",
    nlnl  = "Agressieve toestanden tonen",
    frfr  = "Afficher les conditions agressives",
    fi    = "Näytä aggressiiviset tilat",
    it    = "Mostra le condizioni aggressive",
    zhcn  = "显示攻击性状态",
    ja    = "攻撃的な状態を表示",
    ko    = "공격적인 상태 표시",
  },

  GameConditionsTabFilterAggressiveTooltipHide = {
    en    = "Hide aggressive conditions",
    ptbr  = "Ocultar condições agressivas",
    ptpt  = "Ocultar condições agressivas",
    es419 = "Ocultar condiciones agresivas",
    eses  = "Ocultar condiciones agresivas",
    pl    = "Ukryj agresywne warunki",
    ru    = "Скрывать агрессивные состояния",
    sv    = "Dölj aggressiva tillstånd",
    nb    = "Skjul aggressive tilstander",
    de    = "Aggressive Bedingungen ausblenden",
    nlnl  = "Agressieve toestanden verbergen",
    frfr  = "Masquer les conditions agressives",
    fi    = "Piilota aggressiiviset tilat",
    it    = "Nascondi le condizioni aggressive",
    zhcn  = "隐藏攻击性状态",
    ja    = "攻撃的な状態を非表示",
    ko    = "공격적인 상태 숨기기",
  },

  GameConditionsTabFilterNonAggressiveTooltipShow = {
    en    = "Show non-aggressive conditions",
    ptbr  = "Exibir condições não agressivas",
    ptpt  = "Exibir condições não agressivas",
    es419 = "Mostrar condiciones no agresivas",
    eses  = "Mostrar condiciones no agresivas",
    pl    = "Pokaż nieagresywne warunki",
    ru    = "Показывать неагрессивные состояния",
    sv    = "Visa icke-aggressiva tillstånd",
    nb    = "Vis ikke-aggressive tilstander",
    de    = "Nicht-aggressive Bedingungen anzeigen",
    nlnl  = "Niet-agressieve toestanden tonen",
    frfr  = "Afficher les conditions non agressives",
    fi    = "Näytä ei-aggressiiviset tilat",
    it    = "Mostra condizioni non aggressive",
    zhcn  = "显示非攻击性状态",
    ja    = "非攻撃的な状態を表示",
    ko    = "비공격적 상태 표시",
  },

  GameConditionsTabFilterNonAggressiveTooltipHide = {
    en    = "Hide non-aggressive conditions",
    ptbr  = "Ocultar condições não agressivas",
    ptpt  = "Ocultar condições não agressivas",
    es419 = "Ocultar condiciones no agresivas",
    eses  = "Ocultar condiciones no agresivas",
    pl    = "Ukryj nieagresywne warunki",
    ru    = "Скрывать неагрессивные состояния",
    sv    = "Dölj icke-aggressiva tillstånd",
    nb    = "Skjul ikke-aggressive tilstander",
    de    = "Nicht-aggressive Bedingungen ausblenden",
    nlnl  = "Niet-agressieve toestanden verbergen",
    frfr  = "Masquer les conditions non agressives",
    fi    = "Piilota ei-aggressiiviset tilat",
    it    = "Nascondi condizioni non aggressive",
    zhcn  = "隐藏非攻击性状态",
    ja    = "非攻撃的な状態を隠す",
    ko    = "비공격적 상태 숨기기",
  },

  GameConditionsSortAppear = {
    en    = "Appear",
    ptbr  = "Aparecer",
    ptpt  = "Aparecer",
    es419 = "Aparecer",
    eses  = "Aparecer",
    pl    = "Pojawienie się",
    ru    = "Появление",
    sv    = "Visning",
    nb    = "Visning",
    de    = "Erscheinen",
    nlnl  = "Verschijnen",
    frfr  = "Apparition",
    fi    = "Ilmestymisaika",
    it    = "Apparizione",
    zhcn  = "出现",
    ja    = "出現",
    ko    = "표시",
  },

  GameConditionsSortPercentage = {
    en    = "Percentage",
    ptbr  = "Porcentagem",
    ptpt  = "Percentagem",
    es419 = "Porcentaje",
    eses  = "Porcentaje",
    pl    = "Procent",
    ru    = "Процент",
    sv    = "Procent",
    nb    = "Prosent",
    de    = "Prozentsatz",
    nlnl  = "Percentage",
    frfr  = "Pourcentage",
    fi    = "Prosenttiosuus",
    it    = "Percentuale",
    zhcn  = "百分比",
    ja    = "割合",
    ko    = "백분율",
  },

  GameConditionsSortRemainingTime = {
    en    = "Remaining time",
    ptbr  = "Tempo restante",
    ptpt  = "Tempo restante",
    es419 = "Tiempo restante",
    eses  = "Tiempo restante",
    pl    = "Pozostały czas",
    ru    = "Оставшееся время",
    sv    = "Återstående tid",
    nb    = "Gjenstående tid",
    de    = "Verbleibende Zeit",
    nlnl  = "Resterende tijd",
    frfr  = "Temps restant",
    fi    = "Jäljellä oleva aika",
    it    = "Tempo rimanente",
    zhcn  = "剩余时间",
    ja    = "残り時間",
    ko    = "남은 시간",
  },

  GameConditionsStatePoison = {
    en    = "You are poisoned",
    ptbr  = "Você está envenenado",
    ptpt  = "Você está envenenado",
    es419 = "Estás envenenado",
    eses  = "Estás envenenado",
    pl    = "Jesteś zatruty",
    ru    = "Вы отравлены",
    sv    = "Du är förgiftad",
    nb    = "Du er forgiftet",
    de    = "Du bist vergiftet",
    nlnl  = "Je bent vergiftigd",
    frfr  = "Vous êtes empoisonné",
    fi    = "Olet myrkytetty",
    it    = "Sei avvelenato",
    zhcn  = "你中毒了",
    ja    = "毒状態です",
    ko    = "당신은 중독되었습니다",
  },

  GameConditionsStateBurn = {
    en    = "You are burning",
    ptbr  = "Você está em chamas",
    ptpt  = "Você está em chamas",
    es419 = "Estás en llamas",
    eses  = "Estás en llamas",
    pl    = "Płoniesz",
    ru    = "Вы горите",
    sv    = "Du brinner",
    nb    = "Du brenner",
    de    = "Du brennst",
    nlnl  = "Je staat in brand",
    frfr  = "Vous brûlez",
    fi    = "Palat",
    it    = "Stai bruciando",
    zhcn  = "你着火了",
    ja    = "燃焼状態です",
    ko    = "당신은 불타고 있습니다",
  },

  GameConditionsStateEnergy = {
    en    = "You are electrified",
    ptbr  = "Você está eletrificado",
    ptpt  = "Você está eletrificado",
    es419 = "Estás electrificado",
    eses  = "Estás electrificado",
    pl    = "Jesteś naelektryzowany",
    ru    = "Вы наэлектризованы",
    sv    = "Du är elektrifierad",
    nb    = "Du er elektrifisert",
    de    = "Du bist elektrisiert",
    nlnl  = "Je bent geëlektrificeerd",
    frfr  = "Vous êtes électrifié",
    fi    = "Olet sähköistetty",
    it    = "Sei elettrificato",
    zhcn  = "你被电击了",
    ja    = "感電状態です",
    ko    = "당신은 감전되었습니다",
  },

  GameConditionsStateDrunk = {
    en    = "You are drunk",
    ptbr  = "Você está bêbado",
    ptpt  = "Você está bêbado",
    es419 = "Estás borracho",
    eses  = "Estás borracho",
    pl    = "Jesteś pijany",
    ru    = "Вы пьяны",
    sv    = "Du är berusad",
    nb    = "Du er beruset",
    de    = "Du bist betrunken",
    nlnl  = "Je bent dronken",
    frfr  = "Vous êtes ivre",
    fi    = "Olet humalassa",
    it    = "Sei ubriaco",
    zhcn  = "你喝醉了",
    ja    = "酔っています",
    ko    = "당신은 취했습니다",
  },

  GameConditionsStateManaShield = {
    en    = "You are protected by a magic shield",
    ptbr  = "Você está protegido por um escudo mágico",
    ptpt  = "Você está protegido por um escudo mágico",
    es419 = "Estás protegido por un escudo mágico",
    eses  = "Estás protegido por un escudo mágico",
    pl    = "Jesteś chroniony przez magiczną tarczę",
    ru    = "Вы защищены магическим щитом",
    sv    = "Du skyddas av en magisk sköld",
    nb    = "Du er beskyttet av et magisk skjold",
    de    = "Du wirst von einem magischen Schild geschützt",
    nlnl  = "Je wordt beschermd door een magisch schild",
    frfr  = "Vous êtes protégé par un bouclier magique",
    fi    = "Taikakilpi suojaa sinua",
    it    = "Sei protetto da uno scudo magico",
    zhcn  = "你受到魔法护盾的保护",
    ja    = "魔法の盾に守られています",
    ko    = "당신은 마법 방패의 보호를 받고 있습니다",
  },

  GameConditionsStateParalyze = {
    en    = "You are paralysed",
    ptbr  = "Você está paralisado",
    ptpt  = "Você está paralisado",
    es419 = "Estás paralizado",
    eses  = "Estás paralizado",
    pl    = "Jesteś sparaliżowany",
    ru    = "Вы парализованы",
    sv    = "Du är förlamad",
    nb    = "Du er lammet",
    de    = "Du bist gelähmt",
    nlnl  = "Je bent verlamd",
    frfr  = "Vous êtes paralysé",
    fi    = "Olet halvaantunut",
    it    = "Sei paralizzato",
    zhcn  = "你被麻痹了",
    ja    = "麻痺しています",
    ko    = "당신은 마비되었습니다",
  },

  GameConditionsStateHaste = {
    en    = "You are hasted",
    ptbr  = "Você está acelerado",
    ptpt  = "Você está acelerado",
    es419 = "Estás acelerado",
    eses  = "Estás acelerado",
    pl    = "Jesteś przyspieszony",
    ru    = "Вы ускорены",
    sv    = "Du är snabbare",
    nb    = "Du er raskere",
    de    = "Du bist beschleunigt",
    nlnl  = "Je bent versneld",
    frfr  = "Vous êtes accéléré",
    fi    = "Olet nopeutettu",
    it    = "Sei accelerato",
    zhcn  = "你被加速了",
    ja    = "加速しています",
    ko    = "당신은 가속되었습니다",
  },

  GameConditionsStateSwords = {
    en    = "You may not logout during a fight",
    ptbr  = "Você não pode sair durante uma batalha",
    ptpt  = "Você não pode sair durante uma batalha",
    es419 = "No puedes salir durante una batalla",
    eses  = "No puedes salir durante una batalla",
    pl    = "Nie możesz wylogować się podczas bitwy",
    ru    = "Вы не можете выйти во время битвы",
    sv    = "Du kan inte logga ut under en strid",
    nb    = "Du kan ikke logge ut under en kamp",
    de    = "Du kannst während eines Kampfes nicht ausloggen",
    nlnl  = "Je kunt niet uitloggen tijdens een gevecht",
    frfr  = "Vous ne pouvez pas vous déconnecter pendant une bataille",
    fi    = "Et voi kirjautua ulos taistelun aikana",
    it    = "Non puoi uscire durante una battaglia",
    zhcn  = "战斗期间无法退出",
    ja    = "戦闘中はログアウトできません",
    ko    = "전투 중에는 로그아웃할 수 없습니다",
  },

  GameConditionsStateDrowning = {
    en    = "You are drowning",
    ptbr  = "Você está se afogando",
    ptpt  = "Você está se afogando",
    es419 = "Te estás ahogando",
    eses  = "Te estás ahogando",
    pl    = "Toniesz",
    ru    = "Вы тонете",
    sv    = "Du drunknar",
    nb    = "Du drukner",
    de    = "Du ertrinkst",
    nlnl  = "Je verdrinkt",
    frfr  = "Vous vous noyez",
    fi    = "Olet hukkumassa",
    it    = "Stai annegando",
    zhcn  = "你正在溺水",
    ja    = "溺れています",
    ko    = "물에 빠져 있습니다",
  },

  GameConditionsStateFreezing = {
    en    = "You are freezing",
    ptbr  = "Você está congelando",
    ptpt  = "Você está congelando",
    es419 = "Te estás congelando",
    eses  = "Te estás congelando",
    pl    = "Zamarzasz",
    ru    = "Вы замерзаете",
    sv    = "Du fryser",
    nb    = "Du fryser",
    de    = "Du frierst",
    nlnl  = "Je bevriest",
    frfr  = "Vous gelez",
    fi    = "Olet jäätymässä",
    it    = "Stai congelando",
    zhcn  = "你正在冻结",
    ja    = "凍えています",
    ko    = "얼어가고 있습니다",
  },

  GameConditionsStateDazzled = {
    en    = "You are dazzled",
    ptbr  = "Você está deslumbrado",
    ptpt  = "Você está deslumbrado",
    es419 = "Estás deslumbrado",
    eses  = "Estás deslumbrado",
    pl    = "Jesteś oślepiony",
    ru    = "Вы ослеплены",
    sv    = "Du är bländad",
    nb    = "Du er blendet",
    de    = "Du bist geblendet",
    nlnl  = "Je bent verblind",
    frfr  = "Vous êtes ébloui",
    fi    = "Olet häikäistynyt",
    it    = "Sei abbagliato",
    zhcn  = "你被眩晕了",
    ja    = "目がくらんでいます",
    ko    = "눈이 부신 상태입니다",
  },

  GameConditionsStateCursed = {
    en    = "You are cursed",
    ptbr  = "Você está amaldiçoado",
    ptpt  = "Você está amaldiçoado",
    es419 = "Estás maldito",
    eses  = "Estás maldito",
    pl    = "Jesteś przeklęty",
    ru    = "Вы прокляты",
    sv    = "Du är förbannad",
    nb    = "Du er forbannet",
    de    = "Du bist verflucht",
    nlnl  = "Je bent vervloekt",
    frfr  = "Vous êtes maudit",
    fi    = "Olet kirottu",
    it    = "Sei maledetto",
    zhcn  = "你被诅咒了",
    ja    = "呪われています",
    ko    = "저주받았습니다",
  },

  GameConditionsStatePartyBuff = {
    en    = "You are strengthened",
    ptbr  = "Você está fortalecido",
    ptpt  = "Você está fortalecido",
    es419 = "Estás fortalecido",
    eses  = "Estás fortalecido",
    pl    = "Jesteś wzmocniony",
    ru    = "Вы усилены",
    sv    = "Du är förstärkt",
    nb    = "Du er forsterket",
    de    = "Du bist gestärkt",
    nlnl  = "Je bent versterkt",
    frfr  = "Vous êtes renforcé",
    fi    = "Olet vahvistunut",
    it    = "Sei potenziato",
    zhcn  = "你被强化了",
    ja    = "強化されています",
    ko    = "강화되었습니다",
  },

  GameConditionsStatePZBlock = {
    en    = "You may not logout or enter a protection zone",
    ptbr  = "Você não pode sair ou entrar em uma zona de proteção",
    ptpt  = "Você não pode sair ou entrar em uma zona de proteção",
    es419 = "No puedes desconectarte o entrar en una zona de protección",
    eses  = "No puedes desconectarte o entrar en una zona de protección",
    pl    = "Nie możesz się wylogować ani wejść do strefy ochronnej",
    ru    = "Вы не можете выйти из игры или войти в зону защиты",
    sv    = "Du kan inte logga ut eller gå in i en skyddszon",
    nb    = "Du kan ikke logge ut eller gå inn i en beskyttelsessone",
    de    = "Du kannst dich nicht ausloggen oder eine Schutzzone betreten",
    nlnl  = "Je mag niet uitloggen of een beschermingszone binnengaan",
    frfr  = "Vous ne pouvez pas vous déconnecter ni entrer dans une zone de protection",
    fi    = "Et voi kirjautua ulos tai mennä suoja-alueelle",
    it    = "Non puoi disconnetterti o entrare in una zona di protezione",
    zhcn  = "你不能登出或进入保护区",
    ja    = "ログアウトしたり保護区域に入ったりすることはできません",
    ko    = "로그아웃하거나 보호 구역에 들어갈 수 없습니다",
  },

  GameConditionsStateSecure = {
    en    = "You are secured",
    ptbr  = "Você está em segurança",
    ptpt  = "Você está em segurança",
    es419 = "Estás a salvo",
    eses  = "Estás a salvo",
    pl    = "Jesteś bezpieczny",
    ru    = "Вы в безопасности",
    sv    = "Du är säker",
    nb    = "Du er trygg",
    de    = "Du bist in Sicherheit",
    nlnl  = "Je bent veilig",
    frfr  = "Vous êtes en sécurité",
    fi    = "Olet turvassa",
    it    = "Sei al sicuro",
    zhcn  = "你处于安全状态",
    ja    = "安全な状態です",
    ko    = "안전한 상태입니다",
  },

  GameConditionsStateBleeding = {
    en    = "You are bleeding",
    ptbr  = "Você está sangrando",
    ptpt  = "Está a sangrar",
    es419 = "Estás sangrando",
    eses  = "Estás sangrando",
    pl    = "Krwawisz",
    ru    = "Вы истекаете кровью",
    sv    = "Du blöder",
    nb    = "Du blør",
    de    = "Du blutest",
    nlnl  = "Je bloedt",
    frfr  = "Vous saignez",
    fi    = "Vuodat verta",
    it    = "Stai sanguinando",
    zhcn  = "你正在流血",
    ja    = "出血しています",
    ko    = "출혈 중입니다",
  },

  GameConditionsStateHungry = {
    en    = "You are hungry",
    ptbr  = "Você está com fome",
    ptpt  = "Está com fome",
    es419 = "Tienes hambre",
    eses  = "Tienes hambre",
    pl    = "Jesteś głodny",
    ru    = "Вы голодны",
    sv    = "Du är hungrig",
    nb    = "Du er sulten",
    de    = "Du bist hungrig",
    nlnl  = "Je hebt honger",
    frfr  = "Vous avez faim",
    fi    = "Olet nälkäinen",
    it    = "Hai fame",
    zhcn  = "你饿了",
    ja    = "空腹です",
    ko    = "배고픕니다",
  },

  GameConditionsStateSecureBlock = {
    en    = "You are within a secure blocked zone",
    ptbr  = "Você está em uma zona de bloqueio seguro",
    ptpt  = "Está numa zona de bloqueio seguro",
    es419 = "Estás en una zona de bloqueo seguro",
    eses  = "Estás en una zona de bloqueo seguro",
    pl    = "Jesteś w bezpiecznej strefie blokady",
    ru    = "Вы находитесь в безопасной зоне блокировки",
    sv    = "Du befinner dig i en säker blockerad zon",
    nb    = "Du befinner deg i en sikker blokkert sone",
    de    = "Du befindest dich in einer gesicherten Blockzone",
    nlnl  = "Je bevindt je in een beveiligde geblokkeerde zone",
    frfr  = "Vous êtes dans une zone de blocage sécurisée",
    fi    = "Olet suojatulla suljetulla alueella",
    it    = "Ti trovi in una zona di blocco sicura",
    zhcn  = "你位于安全封锁区域内",
    ja    = "安全な封鎖区域内です",
    ko    = "안전하게 차단된 구역에 있습니다",
  },

  GameConditionsStatePZ = {
    en    = "You are within a protection zone",
    ptbr  = "Você está em uma zona de proteção",
    ptpt  = "Está numa zona de proteção",
    es419 = "Estás en una zona de protección",
    eses  = "Estás en una zona de protección",
    pl    = "Jesteś w strefie ochronnej",
    ru    = "Вы находитесь в зоне защиты",
    sv    = "Du befinner dig i en skyddszon",
    nb    = "Du er i en beskyttelsessone",
    de    = "Du befindest dich in einer Schutzzone",
    nlnl  = "Je bevindt je in een beschermingszone",
    frfr  = "Vous êtes dans une zone de protection",
    fi    = "Olet suoja-alueella",
    it    = "Ti trovi in una zona di protezione",
    zhcn  = "你位于保护区域内",
    ja    = "保護区域内です",
    ko    = "보호 구역에 있습니다",
  },

  GameConditionsStateWZ = {
    en    = "You are within a white zone",
    ptbr  = "Você está em uma zona branca",
    ptpt  = "Está numa zona branca",
    es419 = "Estás en una zona blanca",
    eses  = "Estás en una zona blanca",
    pl    = "Jesteś w białej strefie",
    ru    = "Вы находитесь в белой зоне",
    sv    = "Du befinner dig i en vit zon",
    nb    = "Du er i en hvit sone",
    de    = "Du befindest dich in einer weißen Zone",
    nlnl  = "Je bevindt je in een witte zone",
    frfr  = "Vous êtes dans une zone blanche",
    fi    = "Olet valkoisella alueella",
    it    = "Ti trovi in una zona bianca",
    zhcn  = "你处于白色区域内",
    ja    = "ホワイトゾーン内にいます",
    ko    = "흰색 구역에 있습니다",
  },

  GameConditionsStateRZ = {
    en    = "You are within a red zone",
    ptbr  = "Você está em uma zona vermelha",
    ptpt  = "Está numa zona vermelha",
    es419 = "Estás en una zona roja",
    eses  = "Estás en una zona roja",
    pl    = "Jesteś w czerwonej strefie",
    ru    = "Вы находитесь в красной зоне",
    sv    = "Du befinner dig i en röd zon",
    nb    = "Du er i en rød sone",
    de    = "Du befindest dich in einer roten Zone",
    nlnl  = "Je bevindt je in een rode zone",
    frfr  = "Vous êtes dans une zone rouge",
    fi    = "Olet punaisella alueella",
    it    = "Ti trovi in una zona rossa",
    zhcn  = "你处于红色区域内",
    ja    = "レッドゾーン内にいます",
    ko    = "빨간색 구역에 있습니다",
  },

  GameConditionsStateBZ = {
    en    = "You are within a black zone",
    ptbr  = "Você está em uma zona preta",
    ptpt  = "Está numa zona preta",
    es419 = "Estás en una zona negra",
    eses  = "Estás en una zona negra",
    pl    = "Jesteś w czarnej strefie",
    ru    = "Вы находитесь в чёрной зоне",
    sv    = "Du befinner dig i en svart zon",
    nb    = "Du er i en svart sone",
    de    = "Du befindest dich in einer schwarzen Zone",
    nlnl  = "Je bevindt je in een zwarte zone",
    frfr  = "Vous êtes dans une zone noire",
    fi    = "Olet mustalla alueella",
    it    = "Ti trovi in una zona nera",
    zhcn  = "你处于黑色区域内",
    ja    = "ブラックゾーン内にいます",
    ko    = "검은색 구역에 있습니다",
  },

  GameConditionsInfoOrder = {
    en    = "Order",
    ptbr  = "Ordem",
    ptpt  = "Ordem",
    es419 = "Orden",
    eses  = "Orden",
    pl    = "Kolejność",
    ru    = "Порядок",
    sv    = "Ordning",
    nb    = "Rekkefølge",
    de    = "Reihenfolge",
    nlnl  = "Volgorde",
    frfr  = "Ordre",
    fi    = "Järjestys",
    it    = "Ordine",
    zhcn  = "顺序",
    ja    = "順序",
    ko    = "순서",
  },
})
