-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  CharacterWindowTitle = {
    en    = "Character",
    ptbr  = "Personagem",
    ptpt  = "Personagem",
    es419 = "Personaje",
    eses  = "Personaje",
    pl    = "Postać",
    ru    = "Персонаж",
    sv    = "Karaktär",
    nb    = "Figur",
    de    = "Charakter",
    nlnl  = "Personage",
    frfr  = "Personnage",
    fi    = "Hahmo",
    it    = "Personaggio",
    zhcn  = "角色",
    ja    = "キャラクター",
    ko    = "캐릭터",
  },

  CharacterFightOffensiveBox = {
    en    = "Offensive combat mode",
    ptbr  = "Modo de combate ofensivo",
    ptpt  = "Modo de combate ofensivo",
    es419 = "Modo de combate ofensivo",
    eses  = "Modo de combate ofensivo",
    pl    = "Ofensywny tryb walki",
    ru    = "Атакующий боевой режим",
    sv    = "Offensivt stridsläge",
    nb    = "Offensiv kampmodus",
    de    = "Offensiver Kampfmodus",
    nlnl  = "Agressieve gevechtsmodus",
    frfr  = "Mode de combat offensif",
    fi    = "Hyökkäävä taistelutila",
    it    = "Modalità di combattimento offensiva",
    zhcn  = "进攻战斗模式",
    ja    = "攻撃戦闘モード",
    ko    = "공격 전투 모드",
  },

  CharacterFightBalancedBox = {
    en    = "Balanced combat mode",
    ptbr  = "Modo de combate equilibrado",
    ptpt  = "Modo de combate equilibrado",
    es419 = "Modo de combate equilibrado",
    eses  = "Modo de combate equilibrado",
    pl    = "Zrównoważony tryb walki",
    ru    = "Сбалансированный боевой режим",
    sv    = "Balanserat stridsläge",
    nb    = "Balansert kampmodus",
    de    = "Ausgewogener Kampfmodus",
    nlnl  = "Gebalanceerde gevechtsmodus",
    frfr  = "Mode de combat équilibré",
    fi    = "Tasapainoinen taistelutila",
    it    = "Modalità di combattimento bilanciata",
    zhcn  = "平衡战斗模式",
    ja    = "バランス戦闘モード",
    ko    = "균형 전투 모드",
  },

  CharacterFightDefensiveBox = {
    en    = "Defensive combat mode",
    ptbr  = "Modo de combate defensivo",
    ptpt  = "Modo de combate defensivo",
    es419 = "Modo de combate defensivo",
    eses  = "Modo de combate defensivo",
    pl    = "Defensywny tryb walki",
    ru    = "Защитный боевой режим",
    sv    = "Defensivt stridsläge",
    nb    = "Defensiv kampmodus",
    de    = "Defensiver Kampfmodus",
    nlnl  = "Defensieve gevechtsmodus",
    frfr  = "Mode de combat défensif",
    fi    = "Puolustava taistelutila",
    it    = "Modalità di combattimento difensiva",
    zhcn  = "防御战斗模式",
    ja    = "防御戦闘モード",
    ko    = "방어 전투 모드",
  },

  CharacterChaseModeBox = {
    en    = "Chase mode",
    ptbr  = "Modo de perseguição",
    ptpt  = "Modo de perseguição",
    es419 = "Modo de persecución",
    eses  = "Modo de persecución",
    pl    = "Tryb pościgu",
    ru    = "Режим преследования",
    sv    = "Jaktläge",
    nb    = "Jaktmodus",
    de    = "Verfolgungsmodus",
    nlnl  = "Volgmodus",
    frfr  = "Mode poursuite",
    fi    = "Takaa-ajotila",
    it    = "Modalità inseguimento",
    zhcn  = "追击模式",
    ja    = "追跡モード",
    ko    = "추적 모드",
  },

  CharacterSafeFightBox = {
    en    = "Secure mode",
    ptbr  = "Modo seguro",
    ptpt  = "Modo seguro",
    es419 = "Modo seguro",
    eses  = "Modo seguro",
    pl    = "Tryb bezpieczny",
    ru    = "Безопасный режим",
    sv    = "Säkert läge",
    nb    = "Sikker modus",
    de    = "Sicherer Modus",
    nlnl  = "Veilige modus",
    frfr  = "Mode sécurisé",
    fi    = "Turvatila",
    it    = "Modalità sicura",
    zhcn  = "安全模式",
    ja    = "安全モード",
    ko    = "보안 모드",
  },

  CharacterMountButton = {
    en    = "Mounting",
    ptbr  = "Montar",
    ptpt  = "Montar",
    es419 = "Montar",
    eses  = "Montar",
    pl    = "Wsiadać",
    ru    = "Сесть на ездовое животное",
    sv    = "Rida",
    nb    = "Ri",
    de    = "Aufsteigen",
    nlnl  = "Opstijgen",
    frfr  = "Monter",
    fi    = "Ratsastaa",
    it    = "Montare",
    zhcn  = "骑乘",
    ja    = "騎乗",
    ko    = "탑승",
  },

  CharacterInfoButtonMore = {
    en    = "Show more",
    ptbr  = "Exibir mais",
    ptpt  = "Exibir mais",
    es419 = "Mostrar más",
    eses  = "Mostrar más",
    pl    = "Pokaż więcej",
    ru    = "Показать больше",
    sv    = "Visa mer",
    nb    = "Vis mer",
    de    = "Mehr anzeigen",
    nlnl  = "Meer tonen",
    frfr  = "Afficher plus",
    fi    = "Näytä lisää",
    it    = "Mostra di più",
    zhcn  = "显示更多",
    ja    = "さらに表示",
    ko    = "더 보기",
  },

  CharacterInfoButtonLess = {
    en    = "Show less",
    ptbr  = "Exibir menos",
    ptpt  = "Exibir menos",
    es419 = "Mostrar menos",
    eses  = "Mostrar menos",
    pl    = "Pokaż mniej",
    ru    = "Показать меньше",
    sv    = "Visa mindre",
    nb    = "Vis mindre",
    de    = "Weniger anzeigen",
    nlnl  = "Minder tonen",
    frfr  = "Afficher moins",
    fi    = "Näytä vähemmän",
    it    = "Mostra meno",
    zhcn  = "显示更少",
    ja    = "表示を減らす",
    ko    = "간략히 보기",
  },

BarHealthTooltip = {
  en    = "Your character health is %s out of %s.\nClick to show creatures health bar.",
  ptbr  = "A saúde do seu personagem é %s de %s.\nClique para exibir a barra de saúde das criaturas.",
  ptpt  = "A saúde do seu personagem é %s de %s.\nClique para exibir a barra de saúde das criaturas.",
  es419 = "La salud de tu personaje es %s de %s.\nHaz clic para mostrar la barra de salud de las criaturas.",
  eses  = "La salud de tu personaje es %s de %s.\nHaz clic para mostrar la barra de salud de las criaturas.",
  pl    = "Zdrowie twojej postaci wynosi %s z %s.\nKliknij, aby wyświetlić pasek zdrowia stworzeń.",
  ru    = "Здоровье вашего персонажа составляет %s из %s.\nНажмите, чтобы показать шкалу здоровья существ.",
  sv    = "Din karaktärs hälsa är %s av %s.\nKlicka för att visa varelsernas hälsomätare.",
  nb    = "Figurens helse er %s av %s.\nKlikk for å vise helsefeltet til skapningene.",
  de    = "Die Gesundheit deines Charakters beträgt %s von %s.\nKlicke, um die Gesundheitsleiste der Kreaturen anzuzeigen.",
  nlnl  = "De gezondheid van je personage is %s van %s.\nKlik om de gezondheidsbalk van wezens te tonen.",
  frfr  = "La santé de votre personnage est de %s sur %s.\nCliquez pour afficher la barre de santé des créatures.",
  fi    = "Hahmosi terveys on %s/%s.\nNapsauta näyttääksesi olentojen terveyspalkin.",
  it    = "La salute del tuo personaggio è %s su %s.\nFai clic per mostrare la barra della salute delle creature.",
  zhcn  = "你的角色生命值为 %s/%s。\n点击以显示生物的生命值条。",
  ja    = "キャラクターの体力は%s / %sです。\nクリックするとクリーチャーの体力バーを表示します。",
  ko    = "캐릭터의 체력은 %s/%s입니다.\n클릭하면 생물의 체력 바를 표시합니다.",
},

BarManaTooltip = {
  en    = "Your character mana is %s out of %s.\nClick to show players mana bar.",
  ptbr  = "A mana do seu personagem é %s de %s.\nClique para exibir a barra de mana dos jogadores.",
  ptpt  = "A mana do seu personagem é %s de %s.\nClique para exibir a barra de mana dos jogadores.",
  es419 = "El maná de tu personaje es %s de %s.\nHaz clic para mostrar la barra de maná de los jugadores.",
  eses  = "El maná de tu personaje es %s de %s.\nHaz clic para mostrar la barra de maná de los jugadores.",
  pl    = "Mana twojej postaci wynosi %s z %s.\nKliknij, aby wyświetlić pasek many graczy.",
  ru    = "Мана вашего персонажа составляет %s из %s.\nНажмите, чтобы показать шкалу маны игроков.",
  sv    = "Din karaktärs mana är %s av %s.\nKlicka för att visa spelarnas manamätare.",
  nb    = "Figurens mana er %s av %s.\nKlikk for å vise spillernes manafelt.",
  de    = "Das Mana deines Charakters beträgt %s von %s.\nKlicke, um die Manaleiste der Spieler anzuzeigen.",
  nlnl  = "De mana van je personage is %s van %s.\nKlik om de manabalk van spelers te tonen.",
  frfr  = "Le mana de votre personnage est de %s sur %s.\nCliquez pour afficher la barre de mana des joueurs.",
  fi    = "Hahmosi mana on %s/%s.\nNapsauta näyttääksesi pelaajien manapalkin.",
  it    = "Il mana del tuo personaggio è %s su %s.\nFai clic per mostrare la barra del mana dei giocatori.",
  zhcn  = "你的角色法力值为 %s/%s。\n点击以显示玩家的法力值条。",
  ja    = "キャラクターのマナは%s / %sです。\nクリックするとプレイヤーのマナバーを表示します。",
  ko    = "캐릭터의 마나는 %s/%s입니다.\n클릭하면 플레이어의 마나 바를 표시합니다.",
},

  BarVigorTooltip = {
    en    = "Your character vigor is %s out of %s.\nClick to show players vigor bar.",
    ptbr  = "O vigor do seu personagem é %s de %s.\nClique para exibir a barra de vigor dos jogadores.",
    ptpt  = "O vigor do seu personagem é %s de %s.\nClique para exibir a barra de vigor dos jogadores.",
    es419 = "El vigor de tu personaje es %s de %s.\nHaz clic para mostrar la barra de vigor de los jugadores.",
    eses  = "El vigor de tu personaje es %s de %s.\nHaz clic para mostrar la barra de vigor de los jugadores.",
    pl    = "Wigor twojej postaci wynosi %s z %s.\nKliknij, aby wyświetlić pasek wigoru graczy.",
    ru    = "Энергия вашего персонажа составляет %s из %s.\nНажмите, чтобы показать шкалу энергии игроков.",
    sv    = "Din karaktärs energi är %s av %s.\nKlicka för att visa spelarnas energimätare.",
    nb    = "Figurens energi er %s av %s.\nKlikk for å vise spillernes energifelt.",
    de    = "Die Ausdauer deines Charakters beträgt %s von %s.\nKlicke, um die Ausdauerleiste der Spieler anzuzeigen.",
    nlnl  = "De vitaliteit van je personage is %s van %s.\nKlik om de vitaliteitsbalk van spelers te tonen.",
    frfr  = "La vigueur de votre personnage est de %s sur %s.\nCliquez pour afficher la barre de vigueur des joueurs.",
    fi    = "Hahmosi vireys on %s/%s.\nNapsauta näyttääksesi pelaajien vireyspalkin.",
    it    = "Il vigore del tuo personaggio è %s su %s.\nFai clic per mostrare la barra del vigore dei giocatori.",
    zhcn  = "你的角色活力值为 %s/%s。\n点击以显示玩家的活力值条。",
    ja    = "キャラクターの活力は%s / %sです。\nクリックするとプレイヤーの活力バーを表示します。",
    ko    = "캐릭터의 활력은 %s/%s입니다.\n클릭하면 플레이어의 활력 바를 표시합니다.",
  },

  BarCapacityTooltip = {
    en    = "Your character load weighs %s oz out of %s oz%s.",
    ptbr  = "A carga do seu personagem pesa %s oz de %s oz%s.",
    ptpt  = "A carga do seu personagem pesa %s oz de %s oz%s.",
    es419 = "La carga de tu personaje pesa %s oz de %s oz%s.",
    eses  = "La carga de tu personaje pesa %s oz de %s oz%s.",
    pl    = "Ładunek twojej postaci waży %s oz z %s oz%s.",
    ru    = "Груз вашего персонажа весит %s oz из %s oz%s.",
    sv    = "Din karaktärs last väger %s oz av %s oz%s.",
    nb    = "Lasten til figuren din veier %s oz av %s oz%s.",
    de    = "Die Last deines Charakters wiegt %s oz von %s oz%s.",
    nlnl  = "De lading van je personage weegt %s oz van %s oz%s.",
    frfr  = "La charge de votre personnage pèse %s oz sur %s oz%s.",
    fi    = "Hahmosi kuorma painaa %s oz / %s oz%s.",
    it    = "Il carico del tuo personaggio pesa %s oz su %s oz%s.",
    zhcn  = "你的角色负重为 %s oz / %s oz%s。",
    ja    = "キャラクターの荷重は%s oz / %s oz%sです。",
    ko    = "캐릭터의 무게는 %s oz/%s oz%s입니다.",
  },

  BarCapacityTooltipOverweight = {
    en    = "overweight",
    ptbr  = "acima do peso",
    ptpt  = "acima do peso",
    es419 = "sobrepeso",
    eses  = "sobrepeso",
    pl    = "przeciążony",
    ru    = "перегруз",
    sv    = "övervikt",
    nb    = "overvekt",
    de    = "überladen",
    nlnl  = "overbelast",
    frfr  = "en surcharge",
    fi    = "ylipainoinen",
    it    = "sovraccarico",
    zhcn  = "超重",
    ja    = "重量超過",
    ko    = "초과 중량",
  },

  BarExperienceTooltip = {
    en    = "%s\nClick to show your experience bar.",
    ptbr  = "%s\nClique para exibir sua barra de experiência.",
    ptpt  = "%s\nClique para exibir sua barra de experiência.",
    es419 = "%s\nHaz clic para mostrar tu barra de experiencia.",
    eses  = "%s\nHaz clic para mostrar tu barra de experiencia.",
    pl    = "%s\nKliknij, aby wyświetlić pasek doświadczenia.",
    ru    = "%s\nНажмите, чтобы показать шкалу опыта.",
    sv    = "%s\nKlicka för att visa din erfarenhetsmätare.",
    nb    = "%s\nKlikk for å vise erfaringsfeltet ditt.",
    de    = "%s\nKlicke, um deine Erfahrungsleiste anzuzeigen.",
    nlnl  = "%s\nKlik om je ervaringsbalk te tonen.",
    frfr  = "%s\nCliquez pour afficher votre barre d'expérience.",
    fi    = "%s\nNapsauta näyttääksesi kokemuspalkin.",
    it    = "%s\nFai clic per mostrare la tua barra dell'esperienza.",
    zhcn  = "%s\n点击以显示你的经验值条。",
    ja    = "%s\nクリックすると経験値バーを表示します。",
    ko    = "%s\n클릭하면 경험치 바를 표시합니다.",
  },

  CharacterStatsWindowShow = {
    en    = "Show stats",
    ptbr  = "Exibir estatísticas",
    ptpt  = "Exibir estatísticas",
    es419 = "Mostrar estadísticas",
    eses  = "Mostrar estadísticas",
    pl    = "Pokaż statystyki",
    ru    = "Показать характеристики",
    sv    = "Visa statistik",
    nb    = "Vis statistikk",
    de    = "Statistiken anzeigen",
    nlnl  = "Statistieken tonen",
    frfr  = "Afficher les statistiques",
    fi    = "Näytä tilastot",
    it    = "Mostra statistiche",
    zhcn  = "显示属性",
    ja    = "ステータスを表示",
    ko    = "능력치 표시",
  },

  CharacterStatsWindowHide = {
    en    = "Hide stats",
    ptbr  = "Ocultar estatísticas",
    ptpt  = "Ocultar estatísticas",
    es419 = "Ocultar estadísticas",
    eses  = "Ocultar estadísticas",
    pl    = "Ukryj statystyki",
    ru    = "Скрыть характеристики",
    sv    = "Dölj statistik",
    nb    = "Skjul statistikk",
    de    = "Statistiken ausblenden",
    nlnl  = "Statistieken verbergen",
    frfr  = "Masquer les statistiques",
    fi    = "Piilota tilastot",
    it    = "Nascondi statistiche",
    zhcn  = "隐藏属性",
    ja    = "ステータスを隠す",
    ko    = "능력치 숨기기",
  },

  CharacterInventoryWindowShow = {
    en    = "Show inventory",
    ptbr  = "Exibir inventário",
    ptpt  = "Exibir inventário",
    es419 = "Mostrar inventario",
    eses  = "Mostrar inventario",
    pl    = "Pokaż ekwipunek",
    ru    = "Показать инвентарь",
    sv    = "Visa inventering",
    nb    = "Vis inventar",
    de    = "Inventar anzeigen",
    nlnl  = "Inventaris tonen",
    frfr  = "Afficher l'inventaire",
    fi    = "Näytä varasto",
    it    = "Mostra inventario",
    zhcn  = "显示背包",
    ja    = "インベントリを表示",
    ko    = "인벤토리 표시",
  },

  CharacterInventoryWindowHide = {
    en    = "Hide inventory",
    ptbr  = "Ocultar inventário",
    ptpt  = "Ocultar inventário",
    es419 = "Ocultar inventario",
    eses  = "Ocultar inventario",
    pl    = "Ukryj ekwipunek",
    ru    = "Скрыть инвентарь",
    sv    = "Dölj inventering",
    nb    = "Skjul inventar",
    de    = "Inventar ausblenden",
    nlnl  = "Inventaris verbergen",
    frfr  = "Masquer l'inventaire",
    fi    = "Piilota varasto",
    it    = "Nascondi inventario",
    zhcn  = "隐藏背包",
    ja    = "インベントリを隠す",
    ko    = "인벤토리 숨기기",
  },

  CharacterButtonShopTooltip = {
    en    = "Visit the VIP shop on our Website",
    ptbr  = "Visite a loja VIP no nosso site",
    ptpt  = "Visite a loja VIP no nosso site",
    es419 = "Visita la tienda VIP en nuestro sitio web",
    eses  = "Visita la tienda VIP en nuestro sitio web",
    pl    = "Odwiedź sklep VIP na naszej stronie internetowej",
    ru    = "Посетите VIP-магазин на нашем сайте",
    sv    = "Besök VIP-butiken på vår webbplats",
    nb    = "Besøk VIP-butikken på nettstedet vårt",
    de    = "Besuche den VIP-Shop auf unserer Website",
    nlnl  = "Bezoek de VIP-winkel op onze website",
    frfr  = "Visitez la boutique VIP sur notre site web",
    fi    = "Vieraile verkkosivustomme VIP-kaupassa",
    it    = "Visita il negozio VIP sul nostro sito web",
    zhcn  = "访问我们网站上的 VIP 商店",
    ja    = "ウェブサイトのVIPショップを見る",
    ko    = "웹사이트의 VIP 상점을 방문하세요",
  },

  CharacterButtonDealsTooltip = {
    en    = "Deals",
    ptbr  = "Ofertas",
    ptpt  = "Ofertas",
    es419 = "Ofertas",
    eses  = "Ofertas",
    pl    = "Oferty",
    ru    = "Предложения",
    sv    = "Erbjudanden",
    nb    = "Tilbud",
    de    = "Angebote",
    nlnl  = "Aanbiedingen",
    frfr  = "Offres",
    fi    = "Tarjoukset",
    it    = "Offerte",
    zhcn  = "优惠",
    ja    = "オファー",
    ko    = "상품",
  },
})
