-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameSkillsInfoXP = {
    en    = "EXP",
    ptbr  = "EXP",
    ptpt  = "EXP",
    es419 = "EXP",
    eses  = "EXP",
    pl    = "EXP",
    ru    = "EXP",
    sv    = "EXP",
    nb    = "EXP",
    de    = "EXP",
    nlnl  = "EXP",
    frfr  = "EXP",
    fi    = "Kokemus",
    it    = "EXP",
    zhcn  = "EXP",
    ja    = "経験値",
    ko    = "경험치",
  },

  GameSkillsInfoSpeed = {
    en    = "Speed",
    ptbr  = "Velocidade",
    ptpt  = "Velocidade",
    es419 = "Velocidad",
    eses  = "Velocidad",
    pl    = "Szybkość",
    ru    = "Скорость",
    sv    = "Hastighet",
    nb    = "Hastighet",
    de    = "Geschwindigkeit",
    nlnl  = "Snelheid",
    frfr  = "Vitesse",
    fi    = "Nopeus",
    it    = "Velocità",
    zhcn  = "速度",
    ja    = "速度",
    ko    = "속도",
  },

  GameSkillsInfoFeedTime = {
    en    = "Feed time",
    ptbr  = "Tempo alimentado",
    ptpt  = "Tempo alimentado",
    es419 = "Tiempo de alimentación",
    eses  = "Tiempo de alimentación",
    pl    = "Czas karmienia",
    ru    = "Время кормления",
    sv    = "Matningstid",
    nb    = "Fôringstid",
    de    = "Fütterungszeit",
    nlnl  = "Voertijd",
    frfr  = "Temps d'alimentation",
    fi    = "Ruokinta-aika",
    it    = "Tempo di alimentazione",
    zhcn  = "喂食时间",
    ja    = "給餌時間",
    ko    = "먹이 시간",
  },

  GameSkillsInfoStamina = {
    en    = "Stamina",
    ptbr  = "Energia",
    ptpt  = "Energia",
    es419 = "Resistencia",
    eses  = "Resistencia",
    pl    = "Wytrzymałość",
    ru    = "Выносливость",
    sv    = "Uthållighet",
    nb    = "Utholdenhet",
    de    = "Ausdauer",
    nlnl  = "Uithoudingsvermogen",
    frfr  = "Endurance",
    fi    = "Kestävyys",
    it    = "Stamina",
    zhcn  = "耐力",
    ja    = "スタミナ",
    ko    = "체력",
  },

  GameSkillsInfoFocusPoints = {
    en    = "Focus points",
    ptbr  = "Pontos de foco",
    ptpt  = "Pontos de foco",
    es419 = "Puntos de enfoque",
    eses  = "Puntos de enfoque",
    pl    = "Punkty skupienia",
    ru    = "Очки концентрации",
    sv    = "Fokuspunkter",
    nb    = "Fokuspunkter",
    de    = "Fokuspunkte",
    nlnl  = "Focuspunten",
    frfr  = "Points de concentration",
    fi    = "Keskittymispisteet",
    it    = "Punti concentrazione",
    zhcn  = "专注点",
    ja    = "集中ポイント",
    ko    = "집중력 포인트",
  },

  GameSkillsStaminaRemainingTime = {
    en    = "Remaining %s%% (%s hours and %s minutes).",
    ptbr  = "Restante %s%% (%s horas e %s minutos).",
    ptpt  = "Restante %s%% (%s horas e %s minutos).",
    es419 = "Restante %s%% (%s horas y %s minutos).",
    eses  = "Restante %s%% (%s horas y %s minutos).",
    pl    = "Pozostało %s%% (%s godzin i %s minut).",
    ru    = "Осталось %s%% (%s ч. и %s мин.).",
    sv    = "Återstående %s%% (%s timmar och %s minuter).",
    nb    = "Gjenstående %s%% (%s timer og %s minutter).",
    de    = "Verbleibend %s%% (%s Stunden und %s Minuten).",
    nlnl  = "Resterend %s%% (%s uur en %s minuten).",
    frfr  = "Restant %s%% (%s heures et %s minutes).",
    fi    = "Jäljellä %s%% (%s tuntia ja %s minuuttia).",
    it    = "Rimanente %s%% (%s ore e %s minuti).",
    zhcn  = "剩余 %s%%（%s小时%s分钟）。",
    ja    = "残り%s%%（%s時間%s分）。",
    ko    = "남은 시간 %s%% (%s시간 %s분).",
  },

  GameSkillsStaminaExpNerf = {
    en    = "You are receiving only 50%% of experience and you may not receive loot from monsters.",
    ptbr  = "Você está recebendo apenas 50%% de experiência e pode não receber itens dos monstros.",
    ptpt  = "Você está recebendo apenas 50%% de experiência e pode não receber itens dos monstros.",
    es419 = "Solo recibes el 50%% de experiencia y es posible que no recibas objetos de los monstruos.",
    eses  = "Solo recibes el 50%% de experiencia y es posible que no recibas objetos de los monstruos.",
    pl    = "Otrzymujesz tylko 50%% doświadczenia i możesz nie otrzymać przedmiotów od potworów.",
    ru    = "Вы получаете только 50%% опыта и можете не получить предметы с монстров.",
    sv    = "Du får endast 50%% av erfarenheten och kanske inte får föremål från monster.",
    nb    = "Du får bare 50%% av erfaringen og kan kanskje ikke få gjenstander fra monstre.",
    de    = "Du erhältst nur 50%% der Erfahrung und erhältst möglicherweise keine Gegenstände von Monstern.",
    nlnl  = "Je ontvangt slechts 50%% ervaring en mogelijk geen voorwerpen van monsters.",
    frfr  = "Vous ne recevez que 50%% d'expérience et pourriez ne pas recevoir d'objets des monstres.",
    fi    = "Saat vain 50%% kokemuksesta etkä välttämättä saa esineitä hirviöiltä.",
    it    = "Ricevi solo il 50%% dell'esperienza e potresti non ricevere oggetti dai mostri.",
    zhcn  = "你只能获得50%%的经验值，并且可能无法从怪物那里获得物品。",
    ja    = "経験値を50%%しか獲得できず、モンスターからアイテムを獲得できない場合があります。",
    ko    = "경험치를 50%%만 획득하며 몬스터에게서 아이템을 받지 못할 수 있습니다.",
  },

  GameSkillsStaminaExpLootLock = {
    en    = "You may not receive experience and loot from monsters.",
    ptbr  = "Você pode não receber experiência e itens dos monstros.",
    ptpt  = "Você pode não receber experiência e itens dos monstros.",
    es419 = "Es posible que no recibas experiencia ni objetos de los monstruos.",
    eses  = "Es posible que no recibas experiencia ni objetos de los monstruos.",
    pl    = "Możesz nie otrzymać doświadczenia ani przedmiotów od potworów.",
    ru    = "Вы можете не получить опыт и предметы с монстров.",
    sv    = "Du kanske inte får erfarenhet eller föremål från monster.",
    nb    = "Du kan kanskje ikke få erfaring eller gjenstander fra monstre.",
    de    = "Möglicherweise erhältst du keine Erfahrung und keine Gegenstände von Monstern.",
    nlnl  = "Je ontvangt mogelijk geen ervaring en voorwerpen van monsters.",
    frfr  = "Vous pourriez ne recevoir ni expérience ni objets des monstres.",
    fi    = "Et välttämättä saa kokemusta tai esineitä hirviöiltä.",
    it    = "Potresti non ricevere esperienza e oggetti dai mostri.",
    zhcn  = "你可能无法从怪物那里获得经验值和物品。",
    ja    = "モンスターから経験値やアイテムを獲得できない場合があります。",
    ko    = "몬스터에게서 경험치와 아이템을 받지 못할 수 있습니다.",
  },
})
