-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameDailyRewardWindowTitle = {
    en    = "Daily rewards",
    ptbr  = "Recompensas diárias",
    ptpt  = "Recompensas diárias",
    es419 = "Recompensas diarias",
    eses  = "Recompensas diarias",
    pl    = "Codzienne nagrody",
    ru    = "Ежедневные награды",
    sv    = "Dagliga belöningar",
    nb    = "Daglige belønninger",
    de    = "Tägliche Belohnungen",
    nlnl  = "Dagelijkse beloningen",
    frfr  = "Récompenses quotidiennes",
    fi    = "Päivittäiset palkinnot",
    it    = "Ricompense giornaliere",
    zhcn  = "每日奖励",
    ja    = "デイリー報酬",
    ko    = "일일 보상",
  },

  GameDailyRewardInfoRewardsClaim = {
    en    = "Rewards to claim",
    ptbr  = "Recompensas para resgatar",
    ptpt  = "Recompensas para resgatar",
    es419 = "Recompensas por reclamar",
    eses  = "Recompensas por reclamar",
    pl    = "Nagrody do odebrania",
    ru    = "Награды для получения",
    sv    = "Belöningar att hämta",
    nb    = "Belønninger å hente",
    de    = "Abzuholende Belohnungen",
    nlnl  = "Te innen beloningen",
    frfr  = "Récompenses à récupérer",
    fi    = "Noudettavat palkinnot",
    it    = "Ricompense da riscuotere",
    zhcn  = "待领取的奖励",
    ja    = "受け取れる報酬",
    ko    = "받을 수 있는 보상",
  },

  GameDailyRewardButtonClaim = {
    en    = "Claim",
    ptbr  = "Resgatar",
    ptpt  = "Resgatar",
    es419 = "Reclamar",
    eses  = "Reclamar",
    pl    = "Odbierz",
    ru    = "Получить",
    sv    = "Hämta",
    nb    = "Hent",
    de    = "Abholen",
    nlnl  = "Ophalen",
    frfr  = "Récupérer",
    fi    = "Nouda",
    it    = "Riscuoti",
    zhcn  = "领取",
    ja    = "受け取る",
    ko    = "받기",
  },

  GameDailyRewardInfoWeekBonus = {
    en    = "Week bonus",
    ptbr  = "Bônus semanal",
    ptpt  = "Bônus semanal",
    es419 = "Bono semanal",
    eses  = "Bono semanal",
    pl    = "Bonus tygodniowy",
    ru    = "Недельный бонус",
    sv    = "Veckobonus",
    nb    = "Ukentlig bonus",
    de    = "Wochenbonus",
    nlnl  = "Weekbonus",
    frfr  = "Bonus hebdomadaire",
    fi    = "Viikkobonus",
    it    = "Bonus settimanale",
    zhcn  = "每周奖励",
    ja    = "週間ボーナス",
    ko    = "주간 보너스",
  },

  GameDailyRewardButtonClaimPlayEnough = {
    en    = "Play enough",
    ptbr  = "Jogue o suficiente",
    ptpt  = "Jogue o suficiente",
    es419 = "Juega lo suficiente",
    eses  = "Juega lo suficiente",
    pl    = "Graj wystarczająco długo",
    ru    = "Сыграйте достаточно",
    sv    = "Spela tillräckligt",
    nb    = "Spill nok",
    de    = "Genug spielen",
    nlnl  = "Speel genoeg",
    frfr  = "Jouez suffisamment",
    fi    = "Pelaa tarpeeksi",
    it    = "Gioca abbastanza",
    zhcn  = "玩够时间",
    ja    = "十分にプレイする",
    ko    = "충분히 플레이하기",
  },

  GameDailyRewardButtonClaimClaimNow = {
    en    = "Claim now",
    ptbr  = "Resgatar agora",
    ptpt  = "Resgatar agora",
    es419 = "Reclamar ahora",
    eses  = "Reclamar ahora",
    pl    = "Odbierz teraz",
    ru    = "Получить сейчас",
    sv    = "Hämta nu",
    nb    = "Hent nå",
    de    = "Jetzt abholen",
    nlnl  = "Nu claimen",
    frfr  = "Récupérer maintenant",
    fi    = "Nouda nyt",
    it    = "Riscuoti ora",
    zhcn  = "立即领取",
    ja    = "今すぐ受け取る",
    ko    = "지금 받기",
  },

  GameDailyRewardButtonClaimClaimed = {
    en    = "Claimed",
    ptbr  = "Resgatado",
    ptpt  = "Resgatado",
    es419 = "Reclamado",
    eses  = "Reclamado",
    pl    = "Odebrano",
    ru    = "Получено",
    sv    = "Hämtad",
    nb    = "Hentet",
    de    = "Abgeholt",
    nlnl  = "Geclaimd",
    frfr  = "Récupéré",
    fi    = "Noudettu",
    it    = "Riscattato",
    zhcn  = "已领取",
    ja    = "受取済み",
    ko    = "받음",
  },

  GameDailyRewardButtonClaimPlayEnoughTooltip = {
    en    = "You have not played enough yet to get a reward.",
    ptbr  = "Você ainda não jogou o suficiente para obter uma recompensa.",
    ptpt  = "Você ainda não jogou o suficiente para obter uma recompensa.",
    es419 = "Aún no has jugado lo suficiente para obtener una recompensa.",
    eses  = "Aún no has jugado lo suficiente para obtener una recompensa.",
    pl    = "Nie grałeś jeszcze wystarczająco długo, aby otrzymać nagrodę.",
    ru    = "Вы ещё недостаточно играли, чтобы получить награду.",
    sv    = "Du har inte spelat tillräckligt länge för att få en belöning ännu.",
    nb    = "Du har ikke spilt nok ennå til å få en belønning.",
    de    = "Du hast noch nicht genug gespielt, um eine Belohnung zu erhalten.",
    nlnl  = "Je hebt nog niet genoeg gespeeld om een beloning te krijgen.",
    frfr  = "Vous n'avez pas encore assez joué pour obtenir une récompense.",
    fi    = "Et ole vielä pelannut tarpeeksi saadaksesi palkinnon.",
    it    = "Non hai ancora giocato abbastanza per ricevere una ricompensa.",
    zhcn  = "你还没有玩够时间，无法获得奖励。",
    ja    = "報酬を受け取るには、まだ十分にプレイしていません。",
    ko    = "아직 보상을 받기에 충분히 플레이하지 않았습니다.",
  },

  GameDailyRewardButtonClaimClaimNowTooltip = {
    en    = "You are now able to get your daily reward.",
    ptbr  = "Agora você pode obter sua recompensa diária.",
    ptpt  = "Agora pode obter a sua recompensa diária.",
    es419 = "Ahora puedes obtener tu recompensa diaria.",
    eses  = "Ahora puedes obtener tu recompensa diaria.",
    pl    = "Teraz możesz odebrać swoją codzienną nagrodę.",
    ru    = "Теперь вы можете получить свою ежедневную награду.",
    sv    = "Du kan nu hämta din dagliga belöning.",
    nb    = "Du kan nå hente din daglige belønning.",
    de    = "Du kannst jetzt deine tägliche Belohnung abholen.",
    nlnl  = "Je kunt nu je dagelijkse beloning ophalen.",
    frfr  = "Vous pouvez maintenant obtenir votre récompense quotidienne.",
    fi    = "Voit nyt noutaa päivittäisen palkintosi.",
    it    = "Ora puoi ottenere la tua ricompensa giornaliera.",
    zhcn  = "现在你可以领取每日奖励了。",
    ja    = "デイリー報酬を受け取れるようになりました。",
    ko    = "이제 일일 보상을 받을 수 있습니다.",
  },

  GameDailyRewardButtonClaimClaimedTooltip = {
    en    = "You have already taken your reward today.",
    ptbr  = "Você já pegou sua recompensa hoje.",
    ptpt  = "Já recebeu a sua recompensa hoje.",
    es419 = "Ya has recibido tu recompensa hoy.",
    eses  = "Ya has recibido tu recompensa hoy.",
    pl    = "Odebrałeś już swoją nagrodę dzisiaj.",
    ru    = "Вы уже получили свою награду сегодня.",
    sv    = "Du har redan hämtat din belöning idag.",
    nb    = "Du har allerede hentet belønningen din i dag.",
    de    = "Du hast deine Belohnung heute bereits abgeholt.",
    nlnl  = "Je hebt je beloning vandaag al opgehaald.",
    frfr  = "Vous avez déjà reçu votre récompense aujourd'hui.",
    fi    = "Olet jo noutanut tämän päivän palkintosi.",
    it    = "Hai già ricevuto la tua ricompensa oggi.",
    zhcn  = "你今天已经领取过奖励了。",
    ja    = "今日はすでに報酬を受け取っています。",
    ko    = "오늘은 이미 보상을 받았습니다.",
  },

  GameDailyRewardBonusBarTooltipEnabled = {
    en    = "You are able to get the bonus on each daily reward.",
    ptbr  = "Você pode obter o bônus em cada recompensa diária.",
    ptpt  = "Pode obter o bónus em cada recompensa diária.",
    es419 = "Puedes obtener el bono en cada recompensa diaria.",
    eses  = "Puedes obtener el bono en cada recompensa diaria.",
    pl    = "Możesz otrzymać bonus przy każdej codziennej nagrodzie.",
    ru    = "Вы можете получить бонус с каждой ежедневной наградой.",
    sv    = "Du kan få bonusen på varje daglig belöning.",
    nb    = "Du kan få bonusen på hver daglige belønning.",
    de    = "Du kannst den Bonus bei jeder täglichen Belohnung erhalten.",
    nlnl  = "Je kunt de bonus bij elke dagelijkse beloning krijgen.",
    frfr  = "Vous pouvez obtenir le bonus avec chaque récompense quotidienne.",
    fi    = "Voit saada bonuksen jokaisesta päivittäisestä palkinnosta.",
    it    = "Puoi ottenere il bonus con ogni ricompensa giornaliera.",
    zhcn  = "你可以在每次每日奖励中获得额外奖励。",
    ja    = "各デイリー報酬でボーナスを受け取れます！",
    ko    = "각 일일 보상에서 보너스를 받을 수 있습니다!",
  },

  GameDailyRewardBonusBarTooltipDisabled = {
    en    = "You are not able to get the bonus on each daily reward yet.",
    ptbr  = "Você ainda não pode obter o bônus em cada recompensa diária.",
    ptpt  = "Ainda não pode obter o bónus em cada recompensa diária.",
    es419 = "Aún no puedes obtener el bono en cada recompensa diaria.",
    eses  = "Aún no puedes obtener el bono en cada recompensa diaria.",
    pl    = "Nie możesz jeszcze otrzymać bonusu przy każdej codziennej nagrodzie.",
    ru    = "Вы пока не можете получить бонус с каждой ежедневной наградой.",
    sv    = "Du kan ännu inte få bonusen på varje daglig belöning.",
    nb    = "Du kan ennå ikke få bonusen på hver daglige belønning.",
    de    = "Du kannst den Bonus noch nicht bei jeder täglichen Belohnung erhalten.",
    nlnl  = "Je kunt de bonus bij elke dagelijkse beloning nog niet krijgen.",
    frfr  = "Vous ne pouvez pas encore obtenir le bonus avec chaque récompense quotidienne.",
    fi    = "Et voi vielä saada bonusta jokaisesta päivittäisestä palkinnosta.",
    it    = "Non puoi ancora ottenere il bonus con ogni ricompensa giornaliera.",
    zhcn  = "你目前还不能在每次每日奖励中获得额外奖励。",
    ja    = "まだ各デイリー報酬のボーナスを受け取れません。",
    ko    = "아직 각 일일 보상에서 보너스를 받을 수 없습니다.",
  },

  GameDailyRewardBonusBarTooltipDaysToEnable = {
    en    = "Days to get the bonus",
    ptbr  = "Dias para obter o bônus",
    ptpt  = "Dias para obter o bónus",
    es419 = "Días para obtener el bono",
    eses  = "Días para obtener el bono",
    pl    = "Dni do otrzymania bonusu",
    ru    = "Дней до получения бонуса",
    sv    = "Dagar tills bonusen erhålls",
    nb    = "Dager til du får bonusen",
    de    = "Tage bis zum Erhalt des Bonus",
    nlnl  = "Dagen tot je de bonus krijgt",
    frfr  = "Jours avant d'obtenir le bonus",
    fi    = "Päiviä bonuksen saamiseen",
    it    = "Giorni per ottenere il bonus",
    zhcn  = "获得奖励所需的天数",
    ja    = "ボーナス獲得までの日数",
    ko    = "보너스를 받기까지 남은 일수",
  },

  GameDailyRewardInfoStreak = {
    en    = "Streak",
    ptbr  = "Sequência",
    ptpt  = "Sequência",
    es419 = "Racha",
    eses  = "Racha",
    pl    = "Seria",
    ru    = "Серия",
    sv    = "Sviter",
    nb    = "Rekke",
    de    = "Serie",
    nlnl  = "Reeks",
    frfr  = "Série",
    fi    = "Putki",
    it    = "Serie",
    zhcn  = "连续次数",
    ja    = "連続日数",
    ko    = "연속 기록",
  },
})
