-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  BattleWindowTitle = {
    en    = "Battle",
    ptbr  = "Batalhar",
    ptpt  = "Batalhar",
    es419 = "Batallar",
    eses  = "Batallar",
    pl    = "Walczyć",
    ru    = "Сражаться",
    sv    = "Strida",
    nb    = "Kjempe",
    de    = "Kämpfen",
    nlnl  = "Vechten",
    frfr  = "Combattre",
    fi    = "Taistella",
    it    = "Combattere",
    zhcn  = "战斗",
    ja    = "戦う",
    ko    = "싸우다",
  },

  BattleAutoTargetTooltip = {
    en    = "Whenever the chat is disabled, you are able to use the (${NextTargetActionKey}) to select the next target monster from the list (hold (${PrevTargetActionKey}) for reverse order).\n\nNote: On select the next target monster with this shortcut, the chase mode will be deactivated.",
    ptbr  = "Quando o bate-papo estiver desativado, você pode usar (${NextTargetActionKey}) para selecionar o próximo alvo monstro da lista (segure (${PrevTargetActionKey}) para ordem reversa).\n\nNota: Ao selecionar o próximo alvo monstro com este atalho, o modo de perseguição será desativado.",
    ptpt  = "Quando o chat estiver desativado, pode usar (${NextTargetActionKey}) para selecionar o próximo monstro-alvo da lista (mantenha (${PrevTargetActionKey}) pressionado para inverter a ordem).\n\nNota: Ao selecionar o próximo monstro-alvo com este atalho, o modo de perseguição será desativado.",
    es419 = "Cuando el chat esté deshabilitado, puedes usar (${NextTargetActionKey}) para seleccionar el siguiente monstruo objetivo de la lista (mantén presionado (${PrevTargetActionKey}) para invertir el orden).\n\nNota: Al seleccionar el siguiente monstruo objetivo con este atajo, el modo de persecución se desactivará.",
    eses  = "Cuando el chat esté deshabilitado, puedes usar (${NextTargetActionKey}) para seleccionar el siguiente monstruo objetivo de la lista (mantén pulsado (${PrevTargetActionKey}) para invertir el orden).\n\nNota: Al seleccionar el siguiente monstruo objetivo con este atajo, el modo de persecución se desactivará.",
    pl    = "Gdy czat jest wyłączony, możesz użyć (${NextTargetActionKey}), aby wybrać kolejnego potwora będącego celem z listy (przytrzymaj (${PrevTargetActionKey}), aby odwrócić kolejność).\n\nUwaga: wybranie kolejnego potwora będącego celem za pomocą tego skrótu spowoduje wyłączenie trybu pościgu.",
    ru    = "Когда чат отключен, вы можете использовать (${NextTargetActionKey}), чтобы выбрать следующего монстра-цель из списка (удерживайте (${PrevTargetActionKey}), чтобы выбрать в обратном порядке).\n\nПримечание: при выборе следующего монстра-цели с помощью этого сочетания клавиш режим преследования будет отключен.",
    sv    = "När chatten är inaktiverad kan du använda (${NextTargetActionKey}) för att välja nästa målmonster från listan (håll (${PrevTargetActionKey}) nedtryckt för omvänd ordning).\n\nObs! När du väljer nästa målmonster med denna genväg inaktiveras förföljelseläget.",
    nb    = "Når chatten er deaktivert, kan du bruke (${NextTargetActionKey}) for å velge det neste målmonsteret fra listen (hold (${PrevTargetActionKey}) inne for å velge i omvendt rekkefølge).\n\nMerk: Når du velger det neste målmonsteret med denne snarveien, blir forfølgelsesmodusen deaktivert.",
    de    = "Wenn der Chat deaktiviert ist, kannst du (${NextTargetActionKey}) verwenden, um das nächste Zielmonster aus der Liste auszuwählen (halte (${PrevTargetActionKey}) gedrückt, um die Reihenfolge umzukehren).\n\nHinweis: Wenn du mit diesem Tastenkürzel das nächste Zielmonster auswählst, wird der Verfolgungsmodus deaktiviert.",
    nlnl  = "Wanneer de chat is uitgeschakeld, kun je (${NextTargetActionKey}) gebruiken om het volgende doelmonster uit de lijst te selecteren (houd (${PrevTargetActionKey}) ingedrukt om de volgorde om te keren).\n\nLet op: wanneer je met deze sneltoets het volgende doelmonster selecteert, wordt de volgmodus uitgeschakeld.",
    frfr  = "Lorsque le chat est désactivé, vous pouvez utiliser (${NextTargetActionKey}) pour sélectionner le prochain monstre ciblé dans la liste (maintenez (${PrevTargetActionKey}) enfoncé pour inverser l'ordre).\n\nRemarque : lorsque vous sélectionnez le prochain monstre ciblé avec ce raccourci, le mode poursuite est désactivé.",
    fi    = "Kun chat on poissa käytöstä, voit käyttää (${NextTargetActionKey})-näppäintä valitaksesi seuraavan kohdehirviön luettelosta (pidä (${PrevTargetActionKey}) painettuna valitaksesi käänteisessä järjestyksessä).\n\nHuomautus: kun valitset seuraavan kohdehirviön tällä pikanäppäimellä, takaa-ajotila poistetaan käytöstä.",
    it    = "Quando la chat è disattivata, puoi usare (${NextTargetActionKey}) per selezionare il prossimo mostro bersaglio dall'elenco (tieni premuto (${PrevTargetActionKey}) per invertire l'ordine).\n\nNota: selezionando il prossimo mostro bersaglio con questa scorciatoia, la modalità inseguimento verrà disattivata.",
    zhcn  = "聊天禁用时，你可以使用 (${NextTargetActionKey}) 从列表中选择下一个目标怪物（按住 (${PrevTargetActionKey}) 可按相反顺序选择）。\n\n注意：使用此快捷键选择下一个目标怪物后，追击模式将被禁用。",
    ja    = "チャットが無効になっているときは、(${NextTargetActionKey}) を使って一覧から次の対象モンスターを選択できます（(${PrevTargetActionKey}) を押し続けると逆順になります）。\n\n注意：このショートカットで次の対象モンスターを選択すると、追跡モードが無効になります。",
    ko    = "채팅이 비활성화되어 있을 때 (${NextTargetActionKey})를 사용하여 목록에서 다음 대상 몬스터를 선택할 수 있습니다((${PrevTargetActionKey})를 길게 누르면 역순으로 선택합니다).\n\n참고: 이 단축키로 다음 대상 몬스터를 선택하면 추적 모드가 비활성화됩니다.",
  },

  SortDisplayTime = {
    en    = "Display time",
    ptbr  = "Tempo de exibição",
    ptpt  = "Tempo de exibição",
    es419 = "Tiempo de exhibición",
    eses  = "Tiempo de exhibición",
    pl    = 'Czas wyświetlania',
    ru    = "Время отображения",
    sv    = "Visningstid",
    nb    = "Visningstid",
    de    = "Anzeigezeit",
    nlnl  = "Weergavetijd",
    frfr  = "Durée d'affichage",
    fi    = "Näyttöaika",
    it    = "Tempo di visualizzazione",
    zhcn  = "显示时间",
    ja    = "表示時間",
    ko    = "표시 시간",
  },

  SortHealthPercent = {
    en    = "Health %",
    ptbr  = "Saúde %",
    ptpt  = "Saúde %",
    es419 = "Salud %",
    eses  = "Salud %",
    pl    = 'Zdrowie %',
    ru    = "Здоровье %",
    sv    = "Hälsa %",
    nb    = "Helse %",
    de    = "Gesundheit %",
    nlnl  = "Gezondheid %",
    frfr  = "Santé %",
    fi    = "Terveys %",
    it    = "Salute %",
    zhcn  = "生命值 %",
    ja    = "体力％",
    ko    = "체력 %",
  },

  BattleOrderTooltip = {
    en    = "${BattleOrder} order",
    ptbr  = "Ordem ${BattleOrder}",
    ptpt  = "Ordem ${BattleOrder}",
    es419 = "Orden ${BattleOrder}",
    eses  = "Orden ${BattleOrder}",
    pl    = 'Kolejność ${BattleOrder}',
    ru    = "Порядок ${BattleOrder}",
    sv    = "Ordning ${BattleOrder}",
    nb    = "Rekkefølge ${BattleOrder}",
    de    = "Reihenfolge ${BattleOrder}",
    nlnl  = "Volgorde ${BattleOrder}",
    frfr  = "Ordre ${BattleOrder}",
    fi    = "${BattleOrder}-järjestys",
    it    = "Ordine ${BattleOrder}",
    zhcn  = "${BattleOrder}顺序",
    ja    = "${BattleOrder}順",
    ko    = "${BattleOrder} 순서",
  },

  FilterNPC = {
    en    = "NPCs",
    ptbr  = "NPCs",
    ptpt  = "NPCs",
    es419 = "NPCs",
    eses  = "NPCs",
    pl    = "NPC",
    ru    = "NPC",
    sv    = "NPC",
    nb    = "NPC",
    de    = "NPC",
    nlnl  = "NPC's",
    frfr  = "PNJ",
    fi    = "NPC",
    it    = "NPC",
    zhcn  = "NPC",
    ja    = "NPC",
    ko    = "NPC",
  },

  FilterPlayers = {
    en    = "Players",
    ptbr  = "Jogadores",
    ptpt  = "Jogadores",
    es419 = "Jugadores",
    eses  = "Jugadores",
    pl    = "Gracze",
    ru    = "Игроки",
    sv    = "Spelare",
    nb    = "Spillere",
    de    = "Spieler",
    nlnl  = "Spelers",
    frfr  = "Joueurs",
    fi    = "Pelaajat",
    it    = "Giocatori",
    zhcn  = "玩家",
    ja    = "プレイヤー",
    ko    = "플레이어",
  },

  FilterNeutralPlayers = {
    en    = "Neutral players",
    ptbr  = "Jogadores neutros",
    ptpt  = "Jogadores neutros",
    es419 = "Jugadores neutrales",
    eses  = "Jugadores neutrales",
    pl    = "Gracze neutralni",
    ru    = "Нейтральные игроки",
    sv    = "Neutrala spelare",
    nb    = "Nøytrale spillere",
    de    = "Neutrale Spieler",
    nlnl  = "Neutrale spelers",
    frfr  = "Joueurs neutres",
    fi    = "Neutraalit pelaajat",
    it    = "Giocatori neutrali",
    zhcn  = "中立玩家",
    ja    = "中立プレイヤー",
    ko    = "중립 플레이어",
  },

  FilterPartyMembers = {
    en    = "Party members",
    ptbr  = "Membros do grupo",
    ptpt  = "Membros do grupo",
    es419 = "Miembros del grupo",
    eses  = "Miembros del grupo",
    pl    = "Członkowie drużyny",
    ru    = "Участники группы",
    sv    = "Gruppmedlemmar",
    nb    = "Gruppemedlemmer",
    de    = "Gruppenmitglieder",
    nlnl  = "Groepsleden",
    frfr  = "Membres du groupe",
    fi    = "Ryhmän jäsenet",
    it    = "Membri del gruppo",
    zhcn  = "队伍成员",
    ja    = "パーティーメンバー",
    ko    = "파티원",
  },

  FilterMonsters = {
    en    = "Monsters",
    ptbr  = "Monstros",
    ptpt  = "Monstros",
    es419 = "Monstruos",
    eses  = "Monstruos",
    pl    = "Potwory",
    ru    = "Монстры",
    sv    = "Monster",
    nb    = "Monstre",
    de    = "Monster",
    nlnl  = "Monsters",
    frfr  = "Monstres",
    fi    = "Hirviöt",
    it    = "Mostri",
    zhcn  = "怪物",
    ja    = "モンスター",
    ko    = "몬스터",
  },

  FilterOwnSummons = {
    en    = "Own summons",
    ptbr  = "Próprios invocados",
    ptpt  = "Próprios invocados",
    es419 = "Invocados propios",
    eses  = "Invocados propios",
    pl    = "Własne przywołania",
    ru    = "Собственные призывы",
    sv    = "Egna frammaningar",
    nb    = "Egne påkallinger",
    de    = "Eigene Beschwörungen",
    nlnl  = "Eigen opgeroepen",
    frfr  = "Invocations personnelles",
    fi    = "Omat kutsutut",
    it    = "Le tue evocazioni",
    zhcn  = "自己的召唤物",
    ja    = "自分の召喚獣",
    ko    = "자신의 소환수",
  },

  FilterOtherSummons = {
    en    = "Other summons",
    ptbr  = "Outros invocados",
    ptpt  = "Outros invocados",
    es419 = "Otros invocados",
    eses  = "Otros invocados",
    pl    = "Inne przywołania",
    ru    = "Другие призывы",
    sv    = "Andras frammaningar",
    nb    = "Andre påkallinger",
    de    = "Andere Beschwörungen",
    nlnl  = "Andere opgeroepen",
    frfr  = "Autres invocations",
    fi    = "Muut kutsutut",
    it    = "Altre evocazioni",
    zhcn  = "其他召唤物",
    ja    = "他の召喚獣",
    ko    = "다른 소환수",
  },

  FilterHide = {
    en    = "Hide ${FilterType}",
    ptbr  = "Ocultar ${FilterType}",
    ptpt  = "Ocultar ${FilterType}",
    es419 = "Ocultar ${FilterType}",
    eses  = "Ocultar ${FilterType}",
    pl    = "Ukryj ${FilterType}",
    ru    = "Скрыть ${FilterType}",
    sv    = "Dölj ${FilterType}",
    nb    = "Skjul ${FilterType}",
    de    = "${FilterType} ausblenden",
    nlnl  = "${FilterType} verbergen",
    frfr  = "Masquer ${FilterType}",
    fi    = "Piilota ${FilterType}",
    it    = "Nascondi ${FilterType}",
    zhcn  = "隐藏 ${FilterType}",
    ja    = "${FilterType}を隠す",
    ko    = "${FilterType} 숨기기",
  },

  FilterShow = {
    en    = "Show ${FilterType}",
    ptbr  = "Exibir ${FilterType}",
    ptpt  = "Mostrar ${FilterType}",
    es419 = "Mostrar ${FilterType}",
    eses  = "Mostrar ${FilterType}",
    pl    = "Pokaż ${FilterType}",
    ru    = "Показать ${FilterType}",
    sv    = "Visa ${FilterType}",
    nb    = "Vis ${FilterType}",
    de    = "${FilterType} anzeigen",
    nlnl  = "${FilterType} tonen",
    frfr  = "Afficher ${FilterType}",
    fi    = "Näytä ${FilterType}",
    it    = "Mostra ${FilterType}",
    zhcn  = "显示 ${FilterType}",
    ja    = "${FilterType}を表示",
    ko    = "${FilterType} 표시",
  },
})
