-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameModalDialogLimitChars = {
    en    = "Limit: %s%s%s characters.",
    ptbr  = "Limite: %s%s%s caracteres.",
    ptpt  = "Limite: %s%s%s caracteres.",
    es419 = "Límite: %s%s%s caracteres.",
    eses  = "Límite: %s%s%s caracteres.",
    pl    = "Limit: %s%s%s znaków.",
    ru    = "Ограничение: %s%s%s символов.",
    sv    = "Gräns: %s%s%s tecken.",
    nb    = "Grense: %s%s%s tegn.",
    de    = "Limit: %s%s%s Zeichen.",
    nlnl  = "Limiet: %s%s%s tekens.",
    frfr  = "Limite : %s%s%s caractères.",
    fi    = "Raja: %s%s%s merkkiä.",
    it    = "Limite: %s%s%s caratteri.",
    zhcn  = "限制：%s%s%s 个字符。",
    ja    = "制限：%s%s%s文字。",
    ko    = "제한: %s%s%s자.",
  },

  GameModalDialogMin = {
    en    = "minimum",
    ptbr  = "mínimo",
    ptpt  = "mínimo",
    es419 = "mínimo",
    eses  = "mínimo",
    pl    = "minimum",
    ru    = "минимум",
    sv    = "minimum",
    nb    = "minimum",
    de    = "Minimum",
    nlnl  = "minimum",
    frfr  = "minimum",
    fi    = "vähintään",
    it    = "minimo",
    zhcn  = "最少",
    ja    = "最小",
    ko    = "최소",
  },

  GameModalDialogMax = {
    en    = "maximum",
    ptbr  = "máximo",
    ptpt  = "máximo",
    es419 = "máximo",
    eses  = "máximo",
    pl    = "maksimum",
    ru    = "максимум",
    sv    = "maximum",
    nb    = "maksimum",
    de    = "Maximum",
    nlnl  = "maximum",
    frfr  = "maximum",
    fi    = "enintään",
    it    = "massimo",
    zhcn  = "最多",
    ja    = "最大",
    ko    = "최대",
  },

  GameModalDialogCharsMinErrorMsg = {
    en    = "The text field '%s' should have at least %d characters.",
    ptbr  = "O campo de texto '%s' deve ter pelo menos %d caracteres.",
    ptpt  = "O campo de texto '%s' deve ter pelo menos %d caracteres.",
    es419 = "El campo de texto '%s' debe tener al menos %d caracteres.",
    eses  = "El campo de texto '%s' debe tener al menos %d caracteres.",
    pl    = "Pole tekstowe '%s' powinno mieć co najmniej %d znaków.",
    ru    = "Текстовое поле «%s» должно содержать не менее %d символов.",
    sv    = "Textfältet '%s' ska ha minst %d tecken.",
    nb    = "Tekstfeltet '%s' skal ha minst %d tegn.",
    de    = "Das Textfeld '%s' muss mindestens %d Zeichen enthalten.",
    nlnl  = "Het tekstveld '%s' moet minstens %d tekens bevatten.",
    frfr  = "Le champ de texte « %s » doit contenir au moins %d caractères.",
    fi    = "Tekstikentässä \"%s\" on oltava vähintään %d merkkiä.",
    it    = "Il campo di testo '%s' deve contenere almeno %d caratteri.",
    zhcn  = "文本字段“%s”必须至少包含%d个字符。",
    ja    = "テキスト欄「%s」は%d文字以上で入力してください。",
    ko    = "텍스트 필드 '%s'에는 최소 %d자의 문자가 있어야 합니다.",
  },

  GameModalDialogCharsMaxErrorMsg = {
    en    = "The text field '%s' should up to %d characters.",
    ptbr  = "O campo de texto '%s' deve ter até %d caracteres.",
    ptpt  = "O campo de texto '%s' deve ter até %d caracteres.",
    es419 = "El campo de texto '%s' debe tener hasta %d caracteres.",
    eses  = "El campo de texto '%s' debe tener hasta %d caracteres.",
    pl    = "Pole tekstowe '%s' powinno mieć do %d znaków.",
    ru    = "Текстовое поле «%s» должно содержать не более %d символов.",
    sv    = "Textfältet '%s' ska ha högst %d tecken.",
    nb    = "Tekstfeltet '%s' skal ha maksimalt %d tegn.",
    de    = "Das Textfeld '%s' darf höchstens %d Zeichen enthalten.",
    nlnl  = "Het tekstveld '%s' mag maximaal %d tekens bevatten.",
    frfr  = "Le champ de texte « %s » doit contenir au maximum %d caractères.",
    fi    = "Tekstikentässä \"%s\" saa olla enintään %d merkkiä.",
    it    = "Il campo di testo '%s' può contenere al massimo %d caratteri.",
    zhcn  = "文本字段“%s”最多可包含%d个字符。",
    ja    = "テキスト欄「%s」は%d文字以内で入力してください。",
    ko    = "텍스트 필드 '%s'에는 최대 %d자의 문자가 있어야 합니다.",
  },
})
