-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  ClientServerListAddServerWindow = {
    en    = "New server",
    ptbr  = "Novo servidor",
    ptpt  = "Novo servidor",
    es419 = "Nuevo servidor",
    eses  = "Nuevo servidor",
    pl    = "Nowy serwer",
    ru    = "Новый сервер",
    sv    = "Ny server",
    nb    = "Ny server",
    de    = "Neuer Server",
    nlnl  = "Nieuwe server",
    frfr  = "Nouveau serveur",
    fi    = "Uusi palvelin",
    it    = "Nuovo server",
    zhcn  = "新服务器",
    ja    = "新しいサーバー",
    ko    = "새 서버",
  },

  ClientServerListHostLabel = {
    en    = "Host",
    ptbr  = "Host",
    ptpt  = "Host",
    es419 = "Host",
    eses  = "Host",
    pl    = "Host",
    ru    = "Хост",
    sv    = "Värd",
    nb    = "Vert",
    de    = "Host",
    nlnl  = "Host",
    frfr  = "Hôte",
    fi    = "Isäntä",
    it    = "Host",
    zhcn  = "主机",
    ja    = "ホスト",
    ko    = "호스트",
  },

  ClientServerListPortLabel = {
    en    = "Port",
    ptbr  = "Porta",
    ptpt  = "Porta",
    es419 = "Puerto",
    eses  = "Puerto",
    pl    = "Port",
    ru    = "Порт",
    sv    = "Port",
    nb    = "Port",
    de    = "Port",
    nlnl  = "Poort",
    frfr  = "Port",
    fi    = "Portti",
    it    = "Porta",
    zhcn  = "端口",
    ja    = "ポート",
    ko    = "포트",
  },

  ClientServerListProtocolLabel = {
    en    = "Protocol",
    ptbr  = "Protocolo",
    ptpt  = "Protocolo",
    es419 = "Protocolo",
    eses  = "Protocolo",
    pl    = "Protokół",
    ru    = "Протокол",
    sv    = "Protokoll",
    nb    = "Protokoll",
    de    = "Protokoll",
    nlnl  = "Protocol",
    frfr  = "Protocole",
    fi    = "Protokolla",
    it    = "Protocollo",
    zhcn  = "协议",
    ja    = "プロトコル",
    ko    = "프로토콜",
  },

  ClientServerListServerListWindow = {
    en    = "Server list",
    ptbr  = "Lista de servidores",
    ptpt  = "Lista de servidores",
    es419 = "Lista de servidores",
    eses  = "Lista de servidores",
    pl    = "Lista serwerów",
    ru    = "Список серверов",
    sv    = "Serverlista",
    nb    = "Serverliste",
    de    = "Serverliste",
    nlnl  = "Serverlijst",
    frfr  = "Liste des serveurs",
    fi    = "Palvelinluettelo",
    it    = "Lista dei server",
    zhcn  = "服务器列表",
    ja    = "サーバー一覧",
    ko    = "서버 목록",
  },

  ClientServerListButtonOk = {
    en    = "Select",
    ptbr  = "Selecionar",
    ptpt  = "Selecionar",
    es419 = "Seleccionar",
    eses  = "Seleccionar",
    pl    = "Wybierz",
    ru    = "Выбрать",
    sv    = "Välj",
    nb    = "Velg",
    de    = "Auswählen",
    nlnl  = "Selecteren",
    frfr  = "Sélectionner",
    fi    = "Valitse",
    it    = "Seleziona",
    zhcn  = "选择",
    ja    = "選択",
    ko    = "선택",
  },

  ClientServerListErrorFailedLoadSettings = {
    en    = "Failed to load settings.",
    ptbr  = "Falha ao carregar as configurações.",
    ptpt  = "Falha ao carregar as definições.",
    es419 = "Error al cargar la configuración.",
    eses  = "Error al cargar la configuración.",
    pl    = "Nie udało się załadować ustawień.",
    ru    = "Не удалось загрузить настройки.",
    sv    = "Det gick inte att läsa in inställningarna.",
    nb    = "Kunne ikke laste inn innstillingene.",
    de    = "Fehler beim Laden der Einstellungen.",
    nlnl  = "Instellingen laden mislukt.",
    frfr  = "Échec du chargement des paramètres.",
    fi    = "Asetusten lataaminen epäonnistui.",
    it    = "Impossibile caricare le impostazioni.",
    zhcn  = "加载设置失败。",
    ja    = "設定の読み込みに失敗しました。",
    ko    = "설정을 불러오지 못했습니다.",
  },

  ClientServerListErrorExistsAlready = {
    en    = "Server exists already.",
    ptbr  = "O servidor já existe.",
    ptpt  = "O servidor já existe.",
    es419 = "El servidor ya existe.",
    eses  = "El servidor ya existe.",
    pl    = "Serwer już istnieje.",
    ru    = "Сервер уже существует.",
    sv    = "Servern finns redan.",
    nb    = "Serveren finnes allerede.",
    de    = "Der Server existiert bereits.",
    nlnl  = "De server bestaat al.",
    frfr  = "Le serveur existe déjà.",
    fi    = "Palvelin on jo olemassa.",
    it    = "Il server esiste già.",
    zhcn  = "服务器已存在。",
    ja    = "サーバーはすでに存在します。",
    ko    = "서버가 이미 존재합니다.",
  },

  ClientServerListErrorFieldsMissing = {
    en    = "Required fields are missing.",
    ptbr  = "Campos obrigatórios estão faltando.",
    ptpt  = "Faltam campos obrigatórios.",
    es419 = "Faltan campos obligatorios.",
    eses  = "Faltan campos obligatorios.",
    pl    = "Brakuje wymaganych pól.",
    ru    = "Отсутствуют обязательные поля.",
    sv    = "Obligatoriska fält saknas.",
    nb    = "Obligatoriske felt mangler.",
    de    = "Erforderliche Felder fehlen.",
    nlnl  = "Verplichte velden ontbreken.",
    frfr  = "Des champs obligatoires sont manquants.",
    fi    = "Pakollisia kenttiä puuttuu.",
    it    = "Mancano campi obbligatori.",
    zhcn  = "缺少必填字段。",
    ja    = "必須項目が入力されていません。",
    ko    = "필수 입력란이 비어 있습니다.",
  },

  ClientServerListRemoveHostMsg = {
    en    = "Remove %s?",
    ptbr  = "Remover %s?",
    ptpt  = "Remover %s?",
    es419 = "¿Eliminar %s?",
    eses  = "¿Eliminar %s?",
    pl    = "Usunąć %s?",
    ru    = "Удалить %s?",
    sv    = "Ta bort %s?",
    nb    = "Fjerne %s?",
    de    = "%s entfernen?",
    nlnl  = "%s verwijderen?",
    frfr  = "Supprimer %s ?",
    fi    = "Poistetaanko %s?",
    it    = "Rimuovere %s?",
    zhcn  = "移除 %s？",
    ja    = "%sを削除しますか？",
    ko    = "%s을(를) 삭제하시겠습니까?",
  },
})
