-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameStatsCircleStatHealth = {
    en    = "Health",
    ptbr  = "Saúde",
    ptpt  = "Saúde",
    es419 = "Salud",
    eses  = "Salud",
    pl    = "Zdrowie",
    ru    = "Здоровье",
    sv    = "Hälsa",
    nb    = "Helse",
    de    = "Gesundheit",
    nlnl  = "Gezondheid",
    frfr  = "Vie",
    fi    = "Terveys",
    it    = "Salute",
    zhcn  = "生命值",
    ja    = "体力",
    ko    = "체력",
  },

  GameStatsCircleStatMana = {
    en    = "Mana",
    ptbr  = "Mana",
    ptpt  = "Mana",
    es419 = "Maná",
    eses  = "Maná",
    pl    = "Mana",
    ru    = "Мана",
    sv    = "Mana",
    nb    = "Mana",
    de    = "Mana",
    nlnl  = "Mana",
    frfr  = "Mana",
    fi    = "Mana",
    it    = "Mana",
    zhcn  = "法力值",
    ja    = "マナ",
    ko    = "마나",
  },

  GameStatsCircleStatVigor = {
    en    = "Vigor",
    ptbr  = "Vigor",
    ptpt  = "Vigor",
    es419 = "Vigor",
    eses  = "Vigor",
    pl    = "Wigor",
    ru    = "Энергия",
    sv    = "Vigör",
    nb    = "Vigor",
    de    = "Energie",
    nlnl  = "Vigor",
    frfr  = "Vigueur",
    fi    = "Vireys",
    it    = "Vigore",
    zhcn  = "活力",
    ja    = "活力",
    ko    = "활력",
  },

  GameStatsCircleStatCapacity = {
    en    = "Capacity",
    ptbr  = "Capacidade",
    ptpt  = "Capacidade",
    es419 = "Capacidad",
    eses  = "Capacidad",
    pl    = "Pojemność",
    ru    = "Вместимость",
    sv    = "Kapacitet",
    nb    = "Kapasitet",
    de    = "Kapazität",
    nlnl  = "Capaciteit",
    frfr  = "Capacité",
    fi    = "Kantokyky",
    it    = "Capacità",
    zhcn  = "容量",
    ja    = "容量",
    ko    = "소지 용량",
  },

  GameStatsCircleStatExperience = {
    en    = "Experience",
    ptbr  = "Experiência",
    ptpt  = "Experiência",
    es419 = "Experiencia",
    eses  = "Experiencia",
    pl    = "Doświadczenie",
    ru    = "Опыт",
    sv    = "Erfarenhet",
    nb    = "Erfaring",
    de    = "Erfahrung",
    nlnl  = "Ervaring",
    frfr  = "Expérience",
    fi    = "Kokemus",
    it    = "Esperienza",
    zhcn  = "经验",
    ja    = "経験値",
    ko    = "경험치",
  },
})
