-- Consolidated UTF-8 locale file.

g_locales.addTranslations({
  GameConsoleChannelEventJoin = {
    en    = "%s joined the channel.",
    ptbr  = "%s entrou no canal.",
    ptpt  = "%s entrou no canal.",
    es419 = "%s se unió al canal.",
    eses  = "%s se unió al canal.",
    pl    = "%s dołączył do kanału.",
    ru    = "%s вошёл в канал.",
    sv    = "%s gick med i kanalen.",
    nb    = "%s ble med i kanalen.",
    de    = "%s ist dem Kanal beigetreten.",
    nlnl  = "%s heeft het kanaal betreden.",
    frfr  = "%s a rejoint le canal.",
    fi    = "%s liittyi kanavalle.",
    it    = "%s è entrato nel canale.",
    zhcn  = "%s 加入了频道。",
    ja    = "%sがチャンネルに参加しました。",
    ko    = "%s님이 채널에 참여했습니다.",
  },

  GameConsoleChannelEventLeave = {
    en    = "%s left the channel.",
    ptbr  = "%s saiu do canal.",
    ptpt  = "%s saiu do canal.",
    es419 = "%s abandonó el canal.",
    eses  = "%s abandonó el canal.",
    pl    = "%s opuścił kanał.",
    ru    = "%s покинул канал.",
    sv    = "%s lämnade kanalen.",
    nb    = "%s forlot kanalen.",
    de    = "%s hat den Kanal verlassen.",
    nlnl  = "%s heeft het kanaal verlaten.",
    frfr  = "%s a quitté le canal.",
    fi    = "%s poistui kanavalta.",
    it    = "%s ha lasciato il canale.",
    zhcn  = "%s 离开了频道。",
    ja    = "%sがチャンネルを退出しました。",
    ko    = "%s님이 채널을 나갔습니다.",
  },

  GameConsoleChannelEventInvite = {
    en    = "%s has been invited to the channel.",
    ptbr  = "%s foi convidado para o canal.",
    ptpt  = "%s foi convidado para o canal.",
    es419 = "%s ha sido invitado al canal.",
    eses  = "%s ha sido invitado al canal.",
    pl    = "%s został zaproszony do kanału.",
    ru    = "%s был приглашён в канал.",
    sv    = "%s har blivit inbjuden till kanalen.",
    nb    = "%s har blitt invitert til kanalen.",
    de    = "%s wurde in den Kanal eingeladen.",
    nlnl  = "%s is uitgenodigd voor het kanaal.",
    frfr  = "%s a été invité dans le canal.",
    fi    = "%s kutsuttiin kanavalle.",
    it    = "%s è stato invitato al canale.",
    zhcn  = "%s 被邀请加入频道。",
    ja    = "%sがチャンネルに招待されました。",
    ko    = "%s님이 채널에 초대되었습니다.",
  },

  GameConsoleChannelEventExclude = {
    en    = "%s has been removed from the channel.",
    ptbr  = "%s foi removido do canal.",
    ptpt  = "%s foi removido do canal.",
    es419 = "%s ha sido eliminado del canal.",
    eses  = "%s ha sido eliminado del canal.",
    pl    = "%s został usunięty z kanału.",
    ru    = "%s был удалён из канала.",
    sv    = "%s har tagits bort från kanalen.",
    nb    = "%s har blitt fjernet fra kanalen.",
    de    = "%s wurde aus dem Kanal entfernt.",
    nlnl  = "%s is uit het kanaal verwijderd.",
    frfr  = "%s a été retiré du canal.",
    fi    = "%s poistettiin kanavalta.",
    it    = "%s è stato rimosso dal canale.",
    zhcn  = "%s 已从频道中移除。",
    ja    = "%sがチャンネルから削除されました。",
    ko    = "%s님이 채널에서 제거되었습니다.",
  },

  GameConsoleChatEnable = {
    en    = "Enable chat (disables WASD and other movement shortcuts)",
    ptbr  = "Ativar chat (desativa atalhos para caminhar com WASD e outros)",
    ptpt  = "Ativar chat (desativa atalhos para caminhar com WASD e outros)",
    es419 = "Activar chat (desactiva los atajos para caminar con WASD y otros)",
    eses  = "Activar chat (desactiva los atajos para caminar con WASD y otros)",
    pl    = "Włącz czat (wyłącza skróty WASD i inne skróty do poruszania się)",
    ru    = "Включить чат (отключает WASD и другие сочетания клавиш для передвижения)",
    sv    = "Aktivera chatt (inaktiverar WASD och andra kortkommandon för att gå)",
    nb    = "Aktiver chat (deaktiverer WASD og andre hurtigtaster for å gå)",
    de    = "Chat aktivieren (deaktiviert WASD- und andere Tastenkürzel zum Bewegen)",
    nlnl  = "Chat inschakelen (schakelt WASD- en andere sneltoetsen voor bewegen uit)",
    frfr  = "Activer le chat (désactive les raccourcis WASD et autres raccourcis de déplacement)",
    fi    = "Ota chat käyttöön (poistaa WASD- ja muut liikkumisen pikanäppäimet käytöstä)",
    it    = "Attiva chat (disattiva le scorciatoie WASD e altre scorciatoie per muoversi)",
    zhcn  = "启用聊天（禁用 WASD 和其他移动快捷键）",
    ja    = "チャットを有効にする（WASDなどの移動ショートカットを無効にします）",
    ko    = "채팅 활성화 (WASD 및 기타 이동 단축키를 비활성화합니다)",
  },

  GameConsoleChatPlaceholder = {
    en    = "Type here to chat...",
    ptbr  = "Digite aqui para conversar...",
    ptpt  = "Digite aqui para conversar...",
    es419 = "Escribe aquí para conversar...",
    eses  = "Escribe aquí para conversar...",
    pl    = "Wpisz tutaj, aby porozmawiać...",
    ru    = "Введите сообщение здесь...",
    sv    = "Skriv här för att prata...",
    nb    = "Skriv her for å snakke...",
    de    = "Hier eingeben, um zu chatten...",
    nlnl  = "Typ hier om te chatten...",
    frfr  = "Écrivez ici pour discuter...",
    fi    = "Kirjoita tähän keskustellaksesi...",
    it    = "Scrivi qui per parlare...",
    zhcn  = "在此输入消息...",
    ja    = "ここに入力してチャット…",
    ko    = "여기에 입력하여 채팅하세요...",
  },

  GameConsoleChatInputHelp = {
    en    = "* Alt to move cursor\n* Shift to select\n* Ctrl to skip chunks\n* Ctrl+Backspace to delete a chunk\n* Alt+Up/Alt+Down to browse sent message history",
    ptbr  = "* Alt para mover o cursor\n* Shift para selecionar\n* Ctrl para pular pedaços\n* Ctrl+Backspace para apagar um pedaço\n* Alt+Up/Alt+Down para navegar pelo histórico de mensagens enviadas",
    ptpt  = "* Alt para mover o cursor\n* Shift para selecionar\n* Ctrl para saltar pedaços\n* Ctrl+Backspace para apagar um pedaço\n* Alt+Up/Alt+Down para navegar pelo histórico de mensagens enviadas",
    es419 = "* Alt para mover el cursor\n* Shift para seleccionar\n* Ctrl para saltar fragmentos\n* Ctrl+Backspace para eliminar un fragmento\n* Alt+Up/Alt+Down para navegar por el historial de mensajes enviados",
    eses  = "* Alt para mover el cursor\n* Shift para seleccionar\n* Ctrl para saltar fragmentos\n* Ctrl+Backspace para eliminar un fragmento\n* Alt+Up/Alt+Down para navegar por el historial de mensajes enviados",
    pl    = "* Alt, aby przesunąć kursor\n* Shift, aby zaznaczyć\n* Ctrl, aby pomijać fragmenty\n* Ctrl+Backspace, aby usunąć fragment\n* Alt+Up/Alt+Down, aby przeglądać historię wysłanych wiadomości",
    ru    = "* Alt для перемещения курсора\n* Shift для выделения\n* Ctrl для пропуска фрагментов\n* Ctrl+Backspace для удаления фрагмента\n* Alt+Up/Alt+Down для просмотра истории отправленных сообщений",
    sv    = "* Alt för att flytta markören\n* Shift för att markera\n* Ctrl för att hoppa över delar\n* Ctrl+Backspace för att ta bort en del\n* Alt+Up/Alt+Down för att bläddra i historiken över skickade meddelanden",
    nb    = "* Alt for å flytte markøren\n* Shift for å velge\n* Ctrl for å hoppe over deler\n* Ctrl+Backspace for å slette en del\n* Alt+Up/Alt+Down for å bla gjennom historikken over sendte meldinger",
    de    = "* Alt zum Bewegen des Cursors\n* Shift zum Markieren\n* Ctrl zum Überspringen von Teilen\n* Ctrl+Backspace zum Löschen eines Teils\n* Alt+Up/Alt+Down zum Durchsuchen des Verlaufs gesendeter Nachrichten",
    nlnl  = "* Alt om de cursor te verplaatsen\n* Shift om te selecteren\n* Ctrl om delen over te slaan\n* Ctrl+Backspace om een deel te verwijderen\n* Alt+Up/Alt+Down om door de geschiedenis van verzonden berichten te bladeren",
    frfr  = "* Alt pour déplacer le curseur\n* Shift pour sélectionner\n* Ctrl pour passer des morceaux\n* Ctrl+Backspace pour supprimer un morceau\n* Alt+Up/Alt+Down pour parcourir l’historique des messages envoyés",
    fi    = "* Alt siirtääksesi kohdistinta\n* Shift valitaksesi\n* Ctrl ohittaaksesi osia\n* Ctrl+Backspace poistaaksesi osan\n* Alt+Up/Alt+Down selataksesi lähetettyjen viestien historiaa",
    it    = "* Alt per spostare il cursore\n* Shift per selezionare\n* Ctrl per saltare parti\n* Ctrl+Backspace per eliminare una parte\n* Alt+Up/Alt+Down per scorrere la cronologia dei messaggi inviati",
    zhcn  = "* Alt 移动光标\n* Shift 进行选择\n* Ctrl 跳过部分内容\n* Ctrl+Backspace 删除一部分内容\n* Alt+Up/Alt+Down 浏览已发送消息的历史记录",
    ja    = "* Alt でカーソルを移動\n* Shift で選択\n* Ctrl で部分的にスキップ\n* Ctrl+Backspace で一部分を削除\n* Alt+Up/Alt+Down で送信済みメッセージの履歴を閲覧",
    ko    = "* Alt로 커서를 이동\n* Shift로 선택\n* Ctrl로 부분 건너뛰기\n* Ctrl+Backspace로 부분 삭제\n* Alt+Up/Alt+Down으로 보낸 메시지 기록 탐색",
  },

  GameConsoleChatDisable = {
    en    = "Disable chat (enables shortcuts to walk with WASD and others)",
    ptbr  = "Desativar chat (ativa atalhos para caminhar com WASD e outros)",
    ptpt  = "Desativar chat (ativa atalhos para caminhar com WASD e outros)",
    es419 = "Desactivar chat (habilita atajos para caminar con WASD y otros)",
    eses  = "Desactivar chat (habilita atajos para caminar con WASD y otros)",
    pl    = "Wyłącz czat (umożliwia chodzenie skrótami klawiszowymi WASD i innymi)",
    ru    = "Отключить чат (включает клавиши WASD и другие сочетания для ходьбы)",
    sv    = "Inaktivera chatt (aktiverar genvägar för att gå med WASD och andra)",
    nb    = "Deaktiver chat (aktiverer snarveier for å gå med WASD og andre)",
    de    = "Chat deaktivieren (aktiviert Tastenkürzel zum Gehen mit WASD und anderen)",
    nlnl  = "Chat uitschakelen (schakelt sneltoetsen voor lopen met WASD en andere toetsen in)",
    frfr  = "Désactiver le chat (active les raccourcis de déplacement avec WASD et autres touches)",
    fi    = "Poista chat käytöstä (ottaa WASD-kävelyn ja muut pikanäppäimet käyttöön)",
    it    = "Disattiva chat (attiva le scorciatoie per camminare con WASD e altri tasti)",
    zhcn  = "禁用聊天（启用 WASD 等移动快捷键）",
    ja    = "チャットを無効にする（WASDなどの移動ショートカットを有効化）",
    ko    = "채팅 비활성화 (WASD 및 기타 이동 단축키 활성화)",
  },

  GameConsoleCloneTabTip = {
    en    = "Tip: Double click on this tab to clone it",
    ptbr  = "Dica: Clique duas vezes nesta aba para cloná-la",
    ptpt  = "Dica: Clique duas vezes na aba atual para cloná-la",
    es419 = "Consejo: Haz doble clic en esta pestaña para clonarla",
    eses  = "Consejo: Haz doble clic en esta pestaña para clonarla",
    pl    = "Wskazówka: Kliknij dwukrotnie tę kartę, aby ją sklonować",
    ru    = "Совет: дважды щёлкните эту вкладку, чтобы клонировать её",
    sv    = "Tips: Dubbelklicka på den här fliken för att klona den",
    nb    = "Tips: Dobbeltklikk på denne fanen for å klone den",
    de    = "Tipp: Doppelklicken Sie auf diesen Tab, um ihn zu klonen",
    nlnl  = "Tip: dubbelklik op dit tabblad om het te klonen",
    frfr  = "Astuce : double-cliquez sur cet onglet pour le cloner",
    fi    = "Vinkki: kaksoisnapsauta tätä välilehteä kloonataksesi sen",
    it    = "Suggerimento: fai doppio clic su questa scheda per clonarla",
    zhcn  = "提示：双击此标签页即可克隆它",
    ja    = "ヒント：このタブをダブルクリックすると複製できます",
    ko    = "팁: 이 탭을 두 번 클릭하면 복제할 수 있습니다",
  },

  GameConsoleCloseTabTip = {
    en    = "Tip: Double click on this tab to close it",
    ptbr  = "Dica: Clique duas vezes nesta aba para fechá-la",
    ptpt  = "Dica: Clique duas vezes nesta aba para fechá-la",
    es419 = "Consejo: Haz doble clic en esta pestaña para cerrarla",
    eses  = "Consejo: Haz doble clic en esta pestaña para cerrarla",
    pl    = "Wskazówka: Kliknij dwukrotnie tę kartę, aby ją zamknąć",
    ru    = "Совет: дважды щёлкните эту вкладку, чтобы закрыть её",
    sv    = "Tips: Dubbelklicka på den här fliken för att stänga den",
    nb    = "Tips: Dobbeltklikk på denne fanen for å lukke den",
    de    = "Tipp: Doppelklicken Sie auf diesen Tab, um ihn zu schließen",
    nlnl  = "Tip: dubbelklik op dit tabblad om het te sluiten",
    frfr  = "Astuce : double-cliquez sur cet onglet pour le fermer",
    fi    = "Vinkki: kaksoisnapsauta tätä välilehteä sulkeaksesi sen",
    it    = "Suggerimento: fai doppio clic su questa scheda per chiuderla",
    zhcn  = "提示：双击此标签页即可关闭它",
    ja    = "ヒント：このタブをダブルクリックすると閉じます",
    ko    = "팁: 이 탭을 두 번 클릭하면 닫을 수 있습니다",
  },

  GameConsoleTabServerMsgs = {
    en    = "Show server messages",
    ptbr  = "Mostrar mensagens do servidor",
    ptpt  = "Mostrar mensagens do servidor",
    es419 = "Mostrar mensajes del servidor",
    eses  = "Mostrar mensajes del servidor",
    pl    = "Pokaż wiadomości serwera",
    ru    = "Показывать сообщения сервера",
    sv    = "Visa servermeddelanden",
    nb    = "Vis servermeldinger",
    de    = "Servernachrichten anzeigen",
    nlnl  = "Serverberichten tonen",
    frfr  = "Afficher les messages du serveur",
    fi    = "Näytä palvelimen viestit",
    it    = "Mostra i messaggi del server",
    zhcn  = "显示服务器消息",
    ja    = "サーバーメッセージを表示",
    ko    = "서버 메시지 표시",
  },

  GameConsoleTabClearMsgs = {
    en    = "Clear messages",
    ptbr  = "Limpar mensagens",
    ptpt  = "Limpar mensagens",
    es419 = "Limpiar mensajes",
    eses  = "Limpiar mensajes",
    pl    = "Wyczyść wiadomości",
    ru    = "Очистить сообщения",
    sv    = "Rensa meddelanden",
    nb    = "Tøm meldinger",
    de    = "Nachrichten löschen",
    nlnl  = "Berichten wissen",
    frfr  = "Effacer les messages",
    fi    = "Tyhjennä viestit",
    it    = "Cancella i messaggi",
    zhcn  = "清除消息",
    ja    = "メッセージを消去",
    ko    = "메시지 지우기",
  },

  GameConsoleTabSaveMsgs = {
    en    = "Save messages",
    ptbr  = "Salvar mensagens",
    ptpt  = "Guardar mensagens",
    es419 = "Guardar mensajes",
    eses  = "Guardar mensajes",
    pl    = "Zapisz wiadomości",
    ru    = "Сохранить сообщения",
    sv    = "Spara meddelanden",
    nb    = "Lagre meldinger",
    de    = "Nachrichten speichern",
    nlnl  = "Berichten opslaan",
    frfr  = "Enregistrer les messages",
    fi    = "Tallenna viestit",
    it    = "Salva i messaggi",
    zhcn  = "保存消息",
    ja    = "メッセージを保存",
    ko    = "메시지 저장",
  },

  GameConsoleTabSavedAt = {
    en    = "Channel saved at %s",
    ptbr  = "Canal salvo em %s",
    ptpt  = "Canal guardado em %s",
    es419 = "Canal guardado en %s",
    eses  = "Canal guardado en %s",
    pl    = "Kanał zapisany o %s",
    ru    = "Канал сохранён в %s",
    sv    = "Kanalen sparades i %s",
    nb    = "Kanalen ble lagret i %s",
    de    = "Kanal gespeichert unter %s",
    nlnl  = "Kanaal opgeslagen in %s",
    frfr  = "Canal enregistré dans %s",
    fi    = "Kanava tallennettu sijaintiin %s",
    it    = "Canale salvato in %s",
    zhcn  = "频道已保存到 %s",
    ja    = "チャンネルを%sに保存しました",
    ko    = "채널이 %s에 저장되었습니다",
  },

  GameConsoleTabAppendedTo = {
    en    = "Channel appended to %s",
    ptbr  = "Canal anexado a %s",
    ptpt  = "Canal anexado a %s",
    es419 = "Canal añadido a %s",
    eses  = "Canal añadido a %s",
    pl    = "Kanał dołączony do %s",
    ru    = "Канал добавлен в %s",
    sv    = "Kanalen bifogades till %s",
    nb    = "Kanalen ble lagt til %s",
    de    = "Kanal an %s angehängt",
    nlnl  = "Kanaal toegevoegd aan %s",
    frfr  = "Canal ajouté à %s",
    fi    = "Kanava lisätty kohteeseen %s",
    it    = "Canale aggiunto a %s",
    zhcn  = "频道已添加到 %s",
    ja    = "チャンネルを%sに追加しました",
    ko    = "채널이 %s에 추가되었습니다",
  },

  GameConsoleTabCloneClose = {
    en    = "Close clone",
    ptbr  = "Fechar clone",
    ptpt  = "Fechar clone",
    es419 = "Cerrar clon",
    eses  = "Cerrar clon",
    pl    = "Zamknij klon",
    ru    = "Закрыть клон",
    sv    = "Stäng klonen",
    nb    = "Lukk klonen",
    de    = "Klon schließen",
    nlnl  = "Kloon sluiten",
    frfr  = "Fermer le clone",
    fi    = "Sulje klooni",
    it    = "Chiudi il clone",
    zhcn  = "关闭克隆",
    ja    = "複製を閉じる",
    ko    = "복제 탭 닫기",
  },

  GameConsoleTabClone = {
    en    = "Clone tab",
    ptbr  = "Clonar aba",
    ptpt  = "Clonar aba",
    es419 = "Clonar pestaña",
    eses  = "Clonar pestaña",
    pl    = "Klonuj kartę",
    ru    = "Клонировать вкладку",
    sv    = "Klona flik",
    nb    = "Klon fane",
    de    = "Tab klonen",
    nlnl  = "Tabblad klonen",
    frfr  = "Cloner l'onglet",
    fi    = "Kloonaa välilehti",
    it    = "Clona la scheda",
    zhcn  = "克隆标签页",
    ja    = "タブを複製",
    ko    = "탭 복제",
  },

  GameConsoleMessageTo = {
    en    = "Message to %s",
    ptbr  = "Mensagem para %s",
    ptpt  = "Mensagem para %s",
    es419 = "Mensaje para %s",
    eses  = "Mensaje para %s",
    pl    = "Wiadomość do %s",
    ru    = "Сообщение для %s",
    sv    = "Meddelande till %s",
    nb    = "Melding til %s",
    de    = "Nachricht an %s",
    nlnl  = "Bericht aan %s",
    frfr  = "Message à %s",
    fi    = "Viesti käyttäjälle %s",
    it    = "Messaggio per %s",
    zhcn  = "给 %s 的消息",
    ja    = "%sへのメッセージ",
    ko    = "%s에게 보내는 메시지",
  },

  GameConsoleAddVIP = {
    en    = "Add to contacts",
    ptbr  = "Adicionar aos contatos",
    ptpt  = "Adicionar aos contactos",
    es419 = "Añadir a los contactos",
    eses  = "Añadir a los contactos",
    pl    = "Dodaj do kontaktów",
    ru    = "Добавить в контакты",
    sv    = "Lägg till i kontakter",
    nb    = "Legg til i kontakter",
    de    = "Zu den Kontakten hinzufügen",
    nlnl  = "Aan contacten toevoegen",
    frfr  = "Ajouter aux contacts",
    fi    = "Lisää yhteystietoihin",
    it    = "Aggiungi ai contatti",
    zhcn  = "添加到联系人",
    ja    = "連絡先に追加",
    ko    = "연락처에 추가",
  },

  GameConsoleInviteToChat = {
    en    = "Invite to private chat",
    ptbr  = "Convidar para chat privado",
    ptpt  = "Convidar para chat privado",
    es419 = "Invitar al chat privado",
    eses  = "Invitar al chat privado",
    pl    = "Zaproś do prywatnego czatu",
    ru    = "Пригласить в приватный чат",
    sv    = "Bjud in till privat chatt",
    nb    = "Inviter til privat chat",
    de    = "Zu privatem Chat einladen",
    nlnl  = "Uitnodigen voor privéchat",
    frfr  = "Inviter à une discussion privée",
    fi    = "Kutsu yksityischattiin",
    it    = "Invita alla chat privata",
    zhcn  = "邀请加入私聊",
    ja    = "プライベートチャットに招待",
    ko    = "비공개 채팅에 초대",
  },

  GameConsoleExcludeFromChat = {
    en    = "Exclude from private chat",
    ptbr  = "Excluir do chat privado",
    ptpt  = "Eliminar do chat privado",
    es419 = "Excluir del chat privado",
    eses  = "Excluir del chat privado",
    pl    = "Wyklucz z prywatnego czatu",
    ru    = "Исключить из приватного чата",
    sv    = "Uteslut från privat chatt",
    nb    = "Utelukk fra privat chat",
    de    = "Aus dem privaten Chat ausschließen",
    nlnl  = "Uit privéchat verwijderen",
    frfr  = "Exclure de la discussion privée",
    fi    = "Poista yksityischatista",
    it    = "Escludi dalla chat privata",
    zhcn  = "从私聊中移除",
    ja    = "プライベートチャットから除外",
    ko    = "비공개 채팅에서 제외",
  },

  GameConsoleEnterCharacterName = {
    en    = "Character name:",
    ptbr  = "Nome do personagem:",
    ptpt  = "Nome do personagem:",
    es419 = "Nombre del personaje:",
    eses  = "Nombre del personaje:",
    pl    = "Nazwa postaci:",
    ru    = "Имя персонажа:",
    sv    = "Karaktärens namn:",
    nb    = "Figurens navn:",
    de    = "Charaktername:",
    nlnl  = "Naam van personage:",
    frfr  = "Nom du personnage :",
    fi    = "Hahmon nimi:",
    it    = "Nome del personaggio:",
    zhcn  = "角色名称：",
    ja    = "キャラクター名：",
    ko    = "캐릭터 이름:",
  },

  GameConsoleIgnore = {
    en    = "Ignore %s",
    ptbr  = "Ignorar %s",
    ptpt  = "Ignorar %s",
    es419 = "Ignorar a %s",
    eses  = "Ignorar a %s",
    pl    = "Ignoruj %s",
    ru    = "Игнорировать %s",
    sv    = "Ignorera %s",
    nb    = "Ignorer %s",
    de    = "%s ignorieren",
    nlnl  = "%s negeren",
    frfr  = "Ignorer %s",
    fi    = "Ohita %s",
    it    = "Ignora %s",
    zhcn  = "忽略 %s",
    ja    = "%sを無視",
    ko    = "%s 무시",
  },

  GameConsoleUnignore = {
    en    = "Unignore %s",
    ptbr  = "Deixar de ignorar %s",
    ptpt  = "Deixar de ignorar %s",
    es419 = "Dejar de ignorar a %s",
    eses  = "Dejar de ignorar a %s",
    pl    = "Przestań ignorować %s",
    ru    = "Перестать игнорировать %s",
    sv    = "Sluta ignorera %s",
    nb    = "Slutt å ignorere %s",
    de    = "%s nicht mehr ignorieren",
    nlnl  = "%s niet meer negeren",
    frfr  = "Ne plus ignorer %s",
    fi    = "Lopeta käyttäjän %s ohittaminen",
    it    = "Non ignorare più %s",
    zhcn  = "取消忽略 %s",
    ja    = "%sの無視を解除",
    ko    = "%s 무시 해제",
  },

  GameConsoleAddRuleViolation = {
    en    = "Add rule violation",
    ptbr  = "Adicionar violação de regra",
    ptpt  = "Adicionar violação de regra",
    es419 = "Agregar violación de regla",
    eses  = "Agregar violación de regla",
    pl    = "Dodaj naruszenie zasad",
    ru    = "Добавить нарушение правила",
    sv    = "Lägg till regelbrott",
    nb    = "Legg til regelbrudd",
    de    = "Regelverstoß hinzufügen",
    nlnl  = "Regelovertreding toevoegen",
    frfr  = "Ajouter une infraction",
    fi    = "Lisää sääntörikkomus",
    it    = "Aggiungi violazione delle regole",
    zhcn  = "添加规则违规",
    ja    = "ルール違反を追加",
    ko    = "규칙 위반 추가",
  },

  GameConsoleReportStatement = {
    en    = "Report statement",
    ptbr  = "Reportar declaração",
    ptpt  = "Reportar declaração",
    es419 = "Reportar declaración",
    eses  = "Reportar declaración",
    pl    = "Zgłoś oświadczenie",
    ru    = "Пожаловаться на сообщение",
    sv    = "Rapportera uttalande",
    nb    = "Rapporter melding",
    de    = "Aussage melden",
    nlnl  = "Bericht melden",
    frfr  = "Signaler le message",
    fi    = "Ilmoita lausunto",
    it    = "Segnala dichiarazione",
    zhcn  = "举报发言",
    ja    = "発言を報告",
    ko    = "진술 신고",
  },

  GameConsoleCopy = {
    en    = "Copy",
    ptbr  = "Copiar",
    ptpt  = "Copiar",
    es419 = "Copiar",
    eses  = "Copiar",
    pl    = "Kopiuj",
    ru    = "Копировать",
    sv    = "Kopiera",
    nb    = "Kopier",
    de    = "Kopieren",
    nlnl  = "Kopiëren",
    frfr  = "Copier",
    fi    = "Kopioi",
    it    = "Copia",
    zhcn  = "复制",
    ja    = "コピー",
    ko    = "복사",
  },

  GameConsoleCopyMsg = {
    en    = "Copy message",
    ptbr  = "Copiar mensagem",
    ptpt  = "Copiar mensagem",
    es419 = "Copiar mensaje",
    eses  = "Copiar mensaje",
    pl    = "Kopiuj wiadomość",
    ru    = "Копировать сообщение",
    sv    = "Kopiera meddelande",
    nb    = "Kopier melding",
    de    = "Nachricht kopieren",
    nlnl  = "Bericht kopiëren",
    frfr  = "Copier le message",
    fi    = "Kopioi viesti",
    it    = "Copia messaggio",
    zhcn  = "复制消息",
    ja    = "メッセージをコピー",
    ko    = "메시지 복사",
  },

  GameConsoleCopyName = {
    en    = "Copy name",
    ptbr  = "Copiar nome",
    ptpt  = "Copiar nome",
    es419 = "Copiar nombre",
    eses  = "Copiar nombre",
    pl    = "Kopiuj nazwę",
    ru    = "Копировать имя",
    sv    = "Kopiera namn",
    nb    = "Kopier navn",
    de    = "Namen kopieren",
    nlnl  = "Naam kopiëren",
    frfr  = "Copier le nom",
    fi    = "Kopioi nimi",
    it    = "Copia nome",
    zhcn  = "复制名称",
    ja    = "名前をコピー",
    ko    = "이름 복사",
  },

  GameConsoleSelectAll = {
    en    = "Select all",
    ptbr  = "Selecionar tudo",
    ptpt  = "Selecionar tudo",
    es419 = "Seleccionar todo",
    eses  = "Seleccionar todo",
    pl    = "Zaznacz wszystko",
    ru    = "Выбрать всё",
    sv    = "Markera allt",
    nb    = "Merk alt",
    de    = "Alles auswählen",
    nlnl  = "Alles selecteren",
    frfr  = "Tout sélectionner",
    fi    = "Valitse kaikki",
    it    = "Seleziona tutto",
    zhcn  = "全选",
    ja    = "すべて選択",
    ko    = "모두 선택",
  },

  GameConsoleErrorUnhandledMsgMode = {
    en    = "Error - unhandled onTalk message mode %s",
    ptbr  = "Erro - modo de mensagem onTalk não tratado %s",
    ptpt  = "Erro - modo de mensagem onTalk não tratado %s",
    es419 = "Error - modo de mensaje onTalk no manejado %s",
    eses  = "Error - modo de mensaje onTalk no manejado %s",
    pl    = "Błąd - nieobsługiwany tryb wiadomości onTalk %s",
    ru    = "Ошибка — необработанный режим сообщения onTalk %s",
    sv    = "Fel - ohanterat onTalk-meddelandeläge %s",
    nb    = "Feil - ubehandlet onTalk-meldingsmodus %s",
    de    = "Fehler - Nicht behandelter onTalk-Nachrichtenmodus %s",
    nlnl  = "Fout - onverwerkte onTalk-berichtmodus %s",
    frfr  = "Erreur - mode de message onTalk non géré %s",
    fi    = "Virhe - käsittelemätön onTalk-viestitila %s",
    it    = "Errore - modalità messaggio onTalk non gestita %s",
    zhcn  = "错误 - 未处理的 onTalk 消息模式 %s",
    ja    = "エラー - 未処理のonTalkメッセージモード%s",
    ko    = "오류 - 처리되지 않은 onTalk 메시지 모드 %s",
  },

  GameConsoleTabNameServer = {
    en    = "Server",
    ptbr  = "Servidor",
    ptpt  = "Servidor",
    es419 = "Servidor",
    eses  = "Servidor",
    pl    = "Serwer",
    ru    = "Сервер",
    sv    = "Server",
    nb    = "Server",
    de    = "Server",
    nlnl  = "Server",
    frfr  = "Serveur",
    fi    = "Palvelin",
    it    = "Server",
    zhcn  = "服务器",
    ja    = "サーバー",
    ko    = "서버",
  },

  GameConsoleUnknownMsg = {
    en    = "Warning - message in channel id %d which is unknown. This is a server bug. Relogin, if you want to see messages in this channel.",
    ptbr  = "Aviso - mensagem no canal id %d que é desconhecida. Isso é um problema do servidor. Autentique-se novamente para visualizar mensagens neste canal.",
    ptpt  = "Aviso - mensagem no canal id %d que é desconhecida. Isso é um bug do servidor. Refaça o início de sessão se quiser ver mensagens neste canal.",
    es419 = "Advertencia - mensaje en el canal id %d que es desconocido. Este es un error del servidor. Vuelve a iniciar sesión si deseas ver mensajes en este canal.",
    eses  = "Advertencia - mensaje en el canal id %d que es desconocido. Este es un error del servidor. Vuelve a iniciar sesión si deseas ver mensajes en este canal.",
    pl    = "Ostrzeżenie - nieznana wiadomość na kanale o id %d. To błąd serwera. Zaloguj się ponownie, aby zobaczyć wiadomości w tym kanale.",
    ru    = "Предупреждение — неизвестное сообщение в канале с id %d. Это ошибка сервера. Войдите снова, если хотите видеть сообщения в этом канале.",
    sv    = "Varning - meddelande i kanal med id %d som är okänt. Detta är ett serverfel. Logga in igen om du vill se meddelanden i den här kanalen.",
    nb    = "Advarsel - melding i kanal med id %d som er ukjent. Dette er en serverfeil. Logg inn igjen hvis du vil se meldinger i denne kanalen.",
    de    = "Warnung - Nachricht im Kanal mit der ID %d ist unbekannt. Dies ist ein Serverfehler. Melden Sie sich erneut an, wenn Sie Nachrichten in diesem Kanal sehen möchten.",
    nlnl  = "Waarschuwing - bericht in onbekend kanaal met id %d. Dit is een serverfout. Log opnieuw in als je berichten in dit kanaal wilt zien.",
    frfr  = "Avertissement - le message du canal ID %d est inconnu. Il s'agit d'un bug du serveur. Reconnectez-vous si vous voulez voir les messages de ce canal.",
    fi    = "Varoitus - kanavan %d viesti on tuntematon. Tämä on palvelinvirhe. Kirjaudu uudelleen nähdäksesi kanavan viestit.",
    it    = "Attenzione: messaggio nel canale con ID %d sconosciuto. Si tratta di un errore del server. Riconnettiti se vuoi visualizzare i messaggi in questo canale.",
    zhcn  = "警告 - 频道 id %d 中的消息未知。这是服务器错误。如果想查看此频道中的消息，请重新登录。",
    ja    = "警告 - 不明なチャンネルID %dのメッセージです。サーバーのバグです。このチャンネルのメッセージを見るには再ログインしてください。",
    ko    = "경고 - 채널 id %d의 알 수 없는 메시지입니다. 서버 오류입니다. 이 채널의 메시지를 보려면 다시 로그인하세요.",
  },

  GameConsoleChatWithYourself = {
    en    = "You cannot create a private chat channel with yourself.",
    ptbr  = "Você não pode criar um canal de chat privado consigo mesmo.",
    ptpt  = "Você não pode criar um canal de chat privado consigo mesmo.",
    es419 = "No puedes crear un canal de chat privado contigo mismo.",
    eses  = "No puedes crear un canal de chat privado contigo mismo.",
    pl    = "Nie możesz utworzyć prywatnego kanału czatu z samym sobą.",
    ru    = "Нельзя создать приватный чат с самим собой.",
    sv    = "Du kan inte skapa en privat chattkanal med dig själv.",
    nb    = "Du kan ikke opprette en privat chatkanal med deg selv.",
    de    = "Sie können keinen privaten Chat-Kanal mit sich selbst erstellen.",
    nlnl  = "Je kunt geen privéchatkanaal met jezelf maken.",
    frfr  = "Vous ne pouvez pas créer un canal de discussion privé avec vous-même.",
    fi    = "Et voi luoda yksityistä chat-kanavaa itsesi kanssa.",
    it    = "Non puoi creare un canale di chat privata con te stesso.",
    zhcn  = "你无法与自己创建私聊频道。",
    ja    = "自分自身とのプライベートチャットチャンネルは作成できません。",
    ko    = "자신과 비공개 채팅 채널을 만들 수 없습니다.",
  },

  GameConsoleUnknownChatEventType = {
    en    = "Unknown channel event type (%d).",
    ptbr  = "Tipo de evento de canal desconhecido (%d).",
    ptpt  = "Tipo de evento de canal desconhecido (%d).",
    es419 = "Tipo de evento de canal desconocido (%d).",
    eses  = "Tipo de evento de canal desconocido (%d).",
    pl    = "Nieznany typ zdarzenia kanału (%d).",
    ru    = "Неизвестный тип события канала (%d).",
    sv    = "Okänd kanalhändelsetyp (%d).",
    nb    = "Ukjent kanalhendelsestype (%d).",
    de    = "Unbekannter Kanalereignistyp (%d).",
    nlnl  = "Onbekend type kanaalgebeurtenis (%d).",
    frfr  = "Type d'événement de canal inconnu (%d).",
    fi    = "Tuntematon kanavatapahtuman tyyppi (%d).",
    it    = "Tipo di evento del canale sconosciuto (%d).",
    zhcn  = "未知的频道事件类型（%d）。",
    ja    = "不明なチャンネルイベントタイプ（%d）。",
    ko    = "알 수 없는 채널 이벤트 유형 (%d).",
  },

  GameConsoleCloseChannel = {
    en    = "Close this channel %s",
    ptbr  = "Fechar este canal %s",
    ptpt  = "Fechar este canal %s",
    es419 = "Cerrar este canal %s",
    eses  = "Cerrar este canal %s",
    pl    = "Zamknij ten kanał %s",
    ru    = "Закрыть этот канал %s",
    sv    = "Stäng denna kanal %s",
    nb    = "Lukk denne kanalen %s",
    de    = "Diesen Kanal %s schließen",
    nlnl  = "Dit kanaal %s sluiten",
    frfr  = "Fermer ce canal %s",
    fi    = "Sulje tämä kanava %s",
    it    = "Chiudi questo canale %s",
    zhcn  = "关闭此频道 %s",
    ja    = "このチャンネル%sを閉じる",
    ko    = "이 채널 %s 닫기",
  },

  GameConsoleClearCurrentWindow = {
    en    = "Clear current message window",
    ptbr  = "Limpar a janela de mensagens atual",
    ptpt  = "Limpar a janela de mensagens atual",
    es419 = "Limpiar la ventana de mensajes actual",
    eses  = "Limpiar la ventana de mensajes actual",
    pl    = "Wyczyść bieżące okno wiadomości",
    ru    = "Очистить текущее окно сообщений",
    sv    = "Rensa aktuellt meddelandefönster",
    nb    = "Tøm aktuelt meldingsvindu",
    de    = "Aktuelles Nachrichtenfenster leeren",
    nlnl  = "Huidig berichtenvenster wissen",
    frfr  = "Effacer la fenêtre de messages actuelle",
    fi    = "Tyhjennä nykyinen viesti-ikkuna",
    it    = "Cancella la finestra dei messaggi corrente",
    zhcn  = "清除当前消息窗口",
    ja    = "現在のメッセージウィンドウを消去",
    ko    = "현재 메시지 창 지우기",
  },

  GameConsoleNewChannel = {
    en    = "Open new channel %s",
    ptbr  = "Abrir novo canal %s",
    ptpt  = "Abrir novo canal %s",
    es419 = "Abrir nuevo canal %s",
    eses  = "Abrir nuevo canal %s",
    pl    = "Otwórz nowy kanał %s",
    ru    = "Открыть новый канал %s",
    sv    = "Öppna ny kanal %s",
    nb    = "Åpne ny kanal %s",
    de    = "Neuen Kanal %s öffnen",
    nlnl  = "Nieuw kanaal %s openen",
    frfr  = "Ouvrir un nouveau canal %s",
    fi    = "Avaa uusi kanava %s",
    it    = "Apri nuovo canale %s",
    zhcn  = "打开新频道 %s",
    ja    = "新しいチャンネル%sを開く",
    ko    = "새 채널 %s 열기",
  },

  GameConsoleIgnorePlayers = {
    en    = "Ignore players",
    ptbr  = "Ignorar jogadores",
    ptpt  = "Ignorar jogadores",
    es419 = "Ignorar jugadores",
    eses  = "Ignorar jugadores",
    pl    = "Ignoruj graczy",
    ru    = "Игнорировать игроков",
    sv    = "Ignorera spelare",
    nb    = "Ignorer spillere",
    de    = "Spieler ignorieren",
    nlnl  = "Spelers negeren",
    frfr  = "Ignorer les joueurs",
    fi    = "Ohita pelaajat",
    it    = "Ignora giocatori",
    zhcn  = "忽略玩家",
    ja    = "プレイヤーを無視",
    ko    = "플레이어 무시",
  },

  GameConsoleMsgVolume = {
    en    = "Adjust message range",
    ptbr  = "Ajustar alcance das mensagens",
    ptpt  = "Ajustar volume das mensagens",
    es419 = "Ajustar el alcance de los mensajes",
    eses  = "Ajustar el alcance de los mensajes",
    pl    = "Dostosuj zasięg wiadomości",
    ru    = "Настроить дальность сообщений",
    sv    = "Justera meddelanderäckvidden",
    nb    = "Juster meldingsrekkevidden",
    de    = "Nachrichtenreichweite anpassen",
    nlnl  = "Berichtenbereik aanpassen",
    frfr  = "Régler la portée des messages",
    fi    = "Säädä viestien kantamaa",
    it    = "Regola la portata dei messaggi",
    zhcn  = "调整消息范围",
    ja    = "メッセージの範囲を調整",
    ko    = "메시지 범위 조정",
  },

  GameConsoleChannels = {
    en    = "Channels",
    ptbr  = "Canais",
    ptpt  = "Canais",
    es419 = "Canales",
    eses  = "Canales",
    pl    = "Kanały",
    ru    = "Каналы",
    sv    = "Kanaler",
    nb    = "Kanaler",
    de    = "Kanäle",
    nlnl  = "Kanalen",
    frfr  = "Canaux",
    fi    = "Kanavat",
    it    = "Canali",
    zhcn  = "频道",
    ja    = "チャンネル",
    ko    = "채널",
  },

  GameConsoleOpenPrivateChannel = {
    en    = "Open a private message channel",
    ptbr  = "Abrir um canal de mensagem privada",
    ptpt  = "Abrir um canal de mensagem privada",
    es419 = "Abrir un canal de mensajes privados",
    eses  = "Abrir un canal de mensajes privados",
    pl    = "Otwórz prywatny kanał wiadomości",
    ru    = "Открыть канал личных сообщений",
    sv    = "Öppna en privat meddelandekanal",
    nb    = "Åpne en privat meldingskanal",
    de    = "Einen privaten Nachrichtenkanal öffnen",
    nlnl  = "Een privéberichtkanaal openen",
    frfr  = "Ouvrir un canal de messages privés",
    fi    = "Avaa yksityinen viestikanava",
    it    = "Apri un canale di messaggi privati",
    zhcn  = "打开私信频道",
    ja    = "プライベートメッセージチャンネルを開く",
    ko    = "비공개 메시지 채널 열기",
  },

  GameConsoleCommunicationWindow = {
    en    = "Ignore list",
    ptbr  = "Lista de ignorados",
    ptpt  = "Lista de ignorados",
    es419 = "Lista de ignorados",
    eses  = "Lista de ignorados",
    pl    = "Lista ignorowanych",
    ru    = "Список игнорируемых",
    sv    = "Ignoreringslista",
    nb    = "Ignoreringsliste",
    de    = "Ignorierliste",
    nlnl  = "Negerlijst",
    frfr  = "Liste des ignorés",
    fi    = "Ohitusluettelo",
    it    = "Lista degli ignorati",
    zhcn  = "忽略列表",
    ja    = "無視リスト",
    ko    = "무시 목록",
  },

  GameConsoleCheckboxUseIgnoreList = {
    en    = "Activate ignore list",
    ptbr  = "Ativar lista de ignorados",
    ptpt  = "Ativar lista de ignorados",
    es419 = "Activar lista de ignorados",
    eses  = "Activar lista de ignorados",
    pl    = "Aktywuj listę ignorowanych",
    ru    = "Активировать список игнорируемых",
    sv    = "Aktivera ignoreringslistan",
    nb    = "Aktiver ignoreringslisten",
    de    = "Ignorierliste aktivieren",
    nlnl  = "Negerlijst activeren",
    frfr  = "Activer la liste des ignorés",
    fi    = "Ota ohitusluettelo käyttöön",
    it    = "Attiva la lista degli ignorati",
    zhcn  = "启用忽略列表",
    ja    = "無視リストを有効化",
    ko    = "무시 목록 활성화",
  },

  GameConsoleIgnoredPlayersList = {
    en    = "Ignored players",
    ptbr  = "Jogadores ignorados",
    ptpt  = "Jogadores ignorados",
    es419 = "Jugadores ignorados",
    eses  = "Jugadores ignorados",
    pl    = "Ignorowani gracze",
    ru    = "Игнорируемые игроки",
    sv    = "Ignorerade spelare",
    nb    = "Ignorerte spillere",
    de    = "Ignorierte Spieler",
    nlnl  = "Genegeerde spelers",
    frfr  = "Joueurs ignorés",
    fi    = "Ohitetut pelaajat",
    it    = "Giocatori ignorati",
    zhcn  = "已忽略的玩家",
    ja    = "無視したプレイヤー",
    ko    = "무시한 플레이어",
  },

  GameConsoleIgnoreSettings = {
    en    = "Settings of ignore",
    ptbr  = "Configurações de ignorados",
    ptpt  = "Definições de ignorados",
    es419 = "Configuración de ignorados",
    eses  = "Configuración de ignorados",
    pl    = "Ustawienia ignorowania",
    ru    = "Настройки игнорирования",
    sv    = "Inställningar för att ignorera",
    nb    = "Innstillinger for ignorering",
    de    = "Einstellungen für ignorierte Spieler",
    nlnl  = "Instellingen voor negeren",
    frfr  = "Paramètres des ignorés",
    fi    = "Ohitusten asetukset",
    it    = "Impostazioni di ignoramento",
    zhcn  = "忽略设置",
    ja    = "無視設定",
    ko    = "무시 설정",
  },

  GameConsoleCheckboxIgnorePrivateMessages = {
    en    = "Ignore private messages",
    ptbr  = "Ignorar mensagens privadas",
    ptpt  = "Ignorar mensagens privadas",
    es419 = "Ignorar mensajes privados",
    eses  = "Ignorar mensajes privados",
    pl    = "Ignoruj wiadomości prywatne",
    ru    = "Игнорировать личные сообщения",
    sv    = "Ignorera privata meddelanden",
    nb    = "Ignorer private meldinger",
    de    = "Private Nachrichten ignorieren",
    nlnl  = "Privéberichten negeren",
    frfr  = "Ignorer les messages privés",
    fi    = "Ohita yksityisviestit",
    it    = "Ignora i messaggi privati",
    zhcn  = "忽略私信",
    ja    = "プライベートメッセージを無視",
    ko    = "비공개 메시지 무시",
  },

  GameConsoleCheckboxIgnoreYelling = {
    en    = "Ignore yelling",
    ptbr  = "Ignorar gritos",
    ptpt  = "Ignorar gritos",
    es419 = "Ignorar gritos",
    eses  = "Ignorar gritos",
    pl    = "Ignoruj krzyki",
    ru    = "Игнорировать крики",
    sv    = "Ignorera rop",
    nb    = "Ignorer roping",
    de    = "Schreie ignorieren",
    nlnl  = "Schreeuwen negeren",
    frfr  = "Ignorer les cris",
    fi    = "Ohita huutaminen",
    it    = "Ignora le urla",
    zhcn  = "忽略喊话",
    ja    = "叫び声を無視",
    ko    = "외침 무시",
  },

  GameConsoleCheckboxUseWhiteList = {
    en    = "Activate allowed list",
    ptbr  = "Ativar lista de permitidos",
    ptpt  = "Ativar lista de permitidos",
    es419 = "Activar lista de permitidos",
    eses  = "Activar lista de permitidos",
    pl    = "Aktywuj listę dozwolonych",
    ru    = "Активировать список разрешённых",
    sv    = "Aktivera listan över tillåtna",
    nb    = "Aktiver tillatt-liste",
    de    = "Erlaubnisliste aktivieren",
    nlnl  = "Toegestane lijst activeren",
    frfr  = "Activer la liste des joueurs autorisés",
    fi    = "Ota sallittujen luettelo käyttöön",
    it    = "Attiva la lista dei consentiti",
    zhcn  = "启用允许列表",
    ja    = "許可リストを有効化",
    ko    = "허용 목록 활성화",
  },

  GameConsoleAllowedPlayersList = {
    en    = "Allowed players",
    ptbr  = "Jogadores permitidos",
    ptpt  = "Jogadores permitidos",
    es419 = "Jugadores permitidos",
    eses  = "Jugadores permitidos",
    pl    = "Dozwoleni gracze",
    ru    = "Разрешённые игроки",
    sv    = "Tillåtna spelare",
    nb    = "Tillatte spillere",
    de    = "Erlaubte Spieler",
    nlnl  = "Toegestane spelers",
    frfr  = "Joueurs autorisés",
    fi    = "Sallitut pelaajat",
    it    = "Giocatori consentiti",
    zhcn  = "允许的玩家",
    ja    = "許可したプレイヤー",
    ko    = "허용된 플레이어",
  },

  GameConsoleAllowedSettings = {
    en    = "Settings of allowed",
    ptbr  = "Configurações de permitidos",
    ptpt  = "Definições de permitidos",
    es419 = "Configuración de permitidos",
    eses  = "Configuración de permitidos",
    pl    = "Ustawienia dozwolonych",
    ru    = "Настройки разрешённых",
    sv    = "Inställningar för tillåtna",
    nb    = "Innstillinger for tillatte",
    de    = "Einstellungen für erlaubte Spieler",
    nlnl  = "Instellingen voor toestaan",
    frfr  = "Paramètres des joueurs autorisés",
    fi    = "Sallittujen asetukset",
    it    = "Impostazioni dei consentiti",
    zhcn  = "允许列表设置",
    ja    = "許可設定",
    ko    = "허용 설정",
  },

  GameConsoleCheckboxAllowVIPs = {
    en    = "Allow contacts to message you",
    ptbr  = "Permitir que contatos enviem mensagens",
    ptpt  = "Permitir que contatos enviem mensagens",
    es419 = "Permitir que los contactos te envíen mensajes",
    eses  = "Permitir que los contactos te envíen mensajes",
    pl    = "Zezwól kontaktom na wysyłanie wiadomości",
    ru    = "Разрешить контактам отправлять вам сообщения",
    sv    = "Tillåt kontakter att skicka meddelanden till dig",
    nb    = "Tillat kontakter å sende meldinger til deg",
    de    = "Kontakten erlauben, Ihnen Nachrichten zu senden",
    nlnl  = "Contacten toestaan je berichten te sturen",
    frfr  = "Autoriser les contacts à vous envoyer des messages",
    fi    = "Salli yhteystietojen lähettää sinulle viestejä",
    it    = "Consenti ai contatti di inviarti messaggi",
    zhcn  = "允许联系人向你发送消息",
    ja    = "連絡先からのメッセージを許可",
    ko    = "연락처에서 메시지를 보낼 수 있도록 허용",
  },

  GameConsoleButtonSave = {
    en    = "Save",
    ptbr  = "Salvar",
    ptpt  = "Guardar",
    es419 = "Guardar",
    eses  = "Guardar",
    pl    = "Zapisz",
    ru    = "Сохранить",
    sv    = "Spara",
    nb    = "Lagre",
    de    = "Speichern",
    nlnl  = "Opslaan",
    frfr  = "Enregistrer",
    fi    = "Tallenna",
    it    = "Salva",
    zhcn  = "保存",
    ja    = "保存",
    ko    = "저장",
  },

  GameConsoleIgnoreWindow = {
    en    = "Report rule violation",
    ptbr  = "Reportar violação de regras",
    ptpt  = "Reportar violação de regras",
    es419 = "Reportar violación de reglas",
    eses  = "Reportar violación de reglas",
    pl    = "Zgłoś naruszenie zasad",
    ru    = "Пожаловаться на нарушение правил",
    sv    = "Rapportera regelbrott",
    nb    = "Rapportere regelbrudd",
    de    = "Regelverstoß melden",
    nlnl  = "Regelovertreding melden",
    frfr  = "Signaler une violation des règles",
    fi    = "Ilmoita sääntörikkomuksesta",
    it    = "Segnala una violazione delle regole",
    zhcn  = "举报规则违规",
    ja    = "ルール違反を報告",
    ko    = "규칙 위반 신고",
  },

  GameConsoleRuleViolationSentence = {
    en    = "State the rule violation in one clear sentence and wait for a reply from a gamemaster. Note that your message will disappear if you close the channel.",
    ptbr  = "Declare a violação de regra em uma frase clara e aguarde uma resposta de um gamemaster. Observe que sua mensagem desaparecerá se você fechar o canal.",
    ptpt  = "Declare a violação de regra em uma frase clara e aguarde uma resposta de um gamemaster. Observe que sua mensagem desaparecerá se você fechar o canal.",
    es419 = "Indique la violación de reglas en una oración clara y espere una respuesta de un maestro de juego. Tenga en cuenta que su mensaje desaparecerá si cierra el canal.",
    eses  = "Indique la violación de reglas en una oración clara y espere una respuesta de un maestro de juego. Tenga en cuenta que su mensaje desaparecerá si cierra el canal.",
    pl    = "Podaj naruszenie zasad w jednym jasnym zdaniu i poczekaj na odpowiedź od mistrza gry. Zauważ, że twoja wiadomość zniknie, jeśli zamkniesz kanał.",
    ru    = "Опишите нарушение правил одним ясным предложением и дождитесь ответа мастера игры. Учтите, что ваше сообщение исчезнет, если вы закроете канал.",
    sv    = "Ange regelbrottet i en tydlig mening och vänta på svar från en spelmästare. Observera att ditt meddelande försvinner om du stänger kanalen.",
    nb    = "Angi regelbruddet i én tydelig setning og vent på svar fra en spillmester. Merk at meldingen din forsvinner hvis du lukker kanalen.",
    de    = "Erklären Sie den Regelverstoß in einem klaren Satz und warten Sie auf eine Antwort von einem Gamemaster. Beachten Sie, dass Ihre Nachricht verschwindet, wenn Sie den Kanal schließen.",
    nlnl  = "Beschrijf de regelovertreding in één duidelijke zin en wacht op antwoord van een gamemaster. Let op: je bericht verdwijnt als je het kanaal sluit.",
    frfr  = "Décrivez la violation des règles en une phrase claire et attendez la réponse d'un maître de jeu. Votre message disparaîtra si vous fermez le canal.",
    fi    = "Kuvaile sääntörikkomus yhdellä selkeällä lauseella ja odota pelimestarin vastausta. Viestisi katoaa, jos suljet kanavan.",
    it    = "Descrivi la violazione delle regole in una frase chiara e attendi la risposta di un game master. Nota che il tuo messaggio scomparirà se chiudi il canale.",
    zhcn  = "用一句清晰的话说明违规行为，然后等待游戏管理员回复。请注意，关闭频道后消息会消失。",
    ja    = "ルール違反を明確な一文で記載し、ゲームマスターからの返信を待ってください。チャンネルを閉じるとメッセージが消えることに注意してください。",
    ko    = "규칙 위반 내용을 명확한 한 문장으로 작성하고 게임 마스터의 답변을 기다리세요. 채널을 닫으면 메시지가 사라집니다.",
  },
})
